### ISSUE TITLE
Compilation error due to renamed? FileUtility class

### ISSUE THREAD

**Issue by joetaylor1987** [PlayEveryWare/eos_plugin_for_unity#1012]
**Describe the bug**
`iOSBuilder.cs`, `LinuxPlatformSpecifics.cs` and `WindowsPlatformSpecifics.cs` all make references to `FileUtility.ReadAllText` which doesn't exist and leads to the following error in the Unity Editor:
```
Library/PackageCache/com.playeveryware.eos@2b19812166/Editor/Platforms/iOS/IOSBuilder.cs(63,33): error CS0103: The name 'FileUtility' does not exist in the current context
```

It looks like `FileUtility` has been renamed to `FileSystemUtility` and the three references have not been updated

**To Reproduce**
1. Import the latest version of the package (v3.3.3) using the git url
2. Switch platform in Unity to iOS
3. See error

**Expected behavior**
The package should compile without errors

**Desktop (please complete the following information):**
 - OS: macOS ARM
 - Editor
 - Unity Version 2022.3.40f1
 - v3.3.3

**Comment by joetaylor1987** [comment]
It looks like this is fixed on the `development` branch. Feel free to close this issue if a release is imminent!

**Comment by paulhazen** [comment]
> It looks like this is fixed on the `development` branch. Feel free to close this issue if a release is imminent!

It is indeed imminent, but thank you for bringing it up :) Let us know if you need any other assistance or have other feedback.
