### ISSUE TITLE
Issue with OAuth Login Flow Using EOS Account Portal and PIN Grant in Unity for Android

### ISSUE THREAD

**Issue by suriyaprakash-v** [PlayEveryWare/eos_plugin_for_unity#1023]
**Description of the Issue:**

We are encountering an issue with the OAuth login flow using the Epic Online Services (EOS) Account Portal and PIN Grant method in Unity for Android. The process works as expected until the user enters the verification code on the Account Portal. However, after the user enters the code, the redirection back to the game does not occur.

**Steps to Reproduce:**

- Call the LoginWithAccountPortal() method.
- The user is prompted to visit the Account Portal and enter the PIN displayed in callbackInfo.PinGrantInfo.Value.UserCode.
- The user enters the PIN at the provided URL (callbackInfo.PinGrantInfo.Value.VerificationURI).
- The user expects to be redirected back to the game, but this does not happen.

**Observed Behavior:**

- The user successfully enters the PIN on the Account Portal.
- No redirection occurs back to the game.
- The OnLoginCallback() does not receive a Result.Success or any subsequent callback.
- The verification URL redirects again after the user completes the login process on the Account Portal, but the game is not updated accordingly.

**Expected Behavior:**

After the user successfully enters the PIN on the Account Portal, the game should receive a callback (OnLoginCallback) with a Result.Success, allowing the login process to complete and proceed.

**Request for Assistance:**

We are looking for help to identify and resolve the issue preventing the redirection back to the game after the user completes the PIN verification on the Account Portal.

**Attached Code Snippet:**

```csharp
private void LoginWithAccountPortal()
{
    EOSManager.EOSSingleton.EpicLauncherArgs argsEpic = EOSManager.Instance.GetCommandLineArgsFromEpicLauncher();
    ShowLoading(true);
    EOSManager.Instance.StartLoginWithLoginTypeAndToken(
        LoginCredentialType.AccountPortal,
        null,
        null,
        OnLoginCallback
    );
}

private void OnLoginCallback(LoginCallbackInfo callbackInfo)
{
    ShowLoading(false);
    Debug.Log($"OnLoginCallback: {callbackInfo.ResultCode}");

    if (callbackInfo.ResultCode == Epic.OnlineServices.Result.Success)
    {
        Debug.Log($"Login Successful! User ID: {callbackInfo.LocalUserId}");
        // Proceed with authenticated gameplay or actions.
    } 
    else if (callbackInfo.ResultCode == Epic.OnlineServices.Result.InvalidAuth)
    {
        Debug.LogWarning("PersistentAuth token is invalid. Re-authenticating via AccountPortal...");
        LoginWithAccountPortal();
    } 
    else if (callbackInfo.ResultCode == Epic.OnlineServices.Result.InvalidUser)
    {
        Debug.LogWarning("PersistentAuth failed. Falling back to AccountPortal...");
        LoginWithAccountPortal();
    } 
    else if (callbackInfo.ResultCode == Epic.OnlineServices.Result.AuthPinGrantCode)
    {
        Debug.Log($"Please enter this PIN on the Account Portal: {callbackInfo.PinGrantInfo.Value.UserCode}");
        Debug.Log($"Visit this URL to enter the PIN: {callbackInfo.PinGrantInfo.Value.VerificationURI}");
        GUIUtility.systemCopyBuffer = callbackInfo.PinGrantInfo.Value.UserCode;
        Application.OpenURL(callbackInfo.PinGrantInfo.Value.VerificationURI);
    } 
    else
    {
        Debug.LogError($"Login failed: {callbackInfo.ResultCode}");
        // Notify the user of the failure through UI.
    }
}

```
**Additional Notes:**

- We have ensured that the Redirect URI is configured in the EOS Developer Portal.
- The game does not receive the expected callback (OnLoginCallback) after the PIN is entered, even though the verification URL redirects successfully.
- Any guidance on handling redirection or improving this flow would be greatly appreciated.

Thank you!

**Comment by suriyaprakash-v** [comment]
I am also getting the floowing warning after I returned to the game

```
11/26/2024 17:24:48 LogEOS(Warning): Error response received from backend. ServiceName=[OAuth], OperationName=[TokenGrantv2], Url=[<Redacted>], HttpStatus=[400], ErrorCode=[errors.com.epicgames.oauth.corrective_action_required], NumericErrorCode=[18206], ErrorMessage=[Corrective action is required to continue.], CorrId=[EOS-fIQZBvhN-36Lywq0RlyE1Q-DIhpCdRJpM9FLl2zUCRDyA]

----------------------------------------------------------------

PlayEveryWare.EpicOnlineServices.EOSSingleton:SimplePrintCallback(LogMessage&)
Epic.OnlineServices.Logging.LoggingInterface:LogMessageFuncInternalImplementation(LogMessageInternal&)
Epic.OnlineServices.Bindings:EOS_Platform_Tick(IntPtr)
PlayEveryWare.EpicOnlineServices.EOSSingleton:Tick()
```

**Comment by WispyMouse** [comment]
Ahoy @suriyaprakash-v ! I wanted to offer a bit of insight, while the team comes up with a more complete response.

Your second message, "after I returned to the game", when exactly was this logged? It _sounds like_:

- The user attempts to login using Account Portal
- They are redirected to a place to fill out the pin
- They fill out the pin
- They return to the game; the OnLoginCallback isn't run at all, but there is this logged message about corrective action

Is the above accurate to the experience you're getting?

**Comment by WispyMouse** [comment]
This post mentions the same error code and has a response from Epic Games: https://eoshelp.epicgames.com/s/question/0D54z00009REtVqCAL/hi-i-get-this-error-every-time-i-run-my-lyra-made-game-with-eos-implemented-this-is-the-error-20230714145238299178logeossdk-warning-logeos-error-response-received-from-backend-servicenameoauth-operationnametokengrantv2-urlredacted?language=en_US

Could you review the ideas here, and see if any are relevant?

> This error usually comes up in these situations:
>
>    - The account doesn't have MFA configured
 >   - The 3rd party identity provider account isn't linked to the Epic Games account. You should be getting an in-game prompt to link your account if you are logging in via Steam, etc...
>    - The Epic Account Services client permissions in the developer portal don't match what is being specified in the client For Lyra, unless you've changed the code, you should have BasicProfile, FriendsList and Presence enabled in the developer portal. Note that country should not be enabled.

**Comment by arthur740212** [comment]
Hello, the login completing but not returning to the app looks like `eos_login_protocol_scheme` not being set (or in reality it is being overwritten by an empty string). 
This issue is inconsistent across projects because it seems to depend on how unity decides in what order `eos_login_protocol_scheme` entries are used.
Here is a fix for that can be done on your end, in `eos.aar` use 7zip to open it.
Find `eos-sdk.aar\res\values\values.xml`, edit it and remove the line 
`<string name="eos_login_protocol_scheme">""</string>`
This should prevent the entry from getting rewritten and will likely solve your issue.

**Comment by suriyaprakash-v** [comment]
> * t there is this logged message ab

Hi, So the flow will be as same you mentioned except user will fill out the pin and it will loop the same process again.
It wont redirected to game after filling out the pin in first attempt.

The user attempts to login using Account Portal
They will sign in by providing credentials and permissions then it will redirect to game with result as **AuthPinGrantCode**
Then I will redirect them to the verification URI to fill out the pin
They fill out the pin
Again it will show the page to fill the pin. And its not redirected to game also.

**Comment by suriyaprakash-v** [comment]
Also I used the solution from this issue.
https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/257
After updating the  authScopeOptionsFlags in the config file. The login issue is fixed.
Its not throwing the AuthPinGrantCode error anymore.
But not sure how this works!
![Screenshot 2024-11-27 at 12 02 25 PM](https://github.com/user-attachments/assets/0050ab39-30f4-4435-979b-785cdcab08db)

**Comment by suriyaprakash-v** [comment]
> This post mentions the same error code and has a response from Epic Games: https://eoshelp.epicgames.com/s/question/0D54z00009REtVqCAL/hi-i-get-this-error-every-time-i-run-my-lyra-made-game-with-eos-implemented-this-is-the-error-20230714145238299178logeossdk-warning-logeos-error-response-received-from-backend-servicenameoauth-operationnametokengrantv2-urlredacted?language=en_US
> 
> Could you review the ideas here, and see if any are relevant?
> 
> > This error usually comes up in these situations:
> > 
> > * The account doesn't have MFA configured
> > * The 3rd party identity provider account isn't linked to the Epic Games account. You should be getting an in-game prompt to link your account if you are logging in via Steam, etc...
> > * The Epic Account Services client permissions in the developer portal don't match what is being specified in the client For Lyra, unless you've changed the code, you should have BasicProfile, FriendsList and Presence enabled in the developer portal. Note that country should not be enabled.

Hi, After updating the permission in my config files. the issue got resolved for me.

**Comment by paulhazen** [comment]
Hi @suriyaprakash-v I'm glad your problem was able to be resolved! I'm going to mark this issue as resolved. 
Thank you for reaching out, and please feel free to do so again should you encounter another issue or want continued assistance with anything :)

**Comment by paomeng-game** [comment]
> and

Thank you very much, it working in my project.

**Comment by paomeng-game** [comment]
> Hello, the login completing but not returning to the app looks like not being set (or in reality it is being overwritten by an empty string). This issue is inconsistent across projects because it seems to depend on how unity decides in what order entries are used. Here is a fix for that can be done on your end, in use 7zip or any archive tool to open it. Find , edit it and remove the line This should prevent the entry from getting rewritten and will likely solve your issue.`eos_login_protocol_scheme``eos_login_protocol_scheme``eos.aar``eos-sdk.aar\res\values\values.xml``<string name="eos_login_protocol_scheme">""</string>`

Thank you very much, it working in my project.
