### ISSUE TITLE
Guide to implement with Unity's future network solutions

### ISSUE THREAD

**Issue by PixelSir** [PlayEveryWare/eos_plugin_for_unity#103]
**Describe the solution you'd like**

When this plugin is fully fleshed out it would be nice if we could get a simple guide on how to get it linked up with unity's Netcode for GameObjects - i'm no networking wizard so I am fumbling my way around and so far its quite a chore compared to using other things out there which are already integrated (for example Steamworks already has a transport that integrates into Netcode for GameObjects which makes it work super easily).

**Additional context**
Right now the only real documentation i can check is Unreal's and frankly they are awful when it comes to documentation - they always have been compared to what we are used to with Unity. 

A good documentation and guides will naturally reduce the influx of questions in future when people start using this plugin in larger numbers too.

**Comment by domlaurenti** [comment]
We have something in the works with respect to this request. It will be a little ways out, but it's coming.

**Comment by scovertb** [comment]
An upcoming release will include a sample containing a transport using the EOS P2P service as a backend.
