### ISSUE TITLE
`EOS_Auth_CopyIdToken` seems to be missing from `EOSManager`

### ISSUE THREAD

**Issue by Ermelious** [PlayEveryWare/eos_plugin_for_unity#1033]
**Is your feature request related to a problem? Please describe.**
Documentation: https://dev.epicgames.com/docs/web-api-ref/authentication#online-verification

I've found the ConnectInterface having the following:
Bindings.EOS_Connect_CopyIdToken(InnerHandle, ref optionsInternal, ref outIdTokenAddress);

But this doesn't seem to be the one I should be using for authentication / verification. It should be EOS_Auth_CopyIdToken. Advice appreciated.

Is there already an existing function to retrieve the EOS_Auth_CopyIdToken somewhere in the samples?

Here's the documentation of the Auth_CopyIdToken:
https://dev.epicgames.com/docs/api-ref/functions/eos-auth-copy-id-token

Clickup #EOS-2258

**Comment by WispyMouse** [comment]
> But this doesn't seem to be the one I should be using for authentication / verification. It should be EOS_Auth_CopyIdToken. Advice appreciated.

You're correct here; in situations where you want to be providing a token from Epic to another service, you probably want that token from the Authentication interface rather than the Connect interface.

> But this doesn't seem to be the one I should be using for authentication / verification. It should be EOS_Auth_CopyIdToken. Advice appreciated.
>
> Is there already an existing function to retrieve the EOS_Auth_CopyIdToken somewhere in the samples?

I took a peek around the code base, and couldn't find anything using the AuthInterface's CopyIdToken function. I did find that we have and use the AuthInterface's `CopyUserAuthToken`. So first we should determine which you want to use. This is a comment on that function's documentation:

```csharp (CopyUserAuthToken)
/// Fetch a user auth token for an Epic Account ID.
/// 
/// A user authentication token allows any code with possession (backend/client) to perform certain actions on behalf of the user.
/// Because of this, for the purposes of user identity verification, the <see cref="CopyIdToken" /> API should be used instead.
```

If you want a token from the auth interface that you plan on using _just to validate the identity exists and to use the token to correlate an external managed account to an EpicAccount_, you should use `EOS_Auth_CopyIdToken`, and we'll have to write a solution for you. It'll look like the below:

```csharp
CopyIdTokenOptions copyOptions = new CopyIdTokenOptions()
{
    // Insert whatever account you're targeting; the below assumes you want an already logged in user
    AccountId = EOSManager.Instance.GetLocalUserId()
};
Result copyIdTokenResult = CopyIdToken(ref CopyIdTokenOptions options, out IdToken? outIdToken);
if (copyIdTokenResult == Result.Success)
{
    // Do something with your newly acquired token
}
````

If you want a token from the auth interface that you plan on using to take actions on the user's behalf, you can use the `CopyUserAuthToken` function. This should already have an implementation in `EOSManager` at `EOSManager.GetUserAuthTokenForAccountId`, and then you provide it the local user's account id. I _believe_ this function will only allow you to get a token for a local, logged in user.

I hope this helps! Does this unblock you?

**Comment by Ermelious** [comment]
> > But this doesn't seem to be the one I should be using for authentication / verification. It should be EOS_Auth_CopyIdToken. Advice appreciated.
> 
> You're correct here; in situations where you want to be providing a token from Epic to another service, you probably want that token from the Authentication interface rather than the Connect interface.
> 
> > But this doesn't seem to be the one I should be using for authentication / verification. It should be EOS_Auth_CopyIdToken. Advice appreciated.
> > Is there already an existing function to retrieve the EOS_Auth_CopyIdToken somewhere in the samples?
> 
> I took a peek around the code base, and couldn't find anything using the AuthInterface's CopyIdToken function. I did find that we have and use the AuthInterface's `CopyUserAuthToken`. So first we should determine which you want to use. This is a comment on that function's documentation:
> 
> ```cs
> /// Fetch a user auth token for an Epic Account ID.
> /// 
> /// A user authentication token allows any code with possession (backend/client) to perform certain actions on behalf of the user.
> /// Because of this, for the purposes of user identity verification, the <see cref="CopyIdToken" /> API should be used instead.
> ```
> 
> If you want a token from the auth interface that you plan on using _just to validate the identity exists and to use the token to correlate an external managed account to an EpicAccount_, you should use `EOS_Auth_CopyIdToken`, and we'll have to write a solution for you. It'll look like the below:
> 
> ```cs
> CopyIdTokenOptions copyOptions = new CopyIdTokenOptions()
> {
>     // Insert whatever account you're targeting; the below assumes you want an already logged in user
>     AccountId = EOSManager.Instance.GetLocalUserId()
> };
> Result copyIdTokenResult = CopyIdToken(ref CopyIdTokenOptions options, out IdToken? outIdToken);
> if (copyIdTokenResult == Result.Success)
> {
>     // Do something with your newly acquired token
> }
> ```
> 
> If you want a token from the auth interface that you plan on using to take actions on the user's behalf, you can use the `CopyUserAuthToken` function. This should already have an implementation in `EOSManager` at `EOSManager.GetUserAuthTokenForAccountId`, and then you provide it the local user's account id. I _believe_ this function will only allow you to get a token for a local, logged in user.
> 
> I hope this helps! Does this unblock you?

Am I right to assume EOSManager.GetUserAuthTokenForAccountId does not do what the EOS_Auth_CopyIdToken does? Actually since EOSManager.GetUserAuthTokenForAccountId, is a token that is used to execute actions on the User's behalf based off the description/comments you've shared, it does not sound like I should be using it since the goal here is to have the login to the Epic Account verified by my backend (in this case) via Firebase Cloud Functions (which will send the Epic Token to Epic's endpoint for verification before granting the user access to their data in Firebase using their epic credentials). 

What I'm trying to do is basically for the Game Client to send the Access Token to Firebase (After the player logs in to their Epic Account via the Epic Account Portal) and have Firebase send that token to Epic's endpoint here: https://api.epicgames.dev/epic/oauth/v2/tokenInfo
Documentation: https://dev.epicgames.com/docs/web-api-ref/authentication#online-verification
And have that endpoint check if the Token is legitimate.

So in this case, CopyIdToken seems to be the one I should be using based of your descriptions and also checking with Epic, anyway I've went ahead to test EOS_Auth_CopyIdToken here:
```c#
    Epic.OnlineServices.Auth.Token? userIdToken;
    public Epic.OnlineServices.Auth.IdToken? GetIdTokenForAccountId()
    {
        var EOSAuthInterface = EOSManager.Instance.GetEOSPlatformInterface().GetAuthInterface();
        var copyIdTokenOptions = new Epic.OnlineServices.Auth.CopyIdTokenOptions();
        copyIdTokenOptions.AccountId = EOSManager.Instance.GetLocalUserId();

        EOSAuthInterface.CopyIdToken(ref copyIdTokenOptions, out Epic.OnlineServices.Auth.IdToken? userIdToken);
        return userIdToken;
    }
```
Issue now is Epic is sending the following error code "1032":
`
verifyEpicTokeni8qz2oty2r8k Error verifying token with Epic Games: {
2024-11-28 23:05:47.091 HKT
verifyEpicTokeni8qz2oty2r8k errorCode: 'errors.com.epicgames.common.authentication.authentication_failed',
2024-11-28 23:05:47.091 HKT
verifyEpicTokeni8qz2oty2r8k errorMessage: 'Authentication failed for /api/epicid/v1/oauth/tokenInfo',
2024-11-28 23:05:47.091 HKT
verifyEpicTokeni8qz2oty2r8k messageVars: [ '/api/epicid/v1/oauth/tokenInfo' ],
2024-11-28 23:05:47.091 HKT
verifyEpicTokeni8qz2oty2r8k numericErrorCode: 1032,
2024-11-28 23:05:47.091 HKT
verifyEpicTokeni8qz2oty2r8k originatingService: 'com.epicgames.account.admin',
2024-11-28 23:05:47.091 HKT
verifyEpicTokeni8qz2oty2r8k intent: 'unknown'
2024-11-28 23:05:47.091 HKT
verifyEpicTokeni8qz2oty2r8k }
2024-11-28 23:05:47.091 HKT
verifyEpicTokeni8qz2oty2r8k Error verifying token: Failed to verify token with Epic Games API.
2024-11-28 23:05:47.091 HKT
verifyEpicTokeni8qz2oty2r8k Error verifying token: Failed to verify token with Epic Games API.
2024-11-28 23:05:47.097 HKT
`
On checking the documentations, it is quite vague:
https://dev.epicgames.com/docs/epic-online-services/sdk-error-codes
![image](https://github.com/user-attachments/assets/7ff3f7e5-1752-402e-9283-386f66350bf6)

**Comment by WispyMouse** [comment]
> So in this case, CopyIdToken seems to be the one I should be using based of your descriptions and also checking with Epic, it would be great to have this in the plugin?

Agreed, we should totally have it in the plugin. I made a task in our back-end tasking software to implement these, and consider thinking of a sample to practically apply it.

> Issue now is Epic is sending the following error "Error verifying token: uid argument must be a non-empty string uid":

Just to be clear, *when* are you getting this message back from Epic? The above snippet looks like you grabbed a token, posted its body in json, but what's happening to give you the uid argument message? My wild guess, briefly reading over the documentation for FireBase, is that something you're calling wants a payload with `uid` defined. I found this bit of documentation that mentions providing a uid: https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_a_third-party_jwt_library 

> The Firebase Admin SDK has a built-in method for creating custom tokens. At a minimum, you need to provide a uid, which can be any string but should uniquely identify the user or device you are authenticating. These tokens expire after one hour.

**Comment by Ermelious** [comment]
> > So in this case, CopyIdToken seems to be the one I should be using based of your descriptions and also checking with Epic, it would be great to have this in the plugin?
> 
> Agreed, we should totally have it in the plugin. I made a task in our back-end tasking software to implement these, and consider thinking of a sample to practically apply it.
> 
> > Issue now is Epic is sending the following error "Error verifying token: uid argument must be a non-empty string uid":
> 
> Just to be clear, _when_ are you getting this message back from Epic? The above snippet looks like you grabbed a token, posted its body in json, but what's happening to give you the uid argument message? My wild guess, briefly reading over the documentation for FireBase, is that something you're calling wants a payload with `uid` defined. I found this bit of documentation that mentions providing a uid: https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_a_third-party_jwt_library
> 
> > The Firebase Admin SDK has a built-in method for creating custom tokens. At a minimum, you need to provide a uid, which can be any string but should uniquely identify the user or device you are authenticating. These tokens expire after one hour.

@WispyMouse Thanks. Actually, after looking through my code again, the issue as you've spotted, doesn't seem to be on Epic side but on Firebase. Meaning I've finally gotten Firebase to send the epic token and have Epic verify it and send back the result to Firebase. The response is actually "Successful" and the token is "Active"/Legit. (At least this is what I'm assuming from the logs I've posted above.

```
verifyEpicTokeng0l2fyunpf4f Epic Games Verification Response: {
2024-11-29 10:41:02.244 HKT
verifyEpicTokeng0l2fyunpf4f active: true,
```

The error that I was facing was related to the Firebase Custom Token Creation process and was because I was including a non-existent JSON data as param to the function. After correcting that, the token is created.

**Comment by WispyMouse** [comment]
Oh awesome! Glad the hunch was correct, and I'm glad to have this information in my pocket now. Seems like you've got what you need, then? Is there anything else you would like assistance with on this topic, or are you okay with me closing out this git issue?

**Comment by Ermelious** [comment]
> Oh awesome! Glad the hunch was correct, and I'm glad to have this information in my pocket now. Seems like you've got what you need, then? Is there anything else you would like assistance with on this topic, or are you okay with me closing out this git issue?

Yes I've gotten what I need or at least think I've did at this point by implementing the following:
```c#
    Epic.OnlineServices.Auth.Token? userIdToken;
    public Epic.OnlineServices.Auth.IdToken? GetIdTokenForAccountId()
    {
        var EOSAuthInterface = EOSManager.Instance.GetEOSPlatformInterface().GetAuthInterface();
        var copyIdTokenOptions = new Epic.OnlineServices.Auth.CopyIdTokenOptions();
        copyIdTokenOptions.AccountId = EOSManager.Instance.GetLocalUserId();

        EOSAuthInterface.CopyIdToken(ref copyIdTokenOptions, out Epic.OnlineServices.Auth.IdToken? userIdToken);
        return userIdToken;
    }
```
into my own source seperate from this plugin. Are there any plans to implement something similar to the above in this plugin? If so, I'll refactor my code once it has been added since I would like to avoid duplicated code.

**Comment by WispyMouse** [comment]
I've created a task in our backlog for implementing this functionality. I have an idea for an interactive authentication focused sample where this would be demonstrated.

Your code above looks good, although I'd make one small change: `EOSAuthInterface.CopyIdToken` returns a `Result`, so you could check to make sure the `Result` is a success, and log a message if it isn't.
