### ISSUE TITLE
How to get a callback for the user being kicked from a lobby?

### ISSUE THREAD

**Issue by KimulatorsFilms** [PlayEveryWare/eos_plugin_for_unity#1061]
Hello,

So far, I can easily set up a callback for the `KickMember` function like this:

```csharp
public void KickButtonOnClick(ProductUserId productUserId)
{
    lobbyManager.KickMember(productUserId, OnKickMemberCompleted);
}
```

```csharp
private void OnKickMemberCompleted(Result result)
{
    if (result == Result.Success)
    {
        Debug.Log("Successfully kicked member.");
    }
    else
    {
        Debug.LogError($"Failed to kick member: {result}");
    }
} 
```

I want to do a similar callback for the person getting kicked out to update some UI elements but I can't find how to do it. In the console logs, I see that this function from the `EOSLobbyManager` gets called on the kicked member:

```csharp
private void OnKickedFromLobby(string lobbyId)
{
    Debug.LogFormat("Lobbies (OnKickedFromLobby):  Kicked from lobby: {0}", lobbyId);
    if (CurrentLobby.IsValid() && CurrentLobby.Id.Equals(lobbyId, StringComparison.OrdinalIgnoreCase))
    {
        CurrentLobby.Clear();
        _Dirty = true;

        OnCurrentLobbyChanged();
    }
} 
```      

 How can I detect that the user got kicked out and do my custom logic in my scripts without modifying the `EOSManager`?

 Thank you !

**Comment by WispyMouse** [comment]
If you pull down our samples, `EOSLobbyManager` will have an example of what you need. `EOSLobbyManager` calls `OnKickedFromLobby` when `OnMemberStatusReceived` is fired with the appropriate callback information. Look at `SubscribeToLobbyUpdates` to see where this is subscribed. I think you'll want to do something similar; subscribe to this notification, and then handle the notification by checking if it is an appropriate event.

**Comment by KimulatorsFilms** [comment]
Ah! I got it to work, thank you so much! :)
