### ISSUE TITLE
AssetDatabase calls for saving config don't work in unity 2021.3

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [PlayEveryWare/eos_plugin_for_unity#107]
In unity 2021.3 EpicOnlineServicesConfigEditor.cs cannot delete and store the config file because the path should only contain the part which starts from Assets\SteamingAssets and not hte full path (should be relative to the project folder)

Also there is an anti-cheat compile error in the poject when you install from the package maanger and install samples which can be commented but is anoying to deal with

**Comment by andrew-hirata-playeveryware** [comment]
Just be to sure, which platform are you running Unity on, what version of the plugin are you using, and which device and OS are you building for? Do you have an example log you could attach of the compile errors?

**Comment by ashkan-saeedi-mazdeh** [comment]
I broke the record for spelling issues in the post. sorry for that.
I'm running the editor on windows 10 and unity 2021.3.4f1 
I no longer have the compile errors for that one but it had compile errors in the editor before building and the plugin was 2.0.1

**Comment by domlaurenti** [comment]
Hello @ashkan-saeedi-mazdeh , please update to the latest 2.1.0 version. We have pushed a fix for this issue, let me know if it works for you!
