### ISSUE TITLE
Missing EOSEACLobbyManager

### ISSUE THREAD

**Issue by kamyker** [PlayEveryWare/eos_plugin_for_unity#108]
**Describe the bug**
After installing upm package then samples - EOSEACLobbyManager is missing.

```
Assets\Samples\Epic Online Services Plugin for Unity\2.0.1\EOS Plugin for Unity Samples\Scripts\UI\UILobbiesMenu.cs(92,17): error CS0246: The type or namespace name 'EOSEACLobbyManager' could not be found (are you missing a using directive or an assembly reference?)

```

**Comment by scovertb** [comment]
I installed the plugin from the 2.0.1 release tarball in 2021 LTS and was unable to reproduce the issue. Can you provide any more detailed reproduction steps? Is EOSEACLobbyManager.cs actually missing from EOS Plugin for Unity Samples/Scripts?

**Comment by kamyker** [comment]
> I installed the plugin from the 2.0.1 release tarball in 2021 LTS and was unable to reproduce the issue. Can you provide any more detailed reproduction steps? Is EOSEACLobbyManager.cs actually missing from EOS Plugin for Unity Samples/Scripts?

Not from tarball but git url, https://github.com/PlayEveryWare/eos_plugin_for_unity_upm.git. Yes that file is missing, you can search that whole repo to see it missing. There was one more file missing but I can't remember the name.

**Comment by scovertb** [comment]
Added missing files to upm repo.
