### ISSUE TITLE
Achievement Sample broken

### ISSUE THREAD

**Issue by JarrydHuntley** [PlayEveryWare/eos_plugin_for_unity#112]
**Describe the bug**
When you try the achievement sample, it doesn't work. If you look at the returned result code it returns the ResultCode "InvalidUser".

**To Reproduce**
1. Create an empty project
2. Import the Epic Online Services Plugin for Unity in the package manager.
3. Install the sample scenes.
4. Configure the Epic Online Services Plugin for Unity.
5. Run the scene Achievements
6. Authenticate (I've been using dev authentication for testing.
7. Click the "Get Achievements" button.
8. Click a button on an individual achievement.
9. Click Unlock, nothing happens.

**Expected behavior**
The achievement should be awarded when the unlock button is pressed.

**Desktop:**
OS: Windows 10 Pro
Unity Version: Unity 2020.3.33f1
Plugin Version: 2.0.1

**Additional context**
The issue is with the method `UnlockAchievementManually()` in EOSAchievementManager.cs. The UnlockAchievementsOptions object should have a definition should set the UserId, something like this:
```
            UnlockAchievementsOptions eosAchievementOption = new UnlockAchievementsOptions
            {
                UserId = EOSManager.Instance.GetProductUserId(),
                AchievementIds = new Utf8String[] { achievementId }
            };
```

It looks like the project had similar code, but it appears commit #a9ec3029fa removed it.

**Comment by domlaurenti** [comment]
@JarrydHuntley 
Hello, please update to the latest 2.1.0 version. We have pushed a fix for this issue. Have a nice week!
