### ISSUE TITLE
I am getting these errors on Unity 2021.2.7f1 using Windows x64

### ISSUE THREAD

**Issue by MiniDuncan** [PlayEveryWare/eos_plugin_for_unity#118]
I am getting these errors on Unity 2021.2.7f1 using Windows x64 (In Unity Editor, it crashes instantly when its built)
Also using the latest version of your plugin

Exception: Trying to set the EOSManagerPlatformSpecifics twice: EOSPlatformSpecificsWindows => EOSPlatformSpecificsWindows
PlayEveryWare.EpicOnlineServices.EOSManagerPlatformSpecifics.SetEOSManagerPlatformSpecificsInterface (PlayEveryWare.EpicOnlineServices.IEOSManagerPlatformSpecifics platformSpecifics) (at Library/PackageCache/com.playeveryware.eos@e84aa06c90/Runtime/IEOSManagerPlatformSpecifics.cs:91)
PlayEveryWare.EpicOnlineServices.EOSPlatformSpecificsWindows.Register () (at Library/PackageCache/com.playeveryware.eos@e84aa06c90/Runtime/Windows/EOSManager_Windows.cs:144)

EOSManager::Init: InitializePlatformInterface: initResult = InvalidParameters
UnityEngine.Debug:LogWarning (object)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner,string) (at Library/PackageCache/com.playeveryware.eos@e84aa06c90/Runtime/EOSManager.cs:465)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner) (at Library/PackageCache/com.playeveryware.eos@e84aa06c90/Runtime/EOSManager.cs:422)
PlayEveryWare.EpicOnlineServices.EOSManager:Awake () (at Library/PackageCache/com.playeveryware.eos@e84aa06c90/Runtime/EOSManager.cs:1288)

Exception: Epic Online Services didn't init correctly: InvalidParameters
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) (at Library/PackageCache/com.playeveryware.eos@e84aa06c90/Runtime/EOSManager.cs:504)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) (at Library/PackageCache/com.playeveryware.eos@e84aa06c90/Runtime/EOSManager.cs:422)
PlayEveryWare.EpicOnlineServices.EOSManager.Awake () (at Library/PackageCache/com.playeveryware.eos@e84aa06c90/Runtime/EOSManager.cs:1288)

**Comment by scovertb** [comment]
@MiniDuncan This is likely an issue with your EOS config. If you're still having this issue, could you send a copy of your EpicOnlineServicesConfig.json to [contact@playeveryware.com](mailto:contact@playeveryware.com) and reference this issue? If you have one, it should be in your project's StreamingAssets folder. That should help us narrow down the issue and add some more useful error messaging.

**Comment by wagenheimer** [comment]
@MiniDuncan Was you able to solve it? I have the exact same problem and could not find out the reason.

**Comment by wagenheimer** [comment]
I found the problem. Version should be only a number. I was using 2.1.45, and this was causing the error.
