### ISSUE TITLE
Where is the dev auth tool 

### ISSUE THREAD

**Issue by PixelSir** [PlayEveryWare/eos_plugin_for_unity#124]
As per the title where is the tool located for us to run it? Can't seem to find the exe for it in the files...

**Comment by scovertb** [comment]
If you download the SDK from the EOS developer portal and unzip it, the Dev Auth Tool will be in SDK/Tools.

**Comment by PixelSir** [comment]
Ah thanks ! :)

**Comment by viniotstudios** [comment]
I can't find the dev Auth tool in the Tools folder. It has good EOSBootstrapper.exe, etc.

**Comment by scovertb** [comment]
The Tools folder in the SDK zip should include the file EOS_DevAuthTool-win32-x64-1.1.0.zip

**Comment by 3ternal** [comment]
In the readme, it says that [EOS SDK 1.15.4](https://dev.epicgames.com/docs/epic-online-services/release-notes#1154---2022-nov-16) comes bundled with this plugin. Doesn't that mean the Dev Auth Tool is somewhere in this repo? I can't find it either.
