### ISSUE TITLE
Lobby sample error: Account Portal overlay failed: EOS_Auth_AccountPortalLoadError

### ISSUE THREAD

**Issue by PixelSir** [PlayEveryWare/eos_plugin_for_unity#125]
Loaded the lobby sample and used the port and username from the dev auth tool. When i login i get this error:

 UserAuthGenerated: Account Portal overlay failed: EOS_Auth_AccountPortalLoadError

Some images of the data inputs:

![image](https://user-images.githubusercontent.com/33559521/188049132-f0af4976-3d18-4967-9625-352a1d1e4804.png)

![image](https://user-images.githubusercontent.com/33559521/188049189-532f9e5f-6965-43ea-ab3f-c3d26d6014a8.png)

![image](https://user-images.githubusercontent.com/33559521/188049258-c61b29b5-b652-4ecd-a6bf-3a90c0ba91bc.png)

What am i doing wrong here?

**Comment by Raxnam** [comment]
Sorry this took so long to get back to you. 
The error is a result of the EOS Overlay not being installed, It seems there is an almost circular dependency to get the overlay up and running. To get around this just build the demo, and in the build folder there should be an EOSBootstrapper.exe. Running that will install the overlay, and from there you shouldn't run into any issues with the demos.
