### ISSUE TITLE
Is there a way to cleanly deal with the detection of DEV, STAGE and LIVE sandbox and deployment ids?

### ISSUE THREAD

**Issue by brechtos** [PlayEveryWare/eos_plugin_for_unity#132]
Is there a way to cleanly deal with the detection of DEV, STAGE and LIVE sandbox and deployment ids?

As it stands you only have one value available in the config and that's the one that will be used.
However, with the way the Epic Store works you have the whole setup with uploading to dev, pushing that to stage before going to live.
Which also means that if you made your build with the dev config, test and verify and want to push it all forward you need to make a new build with the live settings. Before doing all the pushing.

You can set the default to use the live settings and then ask everyone to manually adjust the config for testing but it would be nice if there was an option to automate this if desired (I can understand that you wouldn't always want this to happen).

There is a sandbox launch arg available (-epicsandboxid="") but if the config is being read from a dll that is initialized before anything else there probably isn't a way to adjust the config file on launch before it's used in the dll?
You can easily set this up so that it will be autoswitched after a first run but that is not the most elegant solution.

**Comment by scovertb** [comment]
For PC builds, you can access the EOS config containing those values in the StreamingAssets/EOS folder and change them without having to rebuild.
