### ISSUE TITLE
EpicOnlineServicesConfig.json

### ISSUE THREAD

**Issue by IvanLianto** [PlayEveryWare/eos_plugin_for_unity#133]
I uploaded it to epic but when I downloaded the game, I looked in the StreamingAssets -> EOS folder, I saw that there was an EpicOnlineServicesConfig.json file containing the Product ID, Sandbox ID, Client ID and so on, all of which were used to upload builds to Epic.

Is it possible for the EpicOnlineServicesConfig.json file to not be included in the build? So that players who download the game don't see it. Thank you

Screenshot:
![image](https://user-images.githubusercontent.com/45335913/191053106-665de9b5-de5c-41e0-b84a-5201f47bd445.png)
![image](https://user-images.githubusercontent.com/45335913/191056728-ae3ad441-b7cc-4934-b9c7-6da57e229da7.png)

**Comment by domlaurenti** [comment]
See this [previous Issue reported for this](https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/49)
