### ISSUE TITLE
Git conflict markers in DLLs in release v2.1.3

### ISSUE THREAD

**Issue by WI-Lee** [PlayEveryWare/eos_plugin_for_unity#139]
The native DLLs (DynamicLibraryLoaderHelper and GfxPluginNativeRender) just contain git lfs metadata and conflict markers instead of their real contents.

**Comment by domlaurenti** [comment]
Getting someone on the team to look at this directly.

**Comment by pew-dahs** [comment]
I've made a new 2.1.4 release that fixes the conflict marker issue so it should be working now. If it's still happening in the new release, feel free to reopen this issue.
