### ISSUE TITLE
Can't build UPM package on development

### ISSUE THREAD

**Issue by AndrewKahr** [PlayEveryWare/eos_plugin_for_unity#145]
**Describe the bug**
I am trying to build a Unity project targeting IOS and Android and use EOS. I see that on the development branch there is basic support for IOS and Android and this was commented on in #135 saying it's in a bootable state with functionality on most devices. As such, I am looking to build the plugin manually to test mobile support and potentially integrate it into our app. However, after trying to follow the documentation for building the plugin, I use the `Tools->Create Package` button, choose a build directory and choose `Create UPM Package` and end up with the error `NullReferenceException: Object reference not set to an instance of an object
UnityPackageCreationTool.OnGUI () (at Assets/Plugins/Source/Editor/Internal/UnityPackageCreationTool.cs:145)`. Also tried building a unitypackage and that didn't work either. When I tried stable, it was able to build UPM successfully but also not the unitypackage. Any ideas why this isn't building? Appreciate any help I can get on this, would love to use EOS for our mobile Unity game!

**To Reproduce**
1. Choose tools->Create Package
2. Choose output directory
3. Create UPM Package

**Expected behavior**
Builds UPM package from the development branch

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 x64
 - Unity Version: 2020.1.11f1 with Windows Mono, Windows IL2CPP, Mac Mono, Mac IL2CPP, Linux Mono, Linux IL2CPP, Android, and IOS
 - Plugin Version: Development Branch

**Comment by scovertb** [comment]
I wasn't able to reproduce this issue. As far as I can tell, if the null reference error you got is accurate, then the path to the required package description could not have been set, and trying to set the output path should have also produced an error. Does restarting the editor not resolve the issue?

**Comment by AndrewKahr** [comment]
Odd, just tried it again and now it's working. I must've not picked the path correctly. Thanks for trying it out, apologies it seems to just be user error!
