### ISSUE TITLE
How do I log in to the Samples?

### ISSUE THREAD

**Issue by ChronoSynth** [PlayEveryWare/eos_plugin_for_unity#15]

**Comment by adrianpew** [comment]
Hello.

1. Ensure you have an account with Epic and have created and configured a product via the [Epic Games Developer Portal](https://dev.epicgames.com/portal/)
2. [Configure the Unity plugin](https://github.com/PlayEveryWare/eos_plugin_for_unity#configuring-the-plugin)
3. Choose and Authentication Type:
- For Dev Auth, You'll need to install the [Developer Authentication Tool](https://dev.epicgames.com/docs/services/en-US/EpicAccountServices/DeveloperAuthenticationTool/index.html) from the Epic SDK and [configure it with your Epic account](https://github.com/PlayEveryWare/eos_plugin_for_unity#authentication)
- For Dev Portal, that will launch a browser and allow you to authenticate via the Epic Portal.
