### ISSUE TITLE
GfxPluginNativeRender-x64.lib set for Any Platform

### ISSUE THREAD

**Issue by AndrewKahr** [PlayEveryWare/eos_plugin_for_unity#152]
**Describe the bug**
`GfxPluginNativeRender-x64.lib` from the windows x64 runtime folder for a built plugin is set to `Any Platform` which causes it to be copied for any platform build when it doesn't work on iOS/Android. Doesn't cause any errors but throws warnings about it.

**To Reproduce**
1. Build develop and import the built upm tgz to new project
2. Look under `Packages/Epic Online Services Plugin for Unity/Runtime/Windows/x64/GfxPluginNativeRender-x64.lib`

**Expected behavior**
Should probably be set to exclude ios/Android (and possibly mac/linux)

**Screenshots**
![image](https://user-images.githubusercontent.com/22359829/196581676-63ce9c02-2f4e-4576-86e1-d1d716df23a2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 x64
 - Unity Version: 2022.2.0b10
 - Plugin Version: Development Branch@`a4d229abe3c22f5ec6ada1d9178fa04ec802e4b6`

**Comment by AndrewKahr** [comment]
Bump not fixed

**Comment by andrew-hirata-playeveryware** [comment]
I might be mistaken, but I believe that is a build artifact, that shouldn't be in the UPM at all. I will amend the package description file so that those library files aren't included.

**Comment by andrew-hirata-playeveryware** [comment]
This will be resolved in 2.1.6
