### ISSUE TITLE
Git URL package install issue

### ISSUE THREAD

**Issue by supernimbus-dev** [PlayEveryWare/eos_plugin_for_unity#16]
Hey There,

I first tried installing the plugin from git using the Unity package manager, as in the guide here.
I get an error from Unity when i try both URLs...

[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/PlayEveryWare/eos_plugin_for_unity_upm.git]:
  Cannot checkout repository [https://github.com/PlayEveryWare/eos_plugin_for_unity_upm.git]:
    Error when executing git command. git-lfs filter-process: git-lfs: command not found
    fatal: the remote end hung up unexpectedly
 [NotFound].
 
 I thought this was a Unity issue for mac but it appears on my windows machine also.

**Comment by supernimbus-dev** [comment]
Also...
I am using Unity 2020.1 and it is a fresh project with only the EOS package and the sample scenes installed.

**Comment by andrew-hirata-playeveryware** [comment]
I believe that's caused by git-lfs not being in the path or not being installed in the machine. I'm basing this on the line:
`git-lfs: command not found`

**Comment by adrianpew** [comment]
The following guide shows the git dependencies for Unity:
https://docs.unity3d.com/Manual/upm-git.html

Here is the section on Git LFS and unity:
https://docs.unity3d.com/Manual/upm-git.html#git-lfs

**Comment by adrianpew** [comment]
Let us know if you have more questions.

**Comment by supernimbus-dev** [comment]
Sorry for the delay in replying.
Yes, the issue was that LFS wasnt installed (had to dual-boot my mac as the package doesnt work on mac atm).
However, the first GIT URL still doesnt work. 
The second one is fine.
