### ISSUE TITLE
What to do with EOS Config File after Build

### ISSUE THREAD

**Issue by noahbare** [PlayEveryWare/eos_plugin_for_unity#162]
Possibly (hopefully) a dumb question that someone will know the answer to. 
After building the game in unity, under Assets > StreamingAssets > EOS, the user can access the EpicOnlineServicesConfig.json, which has all the EOS config data such as the encryption key, the client secret key, etc. Are we meant to have deleted this file and instead hardcode these values in in EOSManager.cs? 
Thanks for the help.

**Comment by noahbare** [comment]
I see this has been a [previous issue before](https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/49#issue-1081984032), so sorry about the duplicate.
I am now just setting `configDataAsString` in the EOSManager to the appropriate JSON in code, and commented out all code associated with pulling the config file. This seems to work and also hides the data from the StreamingAssets file on build. 
Does anyone see any reason why this shouldn't be done?

**Comment by AndrewKahr** [comment]
This is something I've been thinking about as well. In theory couldn't someone just copy the json files from a game's streaming assets and use the samples from this repo or a custom implementation in Unity to manipulate stuff like achievements, stats, leaderboards, cloud data, etc?

**Comment by noahbare** [comment]
> This is something I've been thinking about as well. In theory couldn't someone just copy the json files from a game's streaming assets and use the samples from this repo or a custom implementation in Unity to manipulate stuff like achievements, stats, leaderboards, cloud data, etc?

Exactly... I find this to be something that is unleasable for security reasons. 
Does anyone have this on a roadmap? Hardcoding in the config data in all of the locations that it's required seems to be a not great idea.

**Comment by andrew-hirata-playeveryware** [comment]
I wrote a [doc](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/docs/eos_config_security.md) a bit ago that goes over some of these issues. 

Concerning why it shouldn't be done that way: the overlay won't work on windows. The reason the config files are in plain text in streaming assets is because it needs to be parsed _before_ Unity is finished bootstrapping, i.e. before any scripts / C# code can be used. It's thus written in C++, which doesn't have access to the Assets, at least not without finding a way to reverse-engineer how unity writes and reads assets in standalone builds.

**Comment by AndrewKahr** [comment]
Perhaps we're attacking this problem from the wrong direction then. Let's continue with the assumption the config must remain in plaintext and this is easily attainable. Is there a way to add additional checks when accessing EOS that it's coming from your own application and not someone else's? Maybe via some kind of digital signature on the binary? Just spitballing ideas though, not sure whether that's even possible from a technical perspective.

**Comment by AndrewKahr** [comment]
Bump still needs a solution

**Comment by MerriemWeebster** [comment]
Wanted to know if a solution was ever reached for this, as this is quite concerning
