### ISSUE TITLE
Standalone Windows builds fail with v2.1.6

### ISSUE THREAD

**Issue by Rory-REDGames** [PlayEveryWare/eos_plugin_for_unity#164]
**Describe the bug**
When taking a sample project, Windows builds fail for multiple reasons in PostProcessing

**To Reproduce**
1. Create new Empty Unity project
2. Import "Epic Online Services Plugin for Unity" from downloaded tarball
3. Import in Samples
5. Configure "EpicOnlineServicesConfig.json"
6. Add a Sample Scene of choice.
7. Build Player for Windows

**Expected behavior**
Build finishes with no issues

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows x86, Windows x64, macOS Intel, macOS ARM]
 - Unity Version: 20203.3.25f
 - Plugin Version: v2.1.6

**Additional context**

- Bug#1 In "EOSOnPostprocessBuild_Windows.InstallBootStrapper()" it will always fail by default because the working directory does not exist. Simple work around 
- Bug#2 In "EOSOnPostprocessBuild_Windows.GenerateIntegrityCert()" will fail because the "/EAC/anticheat_integritytool.exe" is not apart of the package

**Comment by andrew-hirata-playeveryware** [comment]
Hey @Rory-REDGames, I believe a fix for the anti-cheat exe not being included made it into the 2.1.7 release; are you able to upgrade to that version and see if it works for you?
