### ISSUE TITLE
Android APK Build Fails

### ISSUE THREAD

**Issue by noahbare** [PlayEveryWare/eos_plugin_for_unity#169]
**Describe the bug**
When attempting to build an `.apk` file with `EOS_PREVIEW_PLATFORM` set to true and 'Custom Gradle Properties Template' set to true, I receive the following error: 
`Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :launcher
WARNING: The option setting 'android.enableR8=false' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\30.0.2\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-29\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-30\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\30.0.2\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-29\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-30\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\30.0.2\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-29\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-30\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only
File C:\Users\noahb\.android\repositories.cfg could not be loaded.
Checking the license for package Android SDK Build-Tools 30.0.3 in C:\Program Files\Unity\Hub\Editor\2021.3.13f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\licenses
Warning: License for package Android SDK Build-Tools 30.0.3 not accepted.`

**To Reproduce**
1. Create a new project and install Epic Online Services Plugin for Unity v2.1.6 via tarball
2. Enable EOS_PREVIEW_PLATFORM in project settings ("Scripting Define Symbols")
3. Enable 'Custom Gradle Properties Template' in Publishing Settings
4. Attempt to build

**Expected behavior**
To have a happy little .apk file built

**Screenshots**
![image](https://user-images.githubusercontent.com/50649628/204371729-2f7a009f-7df8-44ec-bb14-32ba87095c50.png)

**Desktop**
 - OS: Windows 11 x64
 - Unity Version: 2021.3.13f1
 - Plugin Version: 2.1.6

**Comment by andrew-hirata-playeveryware** [comment]
I can't see the entire error, but it appears you haven't accepted the Android build license. That might be causing the error.

**Comment by noahbare** [comment]
> I can't see the entire error, but it appears you haven't accepted the Android build license. That might be causing the error.

I believe that was the primary issue! I have also been attempting to follow the instruction in [docs](https://github.com/PlayEveryWare/eos_plugin_for_unity/tree/stable/docs)/[android](https://github.com/PlayEveryWare/eos_plugin_for_unity/tree/stable/docs/android)/readme_android.md and I don't think I fully understand. Is this still required to get the android build working in the latest version? 
Or overall what extra/special steps do I need to take to get the android build working as opposed to just the base windows build?

**Comment by andrew-hirata-playeveryware** [comment]
For 2.1.6 yes: you'll need to follow those instructions. For 2.1.7, android will be enabled by default.

**Comment by noahbare** [comment]
> For 2.1.6 yes: you'll need to follow those instructions. For 2.1.7, android will be enabled by default.

After following those steps using Android Studio, everything seems to be working, thanks for the assistance!
