### ISSUE TITLE
Logging in with Oculus Fails

### ISSUE THREAD

**Issue by noahbare** [PlayEveryWare/eos_plugin_for_unity#171]
**Describe the bug**
As described on [this Epic Games post](https://eoshelp.epicgames.com/s/question/0D54z00008UK0Q6CAL/connect-interface-login-with-oculus-issues?language=en_US):
I've obtained the display name, local user id, and a nonce from the oculus sdk, and am now trying to log on with this information.
When using `StartConnectLoginWithOptions`, I pass in the following parameters: `(ExternalCredentialType.OculusUseridNonce, name, $"{{{myId}}}|{{{userProof.Value}}}", OnLoginCallback)`. The token is said to be formatted as the string "{UserID}|{Nonce}" based on the response from the Epic Games staff. 

The error received is: 

> 2022-12-02T15:51:44.1914230-06:00 LogEOS(Warning): Error response received from backend. ServiceName=[EOSAuth], OperationName=[TokenGrant], Url=[<Redacted>], HttpStatus=[401], ErrorCode=[errors.com.epicgames.eos.auth.external.invalid_token], NumericErrorCode=[110013], ErrorMessage=[Invalid Oculus user ID or App ID], CorrId=[EOS-X4gNrmtEY0wXJ12bcIrn0Q-uMDR7BJPUM38246sXYQ1PA-B5Oh9oNMsroyQa27FifuhA]

**To Reproduce**
1. In a new project, retrieve the required data from the oculus sdk (display name, local user id, and nonce; from GetUserProof and GetLoggedInUser)
2. Attempt to login using the correctly formatted data with the function `StartConnectLoginWithOptions`.
3. Notice the error

**Expected behavior**
I would expect the login at this point to be successful (or to result in either a result code of Result.Success or Result.InvalidUser).

**Screenshots**
Code: 
![image](https://user-images.githubusercontent.com/50649628/205397420-4346a6f1-375e-4e5c-a3ef-df73c5a0d839.png)
I also added a case for the oculus external credential type to no avail: 
![image](https://user-images.githubusercontent.com/50649628/205397601-2fad8dc3-b0a2-419b-96d6-0a05ac8d2696.png)

**Desktop:**
OS: Windows 11 x64
Unity Version: 2021.3.13f1
Plugin Version: 2.1.6

**Comment by noahbare** [comment]
Bump *

**Comment by vikramkapoor** [comment]
I am going to try on Oculus too. Hopefully this isn't a blocker.

**Comment by noahbare** [comment]
> I am going to try on Oculus too. Hopefully this isn't a blocker. Have you tried with version 2.1.7?

I have not tried v2.1.7 after the hoops I went through to get v2.1.6 working lol. Let me know if that works for you and then I'll make the switch as well!

**Comment by vikramkapoor** [comment]
I integrated 2.1.7 with my game on Oculus. I believe the only issue I ran into was to use a different Android SDK. Will let you know soon.
Vikram
    On Monday, December 12, 2022 at 04:27:04 PM PST, noahbare ***@***.***> wrote:  
 
 



I am going to try on Oculus too. Hopefully this isn't a blocker. Have you tried with version 2.1.7?


I have not tried v2.1.7 after the hoops I went through to get v2.1.6 working lol. Let me know if that works for you and then I'll make the switch as well!

**Comment by vikramkapoor** [comment]
Unfortunately I am getting the same error in v2.1.7 :( Seems like this plugin doesn't support Oculus. Will try with straight EOS C# SDK next.

**Comment by vikramkapoor** [comment]
Sorry, I am not sure what error I got yesterday. I debugged it more just now. 

On line 943 in EOSManager.cs

if (connectLoginData.LocalUserId != null)


my LocalUserId is null. 

The loginCallbackInfo.ResultCode I am getting is different than yours. It is ConnectExternalServiceConfigurationFailure. So I am wondering why my LocalUserId is null as the next step.

**Comment by noahbare** [comment]
> Sorry, I am not sure what error I got yesterday. I debugged it more just now.
> 
> On line 943 in EOSManager.cs
> 
> if (connectLoginData.LocalUserId != null)
> 
> my LocalUserId is null.
> 
> The loginCallbackInfo.ResultCode I am getting is different than yours. It is ConnectExternalServiceConfigurationFailure. So I am wondering why my LocalUserId is null as the next step.

Do you have some sort of Oculus platform manager in your scene? That should run the entitlement check,  then attempt to login the user, and finally get the userProof (nonce). In the `userProofCallback` is where I then attempt to authenticate the user with EOS Connect Interface where I'll for sure have the LocalUserId (assuming a ResultCode.Success).

**Comment by vikramkapoor** [comment]
![image](https://user-images.githubusercontent.com/3178673/207370262-ffd28f2f-6431-4aeb-a435-c0701dc8e24b.png)

**Comment by vikramkapoor** [comment]
> See above image connectLoginData is not populated and it even has the ResultCode ready to return.

I attached EOSManager.cs to the Oculus PlatformManager in my scene. Here is my calling code after the Oculus entitlement check where I call StartConnectLoginWithOptions.  All the parameters seem fine in that call so I am don't know what else is needed. Should connectLoginData.LocalUserId be null at this point or is this the issue because I need to call/do something else before calling EOSManager.Instance.StartConnectLoginWithOptions?

 ```
		private void GetUserProof()
		{
			Users.GetUserProof().OnComplete(OnUserProofCallback);
		}

		private void OnUserProofCallback(Message<UserProof> msg)
		{
			if (msg.IsError)
			{
				Debug.LogErrorFormat("Oculus: Error getting user proof. Error Message: {0}",
					msg.GetError().Message);
			}
			else
			{
				string oculusNonce = msg.Data.Value;
			    EOSManager.Instance.StartConnectLoginWithOptions(Epic.OnlineServices.ExternalCredentialType.OculusUseridNonce, MyOculusID, $"{{{MyID}}}|{{{oculusNonce}}}", OnLoginCallback);
			}
		}
```

**Comment by noahbare** [comment]
> ![image](https://user-images.githubusercontent.com/3178673/207370262-ffd28f2f-6431-4aeb-a435-c0701dc8e24b.png)

After a bit more debugging, my code never makes it to this callback. This is where I receive the error `ErrorCode=[errors.com.epicgames.eos.auth.external.invalid_token]`. So later today I'll make the jump to v2.1.7 and see if I make it past that point.

**Comment by vikramkapoor** [comment]
That's interesting. It seems that you are getting further than I am. You must have the connectLoginData populated somehow or v2.1.6 is just different code.

**Comment by vikramkapoor** [comment]
Setting up Oculus Identity provider in EOS dashboard didn't make a difference.

**Comment by vikramkapoor** [comment]
I was missing attaching the Oculus Identity provider to the application Sandbox. Once I did that the Error type has changed
to ConnectExternalTokenValidationFailed from ConnectExternalServiceConfigurationFailure. Why is the TokenValidation failing?
![image](https://user-images.githubusercontent.com/3178673/207480322-8b731b18-4411-47b8-ab4a-7499fbdb20f5.png)

**Comment by vikramkapoor** [comment]
This is the message I am getting from EOS       Error response received from backend. ServiceName=[EOSAuth], OperationName=[TokenGrant], Url=[<Redacted>], HttpStatus=[401], ErrorCode=[errors.com.epicgames.eos.auth.external.invalid_token], NumericErrorCode=[110013], ErrorMessage=[Invalid Oculus user ID or App ID], CorrId=[EOS-zmTDgENLUYQeiUCrR_Juxw-iJZ4-VhCaE3LAPSNSiLlxw-b2qwCdJLGZaze8aipon7hg]"

**Comment by vikramkapoor** [comment]
https://forums.unrealengine.com/t/redpoint-eos-quest-2-disconnection/560153
Above link says the same error was resolved by turning trusted server off in the project settings in UE.

**Comment by noahbare** [comment]
After updating to v2.1.7, adding this case: 
![image](https://user-images.githubusercontent.com/50649628/207639232-22cdb2db-4a3f-488d-be3d-bfeb8f9ea0ad.png)
And then I misunderstood the token format (I thought it wanted a curly brace included), after changing my token from:
`$"{{{myId}}}|{{{userProof.Value}"` to `$"{myId}|{userProof.Value}"`, the login works for me! 

So in the end, this works for me: 
```
public void LoginOculusUser()
    {
        string name = PlatformManager.MyOculusID.ToString();
        UserProof userProof = PlatformManager.MyUserProof;
        ulong myId = PlatformManager.MyID;
        if (userProof == null || string.IsNullOrEmpty(name) || myId <= 0) { return; }

        EOSManager.Instance.StartConnectLoginWithOptions(ExternalCredentialType.OculusUseridNonce, name, $"{myId}|{userProof.Value}", OnLoginCallback);
    }

    /// <summary>
    /// What to do after attempting to login with a steam session ticket
    /// </summary>
    /// <param name="loginCallbackInfo"></param>
    private void OnLoginCallback(Epic.OnlineServices.Connect.LoginCallbackInfo loginCallbackInfo)
    {
        if (loginCallbackInfo.ResultCode.Equals(Result.Success))
        {
            Debug.Log(MethodBase.GetCurrentMethod().Name + " - User recognized, and logged in.");
        }
        else if (loginCallbackInfo.ResultCode.Equals(Result.InvalidUser))
        {
            // User does not have a productId associated with them, so we'll make an epic games account for them
            Debug.Log(MethodBase.GetCurrentMethod().Name + " - User not recognized, creating new user.");
            EOSManager.Instance.CreateConnectUserWithContinuanceToken(loginCallbackInfo.ContinuanceToken, OnCreateUserCallback);
        }
        else
        {
            Debug.Log("It failed");
        }
    }

    /// <summary>
    /// Create a new epic games user using the continuence token provided by the steam login attempt
    /// </summary>
    /// <param name="createUserCallbackInfo"></param>
    private void OnCreateUserCallback(Epic.OnlineServices.Connect.CreateUserCallbackInfo createUserCallbackInfo)
    {
        if (createUserCallbackInfo.ResultCode.Equals(Result.Success))
        {
            Debug.Log(MethodBase.GetCurrentMethod().Name + " - User created successfully with ProductId: " + createUserCallbackInfo.LocalUserId);
        }
    }
```
(Note: I know if you get back an invalid user, you're supposed to first attempt to allow them to link to an existing epic games account per their docs but I was just trying to get this thing to work first)

**Comment by vikramkapoor** [comment]
Great. I was also suspecting the curly bracket and wanted to try with those removed. Great teamwork. We did it :)
    On Wednesday, December 14, 2022 at 07:46:36 AM PST, noahbare ***@***.***> wrote:  
 
 


After updating to v2.1.7, adding this case:

And then I misunderstood the token format (I thought it wanted a curly brace included), after changing my token from:
$"{{{myId}}}|{{{userProof.Value}" to $"{myId}|{userProof.Value}", the login works for me!

So in the end, this works for me:
public void LoginOculusUser()
    {
        string name = PlatformManager.MyOculusID.ToString();
        UserProof userProof = PlatformManager.MyUserProof;
        ulong myId = PlatformManager.MyID;
        if (userProof == null || string.IsNullOrEmpty(name) || myId <= 0) { return; }

        EOSManager.Instance.StartConnectLoginWithOptions(ExternalCredentialType.OculusUseridNonce, name, $"{myId}|{userProof.Value}", OnLoginCallback);
    }

    /// <summary>
    /// What to do after attempting to login with a steam session ticket
    /// </summary>
    /// <param name="loginCallbackInfo"></param>
    private void OnLoginCallback(Epic.OnlineServices.Connect.LoginCallbackInfo loginCallbackInfo)
    {
        if (loginCallbackInfo.ResultCode.Equals(Result.Success))
        {
            Debug.Log(MethodBase.GetCurrentMethod().Name + " - User recognized, and logged in.");
        }
        else if (loginCallbackInfo.ResultCode.Equals(Result.InvalidUser))
        {
            // User does not have a productId associated with them, so we'll make an epic games account for them
            Debug.Log(MethodBase.GetCurrentMethod().Name + " - User not recognized, creating new user.");
            EOSManager.Instance.CreateConnectUserWithContinuanceToken(loginCallbackInfo.ContinuanceToken, OnCreateUserCallback);
        }
        else
        {
            Debug.Log("It failed");
        }
    }

    /// <summary>
    /// Create a new epic games user using the continuence token provided by the steam login attempt
    /// </summary>
    /// <param name="createUserCallbackInfo"></param>
    private void OnCreateUserCallback(Epic.OnlineServices.Connect.CreateUserCallbackInfo createUserCallbackInfo)
    {
        if (createUserCallbackInfo.ResultCode.Equals(Result.Success))
        {
            Debug.Log(MethodBase.GetCurrentMethod().Name + " - User created successfully with ProductId: " + createUserCallbackInfo.LocalUserId);
        }
    }

(Note: I know if you get back an invalid user, you're supposed to first attempt to allow them to link to an existing epic games account per their docs but I was just trying to get this thing to work first)
