### ISSUE TITLE
 The name 'AndroidFileIOHelper' does not exist in the current context

### ISSUE THREAD

**Issue by vikramkapoor** [PlayEveryWare/eos_plugin_for_unity#172]
**Describe the bug**
I followed the instructions to download and import this plugin from github and I got above error.
 
**To Reproduce**
1. On Unity 2021.2.17f1 go to package manager
2. Select "Install package from git URL...."
3. Click on import.

**Expected behavior**
The error shouldn't be there and plugin import should complete.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows x86, Windows x64, macOS Intel, macOS ARM]
 - Unity Version 2021.2.17f1
 - Plugin Version 2.1.4

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Oculus Quest 2
 - Unity Version
 - Plugin Version

**Additional context**
I don't get this error when installing from tarball because that installs 2.1.7 not 2.1.4.

**Comment by vikramkapoor** [comment]
I don't get this error when I install 2.1.7 from tarball

**Comment by andrew-hirata-playeveryware** [comment]
> I don't get this error when I install 2.1.7 from tarball

Do you mean that it's working in the official 2.1.7, just not in the older version?

**Comment by vikramkapoor** [comment]
That is correct. When I installed from github url it installed version 2.1.4 instead of 2.1.7.
    On Monday, December 5, 2022 at 02:47:39 PM PST, andrew ***@***.***> wrote:  
 
 



I don't get this error when I install 2.1.7 from tarball


Do you mean that it's working in the official 2.1.7, just not in the older version?

**Comment by andrew-hirata-playeveryware** [comment]
I think this might be an issue that was resolved, if I understand you correctly: the UPM repo might not have been updated at the time, but should be working now.

**Comment by vikramkapoor** [comment]
That sounds reasonable. I haven't tested it since I already have it installed.
