### ISSUE TITLE
Suggestion: Add AuthScopeFlags to EOS Config Editor window

### ISSUE THREAD

**Issue by Jamez0r** [PlayEveryWare/eos_plugin_for_unity#175]
Hello, first off thanks so much for the plugin. I'd like to suggest adding the AuthScopeFlags options to the EOS Config Editor window.

The example scenes are assuming that the AuthScopeFlags should be BasicProfile, FriendsList, and Presence. 

On the dev portal, there is the (supposedly new?) option of including "Country". My project was configured to include it. I spent a couple hours trying to figure out why I couldn't connect/auth - I was getting the error "The User Has Not Consented To The Required Scopes". And being new to this whole system, trying to figure out if it was a Dev Auth Tool problem, or what the actual source of the problem was, was very difficult. 

After figuring out it was the AuthScopeFlags needing to match my Dev Portal's permission configuration, I was able to make a custom "LoginOptions" and get connected.

By adding the AuthScopeFlags to the EOS Config Editor window, it would not only allow new users to make sure they match, but it would also point out that they DO need to match.

Thanks again!

Edit: Just to add another request for future users that are new to the whole system - it's a bit intimidating figuring out how to use the Dev Auth Tool and the EOS Plugin at the same time. I think it would help a lot of people out if the EOS Config Editor window had tooltips (the popups you get when hovering over the text) for each of the fields in the window).

In my case, I was having a lot of trouble figuring out the Dev Auth Tool and getting connected, and the whole time I was wondering if I had the EOS Config Editor window set up correctly. Did I need to do something with the Thread Affinity fields? What is the Time Budget in millisecond field? Etc. If there was a tooltip popup that had a brief explanation and also said "Optional" if they were optional, that would have helped narrow things down when trying to figure out why I couldn't connect.

**Comment by scovertb** [comment]
I added AuthScopeFlags to the EOS config, which should make it into the next release. Descriptions of the config options can be found in EOSConfig.cs, but I'll look into adding tooltips for them.

**Comment by Jamez0r** [comment]
> I added AuthScopeFlags to the EOS config, which should make it into the next release. Descriptions of the config options can be found in EOSConfig.cs, but I'll look into adding tooltips for them.

Much appreciated!
