### ISSUE TITLE
EasyAntiCheat now included in build? Is it needed when uploading?

### ISSUE THREAD

**Issue by Jamez0r** [PlayEveryWare/eos_plugin_for_unity#176]
Hey guys, testing out the plugin for the first time and just did a standalone build.

I noticed the build had some new files - some related to the EOSBootstrapper, and then some related to EasyAntiCheat.

Am I correct that the EOSBootstrapper.exe is what my BuildPatchTool should have as the executable?

And whats up with the EasyAntiCheat files? Are they necessary? Can I opt to not include them when uploading the build via BuildPatchTool?

Thanks a lot for the info!

**Comment by scovertb** [comment]
Yes, EOSBootstrapper.exe should be the target executable, although you can rename it as long as you also rename EOSBootStrapper.ini to match. If you're not using EAC you can delete those files from the build, and I'll add some build config options to disable EAC.

**Comment by scovertb** [comment]
The config option should be available in the next release.
