### ISSUE TITLE
Getting plugin working in Unity 2019

### ISSUE THREAD

**Issue by rtgray** [PlayEveryWare/eos_plugin_for_unity#177]
**Describe the bug**
I was directed to ask here if there was any way of getting this plugin to work with Unity 2019. I assume I'm probably out of luck based on the notes about Unity 2020 and up :) 

Currently when I import the most recent tarbell (2.1.7) I get the following console errors:

Library\PackageCache\com.playeveryware.eos@70dd031ff111-1670023234523\Runtime\Android\AndroidFileIOHelper.cs(18,25): error CS1061: 'UnityWebRequest' does not contain a definition for 'result' and no accessible extension method 'result' accepting a first argument of type 'UnityWebRequest' could be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.playeveryware.eos@70dd031ff111-1670023234523\Runtime\Android\AndroidFileIOHelper.cs(18,74): error CS0117: 'UnityWebRequest' does not contain a definition for 'Result'

Library\PackageCache\com.playeveryware.eos@70dd031ff111-1670023234523\Runtime\Android\AndroidFileIOHelper.cs(21,91): error CS1061: 'UnityWebRequest' does not contain a definition for 'result' and no accessible extension method 'result' accepting a first argument of type 'UnityWebRequest' could be found (are you missing a using directive or an assembly reference?)

**To Reproduce**
1. Followed the steps to import 2.1.7.tgz into our project and got these errors when it tried to compile.

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Unity Version: Unity 2019.4.16f1
 - Plugin Version: 2.1.7

**Comment by arthur740212** [comment]
Thank you for reporting this, we are looking into it now.

**Comment by rtgray** [comment]
Awesome, thanks! I am on the road for the holidays already, so this will probably get to be my first 2023 task to check out!
