### ISSUE TITLE
Leaderboards Sample Scene - Error

### ISSUE THREAD

**Issue by supernimbus-dev** [PlayEveryWare/eos_plugin_for_unity#18]
Hey There,

After i login to the LB sample scene and the scene loads, i get an error when the scene tried to fetch the LB definitions.

Leaderboard (LeaderboardDefinitionsReceivedCallbackFn): QueryDefinitions error: UnrecognizedResponse
UnityEngine.Debug:LogErrorFormat (string,object[])
PlayEveryWare.EpicOnlineServices.Samples.EOSLeaderboardManager:LeaderboardDefinitionsReceivedCallbackFn (Epic.OnlineServices.Leaderboards.OnQueryLeaderboardDefinitionsCompleteCallbackInfo) (at Assets/Samples/Epic Online Services Plugin for Unity/1.0.1/EOS Plugin for Unity Samples/Scripts/EOSLeaderboardManager.cs:220)
Epic.OnlineServices.Leaderboards.LeaderboardsInterface:OnQueryLeaderboardDefinitionsCompleteCallbackInternalImplementation (intptr) (at Library/PackageCache/com.playeveryware.eos@cc1b23eabb12-1630406260137/Runtime/EOS_SDK/Generated/Leaderboards/LeaderboardsInterface.cs:426)
Epic.OnlineServices.Platform.PlatformInterface:Tick () (at Library/PackageCache/com.playeveryware.eos@cc1b23eabb12-1630406260137/Runtime/EOS_SDK/Generated/Platform/PlatformInterface.cs:738)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Tick () (at Library/PackageCache/com.playeveryware.eos@cc1b23eabb12-1630406260137/Runtime/EOSManager.cs:743)
PlayEveryWare.EpicOnlineServices.EOSManager:Update () (at Library/PackageCache/com.playeveryware.eos@cc1b23eabb12-1630406260137/Runtime/EOSManager.cs:841)

... I have 3 test Leaderboards set up. 1 has ended and the other two are active.
Because of this error, there are no LBs loaded into the UI for me to test so i am stuck at the moment.

**Comment by supernimbus-dev** [comment]
Also...
I am using Unity 2020.1 and it is a fresh project with only the EOS package and the sample scenes installed.

**Comment by adrianpew** [comment]
Hello,

In the [Epic dev portal](https://dev.epicgames.com/portal/en-US/), ensure you are targeting the same deployment as what your samples is configured to.  Also make sure you have 'Active' leaderboards:
![image](https://user-images.githubusercontent.com/60490038/131904623-524bc489-7fa4-4d4a-ba99-b0c24d1c3ea3.png)

Also make sure your client policy allows actions:
![image](https://user-images.githubusercontent.com/60490038/131904658-d11c6a47-e0fe-416b-a1f3-3c0095deb91b.png)

Additionally, I found a similar error code on the Epic forums.  Investigating if this can happen in the samples.
https://eoshelp.epicgames.com/s/question/0D52L00004XsLS2SAN/update-unity-lobbysearchfind-result-is-unrecognizedresponse?language=en_US

In the meantime, let us know if the dev portal settings are correct and you still get this error.  Also, please confirm your on [Release 1.0.1](https://github.com/PlayEveryWare/eos_plugin_for_unity/releases/tag/v1.0.1)

Thanks.

**Comment by adrianpew** [comment]
Let us know if you have more questions.

**Comment by supernimbus-dev** [comment]
Thanks,
Sorry for the delay in replying.

Yes, i have active and inactive Leaderboards configured, all tests at the moment
![eos1](https://user-images.githubusercontent.com/58340684/132628401-7260ef4e-1c4d-4d75-bc4c-59ddcdd9ffe5.PNG)
...

The client features list includes LBs...
![eos2](https://user-images.githubusercontent.com/58340684/132628445-5346b13b-077e-4dbf-b890-16268d5eeb58.PNG)

And i can confirm i am on v1.0.1

I still get this error, but a collegue has another project setup with Leaderboard which all all active, none have ended and he is not seeing this issue. Could it be a problem retriving ended LBs?

**Comment by adrianpew** [comment]
Apologies for the delay.  I'm not 100% sure what problem you are having.  I would recommend seeing if running the EOS SDK C++ Native Sample for Leaderboard has the same issues in your environment.  You can also use the Dev Portal's Leaderboard dashboard to see what entries should be displayed.

We have seen similar issues internally dealing with the START and END time of your leaderboard.  I believe those are UTC, but have noticed that stats ingested sometimes won't land in the timespan.

**Comment by adrianpew** [comment]
You may validate your backend setup using the C++ native samples provided by Epic.  That should let you know if the behaviour is with the C# plugin or a backend configuration.  Let us know if you need more Unity Plugin help.  For specific questions unrelated to the Unity Plugin, note that Epic has [forums available](https://eoshelp.epicgames.com/s/?language=en_US), which might provide more insight on Leaderboard configurations.
