### ISSUE TITLE
Compiling error "cannot convert from 'string' to 'char'" in v2.1.7

### ISSUE THREAD

**Issue by RikuTheFuffs** [PlayEveryWare/eos_plugin_for_unity#184]
**Describe the bug**
A compiling error makes the package unusable the error is:

"cannot convert from 'string' to 'char'"

**To Reproduce**
1. Create a new project using Unity 2020.3.26f1
2. Add the package through the package manager, using `https://github.com/PlayEveryWare/eos_plugin_for_unity_upm.git#v2.1.7` as the it address
3. Wait until it is imported
4. The compilation error appears

**Expected behavior**
No errors appear

**Screenshots**
![image](https://user-images.githubusercontent.com/27730963/208726087-bf22f22d-74f0-42f1-bd61-a94708c154da.png)

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Unity: 2020.3.26f1
 - Plugin Version: v2.1.7 tag

**Comment by scovertb** [comment]
A fix for this will be included in the next release.
