### ISSUE TITLE
NetCode.GameObjects transport (I'm actually making it but need a bit of help)

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [PlayEveryWare/eos_plugin_for_unity#187]
**Is your feature request related to a problem? Yes in unity people usually use NetCode.GameObjects for networking and without a transport, many people cannot use the networking feature.
This doesn't require any support outside the SDK.
**Describe the solution you'd like**
A EOSTransport for NetCode.GameObjects and later on DOTS NetCode.

**Describe alternatives you've considered**
I've considered making this myself or not go through Netcode.GameObjects at all. I probably with some help can get to the solution faster. 
As far as not going through the higher level library. Doesn't make much sense for a game with a very low number of players.

**Additional context**
Can you tell me if you guy are up to offerring some help and also if you are working on something similar?

Thanks

**Comment by scovertb** [comment]
An sample with a NetworkTransport using the EOS P2P interface will be in the next release. No plans currently for DOTS NetCode.
