### ISSUE TITLE
PlayerData Sample Scene - Error

### ISSUE THREAD

**Issue by supernimbus-dev** [PlayEveryWare/eos_plugin_for_unity#19]
Hey There,

I am getting an error in the PlayerData sample scene after login.

For the PlayerData scene I get an error when it loads...

NullReferenceException: Object reference not set to an instance of an object
PlayEveryWare.EpicOnlineServices.Samples.EOSPlayerDataStorageManager.QueryFileList () (at Assets/Samples/Epic Online Services Plugin for Unity/1.0.1/EOS Plugin for Unity Samples/Scripts/EOSPlayerDataStorageManager.cs:74)
PlayEveryWare.EpicOnlineServices.Samples.EOSPlayerDataStorageManager.OnLoggedIn () (at Assets/Samples/Epic Online Services Plugin for Unity/1.0.1/EOS Plugin for Unity Samples/Scripts/EOSPlayerDataStorageManager.cs:522)
PlayEveryWare.EpicOnlineServices.Samples.UIPlayerDataStorageMenu.ShowMenu () (at Assets/Samples/Epic Online Services Plugin for Unity/1.0.1/EOS Plugin for Unity Samples/Scripts/UI/UIPlayerDataStorageMenu.cs:201)
UnityEngine.Events.InvokableCall.Invoke () (at <f7f0a900fdf94a2a9316bb3d4c5aa3e8>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <f7f0a900fdf94a2a9316bb3d4c5aa3e8>:0)
PlayEveryWare.EpicOnlineServices.Samples.UILoginMenu.ConfigureUIForLogout () (at Assets/Samples/Epic Online Services Plugin for Unity/1.0.1/EOS Plugin for Unity Samples/Scripts/UI/UILoginMenu.cs:276)
PlayEveryWare.EpicOnlineServices.Samples.UILoginMenu+<>c__DisplayClass30_0.<StartConnectLoginWithLoginCallbackInfo>b__0 (Epic.OnlineServices.Connect.LoginCallbackInfo connectLoginCallbackInfo) (at Assets/Samples/Epic Online Services Plugin for Unity/1.0.1/EOS Plugin for Unity Samples/Scripts/UI/UILoginMenu.cs:371)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton+<>c__DisplayClass20_0.<StartConnectLoginWithEpicAccount>b__0 (Epic.OnlineServices.Connect.LoginCallbackInfo connectLoginData) (at Library/PackageCache/com.playeveryware.eos@cc1b23eabb12-1630406260137/Runtime/EOSManager.cs:506)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton+<>c__DisplayClass22_0.<StartConnectLoginWithOptions>b__0 (Epic.OnlineServices.Connect.LoginCallbackInfo connectLoginData) (at Library/PackageCache/com.playeveryware.eos@cc1b23eabb12-1630406260137/Runtime/EOSManager.cs:549)
Epic.OnlineServices.Connect.ConnectInterface.OnLoginCallbackInternalImplementation (System.IntPtr data) (at Library/PackageCache/com.playeveryware.eos@cc1b23eabb12-1630406260137/Runtime/EOS_SDK/Generated/Connect/ConnectInterface.cs:854)
Epic.OnlineServices.Platform.PlatformInterface.Tick () (at Library/PackageCache/com.playeveryware.eos@cc1b23eabb12-1630406260137/Runtime/EOS_SDK/Generated/Platform/PlatformInterface.cs:738)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Tick () (at Library/PackageCache/com.playeveryware.eos@cc1b23eabb12-1630406260137/Runtime/EOSManager.cs:743)
PlayEveryWare.EpicOnlineServices.EOSManager.Update () (at Library/PackageCache/com.playeveryware.eos@cc1b23eabb12-1630406260137/Runtime/EOSManager.cs:841)

**Comment by supernimbus-dev** [comment]
Also...
I am using Unity 2020.1 and it is a fresh project with only the EOS package and the sample scenes installed.

**Comment by adrianpew** [comment]
In the Epic dev portal, make sure your client policy allows actions:
![image](https://user-images.githubusercontent.com/60490038/131907165-ffc07690-3ab6-4f0c-b517-f84528b635be.png)

Are you running this in the Unity Editor? And are you able to debug?

It looks like you may be getting a null ref when trying to EOSPlayerDataStorageManager.QueryFileList().  I'm wondering if there is a valid user.

**Comment by andrew-hirata-playeveryware** [comment]
I believe this might be caused when the Encryption key isn't configured for the plugin. This can be configured via `Tools -> EpicOnlineServicesConfigEditor`.

**Comment by adamsingle** [comment]
Where does this encryption key come from? I can't see it anywhere in the dashboard.

**Comment by adrianpew** [comment]
The encryption key is something you have to decide on and create yourself.  Note that Epic does not store the encryption key in the cloud, so it is something you have to store and manage yourself.

For PlayerDataStorage:
https://dev.epicgames.com/docs/services/en-US/GameServices/PlayerDataStorage/index.html#datacachingandencryption
`Player Data Storage files are always stored with encryption, using the key you provide during EOS Platform initialization. The encryption key itself is not stored on the cloud, preventing both Epic Games and malicious third parties from using the key to access clients' data. Encryption keys are automatically modified for each user, so different users cannot decrypt each other's data.`

For TitleDataStorage:
https://dev.epicgames.com/docs/services/en-US/GameServices/TitleStorage/index.html#datacachingandencryption
`Title Storage files are always stored with encryption, using the key you provide during EOS Platform initialization. The encryption key itself is not stored on the cloud, preventing both Epic Games and malicious third parties from using the key to access data. Encryption key is identical for all the users of a product.`

**Comment by adrianpew** [comment]
Let us know if you have more questions.

**Comment by supernimbus-dev** [comment]
Thanks, sorry for the delay.
Adding a hex string (32 characters) works!
