### ISSUE TITLE
FAccountPortalBrowserManager error when trying to run after adding configuration 

### ISSUE THREAD

**Issue by gotenxds** [PlayEveryWare/eos_plugin_for_unity#191]
**Describe the bug**
Getting the following warning when running the game 
```
2023-01-04T00:52:46.7337358+02:00 LogEOSAuth(Warning): FAccountPortalBrowserManager::Init: Failed to register overlay: EOS_NotConfigured
```
It's a warning but I debugged the code and when this warning shows it means I dont get a `LocalUserId` for the EOSTransport manager (line368) which gives other errors later on

**Expected behavior**
I Assume the browser to open and request a login

**Screenshots**

**Desktop (please complete the following information):**
Windows x64
 - Unity Version 2022.2.0b16
 - Plugin Version 2.1.7

**Comment by andrew-hirata-playeveryware** [comment]
If it's warning that the overlay isn't configured, it's possible that the EOSConfig for your project is configured to use the overlay (which is the default), but you're not launching the game with the EOSbootstrapper, which I believe is still required to get the overlay to work correctly.

It's possible to disable the overlay if you'd like via the platform option flag  ```EOS_PF_DISABLE_OVERLAY``` flag, which you can add to platform options flag in the EpicOnlineServiceConfigEditor tool in the Unity (Tools -> EpicOnlineServiceConfigEditor).
