### ISSUE TITLE
EOS_DISABLE not working

### ISSUE THREAD

**Issue by Shpek** [PlayEveryWare/eos_plugin_for_unity#192]
It seems that the EOS_DISABLE preprocessor symbol is not working since release 2.1.3. The Runtime/EOS_SDK/Core/Config.cs is missing the code that handles the symbol. There's a bunch of other changes to the file too (like removing the PS5 code).
Last version that's working is 2.1.2. The file is OK in the main repo - the change is only in the packaged releases.

![image](https://user-images.githubusercontent.com/2659777/210881811-64a1504c-8a58-4702-8f5d-b5fba18cd1f3.png)

**Comment by scovertb** [comment]
This will be fixed in an upcoming release.

**Comment by scovertb** [comment]
This is fixed in release 2.1.8.
