### ISSUE TITLE
Duplicate Android Plugin Error

### ISSUE THREAD

**Issue by AndrewKahr** [PlayEveryWare/eos_plugin_for_unity#194]
**Describe the bug**
When trying to build an Android APK, it throws the error `Found plugins with same names, Packages/com.playeveryware.eos/Runtime/Android/eos-sdk.aar and Assets/Plugins/Android/eos-sdk.aar. Delete the one of the duplicate plugins`

**To Reproduce**
1. Create a upm package of the latest develop branch
2. Import samples
3. Switch to android
4. Attempt the build

**Expected behavior**
Build succeeds

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Unity Version: 2022.2.0f1
 - Plugin Version: Latest Develop

**Comment by andrew-hirata-playeveryware** [comment]
Hello AndrewKahr,
Just to double check, do you have an extra version of the eos-sdk.aar on disk? If you delete the one under Assets/Pluins/Android/eos-sdk.arr, does the issue still occur?

**Comment by AndrewKahr** [comment]
I've tried deleting the entire plugins folder but the plugin will regenerate the folder and throw the error.

**Comment by arthur740212** [comment]
Hi, we weren't able to reproduce the issue you were facing, were you using importing the package on an empty project?
Additionally, good news is that there was an update related to the package a couple of days ago.
Would be nice to give it a try, and feel free to report the new problems you find.

**Comment by AndrewKahr** [comment]
@arthur740212 Gave it another try with a fresh project and a fresh build of the latest develop branch but I'm still running into the issue. Note that I am running Unity 2022.2.X and not 2021.3.X, not sure if those have different behaviors, although for an error like this I would expect it to happen regardless of unity version.

**Comment by arthur740212** [comment]
While building for android, it will copy a new aar from the folder according to whether the user decides to use static or dynamic linking.
It seems that an extra aar is packed into the runtime folder in the package, even though it seemed to work on our builds.
Based on my assumption, I pushed a fix on the development branch, please give it a try and let us know if further issues occur.

**Comment by AndrewKahr** [comment]
Just got a chance to test it and the fix seems to work, just an extra meta file for the aar that was left over in the package description that Unity throws a warning about.

**Comment by arthur740212** [comment]
Thanks for the fix and the report. 
The meta file would be needed in a way, but generally lingering meta files is unpleasant.
I have pushed an update to copy the needed library and its corresponding meta file during OnPreprocessBuild.
Together with your fix there should be no more unwanted meta files, and they will exist when we need them.
