### ISSUE TITLE
CI Test Build on Commit/PR

### ISSUE THREAD

**Issue by AndrewKahr** [PlayEveryWare/eos_plugin_for_unity#195]
**Is your feature request related to a problem? Please describe.**
I'm noticing a lot of high level issues such as failing to build the UPM package or including it with a project and failing to build for target platforms popping up as the plugin is developed. This is understandable as the development branch is not expected to be stable, however, it might help to debug issues if developers get immediate feedback on whether their new code works. 

**Describe the solution you'd like**
A GitHub actions workflow that clones the eos plugin repo, builds a fresh upm tar.gz, imports the tar into a Unity project (ideally use several Unity versions for validation across tech/lts streams), then builds for all target platforms. This would at a bare minimum ensure the plugin functions at a bare minimum and lays groundwork for future test implementation. GameCI's [Unity-builder](https://github.com/game-ci/unity-builder) has all the necessary features to do the above and this is a public repo so action minutes are free, it would just require time to write the workflows themselves. You can find the GameCI docs [here](https://game.ci/docs/github/builder). As a bonus, thousands of teams use GameCI to perform builds so knowing the plugin works with GameCI is a pretty big plus. 

**Describe alternatives you've considered**
I did notice PEW has repos for autobuilding Unity projects so perhaps this is already happening behind the scenes, just not on PRs/commits?
Only other alternative is keeping it the way it is with people manually building develop and discovering issues which isn't consistent.

**Comment by AndrewKahr** [comment]
Bump

**Comment by AndrewKahr** [comment]
Bump

**Comment by AndrewKahr** [comment]
Bump

**Comment by domlaurenti** [comment]
@pew-dahs is this something you'd be interested in looking into?

**Comment by pew-dahs** [comment]
I can take a look at doing this for the public plugin.

**Comment by AndrewKahr** [comment]
Bump

**Comment by AndrewKahr** [comment]
Bump

**Comment by mendsley** [comment]
There is indeed some work behind the scenes here. We still need to sort out some security issues before we can build public repositories on our internal infrastructure. But this is definitely on my internal roadmap.
