### ISSUE TITLE
ExternalAuth with Steam isn't working

### ISSUE THREAD

**Issue by maxfpl** [PlayEveryWare/eos_plugin_for_unity#197]
I'm currently working on cross play between Steam and Epic Users. I just need to send invites between Steam and Epic. However the External Auth isn't working.

I've already installed the plugin and configured everything related to the product in the developer portal. 
Also generated the Encrypted Ticket Key in the Steamworks Backend.
And Added the identity provider in the developer portal and set the Encryption Key from last step.

In the code I'm calling the EOSManager GetEOSAuthInterface() in order to make the login.

Then, I created the **Credentials** 

- Type set as ExternalAuth
- ExternalType set as SteamSessionTicket
- Id set to the UserID from Steam
- Token is set to the GetAuthSessionTicket from SteamWorks converted to Hex.

So, those credentials are set into the LoginOptions, with the ScopeFlags (BasicProfile, FriendList, Presence, Country)

**Expected behavior**
At this point, I just need to call the Auth Interface from before, and Login with the Login Options, a new object and the callback function. The SDK should manage if the person has the external Account linked, if the Login fails or if it's successful, however, this isn't happening, I'm only getting an **EOS_Auth_AuthenticationFailure** in the ResultCode from the callback.

I've already upload the game to steam with steamworks working fine, the bootstrapper is working and the Overlay is also installed, so I don't know what I'm missing.

I created a Ticket in the Epic developer support, where they say the code is alright, so there's something else somewhere. So they sent me to ask here.

If anyone has any thoughts or know what the problem may be, please tell me. 

Edit:: Also, the Sample doesn't have the ExternalAuth implemented, so there's no way to test this with the samples.

Thank you!

**Comment by andrew-hirata-playeveryware** [comment]
Thank you for creating the git issue!

Are you able to provide any log and code so we can see what is happening on the Unity side of things? If so, it would help.

**Comment by maxfpl** [comment]
Thank you for the reply! 

Here is the code:

`//Instantiate the Authentication Interface for the Login
var authInt = EOSManager.Instance.GetEOSAuthInterface();

//Create a new variable of Credentials, which will be used in the Login Options
var liCredentials = new Credentials();

//Type is set as External since we will login with Steam Account.
//ExternalType is SteamSessionTicket as the session ticket will let us login
liCredentials.Type = LoginCredentialType.ExternalAuth;
liCredentials.ExternalType = ExternalCredentialType.SteamSessionTicket;

//Credential ID must be the Steam local Player ID
liCredentials.Id = PhotonNetwork.LocalPlayer.UserId;

//Gets the Steam Auth Session and is set to the Credential Token
byte[] buffer = new byte[1024];
uint len = 0;
var ticket = SteamUser.GetAuthSessionTicket(buffer, buffer.Length, out len);
Array.Resize(ref buffer, (int)len);
var tokenStr = buffer.ToHexString();
liCredentials.Token = tokenStr;

//Credentials and ScopeFlags are set to the Login options, then the clientData is created.
var loginOpt = new LoginOptions();
loginOpt.Credentials = liCredentials;
loginOpt.ScopeFlags = AuthScopeFlags.BasicProfile | AuthScopeFlags.FriendsList | AuthScopeFlags.Presence;
object clientData = new object();

//Authentication Login is executed with the credential and options created before.

authInt.Login(ref loginOpt, clientData, (ref LoginCallbackInfo loginCallbackInfo) =>
{

//If Success, the EOS Overlay invites are enabled.
_msg.text = loginCallbackInfo.ResultCode.ToString();

if (loginCallbackInfo.ResultCode == Result.Success)
{
Debug.Log(" Account is Linked!");
}`

And also the log file.

[Logs-cl.txt](https://github.com/PlayEveryWare/eos_plugin_for_unity/files/10383478/Logs-cl.txt)

Thank you!

**Comment by scovertb** [comment]
Started work on example code for the plugin that will test this.

**Comment by scovertb** [comment]
I was able to log in with Steam credentials in editor and in a Windows build. Is PhotonNetwork.LocalPlayer.UserId set to the user's account ID?

**Comment by scovertb** [comment]
When building Steam auth functionality into a package and testing it, I'm getting sporatic failures when logging in. If you attempt to log in a few times, does the issue occur 100% of the time?

**Comment by maxfpl** [comment]
Hello Scovertb, thank you for the help.

I made some changes to the code and the auth works fine most of the time, maybe 90% accuracy, in some other circumstances it fails.
Right now I have a couple of important questions...

When I login in the Auth interface using the ExternalAuth using the SteamSessionTicket, I get a success code form the callback, then I do the Connect Interface login using the same credentials but it fails, the callback returns InvalidUser. The plugin uses the EpicAccountID instead of the steam credentials for the Connect Login, is there a difference between using one or the other?

Also, I would like to know if when connecting to the social overlay using the Steam Credentials, should I see the Steam Friends in the Overlay? Or it only shows the Epic Friends I have from the Epic account linked before?

Thank you!

**Comment by scovertb** [comment]
I believe logging in through the Connect interface authenticates for a shorter period and does not require an Epic account, so any functionality requiring an EpicAccountId would be unavailable. That said, I'm not very familiar with the details of the Connect interface.

The overlay only shows users in your Epic friends list. If you wanted a full list of all friends you would need an in-game UI that pulls from both the EOS friends list and the Steam one. I think the extent of the friend list linking is providing friend suggestions  through the Epic Games Launcher.

**Comment by scovertb** [comment]
On further reading, it looks like logging in with the Auth interface returns an EpicAccountId which is used for Epic Account Services interfaces like Friends, whereas logging in with the Connect interface returns a ProductUserId which is used for Game Services interfaces like Achievements and Leaderboards. For full EOS functionality you would need to log in with both. The easiest way to do so would likely be to log in with the Auth interface first and then use the Epic auth token to log in the Connect interface.
