### ISSUE TITLE
Getting stuck in EOS library unloading

### ISSUE THREAD

**Issue by Sebioff** [PlayEveryWare/eos_plugin_for_unity#20]
When entering play mode for the second time after starting Unity it gets stuck in SystemDynamicLibrary.FreeLibrary(existingHandle); at:

`EOSManager.EOSSingleton.ForceUnloadEOSLibrary() at Library\PackageCache\com.playeveryware.eos@7684ee6c4e\Runtime\EOSManager_DynamicLoading.cs:line 312
EOSManager.EOSSingleton.Init() at Library\PackageCache\com.playeveryware.eos@7684ee6c4e\Runtime\EOSManager.cs:line 254
EOSManager.Awake()`

This is in the latest version of the EOS package using the latest Unity LTS version, 2020.3.17.

**Comment by andrew-hirata-playeveryware** [comment]
Is this when using the samples, or in your own title?

**Comment by Sebioff** [comment]
It's in our own title, not in the samples.
After some more testing I am able to reproduce it in an empty new project (see attachment - you'll just need to set up an EOS config file and run the SampleScene).
It only seems to happen when trying to login to EOS in the same frame in which the EOSManager gets created. When waiting for a few frames it does not happen anymore until Unity gets restarted.
[EOSFreezeRepro.zip](https://github.com/PlayEveryWare/eos_plugin_for_unity/files/7161955/EOSFreezeRepro.zip)

**Comment by Sq3-Matt** [comment]
Not sure if anything's been done with this, but brand new Unity install with latest plugin download in a brand new project and it's still an issue

**Comment by TheSLAP** [comment]
I've noticed this issues when EOS does not fully shutdown and release handles.

**Comment by domlaurenti** [comment]
Apologies for the delayed response, we solved a version of this issue but not the entire thing 
Currently, we are investigating a related issue right now. Still investigating this issue.

**Comment by domlaurenti** [comment]
Apologies for the very long delay here. We have been heads down on quite a few things. 
Please update to the latest 2.1.0 version, there is a fix contained in that version for this issue. Let me know if this is resolved for you. @jfmajor @Sebioff @Sq3-Matt
