### ISSUE TITLE
transport from develop branch doesn't call NetCode.GameObjects timeout if connection cannot be made

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [PlayEveryWare/eos_plugin_for_unity#202]
**Describe the bug**
If the connection for the unity transport canot happen due to some reason like the other player stopping their application, I see th EOSP2P warning about maximum send signal tries and another for timeout but the transport implementation deos not return timeout/transport failure to unity so NetCode.GameObject knows it is not useful to wait more.

I am using a two weeks old transport version so it might have been fixed.

**To Reproduce**
1.create one client and start a host on it
2.start another application and try to connect to the other host using the id of the account
3.quickly close the first app so the second one cannot actually connect. then observe the console output for the next minute or so

**Expected behavior**
unity netcode should call disconnect and you can do that by firing a disconnect event after the timeout. at least the default udp transport calls disconnect in that case.

Also it is a good idea to make the timeout configurable if possible since at the moment it is too long.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:windows 10 x64
 - Unity Version 2022.2
 - Plugin Version latest official release with the transport taken from develop branch two weeks ago

**Additional context**
I was testing the game with different network conditions and realized a failure to connect is not reflected in Netcode.Gameobjects and investigated to see why. I found this out and reproduced it and compared it to the udp default transport implementation which atm uses unity transport.

it should be just because you are not calling a disconnect event after tiemout.

**Comment by scovertb** [comment]
A fix for the disconnect issue will be included in the next release. There isn't currently a way to configure the timeout of the EOS P2P interface, but if one gets added I'll integrate it.
