### ISSUE TITLE
problem with DLL loading

### ISSUE THREAD

**Issue by dziuba91** [PlayEveryWare/eos_plugin_for_unity#203]
**Describe the bug**
There is problem with DLL loading, especially with "DynamicLibraryLoaderHelper". According to logs: wrong architecture issue, but in Unity inspector everything seems to be fine. On 32-bit architecture is the same problem.

**To Reproduce**
1. Run build (on Development mode)

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Unity Version 2021.3.1
 - Plugin Version 2.1.7

**Additional context**
![1111](https://user-images.githubusercontent.com/14006437/212694621-44bdeb55-1cf2-4c2a-8e0e-b725f186988d.png)
![2222](https://user-images.githubusercontent.com/14006437/212700787-589410a1-dc4d-4fcc-b8f2-a3b44db03f6d.png)
![3333](https://user-images.githubusercontent.com/14006437/212701000-35e233dc-1a5c-4721-974f-4fe9d38fe23b.png)

**Comment by scovertb** [comment]
I wasn't able to reproduce this issue. Does this still occur in 2.1.8?

**Comment by andrew-hirata-playeveryware** [comment]
How did you install the plugin?
