### ISSUE TITLE
Built plugin from develop doesn't reflect latest version number

### ISSUE THREAD

**Issue by AndrewKahr** [PlayEveryWare/eos_plugin_for_unity#206]
**Describe the bug**
The Develop branch still seems to build the plugin as version 2.1.7 when the latest release is 2.1.8.

**To Reproduce**
1. Pull the development branch
2. Build a UPM package
3. Observe the version number lagging behind the latest release 

**Expected behavior**
Develop keeps up with stable versioning.

**Comment by scovertb** [comment]
The package number has been updated in the dev branch.
