### ISSUE TITLE
Disconnecting & Lobby [Bugs]

### ISSUE THREAD

**Issue by borekEnter** [PlayEveryWare/eos_plugin_for_unity#213]
Hi, I found some bugs. (Sorry for my English)
I am using the latest version of your plugin 2.1.8. 
I tested it on a few projects, and found some bugs with NetCode integration.
#1 CALLBACKS
Callbacks are executed twice, I'm talking about creating a Lobby, joining a lobby, etc.
#2 DISCONNECTING
After exiting the Lobby I get various errors in the console. (Screenshots I will upload below)
#3 Argument_InvalidOffLen
Sometimes during the game there is an error that displays several times in a few seconds and then stops, after some time it appears again. (in 3 different projects) (Second screenshot)
#3.5 
Sometimes it also spam with an error regarding DisconnectRemoteClient and DisconnectLocalClient in the EOSTransport script. The error is similar to the one in the first screenshot.
Thanks for help!

S1
![BUG_1](https://user-images.githubusercontent.com/123742523/215095388-65b2996f-c7cd-4274-8150-a31b6b800d8c.png)
S2
![BUG_2](https://user-images.githubusercontent.com/123742523/215095595-1f7401c6-41a3-407b-a288-e7a4f968f401.png)
S3
![Screenshot_4](https://user-images.githubusercontent.com/123742523/215094024-14f26c26-5c27-42f7-9076-f1f46c5e1d16.png)
S4
![Screenshot_5](https://user-images.githubusercontent.com/123742523/215094027-aca9d0fb-802f-475d-b1db-1e8d439664c1.png)

**Comment by martinpppx** [comment]
Ye, i have the same problem with InvalidOffLen, that's crashing the game.

**Comment by scovertb** [comment]
Could you provide more context for the error in the fourth screenshot?

**Comment by scovertb** [comment]
Could you provide repro steps for the EOSTransport issues?

**Comment by borekEnter** [comment]
Yes, i'm using your EOSLobbyManager system. I'm creating the lobby, then invoke the lobby callback (callback is invoked twice (i don't know it's a bug?)).
https://pastebin.com/VZN2heW0
That's my code.
Okay, about disconnecting:
1. Create the lobby using CreateLobby function
2.  Join the lobby using id lobby with function Join(ID)
3. Then leave the lobby using function Leave
Will be spamming error messages (Screenshot 1), doesnt matter if you are host or client
Some informations: I'm using NetCode 1.2.0, Unity 2022.2.5f.1, EOS: v2.1.9 
If we just talk about 'Argument_InvalidOffLen' it's hard to show repro cause it's a problem inside. I mean if you just create the lobby, someone join to you, then change the scene and you will play then after some time there will be an error, which will appear at first every few seconds, the longer you play with a friend, this error will occur more and more often, until it finally crash the game.. (Its the second screenshot - Highlighted code in red, and underneath it a notepad with an error)

**Comment by scovertb** [comment]
How are you using lobbies and netcode? The Lobby manager and EOSTransport aren't functionally tied together. Do the EOSTransport errors only happen after changing scenes?

**Comment by borekEnter** [comment]
So do you plan to add support for people who want to use Lobby and Netcode together? When I was using Steam there was an option to connect the lobby system with NetCode.  As for disconnecting, the error occurs no matter if I change the scene or not, while the error with InvalidOffLen I noticed after changing the scene, however, I can still check if it also occurs when the player has not changed the scene after creating the lobby.

**Comment by borekEnter** [comment]
Or maybe it's possible to connect NetCode with EOSTransport from current state?

**Comment by scovertb** [comment]
The EOS Lobby interface and the EOS P2P interface (that is used by EOSTransport) are two separate systems. They can both be used together, but the implementation is up to the user. Can you describe how you are using the Lobby interface and EOSTransport together?

**Comment by borekEnter** [comment]
My lobby system looks like this one. Argument_InvalidOffLen is already called during the game, it's about EOSTransportManager - "ArraySegment<byte> header = new ArraySegment<byte>(packet, 0, FragmentHeaderSize)" line.
After some time, the error shows itself more and more often and crashes the game. As for disconnecting, as I said, it spamming the console with errors after leaving. Here I showed in this project how I implemented the system of leaving lobby.
[Lobby.zip](https://github.com/PlayEveryWare/eos_plugin_for_unity/files/10706939/Lobby.zip)

**Comment by borekEnter** [comment]
@scovertb I see that you have fixed one bug that was causing constant SPAM in the console after leaving the game. I added it and it works, now it mainly concerns the error that is triggered when invalid arguments are passed to the System.ArraySegment<T> constructor (in this case T is of type System.Byte). As far as I can tell, the error is that the offset or count arguments are invalid in relation to the size of the array. The error itself, as I said, occurs after a certain amount of time in the game (tested on 3 different projects), I don't know if only after changing the scene because I haven't tested on the same one, however, I can state that after a certain amount of time it crashes the game because too many times the error starts to show up. I sent you the 'Lobby' above where you can see how I connect EOSTransport with NetCode and the lobby system.

**Comment by scovertb** [comment]
I was able to stop the errors, though I'm not seeing any visible activity in your netcode test so I'm unsure if the problem is actually fixed.

**Comment by borekEnter** [comment]
@scovertb Hi, I checked what you sent. Something is definitely wrong with this system. Let me explain, I tested my game with 3 different transports (EOSTransport, SteamSocketTransport, and UnityTransport), two of them work well and don't cause any internal problems, but EOSTransport does. After some time, the client (not the host) feels a terrible discomfort in the game, packets are lost, it starts moving them back to the place where it should not be for a long time, animation synchronization totally doesn't work due to continuous lag. It even happened that my friend got a crash after 27 minutes of playing. In summary, the first few minutes of the game work flawlessly, the longer we play, the more packets the client loses (that's how it looks), and there is also a chance of getting a crash later on. And I can say that in addition to changing the transport to another one, I tested it with 2 other friends who have really good internet connections.

**Comment by quentinleon** [comment]
Having a similar issue to @borekEnter where as the game runs, a delay accumulates between the host and client.

**Comment by martinpppx** [comment]
Yup, the same problem here.

**Comment by scovertb** [comment]
Are all of these issues exclusive to EOS Transport? In the sample I was provided the LobbyPlayer failed to replicate the player name, but that still occurred when using Unity Transport and seemed to be an issue with RPC implementation for LobbyPlayer.

**Comment by borekEnter** [comment]
@scovertb The project example you were given only shows how to connect with a player using the lobby system, but the problem we're discussing is related to actual gameplay. The longer we play and the more packets that are sent, the more EOSTransport loses. This is definitely a problem with this transport because it doesn't occur with others. The longer we play, the more packets the client will eventually lose, which can be seen in things like position or animation synchronization.

**Comment by borekEnter** [comment]
The latest update has not changed anything, there is still a problem that prevents the use of NetCode and EOS together. In the above post we can see that several other people also have this problem. As I say, after playing for a while all clients lose packets, it teleports them to a place where they have not been for a long time, animations do not have correct synchronization, data update occurs with delays. I'm hoping someone will check it out.

**Comment by manelmourelo** [comment]
I'm using Unity2021.3.15f1 and the 2.3.3 version of the plugin and when using the P2P it ends up crashing, sometimes it takes a while and sometimes its instant (if i play the game without connecting players it doesn't crash). I get no errors on the log file and it crashes both in editor and build. I'm using EOSConnect instead of EOSAuth as I'm using steam accounts and I don't want to go through the linking accounts. The thing is that it crashes even if I don't touch anything and it seems to be a problem of the plugin as the same project works without problems when using steams P2P or when using the normal transport to connect to another computer in a local network. 
I’ve been looking at it for some days and I don’t find why it is crashing. By adding logs I’ve seen that it sometimes enters to the TryReceivePacket function (in the transport manager script) while that function is already in mid execution and the crash.dmp says that the exception code is 0xc0000005.
