### ISSUE TITLE
Creating build for macOS fails if EOS plugin package is installed

### ISSUE THREAD

**Issue by Sebioff** [PlayEveryWare/eos_plugin_for_unity#22]
This package does not support macOS yet, which is fine, but it should still be possible to create macOS builds of your Unity project (without using EOS).

Right now, when trying to do so the build fails due to some methods not existing:

Library\PackageCache\com.playeveryware.eos@7684ee6c4e\Runtime\EOSManager.cs(238,35): error CS0103: The name 'CreateSystemInitOptions' does not exist in the current context

Library\PackageCache\com.playeveryware.eos@7684ee6c4e\Runtime\EOSManager.cs(247,17): error CS0103: The name 'ConfigureSystemInitOptions' does not exist in the current context

Library\PackageCache\com.playeveryware.eos@7684ee6c4e\Runtime\EOSManager.cs(267,39): error CS0103: The name 'CreateSystemPlatformOption' does not exist in the current context

Library\PackageCache\com.playeveryware.eos@7684ee6c4e\Runtime\EOSManager.cs(268,50): error CS0103: The name 'GetTempDir' does not exist in the current context

Library\PackageCache\com.playeveryware.eos@7684ee6c4e\Runtime\EOSManager.cs(289,17): error CS0103: The name 'ConfigureSystemPlatformCreateOptions' does not exist in the current context

**Comment by adrianpew** [comment]
MacOS is not currently supported.  Unfortunately, ability to make builds with the plugin is part of the support.

As a workaround, I would suggest branching your source for platforms that use the EOS Plugin for Unity.  Additionally, you are welcome to modify EOSManager.cs it exclude MacOS and submit a pull request and help grow the open source plugin.

Let us know if you have any other questions.
