### ISSUE TITLE
Anti-Cheat fails to start

### ISSUE THREAD

**Issue by Ahriana** [PlayEveryWare/eos_plugin_for_unity#222]
**Describe the bug**
anti-cheat fails to initialize, the only relevant log I can find is `[AntiCheatClient] Anti-cheat client not available. Verify that the game was started using the anti-cheat bootstrapper if you intend to use it. `, from the behaviour the EAC service starts, can be checked with `query EasyAntiCheat_EOS` but stops running before the game fully starts, I'm not 100% sure where the issue is so thought to ask here first

![image](https://user-images.githubusercontent.com/28003629/219829137-154d215a-de23-4fdc-9c95-dda3102428dd.png)

I did the same command with another game running EAC (Rust) and the service never stops

**To Reproduce**
1. run the samples project (this repo)
2. fill out epic data / configs
3. enable EAC checkbox
4. build and start the game

**Expected behavior**
Service to continue running, AC functions to be avaiable to the client

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 x64 22H2 19045.2604
 - Unity Version: 2021.3.18f1
 - Plugin Version: 2.1.9

**Additional context**
This could absolutely be a me issue, but i cant find anything in the documentation i am doing wrong (here and on EOS docs)
The game is being started with `EACLauncher.exe` but also tried with `EOSBootstrapper.exe` and the games binary and only EACLauncher will start the EAC service before failing, the rest dont start the service at all

the `loader.log` for EAC in appdata shows `[EAC Callback] Code: 1002. Message: 'Easy Anti-Cheat successfully loaded in-game'.` which would indicate to me everything on the Epic config side is correct

**Comment by scovertb** [comment]
The problem was that on Windows, the EAC launcher was launching the bootstrapper which was launching the game, when the correct order was bootstrapper, EAC, game. A fix for this will be in the next release, but in the meantime you can make a build and then change ApplicationPath in EOSBootstrapper.ini to EACLauncher.exe and executable in EasyAntiCheat/Settings.json to the game exe.

**Comment by Ahriana** [comment]
amazing thank you, i will give this a shot soon and report back if any further issues
