### ISSUE TITLE
Null Ref Exceptions On Any EOS Function On Mac

### ISSUE THREAD

**Issue by JasonVibeGames** [PlayEveryWare/eos_plugin_for_unity#225]
**Describe the bug**
Every time the game performs a function there is a null reference exception.

**To Reproduce**
1. Clone repo. 
2. Use Makefile to bypass initial error related to missing Dylib
3. Run any scene in the samples, attempt login
4. See error in console. Same happens in the build version as in the editor.

**Expected behavior**
No error. Game runs as normal.

**Screenshots**
![Screenshot 2023-03-04 at 16 37 18](https://user-images.githubusercontent.com/92737062/222915080-df5c5d9e-fc9a-4640-bbea-2a3c4f11e4fa.png)
![Screenshot 2023-03-04 at 16 37 35](https://user-images.githubusercontent.com/92737062/222915092-29f95932-5a76-4688-b18e-5d77f9150246.png)
![Screenshot 2023-03-04 at 16 41 20](https://user-images.githubusercontent.com/92737062/222915279-8ddad89c-5c53-4320-8135-1c27dac41a1e.png)

**Desktop (please complete the following information):**
 - OS: macOS Intel
 - Unity Version 2021.3.19
 - Plugin Version 2.2.0

**Additional context**
Seems to be different null reference exceptions based on the different functions being called.

Stack Trace:
NullReferenceException: Object reference not set to an instance of an object
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton+<>c.<LoadDelegatesWithEOSBindingAPI>b__90_0 (DLLHandle handle, System.String functionName) (at Assets/Plugins/Source/EOSManager_DynamicLoading.cs:224)
Epic.OnlineServices.Bindings.Hook[TLibraryHandle] (TLibraryHandle libraryHandle, System.Func`3[T1,T2,TResult] getFunctionPointer) (at Assets/Plugins/Source/EOS_SDK/Generated/Bindings.cs:1724)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadDelegatesWithEOSBindingAPI () (at Assets/Plugins/Source/EOSManager_DynamicLoading.cs:220)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadEOSLibraries () (at Assets/Plugins/Source/EOSManager_DynamicLoading.cs:358)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) (at Assets/Plugins/Source/EOSManager.cs:522)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) (at Assets/Plugins/Source/EOSManager.cs:496)
PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager.Awake () (at Assets/Scripts/EOSHostManager.cs:48)

**Comment by arthur740212** [comment]
Try adding EOS_PREVIEW_PLATFORM to the scripting define symbols list under Player Settings -> Other Settings.

**Comment by JasonVibeGames** [comment]
*facepalm* That worked, along with reusing the makefile. Thanks a lot!

**Comment by JasonVibeGames** [comment]
I should say though that there's no way to use the makefile in the Unity Package Manager version. It only works when cloning from the repo right now for macs.
