### ISSUE TITLE
Bug in Achievements Sample if you only have 1 Achievement

### ISSUE THREAD

**Issue by valorwareuk** [PlayEveryWare/eos_plugin_for_unity#229]
**Describe the bug**
If you only have 1 achievement in the dev portal, the Achievements Sample will not detect it and say "no achievement data", even though GetAchievementDefinitionCount() == 1. 

line 199 in UIAchievementsMenu.cs says > 1 instead of > 0
if (achievementDefCount > 1)

**To Reproduce**
Have 1 achievement in your Game
Run the achievements Sample
Observe it says no achievement data, but the log says 1 found

**Expected behavior**
show the achievement

**Comment by andrew-hirata-playeveryware** [comment]
Ah: That's embarrassing bug! As author of that bug, I shall fix it and get that into development this morning

**Comment by andrew-hirata-playeveryware** [comment]
Fixed in 8e3dac4273406cc85520abfe2fd0d6e0dad845e9
