### ISSUE TITLE
errors in unity 

### ISSUE THREAD

**Issue by nitroman123** [PlayEveryWare/eos_plugin_for_unity#231]
**Describe the bug**

Firs time to use the plugin , ive added all the things and followed the steps , i cant really find where is the encryption key

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/62849221/226258315-2b7cf7e5-d488-45d1-9bfe-b09942efb9d1.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows x86, Windows x64, macOS Intel, macOS ARM]
 - Unity Version 2021.3.18f
 - Plugin Version Latest 

**Smartphone (please complete the following information):**
 - Unity Version
 - Plugin Version

**Additional context**

**Comment by andrew-hirata-playeveryware** [comment]
Hello @nitroman123 !
Have you followed the instructions [here](https://github.com/PlayEveryWare/eos_plugin_for_unity#steps)?

I suspect that you haven't configured an encryption key on the portal or you haven't added on in the config file. Technically it can be any string you want.

**Comment by nitroman123** [comment]
i generated a new one but with no luck , also what keys needs to be added to the ids ?  have added the live ids to the editor window

**Comment by andrew-hirata-playeveryware** [comment]
The values need to come from the Epic Online Services Dev portal, which in step four of the previously linked document. Would it be possible for your to share a Unity log so that I can check and see when the plugin it is failing?

**Comment by nitroman123** [comment]
![image](https://user-images.githubusercontent.com/62849221/226528812-3dbd6fba-1d1e-4d24-b5af-9da8494c1adf.png)

still i cannot understand the way to retrieve the encryption key from portal , cant seem to find it , also for my game i only need to retrieve the name of the player in epic or steam

**Comment by andrew-hirata-playeveryware** [comment]
How did you install the plugin? The issue I'm seeing in that screenshot implies that one of the DLLs for the plugin is missing. For you use case, you shouldn't need to copy any of the encryption keys and you should be able to just use the generated one.

If possible, can you share the entire log file for a standalone build?

**Comment by nitroman123** [comment]
NullReferenceException: Object reference not set to an instance of an object
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton+<>c.<LoadDelegatesWithEOSBindingAPI>b__90_0 (DLLHandle handle, System.String functionName) (at Assets/eos_plugin_for_unity-stable/Assets/Plugins/Source/EOSManager_DynamicLoading.cs:224)
Epic.OnlineServices.Bindings.Hook[TLibraryHandle] (TLibraryHandle libraryHandle, System.Func`3[T1,T2,TResult] getFunctionPointer) (at Assets/eos_plugin_for_unity-stable/Assets/Plugins/Source/EOS_SDK/Generated/Bindings.cs:1724)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadDelegatesWithEOSBindingAPI () (at Assets/eos_plugin_for_unity-stable/Assets/Plugins/Source/EOSManager_DynamicLoading.cs:220)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadEOSLibraries () (at Assets/eos_plugin_for_unity-stable/Assets/Plugins/Source/EOSManager_DynamicLoading.cs:358)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) (at Assets/eos_plugin_for_unity-stable/Assets/Plugins/Source/EOSManager.cs:522)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) (at Assets/eos_plugin_for_unity-stable/Assets/Plugins/Source/EOSManager.cs:496)
PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager.Awake () (at Assets/eos_plugin_for_unity-stable/Assets/Scripts/EOSHostManager.cs:48)

NullReferenceException: Object reference not set to an instance of an object
PlayEveryWare.EpicOnlineServices.Samples.EOSFriendsManager..ctor () (at Assets/eos_plugin_for_unity-stable/Assets/Scripts/EOSFriendsManager.cs:110)
System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) (at <1f66344f2f89470293d8b67d71308c07>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) (at <1f66344f2f89470293d8b67d71308c07>:0)
System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) (at <1f66344f2f89470293d8b67d71308c07>:0)
System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) (at <1f66344f2f89470293d8b67d71308c07>:0)
System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) (at <1f66344f2f89470293d8b67d71308c07>:0)
System.Activator.CreateInstance[T] () (at <1f66344f2f89470293d8b67d71308c07>:0)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.GetOrCreateManager[T] () (at Assets/eos_plugin_for_unity-stable/Assets/Plugins/Source/EOSManager.cs:335)
PlayEveryWare.EpicOnlineServices.Samples.UIFriendsMenu.Start () (at Assets/eos_plugin_for_unity-stable/Assets/Scripts/UI/UIFriendsMenu.cs:91)

also in order to play i had to comment that line 824 in UILoginManager.cs

my install was to download the latest zip , export , also i asked what ids should i use , the live , stage , dev ?

**Comment by andrew-hirata-playeveryware** [comment]
Sorry for missing that question: the IDs you'd use depend on which ones you setup on the portal and which one you're working on. To start, it's reasonable to use the Dev ones.

The issue around line 824 in UILoginManager is known, and there will be a fix for that sometime soon. As a work around, it's possible to get the samples working by changing the Api Compatibility layer to .NET Framework.

When you say you used the latest zip, do you mean the installing it via the UPM tgz file? If not, that's how I would recommend installing the plugin, as it's easier to upgrade and manage it as a dependency.

**Comment by nitroman123** [comment]
> Sorry for missing that question: the IDs you'd use depend on which ones you setup on the portal and which one you're working on. To start, it's reasonable to use the Dev ones.
> 
> The issue around line 824 in UILoginManager is known, and there will be a fix for that sometime soon. As a work around, it's possible to get the samples working by changing the Api Compatibility layer to .NET Framework.
> 
> When you say you used the latest zip, do you mean the installing it via the UPM tgz file? If not, that's how I would recommend installing the plugin, as it's easier to upgrade and manage it as a dependency.

ok i ve done it but i dont seem i can find the test scenes at all so how i can test this ?

**Comment by nitroman123** [comment]
> > Sorry for missing that question: the IDs you'd use depend on which ones you setup on the portal and which one you're working on. To start, it's reasonable to use the Dev ones.
> > The issue around line 824 in UILoginManager is known, and there will be a fix for that sometime soon. As a work around, it's possible to get the samples working by changing the Api Compatibility layer to .NET Framework.
> > When you say you used the latest zip, do you mean the installing it via the UPM tgz file? If not, that's how I would recommend installing the plugin, as it's easier to upgrade and manage it as a dependency.
> 
> ok i ve done it but i dont seem i can find the test scenes at all so how i can test this ?

ok i ve made it i was starting de3leting the unnecessary files from the zip... so i just want to retrieve the name of the player is there any example about it ?

**Comment by andrew-hirata-playeveryware** [comment]
> > Sorry for missing that question: the IDs you'd use depend on which ones you setup on the portal and which one you're working on. To start, it's reasonable to use the Dev ones.
> > The issue around line 824 in UILoginManager is known, and there will be a fix for that sometime soon. As a work around, it's possible to get the samples working by changing the Api Compatibility layer to .NET Framework.
> > When you say you used the latest zip, do you mean the installing it via the UPM tgz file? If not, that's how I would recommend installing the plugin, as it's easier to upgrade and manage it as a dependency.
> 
> ok i ve done it but i dont seem i can find the test scenes at all so how i can test this ?
Yes, you can install the samples with the UPM manager, which will put the samples in the assets directory




> > > Sorry for missing that question: the IDs you'd use depend on which ones you setup on the portal and which one you're working on. To start, it's reasonable to use the Dev ones.
> > > The issue around line 824 in UILoginManager is known, and there will be a fix for that sometime soon. As a work around, it's possible to get the samples working by changing the Api Compatibility layer to .NET Framework.
> > > When you say you used the latest zip, do you mean the installing it via the UPM tgz file? If not, that's how I would recommend installing the plugin, as it's easier to upgrade and manage it as a dependency.
> > 
> > 
> > ok i ve done it but i dont seem i can find the test scenes at all so how i can test this ?
> 
> ok i ve made it i was starting de3leting the unnecessary files from the zip... so i just want to retrieve the name of the player is there any example about it ?
The UIDisplayName script has an example of getting the a user display name it it.

**Comment by nitroman123** [comment]
> > > Sorry for missing that question: the IDs you'd use depend on which ones you setup on the portal and which one you're working on. To start, it's reasonable to use the Dev ones.
> > > The issue around line 824 in UILoginManager is known, and there will be a fix for that sometime soon. As a work around, it's possible to get the samples working by changing the Api Compatibility layer to .NET Framework.
> > > When you say you used the latest zip, do you mean the installing it via the UPM tgz file? If not, that's how I would recommend installing the plugin, as it's easier to upgrade and manage it as a dependency.
> > 
> > 
> > ok i ve done it but i dont seem i can find the test scenes at all so how i can test this ?
> 
> Yes, you can install the samples with the UPM manager, which will put the samples in the assets directory
> 
> > > > Sorry for missing that question: the IDs you'd use depend on which ones you setup on the portal and which one you're working on. To start, it's reasonable to use the Dev ones.
> > > > The issue around line 824 in UILoginManager is known, and there will be a fix for that sometime soon. As a work around, it's possible to get the samples working by changing the Api Compatibility layer to .NET Framework.
> > > > When you say you used the latest zip, do you mean the installing it via the UPM tgz file? If not, that's how I would recommend installing the plugin, as it's easier to upgrade and manage it as a dependency.
> > > 
> > > 
> > > ok i ve done it but i dont seem i can find the test scenes at all so how i can test this ?
> > 
> > 
> > ok i ve made it i was starting de3leting the unnecessary files from the zip... so i just want to retrieve the name of the player is there any example about it ?
> 
> The UIDisplayName script has an example of getting the a user display name it it.

prefect thanks a lot , you can cloe this if you want b

**Comment by nitroman123** [comment]
@andrew-hirata-playeveryware i am getting very confuced to get only the name of the user , if the game is not uploaded to yet just coming soon , how i can get the name just for testing , i am getting the game from stream very easily and there is not a tutorial yet on this....
