### ISSUE TITLE
WebRTC

### ISSUE THREAD

**Issue by MerriemWeebster** [PlayEveryWare/eos_plugin_for_unity#235]
Although I am not using EOS on android, it is still a part of my android build since I require it to be used on other platforms. After uploading my app to the Play store, I get a warning that my app includes a version of WebRTC that has security flaws. Just wanted to let you know about this issue incase WebRTC needs to be updated.

**Comment by andrew-hirata-playeveryware** [comment]
Hello @MerriemWeebster,

In order to help with this issue, can you provide us with some additional information:

 - Host OS: [e.g. Windows x86, Windows x64, macOS Intel, macOS ARM]
 - Android Target OS
 - Unity Version
 - Plugin Version
