### ISSUE TITLE
Package don't compile in Unity Linux Editor

### ISSUE THREAD

**Issue by pyroakm** [PlayEveryWare/eos_plugin_for_unity#24]
Missing some #if UNITY_STANDALONE_LINUX in the code.
![image](https://user-images.githubusercontent.com/13466371/133250917-e3681f51-47d3-49d6-afb1-b97ab0b0fbf4.png)

**Comment by adrianpew** [comment]
Linux is not currently supported. Unfortunately, ability to make builds with the plugin is part of the support.

As a workaround, I would suggest branching your source for platforms that use the EOS Plugin for Unity. Additionally, you are welcome to modify EOSManager.cs it exclude Linux and submit a pull request and help grow the open source plugin.

We'll have milestones defined soon with a better timeline on when additional platforms are scheduled for public launch.

Let us know if you have any other questions.
