### ISSUE TITLE
InitializePlatformInterface exception in build

### ISSUE THREAD

**Issue by Manti2000** [PlayEveryWare/eos_plugin_for_unity#241]
On MacOS build the game throws a NullReference exception:

Exception: NullReferenceException: Object reference not set to an instance of an object
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.InitializePlatformInterface (PlayEveryWare.EpicOnlineServices.EOSConfig configData) (at <336ccbf4a9a64333934b72bdd2b67c43>:0)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) (at <336ccbf4a9a64333934b72bdd2b67c43>:0)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) (at <336ccbf4a9a64333934b72bdd2b67c43>:0)

A question: Is the epic games overlay supposed to work on MacOS? It really does not seem clear in the Epic documentation.

**Comment by andrew-hirata-playeveryware** [comment]
Hello @Manti2000 !
The Epic games social overlay isn't expected to work on macOS, but I somewhat expect that it will work in a future version of the EOS SDK. As for the exception, how did you install the plugin, and is this an editor build or a standalone build?

**Comment by arthur740212** [comment]
It is still in preview stage currently. To try it out add EOS_PREVIEW_PLATFORM in the symbol definition, most of the samples should be able to run.
