### ISSUE TITLE
EOSConfig.authScopeOptionsFlagsAsAuthScopeFlags always defaults

### ISSUE THREAD

**Issue by adrienlapoulenoire** [PlayEveryWare/eos_plugin_for_unity#243]
**Describe the bug**
EOSConfig.authScopeOptionsFlagsAsAuthScopeFlags always returns `AuthScopeFlags.BasicProfile | AuthScopeFlags.FriendsList | AuthScopeFlags.Presence` because local `flagSet` remains false
Happens on 2.2.0

**To Reproduce**
Set any valid list of flags in json configuration file for field `authScopeOptionsFlags`

**Expected behavior**
Flags are properly applied when authenticating the user

**Comment by andrew-hirata-playeveryware** [comment]
Hello @adrienlapoulenoire , What platform are you targeting? Is this in editor, in a standalone build?

**Comment by andrew-hirata-playeveryware** [comment]
Can you post what flags you have set in the config file?

**Comment by andrew-hirata-playeveryware** [comment]
Okay, I believe this should be fixed in the the 2.1.2 release.
