### ISSUE TITLE
GC Allocations in p2p hot path

### ISSUE THREAD

**Issue by Cicaeda** [PlayEveryWare/eos_plugin_for_unity#27]
Receiving packets in the P2PInterface.cs generates a ridiculous amount of garbage from the inefficient Marshalling. As per Unity's own coding standards, any garbage that's more than zero should be considered a bug. It should also be noted that each byte from the byte array is being Marshalled individually, also generating garbage each and every time. The performance is absolutely abysmal on such a critical path.

**Comment by adrianpew** [comment]
Hello.  This repository is for the Unity Plugin wrapper that utilizes the EOS SDK C# API.  The issues you describe were previously discussed on the Epic Forums.  When Epic makes fixes and optimizations, we will pick them up with SDK updates.

https://eoshelp.epicgames.com/s/question/0D54z0000775IEsCAM/c-sdk-is-too-slow-to-use-p2p?language=en_US
