### ISSUE TITLE
Compilation error on package import - Unity 2019.4.15f1

### ISSUE THREAD

**Issue by SithiraS** [PlayEveryWare/eos_plugin_for_unity#272]
**Describe the bug**
I followed the instructions on the git installation guide. After I provided the git link on package manager and import the SDK, I get this compilation error on EOSOnPostprocessBuild_Standalone.cs

error CS0117: 'Path' does not contain a definition for 'Join'

Cannot proceed to configuring the plugin. I'm using the Unity version 2019.4.15f1

**To Reproduce**
1. Open Unity 2019.4.15f1
2. Go to the package manager and try importing the package.
3. See error

**Expected behavior**
Scripts should compile and able to configure the sdk.

**Screenshots**

![Screenshot 2023-05-03 130051](https://user-images.githubusercontent.com/97406327/235858683-17075e6f-e1bd-499c-9005-d5db7a89a65c.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Unity Version: 2019.4.15f1
 - Plugin Version: 2.2.1

**Comment by andrew-hirata-playeveryware** [comment]
We have a fix for that in 29e2746539a74e7b9d49ffb6ef799aef19c4d540, which should make it's way into the next release.

**Comment by SithiraS** [comment]
Thank you. It fixed the issue
