### ISSUE TITLE
Unity 2020.3 and Console Preview

### ISSUE THREAD

**Issue by jjolley** [PlayEveryWare/eos_plugin_for_unity#276]
We're launching our game soon and want to use EOS for multiplayer crossplay on Steam, Xbox and Nintendo Switch. We're using Unity 2020.3. I was able to get past some errors by changing Path.Join to Path.Combine, but after that there were errors in the Tools when I tried to make a config. Does this plugin work for Unity 2020.3?

Also is the preview for the Xbox and Nintendo Switch far enough along that I'd be able to use it in production for those platforms. If yes, how do use those platforms. If no, is there any other way to use EOS in Unity other than this plugin?

**Comment by andrew-hirata-playeveryware** [comment]
The issue you're running into with the config file, along with the Path.Join issue, have been resolved and will be in the next release. Sorry that you ran into those issues: the plugin should otherwise work on 2020.3.

Currently, you'll need to first sign up with Epic to get access to those SDKs: have you gone though that step yet?

**Comment by jjolley** [comment]
Great news!

Yeah I have access to the SDKs for xbox and nintendo.

**Comment by andrew-hirata-playeveryware** [comment]
Hey, sorry for the long wait for my reply: 
we're currently working with the various people we need to talk with to get a console release out: we don't have a set timeline for it. I was hoping to get a firm date back before I communicated here on it, but I don't have one, unfortunately.

Additionally, I don't believe I can speak too much about how to resolve your issues for console on this issue, given the confidential nature of the console platforms.
