### ISSUE TITLE
Custom Native Libraries Missing

### ISSUE THREAD

**Issue by worthing-and-moncrieff** [PlayEveryWare/eos_plugin_for_unity#277]
### Discussed in https://github.com/PlayEveryWare/eos_plugin_for_unity/discussions/275

<div type='discussions-op-text'>

<sup>Originally posted by **worthing-and-moncrieff** May  4, 2023</sup>
Hello, all.
This is probably a very noob question here. But any help would be greatly appreciated. I've integrated the PlayEveryWare Unity plugin and I'm currently attempting to build our game. Windows builds fine, but for macOS I keep getting an error reporting that the custom native libraries for the mac are missing. Anyone have any idea what I might have missed? I'll paste the error below. Many thanks in advance!

-E

Custom native libraries missing for mac build, use the makefile in NativeCode/DynamicLibraryLoaderHelper_macOS to install the libraries UnityEngine.Debug:LogError (object) EOSOnPreprocessBuild:OnPreprocessBuild (UnityEditor.Build.Reporting.BuildReport) (at Library/PackageCache/com.playeveryware.eos@a4404cc7d9/Editor/EOSOnPreprocessBuild.cs:26) UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)</div>

**Comment by arthur740212** [comment]
Hello and thanks for the patience.
The mac build needs `DynamicLibraryLoaderHelper_macOS.dylib` to work.
We should be able to find a makefile in  `NativeCode/DynamicLibraryLoaderHelper_macOS/`
To build the `dylib`
1. Right clicking on the folder `NativeCode/DynamicLibraryLoaderHelper_macOS/`, there is an option to open the terminal in that folder.
2. Type `make install`, the `dylib` would be copied to `Assets/Plugins/macOS/`
