### ISSUE TITLE
Steam External Auth Issue

### ISSUE THREAD

**Issue by reithegoat** [PlayEveryWare/eos_plugin_for_unity#280]
Despite setting up Steam Identity Provider in the Epic Dev Portal, I am using the External Auth sample provided and keep getting this error.

```
2023-05-12T08:08:10.6353791-04:00 LogEOS(Warning): Error response received from backend. ServiceName=[OAuth], OperationName=[TokenGrantv2], Url=[<Redacted>], HttpStatus=[400], ErrorCode=[errors.com.epicgames.account.external_auth_validate_failed], NumericErrorCode=[18063], ErrorMessage=[Failed to verify token for authType: steam_session_ticket and sandboxId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, error: Invalid session ticket], CorrId=[EOS-iQxxB_FCYEOf4ylHd7fi0g-WZOulIMrBEmXEHn2FOWQvA-zscf1eOE10KglefGTcMeQw]
```
I am at a loss.

**Comment by andrew-hirata-playeveryware** [comment]
Hello @reithegoat,
Just to help you better, I have some followup questions: 
* Which version of the plugin are you using?
* Which version of unity are you using?
* Which platform are you building from?
* Which platform are you building for ? 
* Which login type are you using?

**Comment by reithegoat** [comment]
- Plugin version is 2.2.1
- Unity Editor version is 2021.3.16
- I am building from **and** for Windows
- I am using ExternalAuth, trying to sign in with Steam.

**Comment by FREEZX** [comment]
Having the same issue.
Latest EOS (2.3.0)
Unity 2022.2.5
Running editor on Windows for standalone windows target
Login type - ExternalAuth
Also having issues with Connect - SteamAppTicket (Error occured when requesting Encrypted App Ticket)

Not really sure where to look for more information on how to use these. I really wouldn't want to display any epic logins on my steam game.

**Comment by FREEZX** [comment]
Alright, I figured it out:
There was a compile error with the samples using the latest Steamworks.NET package:
`SteamUser.GetAuthSessionTicket` now requires another parameter `pSteamNetworkingIdentity`.
I assumed I just need to pass an empty NetworkingIdentity, but actually had to do something a bit more:

Here's my updated `GetSessionTicket` function:
```C#

        public string GetSessionTicket()
        {
#if DISABLESTEAMWORKS
            return null;
#else
            if (sessionTicketHandle != HAuthTicket.Invalid)
            {
                return sessionTicketString;
            }

            int bufferSize = 1024;
            byte[] buffer = new byte[bufferSize];
            uint ticketSize = 0;
            SteamNetworkingIdentity authId = new SteamNetworkingIdentity();
            authId.m_eType = ESteamNetworkingIdentityType.k_ESteamNetworkingIdentityType_GenericString;
            authId.SetSteamID(SteamUser.GetSteamID());
            authId.SetGenericString("epiconlineservices");
            sessionTicketHandle = SteamUser.GetAuthSessionTicket(buffer, bufferSize, out ticketSize, ref authId);
            if ((int)ticketSize > bufferSize)
            {
                SteamUser.CancelAuthTicket(sessionTicketHandle);
                bufferSize = (int)ticketSize;
                sessionTicketHandle = SteamUser.GetAuthSessionTicket(buffer, bufferSize, out ticketSize, ref authId);
            }
            Array.Resize(ref buffer, (int)ticketSize);
            //convert to hex string
            sessionTicketString = System.BitConverter.ToString(buffer).Replace("-", "");
            return sessionTicketString;
#endif

        }
```
the genericString being set (epiconlineservices) is set on the steam identity provider in the dashboard, this is the default value.

**Comment by andrew-hirata-playeveryware** [comment]
@reithegoat, did @FREEZX's fix resolve your issue also?

**Comment by reithegoat** [comment]
> @reithegoat, did @FREEZX's fix resolve your issue also?

Yes, it has!
