### ISSUE TITLE
EOSTransportManager incorrectly fragments packets larger than the maximum packet size

### ISSUE THREAD

**Issue by jaGilbertson** [PlayEveryWare/eos_plugin_for_unity#283]
**Describe the bug**
When using EOSTransportManager included in the Sample to run P2P using EOS relay servers, this error message occurs whenever a packet larger than the EOS max packet size (1170) is sent.

_"Netcode] Received a packet with an invalid Batch Size Value. Please report this to the Netcode for GameObjects team at https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/issues and include the following data: Offset: 0, Size: 2332, Expected Size: 2028"_

This is caused when sending packets, where packets larger than the EOS max packet size are fragmented.
When fragmenting the packet, the fragment array is created with this line:-

byte[] fragment = new byte[Mathf.Min(packet.Length + FragmentHeaderSize, MaxPacketSize)];

which doesn't take into account the data from the packet that has already been fragmented, which means the fragment will always be 1166. The last fragment sent for the packet will always contain trailing empty data.

Apparently this didn't used to cause a problem:
https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/issues/2536
"Just as a note: Good chance this happens on 1.2.0 and just isn't noticed. We added new safety checks in 1.3.1 that validate that what we received matches what we sent."

this can be fixed by changing the line mentioned above to factor in the data already fragmented, like:-
byte[] fragment = new byte[Mathf.Min((packet.Length - currentOffset) + FragmentHeaderSize, MaxPacketSize)];

**To Reproduce**
1. Connect 2 game clients using EOSTransportManager sample
2. Send a packet larger than 1170 bytes
3. Observe error on client (not the host)

**Expected behavior**
Packets get fragmented correctly
**Desktop (please complete the following information):**
 - OS: Windows x64
 - Editor
 - Unity Version 2022.2.13f1
 - Netcode for GameObjects 1.3.1
 - Plugin Version 2.2.1

**Comment by arthur740212** [comment]
Thanks for the observation and report.
Highly possible that it slipped, as the currentOffset exists but wasn't used.
