### ISSUE TITLE
XCode Asset validation failed

### ISSUE THREAD

**Issue by MenesApps** [PlayEveryWare/eos_plugin_for_unity#288]
Hi,
My update is finally ready to be released with the EOS plugin working. It works on Android but I am having issues with iOS.
I build it on my Mac and open it in XCode (tried both 14.2 and 14.3). I manage to archive it correctly but when I try to validate and send to the AppStore, I get this error : 
Asset validation failed.
No architectures in the binary. Lipo failed to detect any architecture in the bundle executable. 
This plugin being the only thing added, I checked the archive and looked around the files for the binary in question. 
I don't know much about Frameworks but all the other ones have a Unix Executable file, except for the EOSSDK one. See below.
![eos](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/13543160/cf83cdfa-7546-492d-a27c-461acaf80b19)
Did I miss a step somewhere ?

Here is my workflow for building with XCode if that helps :  
-Export from Unity.
-Delete Pods files.
-Reinstall pods.
-Open workspace.
-Fill / Check the app info, signing info, etc.
-Check if Bitcode is off in Unity-iPhone & UnityFramework
-Check if Always Embed Swift Standard Libraries is on in Unity-iPhone & off in UnityFramework.
-Archive and publish.

I am stuck so all the help will be appreciated.

**Comment by MenesApps** [comment]
By the way : I am using Unity 2021.3.15f (but I also tried on Unity 2022 with the same result) and using the latest version of the plugin, installed from Git. 
I have tried to build from my mac and using Unity Cloud Build with the same result.

**Comment by arthur740212** [comment]
Hello, here are some possible causes of the issue bases on inspection.
The `EOSSDK` file is smaller than the meta file, which is suspicious.
Does the source of `EOSSDK` also have this size, if so, try downloading the latest version of the EOS from the Epic Games Dev Portal

**Comment by MenesApps** [comment]
I have been testing for the past few days, and no problems :) Thanks for the help.
