### ISSUE TITLE
Verify that user has bought DLC

### ISSUE THREAD

**Issue by elwinverploegen** [PlayEveryWare/eos_plugin_for_unity#292]
Our DLC is already included in the main package, so we only need to do a license check to see if the player has purchased said DLC. I couldn't really find this in the included examples. What is the recommended method to verify if a player has purchased a certain DLC from the store?

**Comment by arthur740212** [comment]
Thanks for the report.
The plugin doesn't have a sample for DLCs yet. 
We're not sure if the SDK does support DLC so we've forwarded this question.
Will update here once we get the information.

**Comment by arthur740212** [comment]
Hi here are some updates. 
The SDK does offer a way of checking it on the client via the QueryOwnership API:
https://dev.epicgames.com/docs/epic-games-store/services/ecom/ecom-quick-start#verify-purchased-durable-content-eg-dlc
However it is recommended to check the ownership in the developer's own backend
