### ISSUE TITLE
We got a error when test this sdk

### ISSUE THREAD

**Issue by ehyea** [PlayEveryWare/eos_plugin_for_unity#293]
**Describe the bug**
We got a error when test this sdk
**To Reproduce**
1. open AuthAndFriends.unity
2. and is got some errors
Loading EOS binary EOSSDK-Win64-Shipping
Win32Exception: Searched in : E:/Unity/eos_plugin_for_unity/Assets\Plugins
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 10 x64
 - Editor, or standalone build
 - Unity Version 2021.3.23f1
 - Plugin Version 2.3.0

**Additional context**

**Comment by arthur740212** [comment]
Were you able to find EOSSDK-Win64-Shipping.dll in the project? If so was the size of the several MBs or KBs. 
If it is in the KB range the dll might be downloaded incorrectly.
