### ISSUE TITLE
Where is the EOS SDK located?

### ISSUE THREAD

**Issue by 3ternal** [PlayEveryWare/eos_plugin_for_unity#294]
In the readme for this repo, it says "Targets [EOS SDK 1.15.4](https://dev.epicgames.com/docs/epic-online-services/release-notes#1154---2022-nov-16) (bundled with plugin)."

That means the Epic SDK is located somewhere in here, right? What directory is it in? I was looking for the [Developer Authentication Tool](https://dev.epicgames.com/docs/epic-account-services/developer-authentication-tool), but I couldn't find it, and I ended up downloading the EOS SDK separately.

**Comment by arthur740212** [comment]
The libraries will be in `Assets/Plugin/[Platform]/...` ,where `...` could be some subfolders depending on architectures or such.
The library name will typically be `EOSSDK_[Platform]_Shipping` with library extension such as `.dll`,`.dylib`

**Comment by 3ternal** [comment]
Ah, hang on, I'm using the OpenUPM version of the asset rather than the standalone version. The folder layout is different, of course (no Plugin folder).

More importantly though, are the Tools included in either release? In the C# SDK from Epic, the tool I'm looking for is normally located at `SDK/Tools/EOS_DevAuthTool-win32-x64-1.1.0.zip`.

Clicking through the files in this repo, I can see `Assets/Plugins/Windows
/x64/EOSSDK-Win64-Shipping.dll` as you suggested, but I haven't found the tools folder.

**Comment by arthur740212** [comment]
The SDK usually means the eossdk.dll itself, that is what was bundled with the plugin.
The DevAuthTool is a tool that isn't a dependency for the SDK to work,
so we didn't include that in the release. (unsure if it is allowed to redistribute)

**Comment by 3ternal** [comment]
All right, that's fair. So it's still worthwhile to download the full package from Epic if we want access to the tools and other things that aren't dependencies.
