### ISSUE TITLE
EOSManagerPlatformSpecifics.Instance is null

### ISSUE THREAD

**Issue by FColor04** [PlayEveryWare/eos_plugin_for_unity#296]
**Describe the bug**
It seems that IL2CPP strips out some code that instantiates EOSPlatformSpecificsWindows, after adding [Preserve] attribute to EOSPlatformSpecificsWindows it still doesn't instantiate properly and throws null reference error.

**To Reproduce**
1. Get the plugin in unity
2. Use Mono, with managed stripping level set to disabled to compile the game and see that it works
3. Use IL2CPP, with managed stripping level set to minimal-high to compile the game and see the null reference error

**Expected behavior**
No errors thrown with clean installation

**Screenshots**

System.NullReferenceException: Object reference not set to an instance of an object.
  at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.InitializeOverlay (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) [0x00000] in <00000000000000000000000000000000>:0 
  at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) [0x00000] in <00000000000000000000000000000000>:0 
  at CrossPlatformUtilities.EpicImplementation.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
  at CrossPlatformUtilities.PlatformManager.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
  at CrossPlatformUtilities.PlatformManager.Awake () [0x00000] in <00000000000000000000000000000000>:0 
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
CrossPlatformUtilities.PlatformManager:Initialize()
CrossPlatformUtilities.PlatformManager:Awake()

EOSManager.cs@476
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/20670523/4f5a84e8-b5f8-4447-9733-a581dace602f)

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Standalone Il2Cpp Build
 - Unity 2022.2.13f1
 - Plugin Version 2.3.0

**Additional context**

**Comment by FColor04** [comment]
IEOSManagerPlatformSpecifics.cs
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/20670523/9a5cd0d4-9b84-4b6d-8a8a-9c649f18d5b7)
This fixed the issue alongside removing .core assembly definition

**Comment by Raxnam** [comment]
We are having some trouble reproducing these errors. The error itself points towards an issue with the Epic Overlay. Just to check, do you have the Epic Games Launcher installed?

**Comment by ChThielsch** [comment]
We are observing the same issue in our build and we do have the Epic Games Launcher installed

**Comment by ChThielsch** [comment]
With the help of [tamuatamu](https://github.com/tamuatamu)'s help over at the discussions tab [here](https://github.com/PlayEveryWare/eos_plugin_for_unity/discussions/302) we were able to find a fix that works with every platform. It appears to stem from IL2CPP and adding
`	<assembly fullname="com.playeveryware.eos">
		<type fullname="PlayEveryWare.EpicOnlineServices.EOSPlatformSpecificsWindows" preserve="all"/>
	</assembly>`
to your linker.xml file fixes the issue (For windows. For other platforms you need to change the EOSPlatformSpecificsWindows part)

When you do not already have a linker.xml there is a plain file within "Library\PackageCache\com.playeveryware.eos@07b08690e0\Editor\link.xml"
you can fill this one in and use Tools/Create linker.xml in Unitys menu bar to creat one

Hope this helps!

**Comment by Raxnam** [comment]
We have found the issue, and a fix should be included in the June Release at the end of the month.
