### ISSUE TITLE
macOS build fail: Cannot sign '<project path>/Contents/PlugIns/libDynamicLibraryLoaderHelper.dylib' because it is not a valid Mach-O binary

### ISSUE THREAD

**Issue by 3ternal** [PlayEveryWare/eos_plugin_for_unity#299]
I just noticed that my macOS builds have been failing since I installed this package. I tested in a blank project, and the builds succeed when I remove the package.

When the build enters the post-process phase, I get the following errors:

```
Building C:\Users\eternal\Desktop\quick build (for laptop)\macOS\Monospaced Lovers.app\Contents\PlugIns\libDynamicLibraryLoaderHelper.dylib failed with output:
System.Exception: Cannot sign 'C:/Users/eternal/Desktop/quick build (for laptop)/macOS/Monospaced Lovers.app/Contents/PlugIns/libDynamicLibraryLoaderHelper.dylib' because it is not a valid Mach-O binary.
   at MacOSCodeSignDylibCopy.Run(CSharpActionContext ctx, SignFlags signFlags)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

```
BuildFailedException: Incremental Player build failed!
UnityEditor.Modules.BeeBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at <36f62d8e760b48f7af5d32916f997ce1>:0)
UnityEditor.OSXStandalone.OSXDesktopStandalonePostProcessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/OSXPlayer/Extensions/Managed/OSXDesktopStandalonePostProcessor.cs:117)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <36f62d8e760b48f7af5d32916f997ce1>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.Int32 subtarget, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <36f62d8e760b48f7af5d32916f997ce1>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```

Unity 2021.3.4
Epic Online Services Plugin for Unity 2.3.0

Is there anything specific we have to do to configure the Mac builds after installing this? And if not, is there a way to just disable the package when creating Mac builds?

**Comment by andrew-hirata-playeveryware** [comment]
Hello @3ternal ,
How did you install the plugin ?

**Comment by 3ternal** [comment]
Hi @andrew-hirata-playeveryware,

Installed via OpenUPM: https://openupm.com/packages/com.playeveryware.eos/

**Comment by arthur740212** [comment]
Was able to reproduce this with OpenUPM.
It appears that with the scoped registry approach it does not fetch git lfs stored resources correctly.
Might need to add additional arguments for OpenUPM/scoped registry to work or try directly adding the package without the scoped registry

**Comment by 3ternal** [comment]
Good to hear that you can reproduce it.

> Might need to add additional arguments for OpenUPM/scoped registry to work

Can you elaborate on this?

Given the choice, I usually opt for OpenUPM because of the auto-updates (I don't think Unity can detect updates if you add the package via git url?). But I can certainly add it directly for now as a workaround.

**Comment by arthur740212** [comment]
Hi, here is an update.
The v2.3.0 build on OpenUPM was on an earlier commit that has faulty lfs support.
There are no extra steps needed for OpenUPM to support lfs, as it already does.
We have updated our v2.3.0 tag to target the commit with git lfs support.
Next step is to contact OpenUPM and wait for an update for the v2.3.0 build.
In the meantime adding the package with the git url directly should be working.
Thanks for the report.

**Comment by 3ternal** [comment]
Hmm, it looks like the new build for 2.3.0 published yesterday is still giving the same problem.

**Comment by arthur740212** [comment]
It did have the same problem, we took a look and found out we were refreshing but not updating our v2.3.0 tag to follow what a release meant in our publishing routine.
But given that we have the fix working from our main repo, and our next release is planned to be out within a week, we will be counting on the next build on OpenUPM to be functioning.
Sorry for the inconvenience, and thanks for the wait and report.

**Comment by 3ternal** [comment]
Hmm, I'm getting a 404 on that link.

Is it possible to do this from a Windows environment? I can set it up on a Mac if required, but I usually build for PC/Mac/Linux from my PC.

**Comment by arthur740212** [comment]
Oops, wrong link. it is corrected now.
And yes it is possible to run a make file on Windows.
But since make isn't installed on Windows by default, we will have to install and set it up first.
Then follow the steps in the doc.

**Comment by 3ternal** [comment]
Thanks, I'll check that out. Just to confirm, is this step necessary for _creating_ a Mac build? Or is it only required if you're building _from_ a Mac?

**Comment by arthur740212** [comment]
It is for *creating* a mac build, as that `.dylib` is something that the plugin/application uses, not what Unity uses.

**Comment by 3ternal** [comment]
All right, I installed make in Windows, but I'm getting the following error.

```
PS C:\Users\eternal\Documents\GitHub\eos_plugin_for_unity\NativeCode\DynamicLibraryLoaderHelper_macOS> make install
test -d build || mkdir build
'test' is not recognized as an internal or external command,
operable program or batch file.
clang++ -dynamiclib DynamicLibraryLoaderHelper_macos.cpp -arch arm64 --std=c++11 -o build/DynamicLibraryLoaderHelper_mac_arm
process_begin: CreateProcess(NULL, clang++ -dynamiclib DynamicLibraryLoaderHelper_macos.cpp -arch arm64 --std=c++11 -o build/DynamicLibraryLoaderHelper_mac_arm, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:48: build/DynamicLibraryLoaderHelper_mac_arm] Error 2
```

Also, I wasn't able to find the NativeCode folder in the OpenUPM package, so I cloned this repo just to test it. Not sure if that would affect it.

**Comment by arthur740212** [comment]
The upm package doesn't include the `Native Code` folder. 
Sorry for the inconvenience.
The last release had some assemblies for mac builds missing.
We are working on a hotfix release, which should be ready in a day.

**Comment by arthur740212** [comment]
The fix/release 2.3.2 is up, have a look and thanks for all the feedback!

**Comment by 3ternal** [comment]
Thanks for the quick fix!

Hmm, I'm still getting a similar error when trying to build it. The "test" part is gone, but the rest of the error is the same.

```
clang++ -dynamiclib DynamicLibraryLoaderHelper_macos.cpp -arch arm64 --std=c++11 -o build/DynamicLibraryLoaderHelper_mac_arm
process_begin: CreateProcess(NULL, clang++ -dynamiclib DynamicLibraryLoaderHelper_macos.cpp -arch arm64 --std=c++11 -o build/DynamicLibraryLoaderHelper_mac_arm, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:48: build/DynamicLibraryLoaderHelper_mac_arm] Error 2
```

If I were to try the other option and manually add the dylib, which file should I add to the project? I see a handful of files named DynamicLibraryLoaderHelper, but none of them are .dylib.

**Comment by arthur740212** [comment]
The missing dylib should be added in the package after release v2.3.2 .
Such that you could directly build the plugin without needing to use the makefile.

**Comment by 3ternal** [comment]
Okay, got it. I think I'm good to go!

I haven't fully onboarded with Epic yet, so I can't test if the integration is working - but I can say that the Mac builds are completing without error, and they can boot up on my Macbook.
