### ISSUE TITLE
Failed to load dll

### ISSUE THREAD

**Issue by s8cusyqr** [PlayEveryWare/eos_plugin_for_unity#312]
**Describe the bug**
On eosmanager init on unity it shows Failed to load 'C:/Program Files/Epic Games/Plugins\x86_64/GfxPluginNativeRender-x64.dll', expected x64 architecture, but was Unknown architecture. You must recompile your plugin for x64 architecture.. In unity i have selected for this dll windows standalone and x64.

**To Reproduce**
Build and run game

**Expected behavior**
dll loaded

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows x64
 - standalone
 - 2021
 - I tried many versions

**Smartphone (please complete the following information):**

**Additional context**
I tried downloading many released from 1.00-2.1-2.3 etc. and use gfxpluginnativerender-x64 from them, but none of them worked. There is always error Failed to load 'C:/Program Files/Epic Games/Plugins\x86_64/GfxPluginNativeRender-x64.dll', expected x64 architecture, but was Unknown architecture. You must recompile your plugin for x64 architecture.. In unity i have selected for this dll windows standalone and x64.

**Comment by arthur740212** [comment]
2.3.0 has some git lfs issues. We will have an 2.3.1 update in a day.
While you have all of the versions not working, that might indicate git lfs isn't installed on the device.
