### ISSUE TITLE
matchmaking

### ISSUE THREAD

**Issue by nsmith1024** [PlayEveryWare/eos_plugin_for_unity#315]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]. 
Also consider if this is an issue that the plugin handles, or something that the Epic Online Services
SDK handles, E.G. "It would be nice if the EOS ran on the Plan 9 Operating System". Such requests are usually best posted to the Epic's [forum](https://eoshelp.epicgames.com/s/). 

The problem is i need matchmaking for Unity

**Describe the solution you'd like**

Does this support matching making for unity?

**Describe alternatives you've considered**

Alternative is to use a different platform from EOS that has matchmaking.

**Additional context**

**Comment by andrew-hirata-playeveryware** [comment]
Hello @nsmith1024,

The EOS SDK doesn't support server side matchmaking, which I believe is the feature you're looking for. However you can replicate similar behavior by using lobby attributes, doing a search for a number of lobbies, and automatically joining one of the servers. 

Additionally, if you would like to request this as a feature for the EOS SDK itself, you can go to the official EOS [forums](https://eoshelp.epicgames.com/s/).

**Comment by nsmith1024** [comment]
Thanks for the info, is there any sample code that shows how to do that?

Thanks
