### ISSUE TITLE
Epic Games Overlay Fails to Initialize on OSX

### ISSUE THREAD

**Issue by Kurtis02** [PlayEveryWare/eos_plugin_for_unity#318]
**Describe the bug**
EOS overlay does not initialize on OSX, but works fine on Windows. This causes various other features of the EOS SDK to not work.

**To Reproduce**
1. Start with a working EOS project using the PlayEveryWare plugin
2. Import `DynamicLibraryLoaderHelper_mac_arm`, `DynamicLibraryLoaderHelper_mac_x86`, `DynamicLibraryLoaderHelper.dylib`, `MicrophoneUtility_macos.dylib`, `MicrophoneUtility_mac_arm`, `MicrophoneUtility_mac_x86` into the `Assets/Plugins` folder (in our project these files are located at `Assets/Plugins/MacOS`, but I don't think the subfolder should matter)
3. Add the `EOS_PREVIEW_PLATFORM` compile flag to the Standalone player settings
4. Build the project for OSX
5. Upload to Epic Games
6. Download and run through the Epic Games launcher on a Mac computer

**Expected behavior**
The EOS SDK should initialize and make the overlay available.

**System used to build the game and upload to Epic:**
 - Windows 10 x64
 - Unity Editor 2019.4.40
 - Plugin Version 2.2.0

**System used to build the OSX native code and run the game:**
- MacOS Ventura 13.3.1

**Additional context**
The EOS SDK initializes without issue, but then fails to initialize the overlay with a "NotConfigured" error. Myself and my teammates have scoured the EOS Dashboard as well as the in-editor config for any settings that might not be right, but we came up empty-handed. As such this doesn't seem like a configuration error on our end.

The only other information that could point to an error is a line in the log file that says 'Platform not supported', however this has no stack trace nor any other info, so I'm not sure where it's coming from.

Thanks in advance, and please let me know if y'all need any other info. Your work is much appreciated.

**Comment by arthur740212** [comment]
The social overlay isn't supported on MacOS, thus the friends UI exists for some basic features of the social overlay.

**Comment by Kurtis02** [comment]
Ah, I see - Thanks for the quick response. That's unfortunate that it isn't supported, is that something on Epic's end or yours?
