### ISSUE TITLE
Error listing oauth scopes (Unable to login for Achievement Example Scene)

### ISSUE THREAD

**Issue by BumpMage** [PlayEveryWare/eos_plugin_for_unity#324]
Hi,

When trying to login in the Achievement Example, using Dev Auth, I get the Error message [Error listing oauth scopes].  When using "Account Portal", the browser shows a message saying "Invalid Client" and "Client scopes are not configured". I have not found any reference to this, and my only guess would be a missing client in the developer portal, or a missing policy for that client. However, neither should be the case.

Sorry if this is a beginner question, because it does feel like it would just be a missing part of the configuration either in the plugin or in the Epic project. But while I have been able to find and eventually solve the errors that came bevor, this time I am at a loss.

Here are the logs as well. 
Upon starting the scene:

```
[Log] : EOSManager: Registering for platform-specific notifications

[Warning] : EOSManager::Init: InitializePlatformInterface: initResult = AlreadyConfigured

[Log] : EOSManager: Registering for platform-specific notifications

[Warning] : EOSManager::Init: InitializePlatformInterface: initResult = Success

[Warning] : 2023-06-18T17:42:33.6748934+02:00 LogEOSAuth(Warning): FAccountPortalBrowserManager::Init: Failed to register overlay: EOS_NotConfigured

[Warning] : There are menu items registered under Edit/Project Settings: FarseerUnity
Consider using [SettingsProvider] attribute to register in the Unified Settings Window.

[Warning] : 2023-06-18T17:42:34.2540521+02:00 LogEOSAnalytics(Warning): EOS SDK Analytics disabled for route [1].
```

Upon trying to login with Dev Auth:

```
[Log] : Attempting to login...

[Warning] : 2023-06-18T17:45:07.4847017+02:00 LogEOS(Warning): Error response received from backend. ServiceName=[OAuth], OperationName=[TokenGrantv2], Url=[<Redacted>], HttpStatus=[400], ErrorCode=[errors.com.epicgames.server_error], NumericErrorCode=[1012], ErrorMessage=[Error listing oauth scopes], CorrId=[EOS-9ajt7nMc-0mVo7dRAQDDQA-pdIq6z7MqU6J7_HJWn7_ug-Y8bS0VPW9UqPjAQTyBFnsA]

[Log] : Error logging in. [UnexpectedError]
```

Upon trying to login with Account Portal:

```
[Log] : Attempting to login...

[Warning] : 2023-06-18T17:47:09.8677614+02:00 LogEOSAuth(Warning): BeginDesktopCrossplayLogin: Desktop crossplay is not ready: EOS_DesktopCrossplay_ApplicationNotBootstrapped

[Warning] : 2023-06-18T17:47:10.0151567+02:00 LogEOSAuth(Warning): UserAuthGenerated: Account Portal overlay failed to load for device auth continuation; falling back to browser based flow

[Warning] : 2023-06-18T17:47:10.1733694+02:00 LogEOS(Warning): Error response received from backend. ServiceName=[OAuth], OperationName=[TokenGrantv2], Url=[<Redacted>], HttpStatus=[400], ErrorCode=[errors.com.epicgames.account.oauth.authorization_pending], NumericErrorCode=[1012], ErrorMessage=[The authorization server request is still pending as the end user has yet to visit and enter the verification code.], CorrId=[EOS-9ajt7nMc-0mVo7dRAQDDQA-pdIq6z7MqU6J7_HJWn7_ug-eO0UCK4nvEmw7bP7z6oOSQ]

[Warning] : 2023-06-18T17:47:20.2924898+02:00 LogEOS(Warning): Error response received from backend. ServiceName=[OAuth], OperationName=[TokenGrantv2], Url=[<Redacted>], HttpStatus=[400], ErrorCode=[errors.com.epicgames.not_found], NumericErrorCode=[1012], ErrorMessage=[PIN grant data not found.], CorrId=[EOS-9ajt7nMc-0mVo7dRAQDDQA-pdIq6z7MqU6J7_HJWn7_ug-8JQS-OXEY0K4Ml5dheaLIw]

[Warning] : 2023-06-18T17:47:20.2924898+02:00 LogEOSAuth(Warning): Polling token grant failed

[Log] : Error logging in. [NotFound]

```

**Comment by arthur740212** [comment]
Hi, were you running with a clone of the repo? or the UPM package of the plugin?
And was your configuration settings all set?

**Comment by BumpMage** [comment]
I was using the UPM package, imported from the newest tarball. After your question, I also tried to import it into Unity via the git link, with the same results.

Configuration is all set as far as I can tell, but to make sure I'm not missing anything, here are the values I filled out:

Product Name: 
Taken from the dev portal

Product Version:
Now that I see it again, this one might be a problem?
I originally entered my latest binary version from the dev portal, but that contained characters other than numbers, and somewhere else here I read that this would be a problem. So currently it is just "1". If the value here should be taken from somewhere else, I have not found it in the documentation.

Product ID, Sandbox ID, Deployment ID, Client ID, Client Secret:
All taken from the dev portal, specifically for the "Dev" Sandbox / Deployment. The values entered are also the same that are included when I let the dev portal generate a header file with the credentials for the "Dev" Deployment.

Encryption Key:
Generated

**Comment by andrew-hirata-playeveryware** [comment]
I believe the issue is that the client scopes and the client on Epic's developer portal haven't been configured, so the plugin can't function. Have you configured a client yet on their back end? It will be under The title's page -> Product Settings -> Clients.

**Comment by BumpMage** [comment]
I have created a client, and linked it to a client policy. The policy uses the standard settings for achievements. If I understand it correctly, I should not have gotten a "Client ID" and "Client Secret" otherwise. I also believe that the client is correctly linked up with the rest of the product, since I can generate a header file in the main Product Settings, which includes that data together with everything else.

However, I have not seen the the word "scopes" in any of these settings, or in the documentation. Only in the error messages and in your comment. Is there another place that these would need to be configured?

**Comment by BumpMage** [comment]
Alright, that got me on the right track, which was "search the general documentation for 'scopes' again and try out everything you find".

For future reference, if anybody else has the same problem:
Epic Account Services -> Permissions -> Save Changes

Even if you want to use the standard settings, you have to "save" these settings once. That's what I did not do the last time, because no changes were needed.

Thank you, to both of you!
