### ISSUE TITLE
On Windows Build: DllNotFoundException: GfxPluginNativeRender-x64

### ISSUE THREAD

**Issue by danewfie** [PlayEveryWare/eos_plugin_for_unity#329]
**Describe the bug**
Imported the Samples and generated a build.
After generating a build and distributing to another computer, I get the following error in the logs at runtime.
```
22:00:11.207 [Log] : Start of Early EOS LOG:
<color=#FF0000>22:00:11.208 [Exception] : DllNotFoundException: GfxPluginNativeRender-x64 assembly:<unknown assembly> type:<unknown type> member:(null)</color>
```

**To Reproduce**
1. Import Samples
2. Build Sample Project
3. Distribute to another computer without unity installed.
4. Launch EOSBootstrapper
5. See error

**Expected behavior**
Expect EOS to initialize without errors.

**Screenshots**
![2023-06-20 (1)](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/10082062/15b03100-f736-424f-a46a-52c4e473e398)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home x64
 - standalone build
 - Unity Version 2021.3.18f1
 - Plugin Version v-2.3.2

**Additional context**
Samples works fine on my local development Machine.

**Comment by arthur740212** [comment]
Is the plugin folder copied to the second computer?
If it is copied, what was the size of the GfxPluginNativeRender-x64.dll?
Also is the architecture(x86/x64) compatible for the device?

**Comment by danewfie** [comment]
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/10082062/3c4d2bf7-1d4a-4580-b89f-bfec00f2c89b)

Plugins folder was copied, doesn't look like the other issues with git lfs not copying.
It was moved onto a second computer with same operating system, but no dev tools installed. (Both dev and test machine are windows 10 x64)
I am trying to validate that when I build I can deploy to another machine for testing. Works in development and get this error on test machine.

Is there anything specific required when deploying that I might be missing?

**Comment by arthur740212** [comment]
Ah. Did the other computer have Epic Game Launcher installed? That might be the cause.

**Comment by danewfie** [comment]
No, I was under the impression that it was not required for crossplay.
I thought only "EpicOnlineServicesInstaller" was required for installation?

I tried installing the Epic Game Launcher and still had the same issue.

I did a clean windows OS install and tried again with no luck.

Process:

1. Installed all the dev tools (Unity) and setup a new project and imported the package. Imported the samples. Installed the Epic Launcher, Epic Game Services and performed a build.
2. (Everything worked fine.)
3. Uninstalled Epic Game Launcher.
4. (Everything still worked fine)
5. Uninstalled Epic Game Services.
6. (Everything Still works)

I will perform a clean OS install again and try to replicate the error from a fresh OS like I had in the original error.

Is it possible something never got installed as part of the bootstrapper?

**Comment by arthur740212** [comment]
We tested this by distributing to a second computer, and wasn't able to reproduce the problem.
How was your build distributed? Is the whole folder copied? 
![Windows 6_23_2023 4_58_40 PM (2)](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/36757173/00561737-32fb-4453-b23a-0dc4aaf11ae1)

**Comment by danewfie** [comment]
I zipped the build folder and distributed that to the other computer.
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/10082062/cb8da07c-8203-464b-a7fa-6c51e9a5df25)

I was able to successfully distribute to another computer the same zip file and it works fine.
Appears to be something with this machine.

I will attempt to build another computer and see if that runs successfully.
At this point I'm not sure how to debug this machine.

**Comment by danewfie** [comment]
I realized afterwards the computer I tested on had unity and other dev tools installed which is what allowed it to succeed.

I retested by using a VM in my Hyper-V. This is the player log I get below:
One thing I noticed from the logs is that there are no dll files in the MonoBleedingEdge folder.


> Mono path[0] = 'C:/Development/Windows/FishEOS_Data/Managed'
> Mono config path = 'C:/Development/Windows/MonoBleedingEdge/etc'
> Plugins: Failed to load 'C:/Development/Windows/FishEOS_Data/Plugins\x86_64/GfxPluginNativeRender-x64.dll' because one or more of its dependencies could not be loaded.
> Plugins: Failed to load 'C:/Development/Windows/FishEOS_Data/Plugins\x86_64/DynamicLibraryLoaderHelper-x64.dll' because one or more of its dependencies could not be loaded.
> Initialize engine version: 2021.3.18f1 (3129e69bc0c7)
> [Subsystems] Discovering subsystems at path C:/Development/Windows/FishEOS_Data/UnitySubsystems
> GfxDevice: creating device client; threaded=1; jobified=1
> Direct3D:
>     Version:  Direct3D 11.0 [level 11.1]
>     Renderer: Microsoft Basic Render Driver (ID=0x8c)
>     Vendor:   Microsoft
>     VRAM:     1023 MB
> Begin MonoManager ReloadAssembly
> - Completed reload, in  1.600 seconds
> Dedicated video D3D11 device creation failed (error: 0x887a0004). This device is used specifically for video decoding, we will use software video decoding instead.
> <RI> Initializing input.
> 
> XInput1_3.dll not found. Trying XInput9_1_0.dll instead...
> <RI> Input initialized.
> 
> <RI> Initialized touch support.
> 
> UnloadTime: 3.794100 ms
> 
> Start of Early EOS LOG:
> Fallback handler could not load library C:/Development/Windows/FishEOS_Data/MonoBleedingEdge/GfxPluginNativeRender-x64
> Fallback handler could not load library C:/Development/Windows/FishEOS_Data/MonoBleedingEdge/GfxPluginNativeRender-x64.dll
> Fallback handler could not load library C:/Development/Windows/FishEOS_Data/MonoBleedingEdge/GfxPluginNativeRender-x64.dll
> Fallback handler could not load library C:/Development/Windows/FishEOS_Data/MonoBleedingEdge/GfxPluginNativeRender-x64
> Fallback handler could not load library C:/Development/Windows/FishEOS_Data/MonoBleedingEdge/libGfxPluginNativeRender-x64
> Fallback handler could not load library C:/Development/Windows/FishEOS_Data/MonoBleedingEdge/libGfxPluginNativeRender-x64.dll
> Fallback handler could not load library C:/Development/Windows/FishEOS_Data/MonoBleedingEdge/libGfxPluginNativeRender-x64.dll
> Fallback handler could not load library C:/Development/Windows/FishEOS_Data/MonoBleedingEdge/libGfxPluginNativeRender-x64
> Fallback handler could not load library C:/Development/Windows/FishEOS_Data/MonoBleedingEdge/GfxPluginNativeRender-x64
> Fallback handler could not load library C:/Development/Windows/FishEOS_Data/MonoBleedingEdge/GfxPluginNativeRender-x64.dll
> Fallback handler could not load library C:/Development/Windows/FishEOS_Data/MonoBleedingEdge/GfxPluginNativeRender-x64.dll
> Fallback handler could not load library C:/Development/Windows/FishEOS_Data/MonoBleedingEdge/GfxPluginNativeRender-x64
> Fallback handler could not load library C:/Development/Windows/FishEOS_Data/MonoBleedingEdge/libGfxPluginNativeRender-x64
> Fallback handler could not load library C:/Development/Windows/FishEOS_Data/MonoBleedingEdge/libGfxPluginNativeRender-x64.dll
> Fallback handler could not load library C:/Development/Windows/FishEOS_Data/MonoBleedingEdge/libGfxPluginNativeRender-x64.dll
> Fallback handler could not load library C:/Development/Windows/FishEOS_Data/MonoBleedingEdge/libGfxPluginNativeRender-x64
> DllNotFoundException: GfxPluginNativeRender-x64 assembly:<unknown assembly> type:<unknown type> member:(null)
>   at (wrapper managed-to-native) PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.global_log_flush_with_function(intptr)
>   at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.GetEOSPlatformInterface () [0x00030] in <a07a25ce8c8b4a4eb009438bab502fb0>:0 
>   at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) [0x00024] in <a07a25ce8c8b4a4eb009438bab502fb0>:0 
>   at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) [0x00000] in <a07a25ce8c8b4a4eb009438bab502fb0>:0 
>   at PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager.Awake () [0x00005] in <2b8982539cc2488bbe2ae9695a31d83d>:0

**Comment by arthur740212** [comment]
When building with the package, the `dll`s should be placed into `[gamename]_Data\Plugins\[x86/x64]` by default
Curious why the dlls are in MonoBleedingEdge instead.

**Comment by arthur740212** [comment]
Just to make sure, were you running through the zip file?

**Comment by danewfie** [comment]
All files are extracted and works when dev tools are installed. (tested on multiple machines)

Only fails and tries the fallback when dev tools are not installed.
(note the dll's exist in the plugin folder but not in the MonoBleedingEdge)

I will try a windows 11 build tonight and see if there is any difference there.

**Comment by arthur740212** [comment]
It is likely that the dlls are dependent on some system binaries.
We will run a quick check on what are needed on the system side

**Comment by danewfie** [comment]
Windows 11 does not throw this error in my tests.
Appears to be windows 10 specific?

**Comment by arthur740212** [comment]
Here is the list of binaries that GfxPluginNativeRender-x64.dll is dependent on
    
```
    KERNEL32.dll
    MSVCP140.dll
    VCRUNTIME140.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
```

**Comment by danewfie** [comment]
These files are missing from a default windows 10 install.

I came across this [EOSHelp](https://eoshelp.epicgames.com/s/question/0D54z00007GySEECA3/the-epic-eossdk-dll-fails-to-load-on-some-windows-machines?language=en_US) thread.

The solution here was to install vc_redist.x64.exe.

This fixes both my VM and non-VM machines.

Is there any way around this? An average user would not know to install this.

**Comment by arthur740212** [comment]
Thanks for the information. We will add this requirement into our docs.
