### ISSUE TITLE
Define symbol "EOS_DISABLE" doesn't disable everything

### ISSUE THREAD

**Issue by mmazurek-fv** [PlayEveryWare/eos_plugin_for_unity#330]
EOS_DISABLE doesn't disable everything

![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/105931080/767c3f74-e274-40b0-aed9-c1e164735948)

Log error
Library\PackageCache\com.playeveryware.eos@59827f9f6983\Runtime\iOS\Core\EOS_iOSLoginOptionsHelper.cs(26,7): error CS0246: The type or namespace name 'Epic' could not be found (are you missing a using directive or an assembly reference?)

Desktop (please complete the following information):

OS: Windows 11 Home x64
standalone build
Unity Version 2021.3.12f1
Plugin Version v-2.3.2

**Comment by arthur740212** [comment]
Oops this slipped during the EOS_DISABLE refactor.
Will be a fix in the next release.
Thanks for the report.

**Comment by arthur740212** [comment]
The fix is in [this commit] (https://github.com/PlayEveryWare/eos_plugin_for_unity/commit/22a09d177732474ae58b3a9a8c7b0b109490f8e4),
which will be in out in the next release.
