### ISSUE TITLE
Add Friend way

### ISSUE THREAD

**Issue by tamuatamu** [PlayEveryWare/eos_plugin_for_unity#331]
I have a question on how to add friend.

I found 
`  private void AddFriendButtonOnClick(EpicAccountId searchResultEntry)
        {
            FriendsManager.AddFriend(searchResultEntry);
        }`
this function.
This function need to know friend's EpicAccountId manually, right?

I want to implement that can serach from friend's Name, And found friend and add Friend.
Is there any function to meet my requirement?

**Comment by arthur740212** [comment]
EOSFriendsManager.QueryUserInfo
Is the function used to find the EpicAccountId for a given DisplayName.
Note that the full DisplayName should be passed into the function to get the result.

**Comment by tamuatamu** [comment]
Thank you for teaching me.
Now,I can found friends.
But after i try to add friend.
it show some error.
Error Unity Friends (SendInviteCompleted):Not Configured

below is code.
` public void SetFriendData(FriendData data)
        {
            Debug.Log(this.gameObject);
            Debug.Log("SetFriendData");
            friendData = new FriendData()
            {
                Name = data.Name,
                Status = data.Status,
                LocalUserId = data.LocalUserId,
                UserId = data.UserId
            };
            DisplayName.text = data.Name;
            Debug.Log(DisplayName.text);
            Debug.Log(friendData);
        }
       `
 ` public void FriendInteractOnClickHandler()
        {
            if (friendData == null)
            {
                Debug.LogError("UIFriendEntry (FriendInteractOnClickHandler): friendData is not set!");
                return;
            }

            if (FriendInteractOnClick != null)
            {
                FriendInteractOnClick(friendData);
            }
            else
            {
                Debug.LogError("UIFriendEntry (FriendInteractOnClickHandler): FriendInteractOnClickHandler is not defined!");
            }
        }
        `
        
        Then Now FriendInteractOnClick is assigned　by below function
        `   private void AddFriendButtonOnClick(FriendData friendData)
        {
            FriendsManager.AddFriend(friendData.LocalUserId);
        }`

**Comment by arthur740212** [comment]
Were you running it through unity editor or standalone?
We supspect the not configured error to be about the EOSOverlay. which is only supported on windows standalone now.

**Comment by tamuatamu** [comment]
I encountered the following error log in an Android application:

vbnet
```
Copy code
2023/07/06 08:39:29.865 30268 30295 Error Unity Friends (SendInviteCompleted): ResultCode error: NotConfigured
2023/07/06 08:39:29.865 30268 30295 Error Unity PlayEveryWare.EpicOnlineServices.Samples.EOSFriendsManager:SendInviteCompleted(SendInviteCallbackInfo&)
2023/07/06 08:39:29.865 30268 30295 Error Unity Epic.OnlineServices.Friends.FriendsInterface:OnSendInviteCallbackInternalImplementation(SendInviteCallbackInfoInternal&)
```

Now, I need to use EOSOverlay to send a friend invite,right? Additionally, I would like to know the best way to establish a connection on Android. My goal is to achieve a peer-to-peer (P2P) connection using the EOS Relay Server. I have tried using the NetCode Sample, but it seems that in order to connect in the sample, I need to become friends with the other user first, is that correct? I'm currently stuck and unable to figure out how to establish a connection on Android. Thank you in advance for your assistance.

**Comment by arthur740212** [comment]
At the moment, sending a friend request could only achieved by the social overlay, which is still under work on android.
The workaround for this is to send the invites through a Windows standalone build.
Sorry for the inconvenience, and thanks for the report, we'll update the plugin as soon as the overlay is ready.
