### ISSUE TITLE
Error loading library: Win32Exception, NullReferenceException on Login attempt

### ISSUE THREAD

**Issue by atomknack** [PlayEveryWare/eos_plugin_for_unity#332]
**Describe the bug**
Error loading library, Error trying to login (even with developer login) for any example.

Win32Exception: Searched in : C:/someoneExamples/eos_plugin_for_unity-2.3.2/Assets\Plugins
DLLHandle.LoadDynamicLibrary (System.String libraryName) (at Assets/Plugins/Source/Core/DLLHandle.cs:190)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadDynamicLibrary (System.String libraryName) (at Assets/Plugins/Source/Core/EOSManager_DynamicLoading.cs:195)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadDelegatesWithEOSBindingAPI () (at Assets/Plugins/Source/Core/EOSManager_DynamicLoading.cs:220)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadEOSLibraries () (at Assets/Plugins/Source/Core/EOSManager_DynamicLoading.cs:360)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) (at Assets/Plugins/Source/Core/EOSManager.cs:550)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) (at Assets/Plugins/Source/Core/EOSManager.cs:498)
PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager.Awake () (at Assets/Scripts/Core/EOSHostManager.cs:49)

NullReferenceException: Object reference not set to an instance of an object
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.StartLoginWithLoginOptions (Epic.OnlineServices.Auth.LoginOptions loginOptions, PlayEveryWare.EpicOnlineServices.EOSManager+OnAuthLoginCallback onLoginCallback) (at Assets/Plugins/Source/Core/EOSManager.cs:1217)

**To Reproduce**
Load latest (or 2.3.2 version) zip from this repository, attempt to run any example.

**Expected behavior**
No error, and can run examples

**Desktop:**
 - OS: Windows 11 x64 updates installed. No any separate Epic game services installed.
 - Editor
 - Unity Version All LTS: 2021.3.8f1, 2021.3.25f1, 2022.3.0f1
 - Plugin Version: 2.3.2, Latest

**Additional context**
Build for 64 (and 32) bit windows fails with message (message translated from non-English version):
Win32Exception: ApplicationName='C:/someoneExamples/eos_plugin_for_unity-2.3.2/Assets\../bin/EOSBootstrapperTool.exe', CommandLine=' --output-path "C:\someoneExamples\eos_plugin_for_unity-2.3.2\build\EOSBootstrapper.exe" --app-path "EOS Unity Plugin - Demo.exe"', CurrentDirectory='C:/someoneExamples/eos_plugin_for_unity-2.3.2/Assets\../bin/', Native error= This version "%1" is not compatible with the version of Windows running on this computer. Check the system information, and then contact the software publisher.

**Comment by arthur740212** [comment]
If the zip installed was the auto-generated zip by github, it will be missing binaries.
Follow [This page](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/readme.md#importing-the-plugin) for a step by step guidance.

**Comment by atomknack** [comment]
You are correct.
I was able to run using 2 methods:
1)By using [com.playeveryware.eos-2.3.2.tgz](https://github.com/PlayEveryWare/eos_plugin_for_unity/releases/download/v2.3.2/com.playeveryware.eos-2.3.2.tgz)
2) by cloning whole repository with git-lfs enabled.

 I just never expected that even github releases could contain not working files (both zip and tar.gz), so there are pictures for people who could have same problem in future:

![eos pictures1](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/110350925/742a455c-b74b-4567-b38f-c30254af9c45)
![eos pictures2](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/110350925/83cacae5-7942-406d-be27-9662fbd56b82)
