### ISSUE TITLE
Android init failed

### ISSUE THREAD

**Issue by alvinsat** [PlayEveryWare/eos_plugin_for_unity#333]
**Describe the bug**
I try to build for android from macOS ventura, I tried on unity editor it works but when I build it the logs says initialization failed object reference not set to an instance of an object

**To Reproduce**
1. Create new android project in unity 2021.3 LTS
2. Add package using upm git link
3. Set init all configuration in Tools>EpicOnlineService configurator 
4. Add macOS Define Symbols for mac preview
5. Build for android min sdk 23.
6. Tested on android 9

**Expected behavior**
Android app runs with no init error message

**Comment by arthur740212** [comment]
We'd like to ask some questions to help us find out what happened. 
1. Which package were you using?
2. Were you able to track which reference was missing?

**Comment by alvinsat** [comment]
Hi, sorry for late response
1. https://github.com/PlayEveryWare/eos_plugin_for_unity_upm.git it was from this link and in unity it shows version 
 - Friendly Plugin for Epic Online Services
 - Unity 2020.1.11f1
 - EOS SDK 1.15.5
2. I am not sure. but it clearly says on initialization failed. So I assume it was the EOS initialization

**Comment by RedMazer** [comment]
what version of the plugin are you on?

also this should be unrelated, but the EOS_PREVIEW_PLATFORM define is for creating a mac app (among other platforms in beta), it wouldnt be needed to build an android app using the mac version of unity

**Comment by alvinsat** [comment]
> We weren't able to repro the issue. Is there a screenshot or a log file available? Also were you able to find the libraries in the apk file?

Here is I attached the log from android logcat. and this is lib under the .apk

<img width="1274" alt="Screenshot 2023-06-30 at 17 51 41" src="https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/15825357/4a9cc228-492c-4707-a579-847f52286ef4">
<img width="489" alt="Screenshot 2023-06-30 at 17 49 18" src="https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/15825357/7d075da1-6dff-429a-80e0-a724a7a43d12">

**Comment by alvinsat** [comment]
> what version of the plugin are you on?
> 
> also this should be unrelated, but the EOS_PREVIEW_PLATFORM define is for creating a mac app (among other platforms in beta), it wouldnt be needed to build an android app using the mac version of unity

I have tried to remove EOS_PREVIEW_PLATFORM but it is still the same showing me uninitialized. or am I doning steps wrong ? 
here is the step I am following :
To Reproduce
## Steps to reproduce the behavior:
- Create new android project in unity 2021.3 LTS
- Add package using upm git link
- Set init all configuration in Tools>EpicOnlineService configurator
- Add macOS Define Symbols for mac preview
- Build for android min sdk 23.
- Tested on android 9

**Comment by arthur740212** [comment]
Did you have gitlfs installed on your mac device?
If the `aar`s in  `PlatformSpecificAssets\EOS\Android` have size of 1 or 2 KB, that would imply that lfs didn't initialize correctly.

**Comment by RedMazer** [comment]
what version of the plug are you on?

also double check you have proper information as described in the config editor, and have both the main and android ones saved, even if the android one is blank.

**Comment by alvinsat** [comment]
yes I have git lfs installed the .aar file size is about 15mb
<img width="390" alt="Screenshot 2023-07-01 at 09 24 39" src="https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/15825357/87b7baf1-4d3e-435b-8f47-f914026962a2">

**Comment by alvinsat** [comment]
I have EOS version of 2.3.2

This is what I have set up in editor :
- ProductName
- ProductVersion
- ProductID
- SandboxID
- DeploymentID
- ClientSecret
- ClientID
- EncryptionKey

**Comment by arthur740212** [comment]
Did you attach EOSManager.cs script on any if the gameobjects?

**Comment by RoxDevvv** [comment]
am facing same problem after building 
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/51464152/cc0d111b-4739-43cc-89e0-11dfb2dd702b)
```
2023/07/15 00:37:25.068 18776 18799 Error Unity   at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.InitializePlatformInterface (PlayEveryWare.EpicOnlineServices.EOSConfig configData) [0x00000] in <00000000000000000000000000000000>:0 
2023/07/15 00:37:25.068 18776 18799 Error Unity   at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) [0x00000] in <00000000000000000000000000000000>:0 

```

**Comment by RoxDevvv** [comment]
> Did you attach EOSManager.cs script on any if the gameobjects?

yes I did

**Comment by RoxDevvv** [comment]
i start a fresh project to be sure and I built one of the simple same error throwing I have both main and android config saved 
am running on unity 2022.3
EOS 2.3.3

![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/51464152/79809cd2-2f08-4386-ab28-0009015318cb)

**Comment by RoxDevvv** [comment]
i used both package from a tarball and package from a git URL both fail when buiild to android 
I clone the main repo and I build to android the build success 
something wrong with the packages

**Comment by RoxDevvv** [comment]
i was able to run the build from my main project by deleting the tarball package and putting this repo files 
`https://github.com/PlayEveryWare/eos_plugin_for_unity.git`
I wish would be a fix for this problem

**Comment by arthur740212** [comment]
Based on the error logs. There might be something going on with the config file.
You will need `EpicOnlineServicesConfig` and `eos_android_config.cs`
And make sure they are in the correct folder.

**Comment by RoxDevvv** [comment]
> Based on the error logs. There might be something going on with the config file. You will need `EpicOnlineServicesConfig` and `eos_android_config.cs` And make sure they are in the correct folder.

i checked the files looks like they are in correct path
"C:\Users\GameDev\Desktop\EOS4thTEST\Library\PackageCache\com.playeveryware.eos@853455d4d663\Runtime\Android\Core\EOSAndroidConfig.cs"
"C:\Users\GameDev\Desktop\EOS4thTEST\Assets\StreamingAssets\EOS\EpicOnlineServicesConfig.json"

**Comment by arthur740212** [comment]
Sorry I mistyped. It is `eos_android_config.json` instead

**Comment by RoxDevvv** [comment]
> Sorry I mistyped. It is `eos_android_config.json` instead
it is correct too 
"C:\Users\GameDev\Desktop\EOS4thTEST\Assets\StreamingAssets\EOS\eos_android_config.json"

the tarball package is broken start a new project and import it you will have the same behavior as same as me on Android 
note on desktop build work perfectly no problems found

**Comment by arthur740212** [comment]
Which tarball did you install? 
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/36757173/6ef6ed2b-3f07-4ea8-a63d-fcc7d57e890a)
We should be using the package on top.

**Comment by RoxDevvv** [comment]
> Which tarball did you install? ![image](https://user-images.githubusercontent.com/36757173/254038809-6ef6ed2b-3f07-4ea8-a63d-fcc7d57e890a.png) We should be using the package on top.

Yes i did used it i even i build one from source using your gui but both fail 
Am pretty sure you will have same issue if you start fresh project and import tarball 2.3.3 in unity 2022.3

**Comment by arthur740212** [comment]
Which scripting backend were you using?
We were able to build with Mono no problem, 
il2cpp seems to have different behavior on different platforms, Android could be one of them.

**Comment by RoxDevvv** [comment]
yes i did il2cpp only  i didn't give a try to Mono 
however il2cpp work perfectly on Android when I build your source `https://github.com/PlayEveryWare/eos_plugin_for_unity`

**Comment by RoxDevvv** [comment]
> yes i did il2cpp only i didn't give a try to Mono however il2cpp work perfectly on Android when I build your source `https://github.com/PlayEveryWare/eos_plugin_for_unity`

Update : 
I just give Mono a try just right now it works perfectly on Android build
however, it is not a solution since all Android stores accept only ARM64 which it is only available in il2cpp

**Comment by arthur740212** [comment]
Yes. il2cpp does indeed work on the source repo.
Good that we get to narrow down the cause.
Will take a deeper look for the fix.
Thanks for the report while help with figuring out the problem.

**Comment by RoxDevvv** [comment]
> Yes. il2cpp does indeed work on the source repo. Good that we get to narrow down the cause. Will take a deeper look for the fix. Thanks for the report while help with figuring out the problem.

Thank you

**Comment by SimoneTurello** [comment]
I faced the same problem in building android with il2cpp and for the moment I solved it creating a `link.xml` file in the project preserving all the scripts in the assembly:

```
<linker>
  <assembly fullname="com.playeveryware.eos" preserve="all" />
</linker>
```

**Comment by RoxDevvv** [comment]
> I faced the same problem in building android with il2cpp and for the moment I solved it creating a `link.xml` file in the project preserving all the scripts in the assembly:
> 
> ```
> <linker>
>   <assembly fullname="com.playeveryware.eos" preserve="all" />
> </linker>
> ```

Interesting am gonna give it a try 
am wondering how did you come with this idea brilliant
