### ISSUE TITLE
How to build EOS on Android?

### ISSUE THREAD

**Issue by Akylzhan** [PlayEveryWare/eos_plugin_for_unity#334]
Hello, we would like to implement EOS features on android but we have already implemented Connect and we do not plan to use this plugin since we also need console support. Unfortunately, Epic told us that it is better to use this plugin as example or ask you directly on how to build it. Therefore I have several questions:

1. What is the difference between `statis-stdc++/eos-sdk.aar` and `dynamic-stdc++/eos-sdk.aar`
2. What exactly is needed to build EOS SDK on android? I see that some native code was written but I didn't get the exact picture

Thanks in advance

**Comment by arthur740212** [comment]
There are some docs in progress for Android that will be up in releases soon. Some information related to the questions.

1. What is the Difference Between Linking the EOS Library Dynamically and Statically?
Static linking packs libraries into the executable, whereas dynamic linking links the function symbols to the corresponding entry point in the dynamic libraries at runtime.
The two `aar`s differ in how they link `against the C++ Library`

If the game is using other libraries that also links to the C++ Library, the EOS Library should use the version that matches the linking type of the others, or else duplicate symbols would occur.

2. Android native code aren't used in the plugin now, most of them are legacy code. Configurating the sdk is needed and optionally a custom gradle build file if required.

**Comment by Akylzhan** [comment]
@arthur740212 Thanks for your reply. The thing is that I wanted to use dynamic `aar` but it returned `DllNotFoundException`. Is there more work to do, other than including `dynamic/eos-sdk.aar` to Android plugins folder?

**Comment by arthur740212** [comment]
There is a setting in `Preference > EOS Plugin` to select whether to build with dynamic or static.
[Documentation (in progress)](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/doc_getstarted_android/docs/android/link_eos_library_settings.md)
