### ISSUE TITLE
SteamManager has errors with newest Steamworks.NET

### ISSUE THREAD

**Issue by P34nut** [PlayEveryWare/eos_plugin_for_unity#338]
When installing the newest version of Steamworks.NET (20.2.0) some errors appear in the SteamManager.cs
It is the SteamUser.GetAuthSessionTicket method since there now is also a ref expected as a parameter.

**Comment by arthur740212** [comment]
Hello! Thanks for the report.
The fix is on this [commit](https://github.com/PlayEveryWare/eos_plugin_for_unity/commit/1b691ed0648d16da4e6499061207460222fd1362)
and will be include in the next release.
