### ISSUE TITLE
Android: Unable to login using Epic Account

### ISSUE THREAD

**Issue by danewfie** [PlayEveryWare/eos_plugin_for_unity#344]
**Describe the bug**
Attempt to login on android fails to complete using epic account portal.

Created a login button to initiate login process.
A browser appears to prompt login. (Assume no overlay for this? Or did I miss something)
Complete workflow to login. (Get Error)

**To Reproduce**
1. Create a new project.
2. Import plugin
3. create a login button configured for Epic
4. Build for Android
5. Test login (Fails)

**Expected behavior**
Authentication should succeed and return to app?

**Screenshots**
![Screenshot_20230706-142404](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/10082062/29d63d49-0d12-4131-ae85-145d9af84ddc)

**Dev Desktop**
 - OS: Windows 10 x64
 - Editor, or standalone build
 - 2021.3.18f1
 - 2.3.3

**Smartphone (please complete the following information):**
 - Device: Motorola moto g play (2021)
 - OS: Android 11
 - 2021.3.18f1
 - 2.3.3

**Additional context**
Logins work on Windows as expected.

**Comment by arthur740212** [comment]
Here is the issue and the fix is discussed [here](https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/205)
We have an automated fix in review now, which you could also check out [here](https://github.com/PlayEveryWare/eos_plugin_for_unity/pull/343)
