### ISSUE TITLE
OnClientDisconnectCallback doesn't fire on host

### ISSUE THREAD

**Issue by RoxDevvv** [PlayEveryWare/eos_plugin_for_unity#345]
this line of code doesn't fire on host disconnect 
NetworkManager.Singleton.OnClientDisconnectCallback+= callback;

how to detect host disconnect!

**Comment by andrew-hirata-playeveryware** [comment]
Hello @RoxDevvv, 
How are you triggering a disconnect? 

Additionally, the following information might help our team assist you:
* Which version of Unity are you using?
* Which version of the EOS Plugin are you using?
* Which platforms are you running on and building from?

**Comment by RoxDevvv** [comment]
Hello @RoxDevvv,
How are you triggering a disconnect?
am using netcode with eos transport layer
```
    private EOSTransportManager transportManager = null;
    private EOSTransport transportLayer;
 
    private void Start()
    {
        transportManager = EOSManager.Instance.GetOrCreateManager<EOSTransportManager>();
        transportLayer = NetworkManager.Singleton?.GetComponent<EOSTransport>();

        RegisterServerStartedCallback(OnServerStarted);
        RegisterConnectCallback(OnConnectedToServer);
        RegisterDisconnectCallback(OnDisconnect);
        RegisterTransportFailureCallback(OnTransportFailure);
    }
    public void RegisterDisconnectCallback(System.Action<ulong> callback)
    {
        if (NetworkManager.Singleton != null)
        {
            NetworkManager.Singleton.OnClientDisconnectCallback -= callback;
            NetworkManager.Singleton.OnClientDisconnectCallback += callback;
        }
    }
    public void DisconnectOnClick()
    {
        transportManager?.Disconnect();
    }
```
OnDisconnect callback doesn't fire on host disconnect


Additionally, the following information might help our team assist you:

Which version of Unity are you using?
2022.3
Which version of the EOS Plugin are you using?
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/51464152/7c5a11cc-93ac-412b-ae80-e81a80d8335e)

Which platforms are you running on and building from?
Android

**Comment by RoxDevvv** [comment]
any update regarding this issue
