### ISSUE TITLE
EpicOnlineServicesConfigEditor throws an error when used with Steamworks.NET

### ISSUE THREAD

**Issue by Lee-jaebeen** [PlayEveryWare/eos_plugin_for_unity#352]
When I used Steamworks.NET at the same time as this plugin in my Unity Project, I got the following compilation error.

Library\PackageCache\com.playeveryware.eos@6d3118adfa\Editor\EpicOnlineServicesConfigEditor.cs(621,60): error CS1503: Argument 1: cannot convert from 'string' to 'char'

Can this be resolved quickly or is there another solution I could try?

**Comment by arthur740212** [comment]
Which version of the package were you using?
And could you provide the context of the exact line?
Depending on different text editors, the line count might be off.

**Comment by Lee-jaebeen** [comment]
Steamworks.NET : 20.2.0 ( Add with git url )
EOS plugin for unity : 2.3.3 ( Add with git url )


in 
Assets/Plugins/Source/Editor/EpicOnlineServicesConfigEditor.cs
```
 private void OnSteamGUI()
        {
            GUILayout.Label("Steam Configuration Values", EditorStyles.boldLabel);
            AssigningFlagTextField("Steam Flags (Seperated by '|')", ref steamEOSConfigFile.currentEOSConfig.flags, 190);
            AssigningTextField("Override Library path", ref steamEOSConfigFile.currentEOSConfig.overrideLibraryPath);
            AssigningUintField("Steamworks SDK major version", ref steamEOSConfigFile.currentEOSConfig.steamSDKMajorVersion, 190);
            AssigningUintField("Steamworks SDK minor version", ref steamEOSConfigFile.currentEOSConfig.steamSDKMinorVersion, 190);
#if STEAMWORKS_MODULE
            if (GUILayout.Button("Update from Steamworks.NET", GUILayout.MaxWidth(200)))
            {
                var steamworksVersion = Steamworks.Version.SteamworksSDKVersion;
                **var versionParts = steamworksVersion.Split("."); // << Error on this line** 
                bool success = false;
                if (versionParts.Length >= 2)
                {
                    success = uint.TryParse(versionParts[0], out uint major);
                    success &= uint.TryParse(versionParts[1], out uint minor);
                    if (success)
                    {
                        steamEOSConfigFile.currentEOSConfig.steamSDKMajorVersion = major;
                        steamEOSConfigFile.currentEOSConfig.steamSDKMinorVersion = minor;
                    }
                }
                if (!success)
                {
                    Debug.LogError("Failed to retrive Steamworks SDK version from Steamworks.NET");
                }
            }
#endif
```

thank you for your fast help!

**Comment by arthur740212** [comment]
We weren't able to repro the issue.
But here are some checks that might lead us to the origin of your problem.
Check `Tools > EpicOnlineServiceConfig > Steam` and check if you're able to press the `update the steam SDK version` button
If not, try reimporting steamworks and EOSUnity packages.
If it still doesn't compile, there might be something going on with your C# compiler. 
`steamworksVersion.Split(".")` returns an array of strings (or something similar), but `versionParts` treats it as a char. That seems a little bit weird.
