### ISSUE TITLE
The finalizer of the NotifyEventHandle class raises a Null exception during Editor DomainReload.

### ISSUE THREAD

**Issue by mohumohu-corp** [PlayEveryWare/eos_plugin_for_unity#367]
This problem does not occur in the actual build and can only be reproduced on UnityEditor.

![NullException](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/85362386/e789baaa-ec6d-4b52-9b06-8ea98dab574f)

The reason for this exception is that the finalizer of GenericSafeHandle, the base class of the NotifyEventHandle class, is called after the EOSPLatformInterface reference is lost.

![NullException2](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/85362386/67d27cc3-42e4-449e-bd3f-45404fb8e010)

On UnityEditor, the finalizer is called at the next EntryPlayMode, so it has already lost reference to the EOSPlatformInterface. 

This error is not displayed as an error in the UnityEditor console, because Unity discards errors during DomainReload. 

However, the IDE's debugger detects this error, so debugging always stops at the exception when running debug.

![TemporaryFix](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/85362386/635e983b-a6b9-452f-b877-087a163b52e4)

To solve this problem, we need to add another null check to the callback in the initialization code within the EOS singleton, as shown in the screenshot above.

**Comment by andrew-hirata-playeveryware** [comment]
Hello @mohumohu-corp,
Thank you for finding this issue! I can make a fix to the EOSGetters that will stop this kind of crash from happening and it will make it's way into the next release!
