### ISSUE TITLE
Simple achivement script

### ISSUE THREAD

**Issue by JWingorn** [PlayEveryWare/eos_plugin_for_unity#368]
Hi,
I learned C# untraditionally, 
So all the scripts in the sample are overcomplex for me. I was wondering if anyone could help me by creating a oversimplified script that simply checks if EOS works, extracts the localUserId && localProductUserId into strings so that i can display them on the screen and if it works it starts unlocking achivments like this:

if (monsters_killed > 10){
//unlock achivement 1
}
if (total_gold > 1000){
//unlock achivement 2
}
and so on.

The GameObject I create will constantly run the script in the background, I will need to know which of the other scripts to also have running in the background? are the ones in Singletons the only ones?

**Comment by arthur740212** [comment]
Taking the achievement scene for example :
`EOSManager.cs` handles the underlying calls to initialize the EOSSDK and login functionality.
After successfully logging in, the `localUserID` would show on the left side of the UI.

For achievement specific calls. `EOSAchievementManager.cs` would be the script to call them from.

**Comment by JWingorn** [comment]
So they don't have to be attached to a object and present in the scene?

can you help me with a "ready to go script"?

**Comment by arthur740212** [comment]
The `Singletons` prefab is has `EOSManager.cs` and other necessary scripts for the SDK to initialize, thus attaching that to one of the scene objects is the simplest way to get started.

For `EOSAchievementManager.cs` however, it is not a MonoBehavior, thus it couldn't be attached to an object.
The plugin's way to work with it is to have another script with a reference to a `EOSAchievementManager`,
and create `EOSAchievementManager` on `Awake`
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/36757173/d972ef82-3005-43b6-ba54-60d866b47a23)

With the `EOSAchievementManager` ready, upon logging in, `EOSAchievementManager.OnConnectLogin` will be called, and the list of achievements of the game will be queried into `EOSAchievementManager.achievementDefinitionCache`,
which is a list of Achievement Definitions (the struct named `DefinitionV2`).

From there you will be able to iterate through the list of achievements.
And unlock any achievement with `EOSAchievementManager.UnlockAchievementManually(string achievementId)`,
by passing in the corresponding achievement ID, which is contained within the `DefinitionV2` of the achievement.
