### ISSUE TITLE
Unity Editor Frozen in AuthSample

### ISSUE THREAD

**Issue by seonghwan-dev** [PlayEveryWare/eos_plugin_for_unity#37]
A Platform Interface initialization failure exception occurs in the first play attempt, and the Unity Editor frees up when the second play is attempted. 
![image](https://user-images.githubusercontent.com/79823287/136875854-fa1657d7-4ac9-495d-b46d-aa96ae99b231.png)

**Comment by adrianpew** [comment]
Hello.  The config should have been saved to a json file and located under StreamingAssets\EOS\EpicOnlineServicesConfig.json

![image](https://user-images.githubusercontent.com/60490038/136887501-f47dd46a-66c9-4f20-ad61-3cdc30325a09.png)

You error you are receiving indicates a failure to initialized EOS.  I would recommend you debug this line to ensure that platformOptions includes the correct values:

https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/31ef5666da20314639e559af05674505f11c915b/Assets/Plugins/Source/EOSManager.cs#L294

Can you clarify "disabled Fast Enter PlayMode"?  I see the following new options under File > Project Settings > Editor.  Are you checking one of these options?

![image](https://user-images.githubusercontent.com/60490038/136887737-eae2d9f4-844e-413e-bc3e-51285d442992.png)

**Comment by adrianpew** [comment]
Hello.  The freezing issue was previously reported in another issue.  We are looking into it.

https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/20

Thanks.

**Comment by domlaurenti** [comment]
Apologies for the delayed response, we solved a version of this issue but not the entire thing 
Currently, we are investigating a related issue right now. Still investigating this issue.

**Comment by scovertb** [comment]
@seonghwan-dev It looks like a related issue was fixed by the latest 2.1.0 release. Is this issue still occurring?

**Comment by seonghwan-dev** [comment]
Hi, It seems good news.
Unfortunately, We're not using this plugin anymore in these days.  
Anyways, thanks for notification. :D
