### ISSUE TITLE
Error when building on the PS5 platform with EOS plugin in project

### ISSUE THREAD

**Issue by afrontera** [PlayEveryWare/eos_plugin_for_unity#372]
The error is the following:
`Library\PackageCache\com.playeveryware.eos@6d3118adfa\Runtime\Core\SystemMemory.cs(91,9): error CS0103: The name 'Mem_GetAllocatorFunctions' does not exist in the current context`
SS: https://puu.sh/JNgRR/a587f22aa7.png

It happens in the first 10 seconds of building at the beginning of the "Building Player" phase.
I have `EOS_DISABLE` set for the PS5 platform: https://puu.sh/JNgQX/5ed62675c9.png
Build type makes no difference (Attempted PC Hosted, Package and Dev/Release build for each).
Unity Version 2021.3.24f1
EOS Plugin version 2.3.3

Thank you for the plugin, it actually worked flawlessly for Standalone builds :)

**Comment by arthur740212** [comment]
There is an ifdef mismatch in SystemMemory.
In `GetAllocatorFunctions()` function
instead of 
```#if ENABLE_GET_ALLOCATOR_FUNCTION```
it should be
```#if DYNAMIC_MEMORY_ALLOCATION_AVAILABLE && ENABLE_GET_ALLOCATOR_FUNCTION```
That should give a build with EOS_DISABLED

**Comment by afrontera** [comment]
Thank you very much arthur! Ill give it a try and let you know how it goes.

*Alfonso Frontera */ Vice President

787-247-3727 / ***@***.*** ***@***.***>


*SRG STUDIOS CORP*

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. SRG Studios Corp is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.
