### ISSUE TITLE
UI in P2PNetcode sample scene

### ISSUE THREAD

**Issue by punkyman** [PlayEveryWare/eos_plugin_for_unity#373]
**Describe the bug**
I'm trying to run the demo named P2PNetcode, when started, the display differs from other demos since it shows a black screen instead of the ability to choose a sample scene and login.
There seems to be something specific done for this demo, where a dedicated panel called "transportLayerUI" is added to the UI, and this object hides the standard scene selection + login options.
Manually disabling the UI before running the editor fixes the issue. I suppose something similar to the friendslist UI should be done, but is missing from the initialization.

**To Reproduce**
Import standard and P2P samples in the project, run the P2PNetcode scene sample in the editor

**Expected behavior**
The layout should look like other sample scenes.

**Additional context**
Tested on latest release (2.3.3) with unity 2022.3.0f1

Thanks,

**Comment by arthur740212** [comment]
Every Sample Scene does have a corresponding UI object that should show up after logging in.
We weren't able to reproduce issue either on the repo or from a package, and liked to know which you were using.
Also at the time being, try reimporting the samples or recloning the repo, and check if the issue still remains.

**Comment by punkyman** [comment]
Right, so I've been using the 2.3.3 packaged version provided in the release link :
https://github.com/PlayEveryWare/eos_plugin_for_unity_upm/releases/download/v2.3.3/com.playeveryware.eos-2.3.3.tgz
Then I placed the package folder into the Packages of the project.
Still got the issue on the P2PNetcode scene after re-importing the package and samples.

One fix I did locally is to do something similar that what is done in friendsmenu by disabling / enabling the parent ui menu :

        public void HideMenu()
        {
            ....
            TransportUIParent.SetActive(false);
            ...
        }

Let me know if you need more information, and thanks for investigating.

**Comment by arthur740212** [comment]
This is interesting, the tests here we still have the loginUI on top of the TransportLayerUI
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/36757173/63caef65-cfe3-4e00-82eb-74fe30a5e2f7)
The `UIP2PTransportMenu` script is attached to TransportLayerUI object however, there may or may not be issues with the UI behavior if we set it inactive.

Great to hear that you found a fix.
In the meantime, perhaps check if there are any settings that accidentally got changed.
We'll keep this issue open, and track this on the next release.
