### ISSUE TITLE
Two necessary DLLs Failed to load stoping the plugin from working?

### ISSUE THREAD

**Issue by aaccensi** [PlayEveryWare/eos_plugin_for_unity#376]
Hello there,

We contancted Epic Games for support and they pointed us in your direction, yet we are not sure if github is the proper channel.
Nonetheless here is the issue we are having:

The game will not launch for one of our players in the Epic Games launcher, it appears as if necessary DLLs for the functioning of the plugin are no being loaded, this is happening on a Windows x64 and the user says he is launching the game from the Epic Games client, so I have no clue why would this happen.

Here you have the begining of the player log where this can be seen:

```
Mono path[0] = 'C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/Managed'
Mono config path = 'C:/Program Files/Epic Games/MegaCityPoliceEVApq/MonoBleedingEdge/etc'
Plugins: Failed to load 'C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/Plugins\x86_64/GfxPluginNativeRender-x64.dll' because one or more of its dependencies could not be loaded.
Plugins: Failed to load 'C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/Plugins\x86_64/DynamicLibraryLoaderHelper.dll' because one or more of its dependencies could not be loaded.
Initialize engine version: 2021.3.16f1 (4016570cf34f)
[Subsystems] Discovering subsystems at path C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=0
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: AMD Radeon (TM) R5 M330 (ID=0x6660)
    Vendor:   ATI
    VRAM:     2039 MB
    Driver:   27.20.21003.1028
Begin MonoManager ReloadAssembly
- Completed reload, in  0.512 seconds
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

New input system (experimental) initialized
Using XInput
<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.849300 ms
INITIALIZING EPICGAMES CLIENT.
Start of Early EOS LOG:
Fallback handler could not load library C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/MonoBleedingEdge/GfxPluginNativeRender-x64
Fallback handler could not load library C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/MonoBleedingEdge/GfxPluginNativeRender-x64.dll
Fallback handler could not load library C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/MonoBleedingEdge/GfxPluginNativeRender-x64.dll
Fallback handler could not load library C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/MonoBleedingEdge/GfxPluginNativeRender-x64
Fallback handler could not load library C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/MonoBleedingEdge/libGfxPluginNativeRender-x64
Fallback handler could not load library C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/MonoBleedingEdge/libGfxPluginNativeRender-x64.dll
Fallback handler could not load library C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/MonoBleedingEdge/libGfxPluginNativeRender-x64.dll
Fallback handler could not load library C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/MonoBleedingEdge/libGfxPluginNativeRender-x64
Fallback handler could not load library C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/MonoBleedingEdge/GfxPluginNativeRender-x64
Fallback handler could not load library C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/MonoBleedingEdge/GfxPluginNativeRender-x64.dll
Fallback handler could not load library C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/MonoBleedingEdge/GfxPluginNativeRender-x64.dll
Fallback handler could not load library C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/MonoBleedingEdge/GfxPluginNativeRender-x64
Fallback handler could not load library C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/MonoBleedingEdge/libGfxPluginNativeRender-x64
Fallback handler could not load library C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/MonoBleedingEdge/libGfxPluginNativeRender-x64.dll
Fallback handler could not load library C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/MonoBleedingEdge/libGfxPluginNativeRender-x64.dll
Fallback handler could not load library C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/MonoBleedingEdge/libGfxPluginNativeRender-x64
EXCEPTION CAUGHT: System.DllNotFoundException: GfxPluginNativeRender-x64 assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.global_log_flush_with_function(intptr)
  at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.GetEOSPlatformInterface () [0x00030] in <6990dac7a5f143a994e984e931f378c2>:0 
  at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) [0x00000] in <6990dac7a5f143a994e984e931f378c2>:0 
  at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) [0x00000] in <6990dac7a5f143a994e984e931f378c2>:0 
  at SDKs.InitEpicGames () [0x0000f] in <27bbd4e63eac48c08008d5b04d4f599c>:0
Uploading Crash Report
...
```

For even more clarity here you have an extract of only th lines that seem to cause the issue:

```
...
Plugins: Failed to load 'C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/Plugins\x86_64/GfxPluginNativeRender-x64.dll' because one or more of its dependencies could not be loaded.
Plugins: Failed to load 'C:/Program Files/Epic Games/MegaCityPoliceEVApq/Mega City Police_Data/Plugins\x86_64/DynamicLibraryLoaderHelper.dll' because one or more of its dependencies could not be loaded.
...
EXCEPTION CAUGHT: System.DllNotFoundException: GfxPluginNativeRender-x64 assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.global_log_flush_with_function(intptr)
  at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.GetEOSPlatformInterface () [0x00030] in <6990dac7a5f143a994e984e931f378c2>:0 
  at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) [0x00000] in <6990dac7a5f143a994e984e931f378c2>:0 
  at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) [0x00000] in <6990dac7a5f143a994e984e931f378c2>:0 
  at SDKs.InitEpicGames () [0x0000f] in <27bbd4e63eac48c08008d5b04d4f599c>:0
...
```

We used the following versions:
- Unity 2021.3.16f1
- EOS Plugin for unity 2.2.0

Did you ever experience this or have any clue why is in this instance not working as intended?

Thanks in advance for any support you can provide.

**Comment by andrew-hirata-playeveryware** [comment]
hello @aaccensi,
From looking at the log, it appears that the gfx library isn't loading correctly. My hunch would be that however you have the plugin installed, the DLLs for the EOS plugin for Unity aren't installed correctly.

Which way did you install the plugin, and can you verify that the DLLs aren't git-lfs pointer files?

**Comment by aaccensi** [comment]
I installed it from the Unity Package Manager a while back. I'm not sure how can I check that they are not Git LFS pointers? They look like normal dlls in the folder.
Also we haven't encountered this issue with other users. Also, another thing that I don't totally understand is why in those 2 paths the slashes before x86_64 are backslashes instead.

**Comment by andrew-hirata-playeveryware** [comment]
You can check by seeing if they're git-lfs pointer files by opening them and checking if they have SHAs in them. If you're using windows, it will just use the filename extension to "determine" the file type, (as does Unity). 

That being said, I think I may have misread something. I missed that this is an issue with a single user: that implication then would be that the correct Visual studio redistributable might not be installed on the user's machine. Do you know which version of windows the user is using?

**Comment by aaccensi** [comment]
I only know is 64 bit, not the exact windows version. But I can ask, is there any other details I should ask the user?

**Comment by aaccensi** [comment]
Alright, so I went to the user to ask for the window version and to my surprise he just let me know the game now is working.
While I'm happy to hear that I'm also quite puzzled to what was the issue. Maybe it was indeed a missing redistributable and the user in the meantime installed something that came with it. If that's the case it will be interesting to know if there is such a dependencies which ones are so we can make sure the players always have them.

**Comment by paulhazen** [comment]
@aaccensi Do you have more logs that can be investigated, or should this issue be marked for closure? I apologize but it's not quite clear to me if the issue is still an issue.

**Comment by aaccensi** [comment]
hi @paulhazen 
Is safe to say is not an issue for this user anymore, weather it will be an issue for other users in the future I don't know.
I guess you can close it and if it comes beck we can revive it. But in case this happens what other **logs** are you talking about that can be investigated. If the errors from the unity **Player.log** aren't enough it will be helpful to know what else can you use to pinpoint the source of the problem so I'm ready to bring you this directly next time (If there is one).

**Comment by paulhazen** [comment]
Sounds good. I always ask for "more logs" in case there is additional information that might be pertinent - there are no _specific_ logs I'm referring to. Errors from `Player.log` should be plenty.

Please feel free to re-open this issue or open a new issue as needs demand - hopefully this was a fluke of circumstances and not indicative of a bug - but we definitely want to know if it's a bug, so please don't hesitate to re-open and we'll hop on it.
