### ISSUE TITLE
Upgrading the SDK to v1.16.0?

### ISSUE THREAD

**Issue by EliasVal** [PlayEveryWare/eos_plugin_for_unity#377]
Epic recently released the 1.16 version of their SDK, which allows [crossplay between Consoles and PC](https://dev.epicgames.com/en-US/news/epic-online-services-expands-free-crossplay-overlay-from-pc-to-consoles)
I've seen that this plugin targets 1.15.4, is an upgrade to 1.16 is possible?

On a sidenote, if anybody can answer, why is Unity 2021.x preferred? and Since the [2021 LTS will reach EOL in April 2024](https://unity.com/releases/editor/qa/lts-releases), will the SDK be optimized for a newer version such as 2022.x or 2023.x?

**Comment by andrew-hirata-playeveryware** [comment]
Hello @EliasVal !
The 1.16 was released this Tuesday and we working on it currently. I don't have a firm date that I can share about when we will be finished with it. But do know it is in the works!

The preferred version, more or less, is the version that we test the most with. Other versions of Unity, particularly newer versions of Unity, will generally work, but we haven't personally tested them. At the moment, I don't know of any issues that will occur with any 2022 version of Unity. 2023, However, is completely untested by out team and I haven't heard of a user that uses it.

**Comment by EliasVal** [comment]
@andrew-hirata-playeveryware thanks for the quick answer :)
Good luck with development!
