### ISSUE TITLE
EOS_InvalidUser when inviting a friend to join your lobby

### ISSUE THREAD

**Issue by OtslaOtt** [PlayEveryWare/eos_plugin_for_unity#380]
Through the social overlay, a player can currently join a friend's lobby with the join lobby button, but when attempting to invite a friend, an "EOS_InvalidUser" error pops up. I have implemented all the necessary notifications/callbacks for when the invite gets received, but the invite never gets sent. The join button on a friend who is in a lobby is working as intended.

1. Enter a lobby in-game.
2. Open the social overlay.
3. Click invite on a friend. 
4. See error "EOS_InvalidUser."

**Expected behavior**
Invite gets sent to the other player, which handles the invite through callbacks.

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Standalone build
 - Unity Version 2021.3.7f1

**Comment by paulhazen** [comment]
Can you confirm which branch you're experiencing this in? I'm assuming it's happening for you in `stable`?
