### ISSUE TITLE
NullReferenceException in EOSManager's Awake on Mac

### ISSUE THREAD

**Issue by 3ternal** [PlayEveryWare/eos_plugin_for_unity#390]
**Describe the bug**
I'm getting a couple of EOS errors in Mac standalone builds (see traceback below).

I took a look at this "Platform not supported" error at line 495, and the comment makes it sound like expected behavior, correct? However, I'm also getting a null reference during the whole Awake sequence (see the second message below). So I suspect that something is off.

Note that this is a standalone build launching from my desktop, not from EGS. I haven't tested yet if this works on EGS; first I'm trying to clean up the errors on other platforms.

```
Platform not supported
UnityEngine.StackTraceUtility:ExtractStackTrace () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/StackTrace.cs:37)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogError (object)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner) (at ./Library/PackageCache/com.playeveryware.eos@2.3.3/Runtime/Core/EOSManager.cs:495)
PlayEveryWare.EpicOnlineServices.EOSManager:Awake () (at ./Library/PackageCache/com.playeveryware.eos@2.3.3/Runtime/Core/EOSManager.cs:1571)
UnityEngine.Object:Instantiate (UnityEngine.Object,UnityEngine.Transform,bool) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:274)
UnityEngine.Object:Instantiate<PlayEveryWare.EpicOnlineServices.EOSManager> (PlayEveryWare.EpicOnlineServices.EOSManager,UnityEngine.Transform,bool) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:310)
UnityEngine.Object:Instantiate<PlayEveryWare.EpicOnlineServices.EOSManager> (PlayEveryWare.EpicOnlineServices.EOSManager,UnityEngine.Transform) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:305)
AchievementMgrPc:InitializeEpic () (at /Users/eternal/Desktop/Unity Projects/monospaced-lovers/Assets/_Scripts/Platform-Specific/AchievementMgrPc.cs:337)
AchievementMgrPc:Initialize () (at /Users/eternal/Desktop/Unity Projects/monospaced-lovers/Assets/_Scripts/Platform-Specific/AchievementMgrPc.cs:211)
AchievementMgr:AfterLoad () (at /Users/eternal/Desktop/Unity Projects/monospaced-lovers/Assets/_Scripts/Platform-Specific/AchievementMgr.cs:322)
AchievementMgrPc:AfterLoad () (at /Users/eternal/Desktop/Unity Projects/monospaced-lovers/Assets/_Scripts/Platform-Specific/AchievementMgrPc.cs:368)
GameController/<_AfterLoadLevel>d__140:MoveNext () (at /Users/eternal/Desktop/Unity Projects/monospaced-lovers/Assets/_Scripts/Singletons/GameController.cs:558)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)

(Filename: ./Library/PackageCache/com.playeveryware.eos@2.3.3/Runtime/Core/EOSManager.cs Line: 495)

Uploading Crash Report
NullReferenceException: Object reference not set to an instance of an object
  at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.InitializePlatformInterface (PlayEveryWare.EpicOnlineServices.EOSConfig configData) [0x00007] in ./Library/PackageCache/com.playeveryware.eos@2.3.3/Runtime/Core/EOSManager.cs:389 
  at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) [0x001af] in ./Library/PackageCache/com.playeveryware.eos@2.3.3/Runtime/Core/EOSManager.cs:580 
  at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) [0x0000c] in ./Library/PackageCache/com.playeveryware.eos@2.3.3/Runtime/Core/EOSManager.cs:498 
  at PlayEveryWare.EpicOnlineServices.EOSManager.Awake () [0x0000c] in ./Library/PackageCache/com.playeveryware.eos@2.3.3/Runtime/Core/EOSManager.cs:1571 
UnityEngine.Object:Internal_CloneSingleWithParent(Object, Transform, Boolean)
UnityEngine.Object:Instantiate(Object, Transform, Boolean) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:274)
UnityEngine.Object:Instantiate(EOSManager, Transform, Boolean) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:310)
UnityEngine.Object:Instantiate(EOSManager, Transform) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:305)
AchievementMgrPc:InitializeEpic() (at /Users/eternal/Desktop/Unity Projects/monospaced-lovers/Assets/_Scripts/Platform-Specific/AchievementMgrPc.cs:337)
AchievementMgrPc:Initialize() (at /Users/eternal/Desktop/Unity Projects/monospaced-lovers/Assets/_Scripts/Platform-Specific/AchievementMgrPc.cs:211)
AchievementMgr:AfterLoad() (at /Users/eternal/Desktop/Unity Projects/monospaced-lovers/Assets/_Scripts/Platform-Specific/AchievementMgr.cs:322)
AchievementMgrPc:AfterLoad() (at /Users/eternal/Desktop/Unity Projects/monospaced-lovers/Assets/_Scripts/Platform-Specific/AchievementMgrPc.cs:368)
<_AfterLoadLevel>d__140:MoveNext() (at /Users/eternal/Desktop/Unity Projects/monospaced-lovers/Assets/_Scripts/Singletons/GameController.cs:558)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)

```

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.7.9
 - Standalone build
 - Unity Version 2022.3.6
 - Plugin Version 2.3.3

**Comment by arthur740212** [comment]
Were you building with il2cpp?
If so, there is a [fix] for that (https://github.com/PlayEveryWare/eos_plugin_for_unity/commit/14672f339aebf9629d2736ce21c59ac5724d134b) ready in the next release.
While the release isn't out yet (real soon), In the meantime you could build a package directly from source to preview the fixes and features.

**Comment by paulhazen** [comment]
@3ternal Obviously we want this to work with `Mono`, but if it solves your problem for now, are you able to use `IL2CPP` as your backend? In the meantime, we will continue to investigate the issue :)

**Comment by 3ternal** [comment]
Ah, my mistake, I thought the problem was with IL2CPP.

That's all right, I can wait for the Mono fix and test on Windows in the meantime - the game isn't out yet, so it doesn't affect any customers.

**Comment by arthur740212** [comment]
Mono didn't have that problem for version 2.3.3 when released, which means there might be a completely different reason that causes the null ref.
Based on when the log shows, I could think of a couple other reasons that could cause the problem.
1. Config files are missing.
2. Libraries aren't built or aren't fully fetched from git-lfs. Check the size of `libDynamicLibraryLoaderHelper.dylib`. If it is 1KB then it is a git-lfs problem.

**Comment by arthur740212** [comment]
Before that, Apply `ENABLE_DEBUG_EOSMANAGER` in the script definition symbols, wanted to check what actually was null.
Suspect it to be `platformSpecific`, why it is null still remains a mystery, hopefully logs will tell us more

**Comment by arthur740212** [comment]
I forgot about one crucial step.
EOS_PREVIEW_PLATFORM is require in the Scripting Define for Mac and platform in preview state.

**Comment by 3ternal** [comment]
> Mono didn't have that problem for version 2.3.3 when released, which means there might be a completely different reason that causes the null ref. Based on when the log shows, it could be a couple other reasons that might cause the problem.
> 
> 1. Config files are missing.
> 2. Libraries aren't built or aren't fully fetched from git-lfs. Check the size of `libDynamicLibraryLoaderHelper.dylib`. If it is 1KB then it is a git-lfs problem.

Hang on, where are the config files located? How would I know if they're missing? I know where the config editor is, but not the files themselves.

libDynamicLibraryLoaderHelper.dylib looks good. I'll try the other debugging steps in a bit.

**Comment by arthur740212** [comment]
All required config files could be made with the config editor, for Mac, only the main config file and the Mac specific one would be required.

**Comment by 3ternal** [comment]
All right, I'm still not sure how to confirm that the config file exists, but I'm seeing some config-related lines in the log.

After enabling those script definition symbols, I'm still getting the "platform not supported" error, but not the null ref. Is there anything specific you need to see from the player.log?

**Comment by arthur740212** [comment]
"platform not supported" is an old error log that never got cleared out, it doesn't prevent any functionalities.
The null ref is what prevents the plugin to work on Mac, at this state you should be able to login and use the EOS features on Mac

**Comment by 3ternal** [comment]
All right, thanks. I'll test it out once I get the achievements implemented.

**Comment by 3ternal** [comment]
Strangely enough, it seems that I still get the null ref when the debugging symbols are removed. The error doesn't occur if I add ENABLE_DEBUG_EOSMANAGER and EOS_PREVIEW_PLATFORM.

**Comment by arthur740212** [comment]
The symbol `ENABLE_DEBUG_EOSMANAGER` is the debug symbol for getting logs.
`EOS_PREVIEW_PLATFORM` isn't for debug use, it is the script definition that enables Mac in the current version.

**Comment by 3ternal** [comment]
Ah, makes sense. Looks like it's working with EOS_PREVIEW_PLATFORM - thanks!
