### ISSUE TITLE
Error loading EOSSDK-Win64-Shipping.dll library: Win32Exception

### ISSUE THREAD

**Issue by jet-zhao** [PlayEveryWare/eos_plugin_for_unity#391]
Describe the bug
When I ran any sample(for example Achievements scene), there was the error showed below:

Win32Exception: Searched in : E:/someoneExamples/Assets/Plugins E:/someoneExamples/Packages/com.playeveryware.eos@853455d4d663\Runtime
DLLHandle.LoadDynamicLibrary (System.String libraryName) (at Assets/Plugins/Source/Core/DLLHandle.cs:190)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadDynamicLibrary (System.String libraryName) (at Assets/Plugins/Source/Core/EOSManager_DynamicLoading.cs:195)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadDelegatesWithEOSBindingAPI () (at Assets/Plugins/Source/Core/EOSManager_DynamicLoading.cs:220)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadEOSLibraries () (at Assets/Plugins/Source/Core/EOSManager_DynamicLoading.cs:360)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) (at Assets/Plugins/Source/Core/EOSManager.cs:550)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) (at Assets/Plugins/Source/Core/EOSManager.cs:498)
PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager.Awake () (at Assets/Scripts/Core/EOSHostManager.cs:49

Expected behavior
No error, and can run examples

Desktop:

OS: Windows 11 x64. No any separate Epic game services installed.
Editor
Unity Version 2020.3.39f1
Plugin Version: 2.3.3

Additional context

I installed the plugin by downloading com.playeveryware.eos-2.3.3.tgz and importing it through Add package from tarball.

**Comment by paulhazen** [comment]
To me, this looks like the DLL is missing - which often happens when the wrong tarball is used - specifically when the "source" tarball is used instead of the one on the releases page. 

To confirm, can you check something for me? Can you show me the contents of your directory `E:/someoneExamples/Assets/Plugins E:/someoneExamples/Packages/com.playeveryware.eos@853455d4d663\Runtime`, and tell me what DLL files are in there, and what size each is? I suspect the DLL file will be there, but I expect it will be very small, and in fact be a `git-lfs` pointer file.

**Comment by jet-zhao** [comment]
> To me, this looks like the DLL is missing - which often happens when the wrong tarball is used - specifically when the "source" tarball is used instead of the one on the releases page.
> 
> To confirm, can you check something for me? Can you show me the contents of your directory `E:/someoneExamples/Assets/Plugins E:/someoneExamples/Packages/com.playeveryware.eos@853455d4d663\Runtime`, and tell me what DLL files are in there, and what size each is? I suspect the DLL file will be there, but I expect it will be very small, and in fact be a `git-lfs` pointer file.

Thanks. I found that it reported the same error message when the plugin version I used was 2.3.3 and 2.3.2. But if I used the version 2.1.8, there was no error and it behaved normally. I am running the sample in Unity 2020.3.39f1 and using the tarball.

**Comment by paulhazen** [comment]
@jet-zhao 
Are you able to test against our newest release? It would be really helpful to know if this is still an issue for you - since it might be an issue others are experiencing.

**Comment by jet-zhao** [comment]
> @jet-zhao Are you able to test against our newest release? It would be really helpful to know if this is still an issue for you - since it might be an issue others are experiencing.

@paulhazen Sure. I will give you feedback asap when I have time to finish this test. Maybe tomorrow.

**Comment by paulhazen** [comment]
> @paulhazen It works now.
> 
> > @jet-zhao Are you able to test against our newest release? It would be really helpful to know if this is still an issue for you - since it might be an issue others are experiencing.

That's great to hear! For my own understanding - did you figure out what the issue was, did you switch to the latest release, or did it inexplicably start working? Either scenario would be helpful to know about :)

**Comment by jet-zhao** [comment]
> > @paulhazen It works now.
> > > @jet-zhao Are you able to test against our newest release? It would be really helpful to know if this is still an issue for you - since it might be an issue others are experiencing.
> 
> That's great to hear! For my own understanding - did you figure out what the issue was, did you switch to the latest release, or did it inexplicably start working? Either scenario would be helpful to know about :)

After upgrading to your newest release 3.0.0, it works for me now. I could confirm that the issue I reported before was fixed by you guys. Thanks and good job!
