### ISSUE TITLE
EpicOnlineServicesConfigEditor.cs(620,41): error CS0103: The name 'Steamworks' does not exist in the current context

### ISSUE THREAD

**Issue by sineang01** [PlayEveryWare/eos_plugin_for_unity#394]
**Describe the bug**
After installing the plugin, I cannot compile the solution because:
`EpicOnlineServicesConfigEditor.cs(620,41): error CS0103: The name 'Steamworks' does not exist in the current context`

**To Reproduce**
1. Run a project that uses Steamworks but has it disabled (Player -> "Scripting define symbols" contain `STEAMWORKS_NET` and `DISABLESTEAMWORKS`)
2. Install the PlayEveryWare EOS plugin
3. Wait for the Editor to recompile the scripts

**Expected behavior**
The code compiles without errors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Editor
 - 2021.3.30f1
 - 2.3.3 (also happened with 2.3.0)

**Additional context**
The issue happens because EpicOnlineServicesConfigEditor.cs:617 checks for `STEAMWORKS_MODULE` and that flag is defined in com.playeveryware.eos@6d3118adfa\Editor\com.playeveryware.eos-Editor.asmdef, so obviously it is going to be set TRUE and then the code fails because Steamworks is in the code but it's entirely disabled (due to `DISABLESTEAMWORKS`).

My workaround was to edit EpicOnlineServicesConfigEditor.cs:617
from
`#if STEAMWORKS_MODULE`
to
`#if !DISABLESTEAMWORKS && STEAMWORKS_MODULE`

**Comment by arthur740212** [comment]
Nice catch! We also have a fix for that planned on the next release, stay tuned :D.
