### ISSUE TITLE
EOS for iOS n Android end of year

### ISSUE THREAD

**Issue by kenofori** [PlayEveryWare/eos_plugin_for_unity#40]
Hi there

https://dev.epicgames.com/en-US/news/epic-online-services-releases-plugins-for-unity-and-unreal-engine?sessionInvalidated=true

According to Epic's official blog post on unity plugin (this one), 
"The Epic Online Services plugin for Unity is now available for PC, with console and mobile following later in the year. "

We are just 2 months away , so do you think this is still applicable? (Unity Plugin for both iOS n Android)

A 'rough' idea will let us plan better. 

Thanks

**Comment by domlaurenti** [comment]
Going to close this one out as we can't really be specific about release periods for platforms. As @FakeByte has said above, keep an eye on the roadmap here for specific support items and release dates: https://trello.com/b/rLvzFJfE/eos-public-roadmap
