### ISSUE TITLE
NewInputSystem is forced to be installed, which is not desirable.

### ISSUE THREAD

**Issue by mohumohu-corp** [PlayEveryWare/eos_plugin_for_unity#402]
Hi,

First of all, thank you for continually updating this project.

Starting with the latest version 3.0.0, the NewInputSystem is now forced to be installed. This will cause projects using the old InputSystem to receive the following warning every time the project is started

Many people prefer to use the old InputSystem because the new InputSystem has latency issues and many unnecessary features. I am one of them.

Using the AssemblyDefinition's VersionDefines feature, you can write code that will only work for projects that have the NewInputSystem installed. That way, it will not affect projects that use the old InputSystem.

I have not read all the source code in this project, but I would like to see this problem fixed.
![captured](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/85362386/f1e3a16a-857e-4cfe-87a6-85f6c0202197)

**Comment by paulhazen** [comment]
Hmmm.... I wonder what the best behavior here is. It seems like a good idea to default to the newest input system, but it should be made easy to prefer to use the old input system.

One solution is to remove the following define in `Assets/Plugins/Source/Editor/com.playeveryware.eos-Editor.asmdef`:
<img width="348" alt="image" src="https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/1439891/0fc31de3-bc5f-4b42-ac1e-4981d78b74a2">

But that feels like a non-intuitive hassle.

Regardless, does removing that define fix the problem for you @mohumohu-corp? 

Failing that, do you have a suggestion for making this smoother without defaulting to the old input system (or is the new input system so bad that nobody is likely to be using it anytime soon in your opinion)?

**Comment by mohumohu-corp** [comment]
I have not read the source code of this update, so I cannot say for sure.

I think it would be better to disable the automatic installation and enclose only the code parts for NewInputSystem in COM_UNITY_MODULE_INPUTSYSTEM directives.

Some mobile developers prefer the old input system because the NewInputSystem consumes a lot of CPU time just to have it installed.

To change the assembly definition settings, this package would have to be used in "Embed "mode, which I don't want to do.

Since the core part of this package should not depend on NewInputSystem, why not enclose only the dependent parts with the COM_UNITY_MODULE_INPUTSYSTEM directive?

NewInputSystem was indeed developed as a replacement for the old InputSystem, but unfortunately it does not perform well.

But again, I appreciate the effort you are putting into updating this package.

**Comment by paulhazen** [comment]
@mohumohu-corp 
Apologies for not getting back to you by EOD like I said I would. It'll be the first thing I do this coming Monday morning.

**Comment by paulhazen** [comment]
@mohumohu-corp 

> Using the AssemblyDefinition's VersionDefines feature, you can write code that will only work for projects that have the NewInputSystem installed. That way, it will not affect projects that use the old InputSystem.

This seems like a cogent way to handle the problem - would you be kind enough to point me toward the documentation for this?

**Comment by mohumohu-corp** [comment]
> @mohumohu-corp
> 
> > Using the AssemblyDefinition's VersionDefines feature, you can write code that will only work for projects that have the NewInputSystem installed. That way, it will not affect projects that use the old InputSystem.
> 
> This seems like a cogent way to handle the problem - would you be kind enough to point me toward the documentation for this?

Which files are the code parts that eos_plugin_for_unity depends on NewInputSystem?

I will take a look at those when I have time.

**Comment by paulhazen** [comment]
This issue is resolved now in both the `stable` and `development` branches.
