### ISSUE TITLE
Error: Duplicate 'AlwaysLinkAssembly' attribute (ver 3.0.0)

### ISSUE THREAD

**Issue by 3ternal** [PlayEveryWare/eos_plugin_for_unity#403]
**Describe the bug**
I just updated to 3.0.0 (OpenUPM version), and I'm getting a compile error.

Library\PackageCache\com.playeveryware.eos@3.0.0\Runtime\Windows\EOSManager_Windows.cs(50,12): error CS0579: Duplicate 'AlwaysLinkAssembly' attribute

I've switched back to 2.3.3 for now.

**To Reproduce**
Should occur after updating the package.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Editor
 - Unity Version 2022.3.6
 - Plugin Version 3.0.0

**Comment by 3ternal** [comment]
Correction: this seems to only occur when the build target in the editor is set to macOS.

**Comment by arthur740212** [comment]
There is a problem happens when the editor platform and target player platform is different, where the always link assembly attribute will be added twice.
We will have a fix that in a quick fix release.
Thank you for the attention to the problem.

**Comment by andrew-hirata-playeveryware** [comment]
This should be resolved in the `3.0.1` release, which was released today.

**Comment by paulhazen** [comment]
Closed by PR #413

**Comment by 3ternal** [comment]
Thanks for the fix. Will this be included in the OpenUPM version as well? Looks like that one is still on 3.0.0.
