### ISSUE TITLE
Achievements not working: ProductUserId s_localProductUserId = null

### ISSUE THREAD

**Issue by Dimetroc** [PlayEveryWare/eos_plugin_for_unity#404]
Achievements are not working in 3.0.0. ProductUserId s_localProductUserId is not set.  Also, static private Epic.OnlineServices.Auth.LoginOptions MakeLoginOptions throws a null reference exception. 

This is how I login:

  var options = MakeLoginOptions(LoginCredentialType.ExchangeCode,null, EOSManager.Instance.GetCommandLineArgsFromEpicLauncher().authPassword);
            EOSManager.Instance.StartLoginWithLoginOptions(options, OnAuthLogin);

Also getting error:
LogEOSUI(Warning): Social Overlay: Achievements disabled because of missing product user id (EOS_InvalidAuth).

**Comment by arthur740212** [comment]
Hello, it looks like the null lies in `EOSManager.Instance.GetCommandLineArgsFromEpicLauncher().authPassword`
were you able to get logs about where the null reference is?

**Comment by Dimetroc** [comment]
This is how I login:
`            var options = MakeLoginOptions(LoginCredentialType.ExchangeCode,null, EOSManager.Instance.GetCommandLineArgsFromEpicLauncher().authPassword);
            EOSManager.Instance.StartLoginWithLoginOptions(options, OnAuthLogin);`

EOSSingleton.s_localProductUserId is never set, it is null. 

Overlay works, but since local product id is null achievements not working.

**Comment by Dimetroc** [comment]
I didn't understand the procedure properly. Do you need to Auth first and then Connect? Is that correct?

**Comment by andrew-hirata-playeveryware** [comment]
Yes, for the Exchange code you will need to do Auth first and then connect.

**Comment by Dimetroc** [comment]
Ok, thank you. Then I am closing the ticket.
