### ISSUE TITLE
PlayEveryWare.EpicOnlineServices.EOSManager missing EOS_DISABLE defnes

### ISSUE THREAD

**Issue by Dimetroc** [PlayEveryWare/eos_plugin_for_unity#406]
Setting EOS_DISABLE defines results in compile errors. 

Errors come from PlayEveryWare.EpicOnlineServices.EOSManager 

Please wrap in EOS_DISABLE  define.

**Comment by andrew-hirata-playeveryware** [comment]
I believe this should be resolved in the 3.0.1 release of the plugin.

**Comment by paulhazen** [comment]
I can confirm that this issue is resolved by the 3.0.1 release, and currently in the `stable` branch.
