### ISSUE TITLE
Issue with OculusManager.cs in the samples.

### ISSUE THREAD

**Issue by WorkingClassDuck** [PlayEveryWare/eos_plugin_for_unity#412]
"The type or namespace name 'Oculus' could not be found (are you missing a using directive or an assembly reference?)"
Theres a comment here telling me to get oculus package, although I already have it. I have reimported the oculus package and the eos package multiple times and this error still haunts me.

**Comment by paulhazen** [comment]
Apologies if I'm suggesting something that's already been checked - but have you confirmed that you have the files properly checked out with `git lfs`? This is the most common cause of this particular kind of problem. 

Failing that possibility - can you please provide the following:
- The exact text of the error (and any errors that come after or before)
- The version number of the plugin that you are using
- The version of the Unity Editor you're using
- The platform you are on (Windows 8/10/11, Linux, or MacOS)

These will be helpful in diagnosing exactly what is going on.

**Comment by paulhazen** [comment]
I'm going to go ahead and close this, but @WorkingClassDuck if you are still having this issue, please feel free to re-open, and provide the extra details listed above.
