### ISSUE TITLE
Certificate has expired error after updating to 3.0.0

### ISSUE THREAD

**Issue by MenesApps** [PlayEveryWare/eos_plugin_for_unity#415]
Hi,
I have had this plugin in my project for some time and didn't have issues.
Today, I have updated to 3.0.0 and I am getting an error when I build on mac for iOS (on Windows for Android, it works fine).
The error is `Curl error 60 : Cert verify failed. Certificate has expired. UnityTIs error code : 7`.
I haven't changed anything in the app or device outside of the plugin and I checked the keychain to see if there was any expired certificates there, but all is fine. 
The project builds, then throw this error at the end. When I open the project in XCode, it can be archived but I get the "no binary found" issue when uploading to AppStore Connect.

Anyone had this issue? Is it related to the plugin? 
Thanks

**Comment by paulhazen** [comment]
Are you certain that the files have properly been checked out with `git lfs pull`? In my experience when a binary goes missing it's because the binary in question is only on the file system as a pointer file.

**Comment by paulhazen** [comment]
It would also be good to know if this happens every time - anecdotal evidence I have read on the topic suggests that it's an intermittent problem, and that `UnityTIs` is actually an internal Unity analytics call.

**Comment by MenesApps** [comment]
The error message appears everytime I build on iOS since the update. Didn't happen before. 

The good news is that reinstalling git lfs + the package fixed the missing binary issue so I was able to build and upload. Initial testings show that the login to EOS is working so I think the error I am getting can be ignored for now. I'll contact Unity to see if this is something they can help with.

Thanks for the help, I wouldn't have thought of reinstalling git lfs since it hasn't been an issue before.
