### ISSUE TITLE
How to disable on consoles? (Error: Unable to determine the name of the EOSSDK library)

### ISSUE THREAD

**Issue by 3ternal** [PlayEveryWare/eos_plugin_for_unity#418]
When building for the Switch, I'm getting an error on line 81 of Config.cs:

```
#error Unable to determine the name of the EOSSDK library. Ensure you have set the correct EOS compilation symbol for the current platform, such as EOS_PLATFORM_WINDOWS_32 or EOS_PLATFORM_WINDOWS_64, so that the correct EOSSDK library can be targeted.
```

I'm still on 2.3.3, but I took a look at the current version of Config.cs, and I think it's roughly the same.

The error talks about setting the correct EOS compilation symbol - is this something we're supposed to do on our end? I do have EOS_PREVIEW_PLATFORM enabled for testing the Mac build.

However, my use case is probably even simpler than this, because I don't actually need EOS outside of the Epic Games Store itself. With that in mind, should I be toggling something to disable EOS in console builds? I can do `#if !UNITY_SWITCH` in my own scripts, but this error is coming from the package itself.

**Comment by paulhazen** [comment]
Sorry, but (currently) the plugin is not supported on the Switch, and while it is something we are working toward, it isn't supported at this time.

_Unrelatedly:_

> The error talks about setting the correct EOS compilation symbol - is this something we're supposed to do on our end? I do have EOS_PREVIEW_PLATFORM enabled for testing the Mac build.

As of PR #387, you should no longer need to specify `EOS_PREVIEW_PLATFORM`.

**Comment by paulhazen** [comment]
Re-opening because a more careful reading of the issue indicates that I may have answered the wrong question. If I'm understanding it correctly (and I apologize for missing it beforehand), you want your build to completely not use the EOS Plugin on the Switch, correct?

If this is the case you'll need to exclude it using the `EOS_DISABLE`, documented [here](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/docs/disable_plugin_per_platform.md).

Let me know if this addresses your problem.

**Comment by 3ternal** [comment]
Ah, yep — I was asking two questions. I don't think I'll need EOS on the Switch (and it's causing build errors anyway), so I'll leave it disabled at least until support is added.

Fortunately, it looks like everything is working now — no build errors. Thanks!

Speaking of 2.3.3, will 3.0.1 be available in the UPM version of the package? I'll update once I'm able to, just in case that solves other problems.

**Comment by paulhazen** [comment]
> Ah, yep — I was asking two questions. I don't think I'll need EOS on the Switch (and it's causing build errors anyway), so I'll leave it disabled at least until support is added.
> 
> Fortunately, it looks like everything is working now — no build errors. Thanks!
> 
> Speaking of 2.3.3, will 3.0.1 be available in the UPM version of the package? I'll update once I'm able to, just in case that solves other problems.

Yes - the 3.0.1 release should be available as a UPM :)
