### ISSUE TITLE
Should the UPM version have already been updated to 3.0.1?

### ISSUE THREAD

**Issue by Jamez0r** [PlayEveryWare/eos_plugin_for_unity#421]
The UPM version is still 3.0.0: https://github.com/PlayEveryWare/eos_plugin_for_unity_upm

When will it be updated to 3.0.1? I am having two issues, both of which have been confirmed fixed in 3.0.1. I saw one or two people mentioning that 3.0.1 should be available via UPM, so just wanted to make sure it wasn't skipped on accident, or something.

Thanks, and thanks as always for the plugin!!

**Comment by andrew-hirata-playeveryware** [comment]
Hello @Jamez0r, 
Yes, that version has now been published to that repo!

**Comment by 3ternal** [comment]
Looks like there's a build error, unfortunately: https://openupm.com/packages/com.playeveryware.eos/?subPage=pipelines

**Comment by Jamez0r** [comment]
> Looks like there's a build error, unfortunately: https://openupm.com/packages/com.playeveryware.eos/?subPage=pipelines

Has this by chance been fixed, or is it something easily fixable on our end after downloading it? Hoping to get all of this set up and tested asap! Thanks!

**Comment by Jamez0r** [comment]
> Hello @Jamez0r, That should be fixed on the OpenUPM side now too!

Thank you Andrew! Updated it last night, and just tested it today and looks like the 2 issues we had are fixed! Appreciate it!
