### ISSUE TITLE
Trying voice chat (Lobbies method), getting disconnect loop, possibly MacOS related

### ISSUE THREAD

**Issue by hdewitte** [PlayEveryWare/eos_plugin_for_unity#426]
### Discussed in https://github.com/PlayEveryWare/eos_plugin_for_unity/discussions/422

<div type='discussions-op-text'>

<sup>Originally posted by **hdewitte** October  2, 2023</sup>
Hi all,

After [asking Epic dev support](https://eoshelp.epicgames.com/s/question/0D54z00009fWeSFCA0/trying-out-voice-chat-in-unitywindowsmac-gets-in-disconnect-loop-lobbies-method) first, they suggested to ask here. So here's the same story:

Due to issues on Mac with our current voice chat service, we're currently looking whether we'll have better luck using EOS voice interface for our Unity game.

We were able to successfully talk Windows to Windows, but so far no luck Windows to Mac. It gets stuck in a "control channel closed"/"reconnect successful" loop. You hope to find something more useful in the logs, but it seems the real disconnect reason is hidden from us... as much as those friendly "Bye!" messages are much appreciated.

So yeah couple of questions:
- Is it simply broken, and relating to why Mac is listed as preview?
- Otherwise, what other places can we check for some kind of log, to continue the hunt?
- Since there's no messages about this from other people, is there something obvious we could be missing? I'm aware that one would need more details of the situation to assess this, however I've no no idea what details would be relevant to provide at this point.
- Any other suggestions?

Here is an [example log](https://github.com/PlayEveryWare/eos_plugin_for_unity/files/12780746/log.txt).

Thanks for your attention!</div>

**Comment by arthur740212** [comment]
Hello, here are some places to check for the issue.
A. Make sure that the application is granted permission to use the device's microphone.
B. Check if the lobby scene is using the Press To Talk feature

**Comment by hdewitte** [comment]
Hi guys, found out we've been testing having the same account logged in on both ends. Making a new account on the other mac seemed to help: the mac proceeded to ask for mic access, received it, and soon terrible panicking echoes be.

What made it tricky is that the logs said nothing & couldn't see this requirement mentioned anywhere.

Thanks for the replies though!
