### ISSUE TITLE
May I ask how this plugin works on the Switch platform?

### ISSUE THREAD

**Issue by WuHaiqiang** [PlayEveryWare/eos_plugin_for_unity#427]
hello,
We are using EOS on the console platform, how can I make it work?
I couldn't find the relevant platform documentation.
thanks.

**Comment by paulhazen** [comment]
Hello @WuHaiqiang. At this time the EOS Plugin for Unity is not yet supported for consoles. It's something that we might look at doing in the future, but for the time being we do not support this.

**Comment by WuHaiqiang** [comment]
Hello, I saw this thread (https://p.siedev.net/forums/thread/303215/) while browsing the PS5 forum. How can I obtain access to the console library?

**Comment by paulhazen** [comment]
@WuHaiqiang For information about access to PlayStation platform support for the EOS Plugin, email us at eos-support@playeveryware.com

Nintendo Switch game developers can access PlayEveryWare’s plugin through the Nintendo Developer Portal via [www.developer.nintendo.com](http://www.developer.nintendo.com/)
