### ISSUE TITLE
Input System - Required for 3.0.1?

### ISSUE THREAD

**Issue by 3ternal** [PlayEveryWare/eos_plugin_for_unity#428]
Hi,

I just installed version 3.0.1. Is Unity's Input System a dependency now? If I try to uninstall it, it seems to reinstall itself after printing the following in the console:

```
PlayEveryWare.Editor.InputSystem.PackageInstallHelper_InputSystem:.cctor () (at ./Library/PackageCache/com.playeveryware.eos@3.0.1/Editor/PackageInstallHelper_InputSystem.cs:43)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes (System.Type[])
```

Is the Input System used for anything in this package? This could be inconvenient because, if you install the Input System but use the old Input manager, Unity hits you with a popup every time you boot up the engine. And, while the old Input is pretty old at this point, some popular assets like Rewired still use it, and Rewired is still regularly updated. So, there are likely quite a few projects that are set up with the old Input for compatability with Rewired or other assets.

**Comment by paulhazen** [comment]
Hi @3ternal 

Can you confirm which version of the plugin you are using? We had a similar issue that we closed a while back - it would be good to know if we closed it prematurely. I thought I had fixed this issue :\

For reference [here](https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/402) is the previous issue on the same topic that we closed.

**Comment by paulhazen** [comment]
> Hi @paulhazen, good to know that there's a potential workaround. This is ver 3.0.1 of the plugin, and Unity version 2022.3.6.

That's not ideal. I will take a look at this issue tomorrow to replicate it and get back to you - in the meantime, can you confirm that one of the workarounds listed in the aforementioned PR works for you? 

I can commiserate with the irritation such a pop-up would cause - so it'll be high on my list of things to address in the following 48 hours.

**Comment by 3ternal** [comment]
> > Hi @paulhazen, good to know that there's a potential workaround. This is ver 3.0.1 of the plugin, and Unity version 2022.3.6.
> 
> That's not ideal. I will take a look at this issue tomorrow to replicate it and get back to you - in the meantime, can you confirm that one of the workarounds listed in the aforementioned PR works for you?
> 
> I can commiserate with the irritation such a pop-up would cause - so it'll be high on my list of things to address in the following 48 hours.

Sure, no worries. I can take a look later, but I don't mind dealing with the popup for a couple of days, so I might not get to it right away.

**Comment by tvogt** [comment]
Just confirming that I have the same issue. 3.0.1 with Unity editor version 2022.3.10

**Comment by arthur740212** [comment]
[Here](https://github.com/PlayEveryWare/eos_plugin_for_unity/pull/432) are the changes that remove the input system dependency.
Let us know if it is behaving well :D

**Comment by 3ternal** [comment]
Hmm, looks like the popup is still occurring on 3.0.2? Did this work on your end @paulhazen?

**Comment by arthur740212** [comment]
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/36757173/c60363b8-5ca2-4f31-8cf6-c69e9d9bd443)
Remember to change the Input module back to `Input Manager(Old)`
Also the samples have to be reimported because the previous version has Input System module attached to them.

**Comment by 3ternal** [comment]
> ![image](https://user-images.githubusercontent.com/36757173/279839089-c60363b8-5ca2-4f31-8cf6-c69e9d9bd443.png) Remember to change the Input module back to `Input Manager(Old)` Also the samples have to be reimported because the previous version has Input System module attached to them.

Wait, my bad. I forgot that I was supposed to uninstall the new input system first!

Okay, it's working now. I can uninstall input system, and it doesn't get automatically re-installed.
