### ISSUE TITLE
Mac - Store Overlay

### ISSUE THREAD

**Issue by adrianmaker** [PlayEveryWare/eos_plugin_for_unity#431]
**Describe the bug**
When calling the EOSManager.Instance.GetEOSEcomInterface().Checkout query on Mac on the Epic store I get the following error instead of opening the checkout page:
Checkout NotConfigured

**To Reproduce**
Try and purchase something on Mac using the example store code

**Expected behavior**
The Epic overlay to display like it does on Windows

**Desktop (please complete the following information):**
 - OS: macOS intel/arm
 - Standalone build deployed on the Epic store
 - Unity version: 2021.3.29f1
 - plugin version: 3.0.1

**Additional context**
I know the Mac version is still in preview so I wanted to check if this was a known bug, if its something I am doing wrong on my end or if there is a workaround

**Comment by arthur740212** [comment]
Hi. the overlay isn't supported on Mac, so there isn't anything wrong on your end.
