### ISSUE TITLE
In v3.0.1, an error occurs when clicking the "Update from Steamworks.NET" button in the EOS Config Editor.

### ISSUE THREAD

**Issue by yohei-washizaki-aktsk** [PlayEveryWare/eos_plugin_for_unity#437]
**Describe the bug**

I created a new project and installed Steamworks.NET and eos_plugin_for_unity via package manager.

When I pressed the "Update from Steamworks.NET" button in the EOS Config Editor, I got the following error

```
Failed to retrive Steamworks SDK version from Steamworks.NET
UnityEngine.Debug:LogError (object)
PlayEveryWare.EpicOnlineServices.EpicOnlineServicesConfigEditor:OnSteamGUI () (at Library/PackageCache/com.playeveryware.eos@e1223c01fc/Editor/EpicOnlineServicesConfigEditor.cs:635)
PlayEveryWare.EpicOnlineServices.EpicOnlineServicesConfigEditor:OnGUI () (at Library/PackageCache/com.playeveryware.eos@e1223c01fc/Editor/EpicOnlineServicesConfigEditor.cs:660)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

**To Reproduce**

The complete reproduction file and documentation are attached at the end.

1. Create a new empty project.
2. Install Steamworks.NET (v20.2.0) via package manager.
3. Install eos_plugin_for_unity (v3.0.1) via package manager.
4. "Tools > EOS Plugin > Dev Portal Configuration" to open the config editor.
5. Select "Steam" tab.
6. Click "Update from Steamworks.NET" button.
7. See error

**Expected behavior**

1. No error output is generated.
2. "Steamworks SDK major version" is set to "1".
3. "Steamworks SDK minor version" is set to "57".

**Screenshots**

![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/91718181/9cb41715-6921-41bf-ad2f-cfe82991478b)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows x86, Windows x64, macOS Intel, macOS ARM]
   - Windows x64
 - Editor, or standalone build
   - Editor
 - Unity Version
   - 2021.3.19f1
 - Plugin Version
   - v3.0.1

**Additional context**

- Full reproduction files are [here](https://github.com/PlayEveryWare/eos_plugin_for_unity/files/13050539/min.zip).
- This issue does not occur in v2.3.3, but does occur in v3.0.0 and v3.0.1.
- For my project, I would like to adopt v3.0.0 or higher version for the IL2CPP supported plugin.
 cf. https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/353

Best regards and thank you in advance.

**Comment by arthur740212** [comment]
Thanks for the feedback.
A asmdef is missing in the package which causes the problem, also a bit surprised that no compile errors were shown.
Will fix this problem in the next release.

**Comment by arthur740212** [comment]
ca3821abc7030b85c108e1096c3f91feafd36157
2c01c365d1712773f5031b918951c72ea6d175f3
These two commits together fixes the problem

**Comment by yohei-washizaki-aktsk** [comment]
@arthur740212 
That's a quick fix, great! Looking forward to the next update.
Thanks to this plugin, I can develop more efficiently.😊
