### ISSUE TITLE
EOS ACHIEVEMENT

### ISSUE THREAD

**Issue by surifier** [PlayEveryWare/eos_plugin_for_unity#438]
We are ready to ship our game to epic games this month for post release we are planning to add someachievements for our game but i am really confused how to proceed furture.i already added https://eospluginforunity.playeveryware.com/ this eos package and filled all important details of productid,clientid,clientsecretid etc etc in configuration under tools/configuration and first scene of our game we added the EOS manager also.so far this its fine but i dont know how to exactly configure after this i mentioned already added the neccessary details in configuration of the eos sdk what we need to do to process furture to add the achievement for my game.please assist me regarding this issue thanks.hi one more step i did i added the samples also so here is were i got struck and dont know how to process future in this sdk.any sample scene i open the ui is not [working.as](http://working.as/) i mentioned please let me know if i am missing something thanks

**Comment by arthur740212** [comment]
Hi, were the achievements set up in the game's dev portal?
The plugin will query the achievements if they are set in the dev portal.

**Comment by surifier** [comment]
No not yet I want to know exactly how to configure it in plugin after
adding to the dev portal also we are working in a racing game so we will be
configuring it at the end of a winning race.so please give me some
instructions to be followed thanks🤝

**Comment by arthur740212** [comment]
The configurations you've completed pretty much sets the whole plugin up for EOSSDK usage.
If you mean scripting for achievements, the `EOSAchievementManager.cs` is where to look for methods to use.
There are samples in the plugin too, try logging in with the Achievement scene to make the EOSSDK is in fact configured correctly. You will also find scripting examples in the scene too.

**Comment by paulhazen** [comment]
Hi @surifier, were you able to follow the sample scenes to figure out how to add achievements to your game?

**Comment by surifier** [comment]
No not yet currently we are working on the some bug fixes I will look into
it🤝

**Comment by paulhazen** [comment]
@surifier I'm going to close this issue for now, please feel free to re-open it if when you get to it you are still having difficulty! :)
