### ISSUE TITLE
Android Build Failing - Missing Directory

### ISSUE THREAD

**Issue by DeepP2667** [PlayEveryWare/eos_plugin_for_unity#439]
**Describe the bug**
Android build fails because of missing directory Temp\Android\eos-sdk\res\values\values.xml. It's happening because there is no values folder. This section of code EOSOnPreprocessBuild_android.cs:394 is labeled Pre EOS 1.16 SDK, maybe it can be removed since SDK is updated?

**To Reproduce**
1. Create new project
2. Installed package through git url + added samples
3. Build for Android
4. Error :(

**Desktop (please complete the following information):**
 - Windows (building for android)
 - Build
 - Unity - 2022.3.1.f1
 - Package - 3.01

**Stack Trace**
<img width="742" alt="image" src="https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/70382249/0a5a6b9c-bf13-4d94-ab5b-0c83a49726f7">

**Comment by arthur740212** [comment]
We might have missed this fix in 3.0.1 :O 
There is a fix in development branch (commit 953463b)
along slight changes to android aar related stuff.
Expect a build to happen at the end of the month.
Thanks for the feedback.
