### ISSUE TITLE
Should EOS_DISABLE work with buildPlayerOptions.extraScriptingDefines? It isn't for me

### ISSUE THREAD

**Issue by Jamez0r** [PlayEveryWare/eos_plugin_for_unity#440]
Hello, first off thanks a lot for the plugin!

I'm working on automating my builds. On PC, I am targeting Steam and Epic Games Store. I'd like to disable the EOS plugin when building for Steam (I don't want the build to include the EOS-related files).

I thought I would be able to do it by adding EOS_DISABLE to my buildPlayerOptions.extraScriptingDefines, but that doesn't seem to work (the build still contains the EOS-related files). However, if I manually add EOS_DISABLE to the list in ProjectSettings (as mentioned here: [https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/docs/disable_plugin_per_platform.md](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/docs/disable_plugin_per_platform.md)), it does indeed seem to disable the plugin and the build does not include the EOS-related files.

How can I automate this, so that when I'm building for Steam it disables the plugin, and building the Epic keeps it enabled, without manually adding/removing the EOS_DISABLE from the ProjectSettings? Is there a reason it doesn't work with buildPlayerOptions.extraScriptingDefines?

Thanks for the help!!

**Comment by arthur740212** [comment]
Hello, we're here to help you.
At first glance it could be related how assemblies are set up in the plugin
we'll be investigating the problem and come back to you soon.
Thanks for the feedback and support!

**Comment by Jamez0r** [comment]
> Hello, we're here to help you. At first glance it could be related how assemblies are set up in the plugin we'll be investigating the problem and come back to you soon. Thanks for the feedback and support!

Thanks Arthur!

In case it matters, I'm using EOS Plugin version 3.0.1 of the plugin, and Unity 2021.3.30f1

**Comment by paulhazen** [comment]
@Jamez0r Sorry for the slow motion on this. 

Re-reading your original post I'm noting that you mention that making a Steam build and utilizing the `EOS_DISABLE` results in a build that still has EOS-relevant files. Admittedly, that feels like broken behavior that should be fixed - however _it is mentioned_ in the [final section](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/docs/disable_plugin_per_platform.md#effects-of-eos_disable) of the guide to [disable_plugin_per_platform.md](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/docs/disable_plugin_per_platform.md) that while using `EOS_DISABLE` _will disable EOS functionality_, it still may include files.  

That's something we should probably fix - but it is _distinct_ in my mind from whether or not it actually disables EOS functionality. Can you confirm that using the `EOS_DISABLE` flag does result in a functional build that (while containing some of the related files) does not actually implement EOS?

Sort of a subtle distinction, and I'm not certain if I've adequately articulated it - so feel free to ask follow-up questions if what I am suggesting is unclear.

**Comment by Jamez0r** [comment]
> @Jamez0r Sorry for the slow motion on this.
> 
> Re-reading your original post I'm noting that you mention that making a Steam build and utilizing the `EOS_DISABLE` results in a build that still has EOS-relevant files. Admittedly, that feels like broken behavior that should be fixed - however _it is mentioned_ in the [final section](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/docs/disable_plugin_per_platform.md#effects-of-eos_disable) of the guide to [disable_plugin_per_platform.md](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/docs/disable_plugin_per_platform.md) that while using `EOS_DISABLE` _will disable EOS functionality_, it still may include files.
> 
> That's something we should probably fix - but it is _distinct_ in my mind from whether or not it actually disables EOS functionality. Can you confirm that using the `EOS_DISABLE` flag does result in a functional build that (while containing some of the related files) does not actually implement EOS?
> 
> Sort of a subtle distinction, and I'm not certain if I've adequately articulated it - so feel free to ask follow-up questions if what I am suggesting is unclear.

Hey Paul, thanks for the response!

I'd be glad to test that out - could you let me know what the easiest way would be to test if the plugin's functionality is disabled in the build? If there is a simple way to check that I can do a Debug.Log() to verify that its disabled.

And just to be sure, I believe this is what you're asking me to do:
-Use my setup where I build the game using **buildPlayerOptions.extraScriptingDefines** to include EOS_DISABLE (NOT using the ProjectSettings window to add it).
-The build will include the EOS-specific files, but to just ignore that.
-Test whether or not the EOS plugin is actually functionally disabled in the build.

If thats correct, and you can let me know a way to test if the plugin is 'functionally disabled' then I can test that out soon!

Thanks!

**Comment by paulhazen** [comment]
@Jamez0r Yes, you understand correctly.

Perhaps the best way to test it would just be to place a breakpoint inside the EOSManager init code, and check to make sure it is not being hit. If the breakpoint doesn't get hit, then you know the plugin isn't functioning.

Eager to know if this _doesn't_ work for you, because it will mean there's a bug that needs addressing - which is always good to have caught :D

Also - you should be able to use _either_ `buildPlayerOptions.extraScriptingDefines`, or use the ProjectSettings window to add `EOS_DISABLE`, the result should be the same either way.

**Comment by Jamez0r** [comment]
@paulhazen Thanks for the info! I'll test that out this weekend and get back to you.

**Comment by Jamez0r** [comment]
@paulhazen Alright, I tested it out:

Test Setting 1:
Run game in Unity Editor
Without EOS_DISABLE set anywhere
Result:
EOS did initialize, as expected

Test Setting 2:
Run game in Unity Editor
With EOS_DISABLE set in the Project Settings window
Result:
EOS did not initialize, as expected

Test Setting 3:
Standalone build
Without EOS_DISABLE set anywhere
Result:
EOS-related files were included in build, as expected
EOS did initialize, as expected

Test Setting 4:
Standalone build
With EOS_DISABLE set in the Project Settings window
Result:
EOS-related files were not included in build, as expected
EOS did not initialize, as expected

Test Setting 5:
Standalone build
With EOS_DISABLE **set through buildPlayerOptions.extraScriptingDefines**
Result:
**EOS-related files were included in build - not desired**
EOS did **not** initialize (good)

So looks like the buildPlayerOptions.extraScriptingDefines does 'functionally disable' it, but is there a way to prevent the EOS-related files (the two EOSBootstrapper files) from being included? That would complete the deal 👍

**Comment by paulhazen** [comment]
Moved this to issue #466. The conversation will move there. There may be complicated reasons it is not feasible, but we will have that discussion there instead of here.
