### ISSUE TITLE
Netcode not working 

### ISSUE THREAD

**Issue by Arex360** [PlayEveryWare/eos_plugin_for_unity#441]
So, I installed playeverywhere with sample Netcode as per instruction, and alsp I have added my EOS credientals as well. so I went to scene , and it says success but when I click on Start Host, I get error of null exceptions

`NullReferenceException: Object reference not set to an instance of an object
PlayEveryWare.EpicOnlineServices.Samples.Network.NetworkSamplePlayer.OnNetworkSpawn ()`

and 

`NullReferenceException: Object reference not set to an instance of an object
PlayEveryWare.EpicOnlineServices.Samples.Network.EOSTransport.PollEvent (System.UInt64& clientId, System.ArraySegment`1[System.Byte]& payload, System.Single& receiveTime) (at Assets/Samples/Epic Online Services Plugin for Unity/3.0.1/Extra Pack 1 _ P2P Netcode Sample/Scripts/Networking/EOSTransport.cs:197)`

Can anyone help me?

**Comment by paulhazen** [comment]
Hi @Arex360, is this still an issue for you? If it's not, I'd like to be able to close it - if it is still an issue for you, we'll need a little bit more context I think to help resolve it.

**Comment by paulhazen** [comment]
@Arex360 Closing this issue now, if you are still experiencing it please feel free to re-open.
