### ISSUE TITLE
The EOS SDK causes memory corruption issues and crashes.

### ISSUE THREAD

**Issue by Satiriano** [PlayEveryWare/eos_plugin_for_unity#463]
**Describe the bug**
Since adding the EOS SDK, I've noticed crashing in my game. Usually it crashes within 5-15 minutes of gameplay after connection and talking between 2 users. I've spent the last couple of days debugging those crashes, and I'm lost. The more things that are going on (voice, sending serverRPC/clientRPC), the faster the crash occurs.

**To Reproduce**
I don't know if the sample crashes as well, but, basically I've implemented lobbies creation and joining same as you are doing in your sample. The only difference is that I also have players spawned and running around in netcode for gameobjects. That being said, the sample is not really straight-forward and easy (just recently learned that I forgot to use "onloggedin()" in lobbiesmanager, and for that reason my lobby members weren't getting updated...).

So it's entirely possible I missed something. That being said, I will appreciate any help with this, as I'm frustrated, lost, and my game open beta is coming soon.

I'm not doing anything fancy here, just joining the lobby and starting client/host via netcode for gameobjects. 
It could very well be EOS networktransport being weird. I might need to come back to facepunch steamworks transport, as the game didn't have any issues using that library and networktransport.

**Expected behavior**
Game not crashing / no memory corruption issues.

**Crash logs**
```
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFF8881744B)
0x00007FFF8881744B (UnityPlayer) (function-name not available)
0x000001AEED5D3B71 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.Component:get_transform (UnityEngine.Component)
0x000001AF3343490B (Mono JIT Code) Pooling:Borrow<T_REF> (T_REF,UnityEngine.Vector3&,UnityEngine.Quaternion&)
0x000001AF33434283 (Mono JIT Code) EffectsForPlayer/<SpawnAndAnimateDecal>d__12:MoveNext ()
0x000001AEED5D9A00 (Mono JIT Code) UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
0x000001AEED5D9B2F (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_void_object_intptr (object,intptr,intptr,intptr)
0x00007FFF230B4B6E (mono-2.0-bdwgc) mono_jit_set_domain
0x00007FFF22FED204 (mono-2.0-bdwgc) mono_object_get_virtual_method
0x00007FFF22FED37C (mono-2.0-bdwgc) mono_runtime_invoke
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFF88E869AD)
0x00007FFF88E869AD (UnityPlayer) (function-name not available)
```
I get random crash logs, random functions that worked fine suddenly not working, so basically memory corruption issues - "Attempt to access invalid address".

[Player-crash.log](https://github.com/PlayEveryWare/eos_plugin_for_unity/files/13322537/Player-crash.log)
[Player-crash2.log](https://github.com/PlayEveryWare/eos_plugin_for_unity/files/13322538/Player-crash2.log)
[Player-crash3.log](https://github.com/PlayEveryWare/eos_plugin_for_unity/files/13322539/Player-crash3.log)
[Player-crash4.log](https://github.com/PlayEveryWare/eos_plugin_for_unity/files/13322541/Player-crash4.log)

**Desktop (please complete the following information):*

 - OS: Windows x64
 -  Standalone build
 - 2022.3.12f1
 - 3.0.2

**Comment by arthur740212** [comment]
Hello, sorry for the inconvenience, we have received several crash reports recently, and in common they were all using netcode with gameobjects
Good news is that we were able to find out where the problem was and made a fix for that right [here].(https://github.com/PlayEveryWare/eos_plugin_for_unity/pull/453)
It was tested on several projects and the fix was reported to be working,
So we think it is highly possible that you were hitting the same problem.
There will be a release soon if you're not in a hurry, you could also build a package from the repo `development` branch, the fix is in there already. 
Thanks for the report.

**Comment by Satiriano** [comment]
Thank you, for returning me my sanity... I'll test the solution out and get back to you

**Comment by arthur740212** [comment]
The release with the fix is out, let us know if new problems occur. :D

**Comment by greatOmouse** [comment]
> The release with the fix is out, let us know if new problems occur. :D

I've been testing it as well, I saw the same issues previously and it seems that they are now all gone! thanks so much
