### ISSUE TITLE
[Android] Crash when Minify is active

### ISSUE THREAD

**Issue by bilck** [PlayEveryWare/eos_plugin_for_unity#476]
**Describe the bug**
When Minify is enabled the game crashes as soon as EOS tries to initialize with the following error:
`2023/11/22 11:13:15.034 24872 24972 Fatal ds.playtogether java_vm_ext.cc:591] JNI DETECTED ERROR IN APPLICATION: JNI IsSameObject called with pending exception java.lang.ExceptionInInitializerError: `

This doesn't happen if minify is disabled.
I don't know EOS proguard rules and it's not clear in the 

**To Reproduce**
1. Build the app with minify enabled (I enabled it for a development build)
2. Open the app
3. The app will crash (at least it crashed for us)

Alternatively, [this is a Google Drive link](https://drive.google.com/drive/folders/1846JUKR_0lsFIttqA1XmEqtIHVHZ10J_?usp=sharing) for the development build and the player log.

**Smartphone (please complete the following information):**
 - Device: Galaxy S21+
 - OS: Android 13
 - Unity Version: 2022.3.10f1
 - Plugin Version: 3.0.2

**Comment by paulhazen** [comment]
Hi @bilck, sorry for the delayed response. 

>This doesn't happen if minify is disabled.
>I don't know EOS proguard rules and it's not clear in the

I think I can infer the remainder of what you meant to include ("it's not clear in the documentation"?). But for the sake of clarity, can you amend your issue comment and complete your thought starting with "I don't know EOS proguard rules and it's not clear in the..." (or just confirm my inference is correct)?

A few other questions I have:

1. Are you using ProGuard _and_ Minify? (There shouldn't be a problem with that AFAIK, but just checking)
2. Do you have any special configuration set up for ProGuard or Minify that might be errantly labeling some portion of the EOS plugin as dead code?
3. This "smells" to me like it may be an issue related to threading. I know that the EOS SDK has some threading quirks - these might be to blame, although I don't understand why it would only be failing when minify is enabled...
4. From reading the player log (thank you for providing that by the way!) it seems that the exception is being thrown by the EOS SDK itself, which means the plugin code isn't catching it for some reason. It's not clear to me where the plugin is _making_ that call to the SDK from. Could you add some log statements where you suspect the plugin is calling this so we can investigate further?

**Comment by bilck** [comment]
1. No we are not using Proguard. The reason we detected this is because we tried to enable it in this project.

I will try to investigate more as soon as we get some time to investigate this in more details.

For now, that's all we have.

**Comment by paulhazen** [comment]
Hi @bilck, just following up. Were you able to do more investigative work on this issue, or perhaps even resolve it?

**Comment by paulhazen** [comment]
Hi @bilck, without additional information to work with, I'm going to close this issue. Please feel free to re-open if the issue persists or you have additional information. If you've _resolved_ the issue that would be really good to know, just so we can document what the resolution is along with the probable cause. Thank you so much for bringing this to our attention in the first place. :)
