### ISSUE TITLE
Error "Player data storage: could not receive data: too much of it."

### ISSUE THREAD

**Issue by GalBorSan** [PlayEveryWare/eos_plugin_for_unity#480]
**Describe the bug**
Error "Player data storage: could not receive data: too much of it." is triggered by the ReceiveData method of the EOSPlayerDataStorage.cs file

**To Reproduce**
1- Save a file to cloud (named gabo_visionpictures_20231123131149). The callback log Success ok is triggered.
2- Try to get the file from cloud using EOSPlayerDataStorage::StartFileDataDownload method.
3- The log Error "[EOS SDK] Player data storage: could not receive data: too much of it." is triggered from EOSPlayerDataStorage::ReceiveData method.

We can't read a file downloaded from cloud. The transfers progress seem to be completed because this log "[EOS SDK] Player data storage: transfer progress 27444 / 27444" is triggered before the error. It's only 27,4 KB so is not too much.

**Expected behavior**
To be able to download a file previously saved in the cloud without problems.

**Desktop (please complete the following information):**
 - OS: [Windows x64]
 - Standalone build
 - Unity Version: 2021.3.0f1
 - Plugin Version: 3.0.1
 - Epic Online Services Version: 1.16.0-27024038

**Comment by paulhazen** [comment]
Can confirm this is a bug. Working on a fix now, will update with PR shortly.

**Comment by paulhazen** [comment]
PR #481 resolves this issue. Once it's merged it will be reflected in the `development` branch, and after a few weeks or so it will be in a new release. Let me know if you need assistance exporting the plugin from the development branch.

**Comment by paulhazen** [comment]
It's been merged. Marking this issue as "pending" until the change gets into `stable`

**Comment by paulhazen** [comment]
I'm closing this issue as resolved. It's unclear to me whether the solution is yet in the `stable` branch, but the solution has been tested, and will certainly be in `stable` shortly.
