### ISSUE TITLE
Support On Xbox O|S and PS4/PS5

### ISSUE THREAD

**Issue by AMateenKhan** [PlayEveryWare/eos_plugin_for_unity#482]
I'm aiming to integrate the PlayEveryWare plugin into my Unity project for a multiplatform game, already supporting Steam, Nintendo Switch, Xbox O|S and PS4/PS5. However, I think it currently lacks support for Xbox and PlayStation. I'm seeking guidance on whether it's possible to extend its functionality to these platforms(Xbox and PS) or if there are alternative methods to incorporate Xbox and PS support. If additional support for Xbox and PlayStation is available, it would significantly help us make one window solution for all the platforms.

**Comment by paulhazen** [comment]
Hi @AMateenKhan, thanks for reaching out.

For information about access to PlayStation or Xbox platform support for the EOS Plugin, email us at eos-support@playeveryware.com.
