### ISSUE TITLE
Push to talk adds big delay.

### ISSUE THREAD

**Issue by nitrocss** [PlayEveryWare/eos_plugin_for_unity#485]
Using press to talk rather than continuous sending adds a huge delay. Sometimes up to 3-4 seconds are added before audio is heard, even when testing with machines that are in the same city. The problem is clearly with PTT, as when PTT is turned off the audio is instantenous.

All I can add to help you, is that I've found a workaround that works, which is instead of using current PTT solution, I update the volume directly instead. 

To anyone wondering how to update the volume:
```
var eosRtcAudioInterface = eosRtcInterface.GetAudioInterface();
eosRtcAudioInterface.UpdateSendingVolume(ref setAudioInputSettingsOptions, null, OnCompleteVolume);
```

I wish this delay was removed, because I'm pretty sure my current solution might be wasting some bandwidth, but I can't know for sure. But it produces 100x better (because it's usable) voip with PTT.

**Comment by arthur740212** [comment]
That is a splendid solve, I am despising myself for not thinking of this when making PTT.
Would like to do the honor by making a PR and contributing to the repo?
Or we could also apply the fix you like the idea of being an unsung hero :D
Please let us know!

**Comment by nitrocss** [comment]
Hey, thanks for acknowledging my solve, it took a couple of different approaches to figure it out. 
I don't feel like I know the project enough yet to implement a PR by myself. I will cheer you on from the shadows :).
It works really well, so definitely worth. Take care!

**Comment by arthur740212** [comment]
Hello, we are working on the fix on this branch 9e13851fba39ce3f0114f68766b19b38d02d57f0
The volume method worked like a charm.
Though we found out that even without PTT, the audio will slowly begin to lag as well.
To further investigate the problem, we'd like to know if you were also experiencing the lag without PTT.

**Comment by Satiriano** [comment]
I didn't notice the audio slowly beginning to lag, however, I did rather short tests of like 5-10 minutes at most. I'll do a longer one and get back to you.

**Comment by nitrocss** [comment]
I didn't notice the audio to start lagging over time. I only did tests of about 5-10 minutes in length though. I'll do a longer one and get back to you.

**Comment by paulhazen** [comment]
Hi @nitrocss, I'm marking this PR as "pending" since we have a tentative fix in. I'll make sure this issue is closed once we have the feature in our `stable` branch. Thanks again!

**Comment by arthur740212** [comment]
After some testing the growing lag was only found on a screen locked Android device,
the lag will disappear when unlocking the screen.

On PC the send/receive delay is consistent.
We will apply the fix in a PR and track the growing lag issue on a separate task.

**Comment by paulhazen** [comment]
Closing this issue as the solution exists in the `development` branch and will in short time be in the `stable` branch.
