### ISSUE TITLE
Achievement icon display abnormally after token expired and updated

### ISSUE THREAD

**Issue by HouTing** [PlayEveryWare/eos_plugin_for_unity#487]
I registered the event in `enable()`
But the achievement icon doesn't show up properly when unlocking the achievement.
Is this the right way to do it?

```csharp
authExpirationCallbackHandle = connectInterface.AddNotifyAuthExpiration(ref addNotifyAuthExpirationOptions, null, (ref Epic_Connect.AuthExpirationCallbackInfo resultCallback) =>
{
    Epic_Auth.LoginCallbackInfo loginCallbackInfo = new Epic_Auth.LoginCallbackInfo
    {
        LocalUserId = accountId
    };
    StartConnectLoginWithLoginCallbackInfo(loginCallbackInfo);
});
```
![achievement](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/28332031/96bef86a-bce5-4734-8cd0-f8f9c1c0c554)

**Comment by andrew-hirata-playeveryware** [comment]
I believe that is correct: Do the icons also display abnormally in the EOS overlay?

**Comment by arthur740212** [comment]
In our plugin's achievement scene, the achievement icons are loaded upon logging in, which is separate from the unlocking part.
You might have to download the icon before the unlock happens.
Also, the icons might need to be set in the dev portal or else it might be empty.

**Comment by HouTing** [comment]
> I believe that is correct: Do the icons also display abnormally in the EOS overlay?

Yes. The icon for the overlay is in the same condition.
![achievement02_1](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/28332031/d36e564c-9f0a-467c-9cef-f45dee3e276f)

**Comment by HouTing** [comment]
In addition, when unlocking achievements, the icons don't show up immediately, as if they haven't been downloaded yet, as shown in the attached picture.
Is there a way to preload the icon to avoid this problem?
![03-1](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/28332031/4ee8c3b0-af1d-4ba6-8519-3edc687e6bc7)

**Comment by arthur740212** [comment]
Hi, is the image on the top left a part of the icon?
If it is, does the icon gradually show its full form?

**Comment by HouTing** [comment]
> Hi, is the image on the top left a portion of the icon? If it is, does the icon gradually show its full form?

Hello,
Yes, the picture will gradually become complete.
But sometimes the unlock achievement notification disappears before the picture is complete.
I expect that the unlock achievement notification should be displayed with the full icon and not a broken icon.

In fact, I've tried exporting the sample program to Epic Launcher and running it, and it has the same problem when unlocking.
Is this normal? Or is there something else I haven't noticed?
Also, my icons are 96*96, so the file size should be small.

**Comment by paulhazen** [comment]
Hi @HouTing. Thanks for bringing this to our attention. Unfortunately, there is not currently a method in the EOS SDK for pre-caching the achievement icons defined in the dev portal. I suspect implementation of such a feature would be best placed in the SDK itself instead of the plugin. Let's look at a few other possibilities though:

I have a couple of questions regarding the issue:

1. Can you check these values to make sure that the locale of the application you are running is consistent with the locale indicated when creating the achievement?

<img width="539" alt="image" src="https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/1439891/fffbe576-24f9-4cdd-a849-f0852cd7fa4b">

2. It's not immediately clear to me how this achievement is related to token expiration. Can you explain to me in simple terms when the achievement is intended to be unlocked? (Is it an achievement you earn for logging in?)

**Comment by HouTing** [comment]
Hello @paulhazen ! Thanks for reply.
1. Yeah, I'm sure the settings are right. In fact, it doesn't happen all the time. The unlock achievement icons are displayed correctly when first start the game, but after a while the game may have a problem.
My achievements are currently available in two languages, English and Chinese.

2. In my game, I use the manual unlock method when completing in-game tasks. Here's resource code.
public void UnlockAchievementManually(string achievementId, OnUnlockAchievementsCompleteCallback callback = null)
{
	var localUserId = productUserId;
	var eosAchievementOption = new UnlockAchievementsOptions
	{
		UserId = localUserId,
		AchievementIds = new Utf8String[] { achievementId }
	};
	achievementsInterface.UnlockAchievements(ref eosAchievementOption, null, null);
}

**Comment by paulhazen** [comment]
I've experienced things like this happening to varying degrees on Android devices that are being used as development devices - ie devices that you are manually deploying an application to. If you do a clean on the device in question between deployments, do you experience the same behavior? I'm wondering if there is something lingering in Android's file system cache that's causing problems.

**Comment by dulceangustia** [comment]
I'm experiencing the same issue. 

After ~70 minutes of starting the game and being able to unlock quite a few achievements during the first hour, I start getting achievements unlocked without the configured image being displayed. Name, description and XP are correct. In the overlay achievement list all achievements are listed correctly, except for the images of those unlocked, allegedly, after reconnecting.

I'm using the same reconnection approach that the one posted in the OP.

In case it helps solving this issue, I'm testing my game through the EGL, in Stage sandbox, and this is the first run.

**Comment by dulceangustia** [comment]
In case it helps, it continued playing the day after. First achievement to get was unlocked correctly (with correct image), but the next one (after ~75 minutes) didn't show the correct image (grey placeholder, as in the OP).

So it's a persistent issue.

**Comment by dulceangustia** [comment]
Hello again. I'd like to share a small update.

I made a small change on the code and now the achievements are unlocking with the correct images, but I'm not sure that change is correct, so I hope you can help me confirm.

Before, I was registering for the AuthExpiration notification **only at the first login**, as I assumed I would not need to register for it with every token refresh. However, **now I am registering on every login/token refresh** (every hour) and achievements seem to be unlocking correctly. Is this what I was supposed to be doing?

**Comment by dulceangustia** [comment]
Hey @HouTing. 

I'm afraid it worked (?) the first time I tried it, but the day after, when I tried unlocking more achievements it failed again.

That makes me think that it's not really an issue about on how we implement it, but on Epic's backend. Does it make sense? I don't know what else to try, honestly.

**Comment by HouTing** [comment]
Hello @paulhazen @dulceangustia  !
After days of trying and still not finding a solution, I'm guessing if the image information used for notifications or overlay displays are reset when the login token is refreshed, or if the UI events need to be re-registered after the refresh.

This is because if the overlay is opened and the achievement icon is displayed before refreshing the login token, it will work fine when unlocking the achievement, but the icon that was displayed before refreshing will have the problem.

Is there an event to register the overlay to show the UI or a refresh function? Or does the native EPIC UI system handle this during authentication?
