### ISSUE TITLE
Connect token expires and isn't being refreshed correctly

### ISSUE THREAD

**Issue by GalBorSan** [PlayEveryWare/eos_plugin_for_unity#494]
We have spoken to Epic support about this problem we were having:
> Occasionally, while we are playing, a login state change is called and the user is logged out. 
> 
> When this happens, when trying to do a save we get an error because the GetProductUserId() function is null.

We were told that the problem was as follows:

> Connect token isn't being refreshed correctly. The token expires every hour. When the token expires EOS_Connect_AddNotifyAuthExpiration should be triggered and EOS_Connect_Login should be getting called. See User authentication refresh notification for more details.
> 
> Looking at the PEW plugin in the function `ConfigureConnectExpirationCallback` in `EOSManager.cs`, I'm not certain this is being setup correctly.

We have noticed that in the `EOS_Manager::ConfigureConnectExpirationCallback` method the `AuthExpirationCallbackInfo` parameter `callbackInfo` is empty.

We have implemented the code , is it correct, is it a bug that you have already fixed in the develop branch?

```csharp
private void ConfigureConnectExpirationCallback()
{
    if (s_notifyConnectAuthExpirationCallbackHandle == null)
    {
        var EOSConnectInterface = GetEOSConnectInterface();
        var addNotifyAuthExpirationOptions = new Epic.OnlineServices.Connect.AddNotifyAuthExpirationOptions();
        ulong callbackHandle = EOSConnectInterface.AddNotifyAuthExpiration(
            ref addNotifyAuthExpirationOptions, 
            null, 
            (ref AuthExpirationCallbackInfo callbackInfo) => {
            EpicLauncherArgs argsEpic = GetCommandLineArgsFromEpicLauncher();
            StartLoginWithLoginTypeAndToken(
                LoginCredentialType.ExchangeCode,
                argsEpic.epicUserID,
                argsEpic.authPassword,
                (Epic.OnlineServices.Auth.LoginCallbackInfo callbackInfo) => {
                    if (callbackInfo.ResultCode != Result.Success)
                    {
                        // ask user if they want to connect; assume they do
                        CreateConnectUserWithContinuanceToken(callbackInfo.ContinuanceToken, (CreateUserCallbackInfo createUserCallbackInfo) => {
                            StartConnectLoginWithEpicAccount(callbackInfo.LocalUserId, (Epic.OnlineServices.Connect.LoginCallbackInfo retryConnectLoginCallbackInfo) => {
                                if (retryConnectLoginCallbackInfo.ResultCode == Result.Success)
                                {
                                    print("ConfigureConnectExpirationCallback :: CreateAndConnectWithContinuanceToken::login with Epic Account Success, ProductUserId [" + retryConnectLoginCallbackInfo.LocalUserId.ToString() + "]");
                                }
                                else
                                {
                                    print("ConfigureConnectExpirationCallback :: CreateAndConnectWithContinuanceToken::Failed to login with Epic Account [" + retryConnectLoginCallbackInfo.ResultCode + "]");
                                }
                            });
                        });
                    }
                    else
                    {
                        StartConnectLoginWithEpicAccount(callbackInfo.LocalUserId, (Epic.OnlineServices.Connect.LoginCallbackInfo connectLoginCallbackInfo) => {
                            if (connectLoginCallbackInfo.ResultCode == Result.Success)
                            {
                                print("ConfigureConnectExpirationCallback :: Connect Login Successful. [" + connectLoginCallbackInfo.ResultCode + "]");
                            }
                            else if (connectLoginCallbackInfo.ResultCode == Result.InvalidUser)
                            {
                                // ask user if they want to connect; assume they do
                                EOSManager.Instance.CreateConnectUserWithContinuanceToken(connectLoginCallbackInfo.ContinuanceToken, (CreateUserCallbackInfo createUserCallbackInfo) =>
                                {
                                    EOSManager.Instance.StartConnectLoginWithEpicAccount(callbackInfo.LocalUserId, (Epic.OnlineServices.Connect.LoginCallbackInfo retryConnectLoginCallbackInfo) =>
                                    {
                                        if (retryConnectLoginCallbackInfo.ResultCode == Epic.OnlineServices.Result.Success)
                                        {
                                            print("ConfigureConnectExpirationCallback :: StartConnectLoginWithLoginCallbackInfo::login with Epic Account Success, ProductUserId [" + retryConnectLoginCallbackInfo.LocalUserId.ToString() + "]");
                                        }
                                        else
                                        {
                                            print("ConfigureConnectExpirationCallback ::StartConnectLoginWithLoginCallbackInfo::Failed to login with Epic Account [" + retryConnectLoginCallbackInfo.ResultCode + "]");
                                        }
                                    });
                                });
                            }
                        });
                    }
                });
            });

        s_notifyConnectAuthExpirationCallbackHandle = new NotifyEventHandle(callbackHandle, (ulong handle) => {
            GetEOSConnectInterface()?.RemoveNotifyAuthExpiration(handle);
        });
    }
}
```
Thank you very much!

**Comment by GalBorSan** [comment]
Hello again,

We would need an answer regarding this. 
Thank you.

**Comment by paulhazen** [comment]
Hi @GalBorSan, I apologize that we have not gotten back to you on this. I'm sure that the holiday season contributed, but that's not an excuse for not at least touching base. 

I'm going to clean-up your original post so I can read the code a little bit better, then I will take a look more closely and get back to you with some more information.

**Comment by GalBorSan** [comment]
Hi again,

We get an error when calling EOSAuthInterface.Login inside the StartLoginWithLoginOptions method:

"LogEOS(Warning): Error response received from backend. ServiceName=[OAuth], OperationName=[TokenGrantv2], Url=[<Redacted>], HttpStatus=[400], ErrorCode=[errors.com.epicgames.account.oauth.exchange_code_not_found], NumericErrorCode=[18057], ErrorMessage=[Sorry the exchange code you supplied was not found. It is possible that it was no longer valid], CorrId=[EOS-Ras6yu0c80KH_d9Uk2PnjA-UKUgz02gB0qrLB-mfkwZAw]

EPIC LOG:: LoginCallBackResult : AuthExchangeCodeNotFound"

We have removed StartLoginWithLoginTypeAndToken call and we now call StartConnectLoginWithEpicAccount directly and it works! This is the final code:

private void ConfigureConnectExpirationCallback()
          {
              print("ConfigureConnectExpirationCallback");

              if (s_notifyConnectAuthExpirationCallbackHandle == null)
              {
                  var EOSConnectInterface = GetEOSConnectInterface();
                  var addNotifyAuthExpirationOptions = new Epic.OnlineServices.Connect.AddNotifyAuthExpirationOptions();
                  ulong callbackHandle = EOSConnectInterface.AddNotifyAuthExpiration(ref addNotifyAuthExpirationOptions, null, (ref AuthExpirationCallbackInfo callbackInfo) =>
                  {
                      AuthInterface AuthInterface = GetEOSPlatformInterface().GetAuthInterface();
                      EpicAccountId accountId = AuthInterface.GetLoggedInAccountByIndex(0);

                      StartConnectLoginWithEpicAccount(accountId, (Epic.OnlineServices.Connect.LoginCallbackInfo connectLoginCallbackInfo) =>
                      {
                          if (connectLoginCallbackInfo.ResultCode == Result.Success)
                          {
                              print("ConfigureConnectExpirationCallback :: Connect Login Successful. [" + connectLoginCallbackInfo.ResultCode + "]");
                          }
                          else if (connectLoginCallbackInfo.ResultCode == Result.InvalidUser)
                          {
                              // ask user if they want to connect; assume they do
                              EOSManager.Instance.CreateConnectUserWithContinuanceToken(connectLoginCallbackInfo.ContinuanceToken, (CreateUserCallbackInfo createUserCallbackInfo) =>
                              {
                                  print("ConfigureConnectExpirationCallback :: StartConnectLoginWithLoginCallbackInfo::Creating new ConnectUserWithContinuanceToken");
                                  EOSManager.Instance.StartConnectLoginWithEpicAccount(accountId, (Epic.OnlineServices.Connect.LoginCallbackInfo retryConnectLoginCallbackInfo) =>
                                  {
                                      if (retryConnectLoginCallbackInfo.ResultCode == Epic.OnlineServices.Result.Success)
                                      {
                                          print("ConfigureConnectExpirationCallback :: StartConnectLoginWithLoginCallbackInfo::login with Epic Account Success, ProductUserId [" + retryConnectLoginCallbackInfo.LocalUserId.ToString() + "]");
                                      }
                                      else
                                      {
                                          print("ConfigureConnectExpirationCallback ::StartConnectLoginWithLoginCallbackInfo::Failed to login with Epic Account [" + retryConnectLoginCallbackInfo.ResultCode + "]");
                                      }
                                  });
                              });
                          }
                      });
                  });

                  s_notifyConnectAuthExpirationCallbackHandle = new NotifyEventHandle(callbackHandle, (ulong handle) =>
                  {
                      GetEOSConnectInterface()?.RemoveNotifyAuthExpiration(handle);
                  });
              }
          }

Thanks!

**Comment by paulhazen** [comment]
Hi @GalBorSan, 

Thank you for sharing your findings with us! It's great to hear that you've found a workaround by using `StartConnectLoginWithEpicAccount` directly, and it's working for you. Your initiative in resolving this issue is really appreciated, and your solution could be valuable to others facing a similar challenge.

To ensure that everything is running smoothly on your end, could you confirm if this approach has completely resolved the issue for you, or are there any other aspects that you're still experiencing difficulties with? We want to make sure that all potential problems are addressed, and your feedback is crucial for that.

Thanks again for your proactive approach!

**Comment by GalBorSan** [comment]
Hello again,

For now everything is working correctly.

Thanks for your support!
