### ISSUE TITLE
Exception: Epic Online Services didn't init correctly: InvalidParameters

### ISSUE THREAD

**Issue by sheenvankhorosan** [PlayEveryWare/eos_plugin_for_unity#499]
**Describe the bug**
I'm having an issue with the examples... AFAIK i've correctly set up the config editor... but still dealing with this issue. 

Exception: Epic Online Services didn't init correctly: InvalidParameters
```
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) (at Library/PackageCache/com.playeveryware.eos@df7dc4a38cb8/Runtime/Core/EOSManager.cs:657)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) (at Library/PackageCache/com.playeveryware.eos@df7dc4a38cb8/Runtime/Core/EOSManager.cs:520)
PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager.Awake () (at Assets/Samples/Epic Online Services Plugin for Unity/3.0.3/Standard Pack _ EOS Plugin for Unity Samples/Scripts/Core/EOSHostManager.cs:49)
```

![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/4756613/a52db608-422b-4a14-ad9b-379b9f298f9b)

 - OS: Windows
 - Editor 
 - Unity Version: 2021.3.8f1
 - Plugin Version: 3.0.3

**Additional context**
Additionally, I get an error for a nullreference relating to the friendsui but assume this is related.

**Comment by paulhazen** [comment]
Hi @sheenvankhorosan, sorry it took us so long to get back to you. I'm sure the holiday season was a contributing factor, but we should have probably at least touched base with you.

This error happens a lot when the options set in `Tools` -> `EOS Plugin` -> `Dev Portal Configuration` are either incorrect or have not been saved. The following is a screenshot of what that window should look like when freshly checked out of the repository:

<img width="478" alt="image" src="https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/1439891/9235b084-eaee-4502-bda7-6ef39f033561">


Can you confirm yours looks the same? If so, try hitting `Save All Changes` even if you haven't saved anything, then try running the samples again.

**Comment by sheenvankhorosan** [comment]
Yes, I've doubled & tripled check. 
Perhaps the encryption key is incorrect? what i've done is added the client id & client secret then hit generate to create that key. I'm assuming the 1s there are for example...

**Comment by sheenvankhorosan** [comment]
Also, I am using the peer2peer client policy. Is that an issue?

**Comment by sheenvankhorosan** [comment]
Is there anything else I can do to give you more information?

**Comment by paulhazen** [comment]
I'm not aware of any reason that the use of peer2peer would be causing that. 

Could you place breakpoints at the following spots in `EOSManager.cs`, and share with me what the value of `initResult` is for the first one, and what the value of `secondTryResult` is for the second one?

<img width="791" alt="image" src="https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/1439891/0d8fa13c-bf52-4345-b693-87df3d8dcf35">
