### ISSUE TITLE
Release date of the v1.0.2

### ISSUE THREAD

**Issue by azokal** [PlayEveryWare/eos_plugin_for_unity#51]
Hello,
I see on the development branch the change for the v1.0.2 release.
In this version you add the support of macOS.
When do you think, it will be release ?
Thanks for your great work.

**Comment by domlaurenti** [comment]
Apologies but we can't be specific about release dates, we can only say that the plugin currently officially supports PC only. I'd keep an eye on the roadmap here for specific support items and release dates: https://trello.com/b/rLvzFJfE/eos-public-roadmap
