### ISSUE TITLE
Using EOS Voice as an Audio Source (LocalRTCOptions) on Create/Join Lobbies

### ISSUE THREAD

**Issue by dvd900** [PlayEveryWare/eos_plugin_for_unity#512]
**Is your feature request related to a problem? Please describe.**
I need to be able to use the rtc audio buffer in an audio source to utilize unity's audio processing (think spatial audio). This works fine using the [Notify Before Render Callback](https://dev.epicgames.com/docs/en-US/api-ref/functions/eos-rtc-audio-add-notify-audio-before-render). However, without passing in LocalRTCOptions to EOS SDK, The RTC audio gets played directly to my output device, as well as giving me a buffer in the callback mentioned above.

**Describe the solution you'd like**
I want be able to pass in EOS_Lobby_LocalRTCOptions into the create/join lobby calls so that I can set the flag [UseManualAudioOutput](https://dev.epicgames.com/docs/api-ref/structs/eos-lobby-local-rtc-options) to true. This prevents the audio from rendering twice, once from my audio source, once directly to my output device.  

**Describe alternatives you've considered**
The create/join functions have a purposely trim interface but I'd like to use this feature without modifying the library. So I can stay up to date without having to reimplement the feature each release. I've considered writing an extension class, but that doesn't give me access to the private variables I need. 

EDIT: Previously I had assumed the feature was not working as intended because of platform issues, sorry about that.

**Comment by arthur740212** [comment]
https://github.com/PlayEveryWare/eos_plugin_for_unity/pull/513

Hello, here is a PR attempting to allow more control over local RTC options.
We would like to invite you to review this feature, and please let us know if it solves your problem. :D

**Comment by virtualboys** [comment]
It does not fully, as you also need to be able to set LocalRTC options when joining a lobby as well. Created a PR #514 solving this by overloading CreateLobby and JoinLobby. Considered extending the Lobby class but thought this was not the right way as these options are not properties of the lobby itself but rather local options.

**Comment by arthur740212** [comment]
Hi, I changed the PR a bit, and added notes on how to use custom rtc options.
Let us know if it tackles your problem.
This change doesn't change the plugin code to much, and you would not need to manually change code every update.
https://github.com/PlayEveryWare/eos_plugin_for_unity/pull/513

**Comment by virtualboys** [comment]
Yup this looks great!
