### ISSUE TITLE
Estimate for Android and IOS support?

### ISSUE THREAD

**Issue by jobo22** [PlayEveryWare/eos_plugin_for_unity#52]
Hi, do you guys have an estimate for when you will have android and IOS support? I'm currently using the C# SDK, but it's not working on android for arm64 builds.

**Comment by iamsince1998** [comment]
Please give us any Idea 😕

**Comment by kenofori** [comment]
@iamsince1998 unfortunately they dont seem to care about responding to issues here, its better to raise voice in official forums

**Comment by jobo22** [comment]
> @iamsince1998 unfortunately they dont seem to care about responding to issues here, its better to raise voice in official forums

Yeah I asked about the problem of not being able to build on arm64 on the official Epic dev support forums and they have responded there. They asked for my project so I sent it to them, hopefully they can reproduce it and figure out the problem!

**Comment by domlaurenti** [comment]
Apologies but we can't be specific about release dates at this time, we can only say that the plugin currently officially supports PC only. I'd keep an eye on the roadmap here for specific support items and release dates: https://trello.com/b/rLvzFJfE/eos-public-roadmap
