### ISSUE TITLE
Having issues with member inconsistency and lobby backend attributes missing from client.

### ISSUE THREAD

**Issue by Satiriano** [PlayEveryWare/eos_plugin_for_unity#520]
I am having issues with getting warnings from EOS backend, but I don't know what I'm doing wrong. I tried my best to follow all practises presented in samples, but I keep getting warnings like:

```
LogEOSLobby(Warning): Lobby backend has attributes missing from client
LogEOSLobby(Warning): Lobby membership count inconsistency
```

I wish there was a way to find where the problem is, what I'm doing wrong, if anything. If those warnings are potentially something harmful. Usually the warnings appear the moment I start/leave/join or even search for a lobby. The member inconsistency is kinda weird as it does show player count correctly as far as I can see. 

Lobby backend attributes missing from client I really have no clue what that is about.

**Comment by paulhazen** [comment]
@Satiriano Warnings are only meant to indicate a possible problem, so they do not indicate something broken, just that something *might* be broken. That said, it doesn't seem like you should be getting those warnings, so it's worth investigating. Can you give me some more details about where this is happening? A call stack indicating where the warning is being thrown from would be helpful.

**Comment by paulhazen** [comment]
@Satiriano, are you still experiencing this warning? If so please feel free to re-open this issue. Until we have more details we are going to close this issue for the time being.
