### ISSUE TITLE
Win32 Exception

### ISSUE THREAD

**Issue by Miguelfanclub** [PlayEveryWare/eos_plugin_for_unity#522]
After correctly configuring the Dev Portal options and login in the dev auth tool, i get this error any time I Play any of the scenes:

Win32Exception: Searched in : D:/Projects/eos_plugin_for_unity-stable/Assets\Plugins
DLLHandle.LoadDynamicLibrary (System.String libraryName) (at Assets/Plugins/Source/Core/DLLHandle.cs:190)

**Comment by andrew-hirata-playeveryware** [comment]
Hello @Miguelfanclub 
How did you install the plugin? Sometimes that kind of error can occur from just cloning the repo without git-lfs installed, as the default windows libraries won't be fetched without git-lfs. 

It's generally recommended to install via the [upm package](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/docs/add_plugin.md#adding-the-package-from-a-tarball) if you don't wish to install git-lfs. Installation this way will also provide you with prebuilt libraries, removing the need to rebuild all the native code.

**Comment by paulhazen** [comment]
Hi @Miguelfanclub, I'm going to close this issue due to inactivity. If (after determining that proper use of `git-lfs` is not to blame for the Win32 exception) you are still experiencing this issue, please feel free to reach out and re-open this issue.
