### ISSUE TITLE
NULL EOS Platform returned by native code: issue probably occurred in GFX Plugin!

### ISSUE THREAD

**Issue by DjPls** [PlayEveryWare/eos_plugin_for_unity#528]
I'm integrating EOS into a project and running into an issue with standalone builds. Everything works fine inside the editor, but running a standalone Win64 build results in the following Exception being thrown from inside 

`EOSSingleton.GetEOSPlatformInterface()`:

`NULL EOS Platform returned by native code: issue probably occurred in GFX Plugin!`

We have a somewhat complex build pipeline and have modified `EOSManager.Awake()` to suit our needs for conditional initialisation of the EOS platform (we don't always want it). That said, `EOSManager.Instance.Init` is still called from Awake at roughly the same time as it would otherwise.
As mentioned before, EOS and all its subsystems perform well inside the editor, it is only in Standalone that it presents a problem.

I'm trying to understand why the platform might fail to initialise, or any steps I can take to get more info to help narrow it down. 

Some threads suggest vc_redist installs but I'd have expected an exception inside the gfx plugin itself.
[This](https://dev.epicgames.com/docs/epic-online-services/eos-get-started/working-with-the-eos-sdk/eos-overlay-overview#general-integration-requirements) suggests the EOS SDK needs to run before the gfx context is created, but that seems at odds with initialising the platform from Awake. Is there an earlier Init that happens somewhere in standalone? The error presents whether running EOSBootstrapper.exe or the standalone.exe directly.

 - Plugin Version 3.0.1

**Comment by paulhazen** [comment]
Hi @DjPls, there are a few reasons this might be happening. To start with, can you clarify which method you are using to incorporate the plugin into your project (are you using a release upm?).

Also, if you could tell us what version of Unity you are using, as well as your OS those pieces of information will be helpful.

**Comment by DjPls** [comment]
Hi Paul,
Thanks for giving your advice on this matter.

Scripting defines was an interesting thought but I was unable to find a clear culprit. I thought it could be `UNITY_64` and `UNITY_EDITOR_64` as they are undocumented in Unity 2018, but the defines are active in the Editor solution. I stopped short of testing in standalone.

As a side note, I noticed `PLATFORM_64BITS` and its 32 bit counterpart are referenced in conditionals inside Config.cs and the <platform>binding.cs files even though those defines are never defined in those files files.

The configuration of the plugin is unchanged, There has been some build pipeline traffic, and further implementation of features/interfaces, but nothing to do with the initialisation of the plugin.

On further investigation I noticed this line in the log:
> NativePlugin (WARNING): Failed to load a valid json config for EOS
I originally grouped it with the info/warning about not finding the `EOSGenerated.dll`, of which I established its generation was commented out in the plugin code and therefore expected. However failing to parse the JSON would suggest it doesn't have a config to launch with, and therefore fails to init the platform. I may need to look into the EOS SDK docs/source in the morning to see why the config file is considered invalid.

**Comment by paulhazen** [comment]
> Edit 2: I've established the root of the issue. The path of the JSON config file is established incorrectly by the NativePlugin. It defines path as `<location of GfxPluginNativeRender-x64.dll + ..\.. + StreamingAssets\EOS\` instead of `<exe_root>\ProjectWin64_Data\StreamingAssets\EOS\`. In our case the dll is sat in ProjectWin64_Data\Plugins. which results in the path being resolved to `<exe_root>\StreamingAssets\EOS\`; up one directory too many.

This is great info, thank you.

> In the short term I can get around this by doing a post-build copy of the JSON config to the path it looks for. It would be great if the plugin reported the config path prior to failure, and ideally it would build the path for StreamingAssets based on the built Unity project structure, instead of where the plugin is running from.

Excellent that you've found a work-around, and I completely agree with you both on the need for it to report the path, and for the path to be correctly constructed. I'll look into this today and see if I can get a PR up. 

Just so you are aware, it may take some time for that change to propagate through our `development` branch and into our `stable` branch and subsequent UPM releases.

> As a side note, I noticed `PLATFORM_64BITS` and its 32 bit counterpart are referenced in conditionals inside Config.cs and the binding.cs files even though those defines are never defined in those files.

I'll look into these as well, but as those source files are provided by Epic, we try to keep them as un-touched as possible as a practice. 

Once I have the PR introduced, and it gets merged, I will close out this issue and mark it as `unresolved` until the solution makes its way into `stable` and subsequent releases.

Thank you so much for being such a rockstar about sharing your thought process, diagnoses, and conclusions!

**Comment by DjPls** [comment]
Hi @paulhazen,

> This is great info, thank you. Which file in particular has the path improperly assigned?

`EpicOnlineServicesConfig.json`. Its path is constructed [here](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/stable/lib/NativeCode/DynamicLibraryLoaderHelper/NativeRender/dllmain.cpp#L1044).

> Excellent that you've found a work-around, and I completely agree with you both on the need for it to report the path, and for the path to be correctly constructed. I'll look into this today and see if I can get a PR up.
> 
> Just so you are aware, it may take some time for that change to propagate through our `development` branch and into our `stable` branch and subsequent UPM releases.

Great news, I appreciate pushing for a PR. And of course no problem on the turn-around. While having the post-build copy of the files is perhaps not the most elegant, it's a cheap easy solution that does the job just fine.

I'd been wondering why this is a problem in our project and not for anyone else. Best I can tell, it's a change Unity made to their Plugins output.
Creating a build in our Unity 2018 has the plugins in the build output under
`BuildRoot\UnityGame_Data\Plugins\*.dll`, while building the same project in Unity 2020 results in 
`BuildRoot\UnityGame_Data\Plugins\x86_64\*.dll` as the plugin root. One extra folder deep.

> I'll look into these as well, but as those source files are provided by Epic, we try to keep them as un-touched as possible as a practice.

Ah gotcha - I'd ignore them in that case. The defines aren't causing any problems apart from being a red herring in my search.

> Once I have the PR introduced, and it gets merged, I will close out this issue and mark it as `unresolved` until the solution makes its way into `stable` and subsequent releases.
> Thank you so much for being such a rockstar about sharing your thought process, diagnoses, and conclusions!

Great! And thank you for your assistance in the matter!
