### ISSUE TITLE
Error from adding package via Git URL

### ISSUE THREAD

**Issue by cjaligaga** [PlayEveryWare/eos_plugin_for_unity#529]
Adding the package via Git URL logs the error:

> [Package Manager Window] Error adding package: git@github.com:PlayEveryWare/eos_plugin_for_unity_upm.git.
> Unable to add package [git@github.com:PlayEveryWare/eos_plugin_for_unity_upm.git]:
>   Error when executing git command. Host key verification failed.
>   fatal: Could not read from remote repository.
> 
>   Please make sure you have the correct access rights
>   and the repository exists.

**Comment by arthur740212** [comment]
Thanks for the report.
Try this link `https://github.com/PlayEveryWare/eos_plugin_for_unity_upm.git` instead.

**Comment by cjaligaga** [comment]
Thank you, the HTTPS version worked.
