### ISSUE TITLE
Reauthorization via steam session ticket

### ISSUE THREAD

**Issue by nitrocss** [PlayEveryWare/eos_plugin_for_unity#530]
Hi, I'm looking for a bit of assistance trying to squash issues that I'm having now that I'm closer to game release. I'm sure most of the things I encounter is me doing something in a wrong way / wrong order. But it's very difficult for me to debug these things by myself, especially if they fail only sometimes, and need an hour or two to test like reauthorization. It's a difficult issue and I appreciate any help.

I'm using session ticket from steam to prevent logging off, I tested it once before due to it being hard to test, and it worked. Today I tested it during public playtest and it failed. 

Here's log:

```
Using Continuance Token to prevent logging off.
Starting to connect to EOS SDK using steam ticket
2024-02-09T10:42:24.5670226+01:00 LogEOS(Warning): Error response received from backend. ServiceName=[EOSAuth], OperationName=[TokenGrant], Url=[<Redacted>], HttpStatus=[401], ErrorCode=[errors.com.epicgames.eos.auth.external.invalid_token], NumericErrorCode=[110013], ErrorMessage=[Invalid session ticket], CorrId=[EOS-GRHXcDDIn0WswzaUCQPI_Q-SpZRMQcs5Uei9j1rF-2ftA]
```

after a while (takes some seconds to get disconnected)

```
Lobbies (OnRTCRoomConnectionChangedReceived): connection status changed. LobbyId=975209baad0a4789a67ea8c4d745d856, IsConnected=False, DisconnectReason=Success
2024-02-09T10:43:24.2420995+01:00 LogEOSP2P(Warning): Attempted to send a packet with a LocalUserId that did not validate correctly. LocalUserId=[000...711] RemoteUserId=[000...13c] SocketId=[EOSP2PTransport] Result=[EOS_InvalidAuth]
EOSTransportManager.SendPacket: Unable to send 60 byte packet to RemoteUserId '00025aa1b9434d2cb62880728ff1213c' - Error result, InvalidAuth.
2024-02-09T10:43:24.2426085+01:00 LogEOSP2P(Warning): Attempted to get next received packet size with a LocalUserId that did not validate correctly. LocalUserId=[000...711] Result=[EOS_InvalidAuth]
2024-02-09T10:43:24.3059590+01:00 LogEOSP2P(Warning): Attempted to get next received packet size with a LocalUserId that did not validate correctly. LocalUserId=[000...711] Result=[EOS_InvalidAuth]
```

Here's the code I use for logging in and reauthorizing.

```csharp
    private void ConfigureConnectExpirationCallback()
    {
        if (NotifyConnectAuthExpirationCallbackHandle == null)
        {
            var EOSConnectInterface = EOSManager.Instance.GetEOSConnectInterface();
            var addNotifyAuthExpirationOptions = new Epic.OnlineServices.Connect.AddNotifyAuthExpirationOptions();
            ulong callbackHandle = EOSConnectInterface.AddNotifyAuthExpiration(ref addNotifyAuthExpirationOptions, null, (ref Epic.OnlineServices.Connect.AuthExpirationCallbackInfo callbackInfo) =>
            {
                Debug.LogError("Using Continuance Token to prevent logging off.");
                StartConnectLoginWithSteamSessionTicket(ConnectLoginTokenCallback);
            });

            NotifyConnectAuthExpirationCallbackHandle = new NotifyEventHandle(callbackHandle, (ulong handle) => { EOSManager.Instance.GetEOSConnectInterface()?.RemoveNotifyAuthExpiration(handle); });
        }
    }
```

```csharp
    public void StartConnectLoginWithSteamSessionTicket(EOSManager.OnConnectLoginCallback onLoginCallback)
    {
        Debug.LogError("Starting to connect to EOS SDK using steam ticket");
        var sessionTicketString = System.BitConverter.ToString(SteamUser.GetAuthSessionTicket().Data).Replace("-", "");
        string steamToken = sessionTicketString;
        EOSManager.Instance.StartConnectLoginWithOptions(Epic.OnlineServices.ExternalCredentialType.SteamSessionTicket, steamToken, onloginCallback: onLoginCallback);
    }
```

Looking at the log it seems that I received "ErrorMessage=[Invalid session ticket]" from EOS, but why would that happen? How could the ticket be invalid if it was just grabbed, and how could I prevent this from happening in the future?

It's worth noting that I use (the same) "StartConnectLoginWithSteamSessionTicket" to login into EOS after launching the game.
It's also worth noting that I have a button that calls exactly the same function. I clicked it after failing to connect, and it logged me in successfully this time.

EOS 3.0.3 plugin version
Unity 2022.3.12f1
OS: Windows 10
Netcode GO 1.7.1 (version is not related to this issue)

**Comment by paulhazen** [comment]
> It's worth noting that I use (the same) "StartConnectLoginWithSteamSessionTicket" to login into EOS after launching the game. It's also worth noting that I have a button that calls exactly the same function. I clicked it after failing to connect, and it logged me in successfully this time.

Does the button always work? As in, re-authorization fails, but if you manually initiate the process, it functions as expected?

**Comment by paulhazen** [comment]
@nitrocss Is this still an issue you are experiencing? If so, are you able to provide reproduction steps? We haven't had much luck replicated the issue on our end.

**Comment by secondimpactrob** [comment]
@nitrocss fyi this looks to be the same as this issue:

https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/582

Which is fixed by adding a short delay between getting the steam ticket and using it.
