### ISSUE TITLE
First launch per steam account fails to connect to EOS service (always).

### ISSUE THREAD

**Issue by nitrocss** [PlayEveryWare/eos_plugin_for_unity#531]
Hey, I apologize for creating another issue, but I've decided it's better to keep them separate, because I don't know if there is a connection or not.

Anyhow, it seems I've discovered something new that I haven't had before. 
Whenever a player launches my game for the first time (which explains why I wasn't able to catch this before), the EOS fails to connect using steam session ticket. Now what makes this even more strange, is that it only happens during the first launch. I've tested this on 3+ PCs and multiple steam accounts, and I couldn't find a way to reproduce this again after it happens. Not on the same account.

The error that gets thrown is 
`2024-02-09T17:05:31.8309473+01:00 LogEOS(Warning): Error response received from backend. ServiceName=[EOSAuth], OperationName=[TokenGrant], Url=[<Redacted>], HttpStatus=[404], ErrorCode=[errors.com.epicgames.eos.auth.user_not_found], NumericErrorCode=[110016], ErrorMessage=[EOS User Identity not found. identityProviderId: steam accountId: 765611...9], CorrId=[EOS-S5GcrWurVEmgjy-3bUH4UQ-hhHeLDMtOkSmKV91tv_Jmg]
connectLoginCallbackInfo Result = InvalidUser`

I've closed the game more than a hundred times and reopened it, and I wasn't able to reproduce this. I wasn't able to reproduce it even after reinstalling the game or deleting playerprefs. I was only able to reproduce after switching account to another one. I was able to reproduce on two other PCs after launching the game.

I know it's a long shot that anybody will be able to help me with this without a clear repro or fresh project, but I've decided to post anyway because I'm desparate, and those are the only two issues I experience as of right now.

All relevant code to the setup is below.

```csharp
  private IEnumerator Start()
    {
        UserInfoManager = EOSManager.Instance.GetOrCreateManager<EOSUserInfoManager>();
        LobbyManager = EOSManager.Instance.GetOrCreateManager<EOSLobbyManager>();

        VoipAction.action.Enable();
        NetworkManager.Singleton.OnClientDisconnectCallback += OnClientDisconnectCallback;
        yield return null;
        LobbyManager.AddNotifyLobbyChange(OnLobbyChanged);
        yield return null;
        yield return TryConnectEpicServicesCoroutine();
     }
```

```csharp
 public IEnumerator TryConnectEpicServicesCoroutine()
    {
        var connectInterface = EOSManager.Instance.GetEOSPlatformInterface().GetConnectInterface();
        Debug.LogError("TryConnectEpicServicesCoroutine: Trying to connect to Epic Games Server");
        try
        {
            StartConnectLoginWithSteamSessionTicket(ConnectLoginTokenCallback);
        }
        catch (Exception e)
        {
            Debug.LogError("EXCEPTION: Failed to connect to Epic Games Server: " + e.Message + " " + e.StackTrace);
        }

        var time = 0f;
        while (time < 5f)
        {
            if (connectInterface.GetLoggedInUsersCount() != 0)
            {
                yield break;
            }

            time += Time.deltaTime;
            yield return null;
        }
    }
```

```csharp
    public void StartConnectLoginWithSteamSessionTicket(EOSManager.OnConnectLoginCallback onLoginCallback)
    {
        Debug.LogError("Starting to connect to EOS SDK using steam ticket");
        var sessionTicketString = System.BitConverter.ToString(SteamUser.GetAuthSessionTicket().Data).Replace("-", "");
        string steamToken = sessionTicketString;
        EOSManager.Instance.StartConnectLoginWithOptions(Epic.OnlineServices.ExternalCredentialType.SteamSessionTicket, steamToken, onloginCallback: onLoginCallback);
    }
```
Below is the TokenCallback that I've partially copied from your samples. This is the first time I have been met with "Result.InvalidUser", that I know of, so I didn't really get to changing this part of the code yet. I'd like to also ask what this code does, because I'm confused. It seems to create a new Connect User with continuance token, but I don't know what that means exactly.

```csharp
    private void ConnectLoginTokenCallback(Epic.OnlineServices.Connect.LoginCallbackInfo connectLoginCallbackInfo)
    {
        if (connectLoginCallbackInfo.ResultCode == Result.Success)
        {
            Debug.LogError("Login TO SDK Successful. [" + connectLoginCallbackInfo.ResultCode + "]");
            StartCoroutine(OnConnectedToEOSSDKCoroutine());
            ConfigureConnectExpirationCallback();
        }
        else if (connectLoginCallbackInfo.ResultCode == Result.InvalidUser)
        {
            // ask user if they want to connect; sample assumes they do
            Debug.LogError("connectLoginCallbackInfo Result = InvalidUser");
            EOSManager.Instance.CreateConnectUserWithContinuanceToken(connectLoginCallbackInfo.ContinuanceToken, (Epic.OnlineServices.Connect.CreateUserCallbackInfo createUserCallbackInfo) =>
            {
                print("Creating new connect user");
                if (createUserCallbackInfo.ResultCode == Result.Success)
                {
                    //    ConfigureUIForLogout();
                    Debug.Log("Login Successful");
                }
                else
                {
                    Debug.Log("Login Unsuccessful");
                    //     ConfigureUIForLogin();
                }
            });
        }
        else
        {
            Debug.LogError("Login Unsuccessful. [" + connectLoginCallbackInfo.ResultCode + "]");
            Debug.LogError("Retrying...");
             // retry code here, not implemented yet
            //  ConfigureUIForLogin();
        }
    }
```

My theory (and I have no idea what I'm doing) is that I might be lacking some code that creates a 'connect user'. Once EOS gives me Result.InvalidUser when I try to connect using steam session ticket, in the callback, I create a connect user because of the code I blatantly copied without understanding from your sample. And then the issue is resolved, but I'm not sure how this works or why. I'm still not sure why you only seem to need to create a 'connect user' once, does it save the data somewhere on the drive? Or am I just completely off here?

Full log below:
[Player.log](https://github.com/PlayEveryWare/eos_plugin_for_unity/files/14224343/Player.log)

EOS 3.0.3 plugin version
Unity 2022.3.12f1
OS: Windows 10
Netcode GO 1.7.1 (version is not related to this issue)

Thank you for your continuous help.

**Comment by paulhazen** [comment]
> Hey, I apologize for creating another issue

Nothing to apologize for @nitrocss.

Helps us make the plugin better and better - plus I usually learn something along the way 😄 

I'll look into this and the other issue first thing at the start of next week.

**Comment by Kenny5** [comment]
We came across this issue too.
If you look at the managing user flow from the epic documentation (https://dev.epicgames.com/docs/game-services/eos-connect-interface#managing-users) you'll see that if the user does not exist, the login API returns a EOS_InvalidUser result along with a EOS_ContinuanceToken. The token provides details about the login attempt and is required during the next steps in the login flow.

We fixed is by adding a call to  EOSManager.Instance.CreateConnectUserWithContinuanceToken in our  ConnectLoginCallback.

For Example:

`
if (connectLoginCallbackInfo.ResultCode == Result.InvalidUser)
{
    //Invalid user so create one with the connect ContinuanceToken
    EOSManager.Instance.CreateConnectUserWithContinuanceToken(connectLoginCallbackInfo.ContinuanceToken, createUserCallbackInfo => { 
            //REDACTED
        }
    });
}else{
    Debug.LogError($"Connect Login Failed.  [{connectLoginCallbackInfo.ResultCode}]");
}
`

(apologies for formatting!)

**Comment by paulhazen** [comment]
@nitrocss I'm going to close this issue and mark it as `pending`, which is how we track issues for which a work-around has been provided and a change has been introduced to the `development` branch, but has not yet made it into `stable` or filtered into our releases. Thanks again to @Kenny5 for providing such a clear overview of the problem and how to resolve it.
