### ISSUE TITLE
Error after importing EOS tarball in Unity on MAC. 

### ISSUE THREAD

**Issue by LightfootBros** [PlayEveryWare/eos_plugin_for_unity#543]
Error after importing EOS tarball in Unity on MAC. 

I am getting the below error, anyone got a clue how to sort please? THANKS
Library/PackageCache/com.playeveryware.eos@a25df34b1831-1707981599563/Editor/EpicOnlineServicesConfigEditor.cs(621,60): error CS1503: Argument 1: cannot convert from 'string' to 'char'

**Comment by arthur740212** [comment]
You might be using a different version of .NET.

On the line `var versionParts = steamworksVersion.Split(".");`
Changing `(".")` into `('.')`, this should be compatible with your version of .NET.

**Comment by LightfootBros** [comment]
Awesome thank you!
