### ISSUE TITLE
How to build for android ?

### ISSUE THREAD

**Issue by Daniyal-Ibrahim** [PlayEveryWare/eos_plugin_for_unity#55]
I am  trying to make a build for android using the latest dev branch, but the build is failing with the following errors.
![image](https://user-images.githubusercontent.com/41608096/159228313-e6dbbc6d-a703-4c25-880a-e4b9ca0a415c.png)
![image](https://user-images.githubusercontent.com/41608096/159228378-0b04c48b-bc45-425e-be85-b2402957dc16.png)

**Comment by jobo22** [comment]
I get that same error when I just try to go into playmode haha. And also get build errors when trying to build for android.

**Comment by acolean-pew** [comment]
Hello,

Apologies but currently the EOS Plugin for Unity does not fully support Android builds. We are looking to implement Android support in the future and our list of currently supported platforms can be found here: [https://eospluginforunity.playeveryware.com](https://eospluginforunity.playeveryware.com)
