### ISSUE TITLE
UnreliableUnordered reliability is resending packets when more than one client is connected to you

### ISSUE THREAD

**Issue by miguel-ferradans-coherence** [PlayEveryWare/eos_plugin_for_unity#551]
**Describe the bug**
We have a setup where we have a host that is listening for connection requests.

If more than one client connects to the host, there are situations where the EOS plugin is resending packets even though the reliability is set to UnreliableUnordered, changing reliability doesn't seem to have any effect. The packets that we are sending have a sequence id, and the behaviour that we observe is that Epic is constantly resending packets with the same sequence id, which causes a lot of artificial latency.

This is easily reproducible by lowering the framerate of the host, although is not the only trigger, since we've managed to reproduced it without low framerates.

**To Reproduce**
1. Set up two connections, with different clients, to the same host with UnreliableUnordered
2. Send packets from the host to both clients with a sequence id
3. Lower framerate of the host
4. Watch how Epic is resending packets with the same sequence id

Repro rate: Almost 100% whilst lowering framerate of host, around 30% without lowering framerate

**Expected behavior**
When i'm sending packets with UnreliableUnordered reliability, Epic should only send the packet once.

**Desktop (please complete the following information):**
 - OS: Windows/macOS/Linux
 - Both editor and standalone build
 - Unity Version: 2021.3.33f
 - Plugin Version: 3.0.3

**Additional context**
Forcing relay usage or p2p connections doesn't seem to matter, the issue is reproducible with both

**Comment by andrew-hirata-playeveryware** [comment]
Hello @miguel-ferradans-coherence,

I apologize for the late reply; that is entirely an oversight on my part.

But to the issue at hand:
Is this issue happening when directly using the EOS SDK APIs, or only when using the EOSTransport?
If it is happening when directly using the EOS SDK APIs in P2PInterface, that could be a bug in the EOS SDK itself, which we don't directly control.

**Comment by paulhazen** [comment]
Hi @miguel-ferradans-coherence, just to follow-up, are you still experiencing this issue?

**Comment by miguel-ferradans-coherence** [comment]
We stopped using the plugin due to this issue and several Editor crashes on the native library.

The issue was in the P2PInterface so the it feels like is on the EOS SDK itself like @andrew-hirata-playeveryware said, but we didn't look into it further.

**Comment by andrew-hirata-playeveryware** [comment]
@miguel-ferradans-coherence; Have you posted about this on Epic's forums for the EOS SDK? They have discussion board that might help: https://eoshelp.epicgames.com/s/discussions
