### ISSUE TITLE
"eac_launcher" app not opening

### ISSUE THREAD

**Issue by The-RealBobi** [PlayEveryWare/eos_plugin_for_unity#554]
**Describe the bug**
Whenever I make a build in MacOS, and launch my game using the provided "eac_launcher" app, I'm always greeted by a "The application eac_launcher can't be opened" error.

**To Reproduce**

Make a build with EAC and launch your game with the "eac_launcher" app.

**Expected behavior**
To have my game launched.

**Desktop (please complete the following information):**
 - OS: MacOS ARM Sonoma 14.2.1
 - Standalone build
 - 2022.3.17f1
 - Plugin Version 3.0.2

**Additional context**
This issue doesn't happen if I use the "start_protected_game" app provided with the EOS SDK, executing that app launches the game perfectly fine, with EOS and EAC.

**Comment by arthur740212** [comment]
Did you have Epic Launcher installed on the Mac device?

**Comment by The-RealBobi** [comment]
> Did you have Epic Launcher installed on the Mac device?

Hi, yes. Epic Games Launcher is installed.

**Comment by arthur740212** [comment]
That might indicate our EAC implementation for Mac has something missing. 
We'll take a closer look on how EAC is set up for Mac.

**Comment by arthur740212** [comment]
Have you enabled `use EAC` in `Edit -> Preferences -> EOS Plugin`.
The EAC related configurations might need to be filled as well for `eac_launcher.app` to work.

**Comment by The-RealBobi** [comment]
> Have you enabled `use EAC` in `Edit -> Preferences -> EOS Plugin`.
> The EAC related configurations might need to be filled as well for `eac_launcher.app` to work.

Hello, yes, the "Use EAC" option is checked, and all the paths are filled correctly.

**Comment by arthur740212** [comment]
Hello, we found out that the permission flags for the EACLauncher have some interesting behavior on Windows, which is the platform we mainly build with, causing the upm repo to have missing info.

Quick fix is to run the command `chmod +x eac_launcher` (preferably on the launcher in the package, as modifying the one in the build might be considered violation by the anti cheat detection), this will allow the user to execute the file.

We will look for a more elaborate way to fix this issue in following releases. Thanks for the report.

**Comment by paulhazen** [comment]
Closing this issue as it has been resolved in the `development` branch.
