### ISSUE TITLE
Player Data Storage Encryption Key Not Set

### ISSUE THREAD

**Issue by TheSLAP** [PlayEveryWare/eos_plugin_for_unity#56]
I'm having the following error when using the demo scene and my own scene.

"[EOS SDK] Player data storage: could not upload file: PlayerDataStorageEncryptionKeyNotSet"

I've set up the encryption key to a 256-bit hex string as well as a 128-bit hey string and neither seem to work. Do we need to initialize this key somewhere else in the code?

**Comment by KesKim** [comment]
Just trying to figure out this stuff myself here, so no guarantees I have this correct...

On Unreal (yeah, I know) documentation, it says the following about "Encryption Key":
> Encryption Key: When you upload data to an EOS service, this 64-byte hexadecimal string is used to encrypt it. Unlike other settings, EOS does not manage this Encryption Key and it is not stored in your product settings. The key is unique to your game and not known to Epic Games, to protect users' data privacy.

So, a 64-byte hexadecimal string is what you need: no hyphens between hex pairs and hex values always in "X2" string format (so "0A" etc. should never be shorthanded to "A").

**Comment by pew-dahs** [comment]
You need to set a 64 character hexadecimal string under Tools > EpicOnlineServicesConfigEditor, and click save all changes to save it to the config file. Then restart the demo and it'll load the new string. The string is any 64 character hex string, so you could put 64 9's as the string and it'll work (though you should use something more secure).

**Comment by TheSLAP** [comment]
> You need to set a 64 character hexadecimal string under Tools > EpicOnlineServicesConfigEditor, and click save all changes to save it to the config file. Then restart the demo and it'll load the new string. The string is any 64 character hex string, so you could put 64 9's as the string and it'll work (though you should use something more secure).

Thank you for your help. I swear that I had tested a 256-bit hex code but perhaps it didn't paste and save properly. It is working now.

I strongly encourage you guys to make a note of the requirements of the key in the error and the config file itself. It is not mentioned anywhere within the plugin that I could find.
