### ISSUE TITLE
Samples, steam account linking, loginCallbackInfo.LocalUserId is null

### ISSUE THREAD

**Issue by hesham-akmal** [PlayEveryWare/eos_plugin_for_unity#576]
I have encountered a null exception and I've fixed it in my project, so I'm sharing the fix.

The error log:
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/22731896/037e8830-c4df-422b-bd47-44171bb1dcd3)

In the sample "Standard Pack : EOS Plugin for Unity Samples", a script named UILoginMenu.cs (I used it as reference for steam login, steam account linking with EOS on the first session).

The method named StartConnectLoginWithLoginCallbackInfo(LoginCallbackInfo loginCallbackInfo), the paramater LoginCallbackInfo is used to get loginCallbackInfo.LocalUserId. 
But in the case of "loginCallbackInfo.ResultCode == Epic.OnlineServices.Result.InvalidUser" (User is linking steam with an active Epic account), the loginCallbackInfo.LocalUserId was null in my case, so I needed to use linkAccountCallbackInfo.LocalUserId instead (callback of AuthLinkExternalAccountWithContinuanceToken).

I changed StartConnectLoginWithLoginCallbackInfo parameter of LoginCallbackInfo to EpicAccountId, and to send the LocalUserId accordingly.

Like so:

![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/22731896/00a4786f-5738-457f-b98f-7c0ed0ae662b)

**Comment by paulhazen** [comment]
Hi @hesham-akmal, apologies for the delayed response. Can you tell me which version of the plugin you are using? Based on your posted code I'm wondering whether you might be using an older version of the plugin. 

In the absence of that possibility, did you perhaps refactor `UILoginMenu.cs`?

**Comment by hesham-akmal** [comment]
@paulhazen no worries! Version is 3.0.3
Sample imported from the unity package manager
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/22731896/ab08965b-a629-4207-ae7e-e4f778000046)

Sorry for the confusion, the above image is after my refactoring and fixes. 

Original UILoginMenu.cs, this is where the issue resides, the loginCallbackInfo.LocalUserId (used in method StartConnectLoginWithLoginCallbackInfo) was null/empty as loginCallbackInfo.ResultCode is Epic.OnlineServices.Result.InvalidUser (line 1330)
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/22731896/a68777b6-846a-4caa-980d-ce79aa5d50e5)

However for some reason I think this was working for me like 6 months ago, not really sure.

**Comment by andrew-hirata-playeveryware** [comment]
Ah I think I see the error with this: The code is using what appears to be the wrong callback for information. It should be using the other callback information. I can probably throw together a little fix for this.

**Comment by paulhazen** [comment]
@hesham-akmal I'm closing this issue as it has been fixed in the `development` branch via pull #626. If you are still having difficulty with it please feel free to re-open the issue with additional context about the problem.

**Comment by paulhazen** [comment]
Re-opening because I realized that the PR (while open) has not been merged.
