### ISSUE TITLE
Missing script in Samples

### ISSUE THREAD

**Issue by dnorambu** [PlayEveryWare/eos_plugin_for_unity#58]
Hi, is it normal to have a missing script in the "EventSystem" Game Object? I followed the installing instructions from this repo (install using git url + samples import). Currently, in every Sample scene, this script is missing. 

![image](https://user-images.githubusercontent.com/65257235/166003424-c4f77d0f-6233-4c47-92dd-730c8a551c6a.png)

Btw, I've been having troubles running this scenes (maybe because of the missing script). When I hit Play, the Game view shows the logs but I'm not able to interact with it e.g. press the "copy logs" button .

**Comment by noahbare** [comment]
I'm not really sure what they were trying to change, but in v1.0.1 in the event system game object, there was an `Event System` and a `Standalone Input Module` component. So I just deleted the missing script component and added back the `Standalone Input Module` component and everything worked as expected.

![image](https://user-images.githubusercontent.com/50649628/166157241-a485397d-cb74-4e2a-9bb9-d54a6da76fef.png)

**Comment by dnorambu** [comment]
Thanks @noahbare , that component was the solution :D
