### ISSUE TITLE
Possible typos in SteamManager edge case?

### ISSUE THREAD

**Issue by secondimpactrob** [PlayEveryWare/eos_plugin_for_unity#581]
Minor things, but in my travels exploring the sample code (while working on our implementation) I believe there may be some accidental typos in edge case code inside the sample SteamManager.cs.

I may be wrong... and even if I'm right, it might be extremely unlikely this code even gets called, but still thought I'd point it out.

1) In RequestAppTicketResponse, where it realises it requires a larger buffer, it's calling CancelAuthTicket.

It would seem this was copy pasted from the similar code related to Auth Tickets, but doesn't appear to be valid in this context.

2) In both RequestAppTicketResponse and GetSessionTicket, where they determine the ticket is too larger for their buffer, they increase their bufferSize int variable, but fail to actually increase the size of the buffer byte array itself.

It would seem to me that both these code paths should have:

buffer = new byte[bufferSize];

Inserted before they retry their 'get'.

**Comment by andrew-hirata-playeveryware** [comment]
Hello @secondimpactrob,
Those are indeed errors: I'll need to read the rest of the code before I make a "real" fix. But thank you so much for reporting those issues!

**Comment by paulhazen** [comment]
@secondimpactrob I'm closing this issue as it has been resolved in the `development` branch via PR #637. Please feel free to re-open with additional context if you are continuing to have problems.

**Comment by paulhazen** [comment]
Re-opening because I realized that while it is open, the PR has not yet been merged.
