### ISSUE TITLE
Steam login fails first time due to timing issue

### ISSUE THREAD

**Issue by secondimpactrob** [PlayEveryWare/eos_plugin_for_unity#582]
In the sample, attempts to login via Steam always fail the first time. The issue appears to be due to timing.

(Seen in both Editor and PC build.)

**Steps to Reproduce**

1) Ensure you have everything set up for testing Steam
2) Run the Auth & Friends sample scene (editor or build)
3) Choose External Auth and click Login
4) This always (for me) comes back with an error from the Epic server:

`LogEOS(Warning): Error response received from backend. ServiceName=[OAuth], OperationName=[TokenGrantv2], Url=[<Redacted>], HttpStatus=[400], ErrorCode=[errors.com.epicgames.account.external_auth_validate_failed], NumericErrorCode=[18063], ErrorMessage=[Failed to verify token for authType: steam_session_ticket and sandboxId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, error: Invalid session ticket]`

5) Note that on clicking Login a second time it now works as expected.

**Possible Cause**

I believe the problem is that the sample does all of the following in immediate succession when you press Login:

1) Initialise Steam
 -> This happens when `SteamManager.Instance` is accessed for first time, inside `OnLoginButtonClick`
2) Request session ticket
 -> Via `SteamUser.GetAuthSessionTicket()`  (in SteamManager's `GetSessionTicket()`)
3) Attempt login with Epic
 -> `EOSManager.Instance.StartLoginWithLoginTypeAndToken()`

I tested out moving some of these steps into Start, to introduce a time gap, and the login started working first time once both steps 1 and 2 were being done in advance.

My theory is that if you ask steam for an auth session ticket and then immediately fire that off to Epic, something on Steam or Epic's servers has not quite had enough time to process it.

I am not sure exactly what sort of time gap is necessary, or if there is a way to query whether it is ready before making the login attempt. (I guess one way to query is by making the login attempt knowing that it might come back with invalid session ticket, but not ideal).

**Comment by andrew-hirata-playeveryware** [comment]
Hello @secondimpactrob,
That is a interesting find! Are you able to make a pull request with your changes so that we can look at them?

**Comment by secondimpactrob** [comment]
Hi Andrew,

At the time this was reproing every single time, but now it's intermittent.

In the EOS Plugin Samples, all I did to hackily test a fix was to add a call to `Steam.SteamManager.Instance.GetSessionTicket();` inside UILoginMenu's Start() function.

This ensured the session ticket was queried in advance of the login attempt, which seemed to prevent the issue. It was just a test though.

In our actual project I introduced a 500ms wait into our steam login process to resolve this.

**Comment by andrew-hirata-playeveryware** [comment]
I wonder if this a case of Valve, Epic, or both throttling connections ? i.e. "Too many" connections are being made from a given IP, so one or both are throttling it? 

This might need to be something we look at for our next release.

**Comment by paulhazen** [comment]
Closing this issue as it was fixed in PR #639.
