### ISSUE TITLE
Samples not reacting to player input

### ISSUE THREAD

**Issue by abusaenanos** [PlayEveryWare/eos_plugin_for_unity#59]
Hello,

    I installed the plugin package and the samples and have entered the product, client id, etc. parameters with the Config Editor.
    Now, when I load any of the sample scenes (e.g. AuthAndFriends) and run it, it initializes EOS correctly but I can't interact with the UI (mouse clicks are ignored) so I can't login, etc.
    The logs show they are trying to access a missing script in the 'EventSystem' object, and indeed this object has a broken reference to a script (shows 'missing script').

    Is this expected or maybe something went wrong when importing the samples?

    Thanks a lot.

**Comment by Nemeki** [comment]
Hello,

This was already answer in issue 58 https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/58

**Comment by abusaenanos** [comment]
Cool. Thanks a lot!
