### ISSUE TITLE
Unknown file type in EOSSDK.framework on iOS at link time.

### ISSUE THREAD

**Issue by JonathantNvizzio** [PlayEveryWare/eos_plugin_for_unity#594]
**Describe the bug**
We integrated the **Epic Online Services Plugin for Unity** in our project and are facing linking errors only on iOS-iPhone with the file EOSSDK which appears to contain a file of unrecognized type. 

**To Reproduce**
1. Integrate Epic Online Services Plugin for Unity 3.0.3 as a git package
2. Compile Unity Project
3. Try to compile generated xcode worskpace

```
 ❌  ld: unknown file type in /Volumes/nas/agent3/work/Game/Builds/iOS/Game/Frameworks/com.playeveryware.eos/Runtime/iOS/EOSSDK.framework/EOSSDK'
 ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Expected behavior**
Framework file is recognized as such and can be linked properly by XCode.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS M1]
 - Editor, or standalone IPhone build
 - Unity Version 2022.3.23f1
 - Plugin Version 3.0.3

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] NA
 - OS: [e.g. iOS8.1] NA
 - Unity Version 2022.3.23f1
 - Plugin Version 3.0.3

**Additional context**

**Comment by andrew-hirata-playeveryware** [comment]
Hello @JonathantNvizzio !
I have a gut feeling that this issue is being caused by a missing or incorrectly configured version of git-lfs on your mac. Are you able to open up the file referenced in that error to check and see if it is a git-lfs pointer file instead of a binary?

**Comment by JonathantNvizzio** [comment]
Hello Andrew !

We did not initially have git-lfs installed. We got it installed on one of our CI agents and I tried to rebuild with the same result, the EOSSDK.framework appears as an actual .framework file when doing a 'get info' on it :

`/Builds/iOS/Game/Frameworks/com.playeveryware.eos/Runtime/iOS/EOSSDK.framework`
so it appears to be the binary and not a git-lfs pointer.

Note, in unity the file appears perfectly fine :
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/93552959/59612db5-3b06-4047-ab67-061fb14711e0)

**Comment by JonathantNvizzio** [comment]
Update, you may close the ticket, our build master did some cleanup and we've had working builds since. Turns out it was indeed the missing git-lfs. Thanks for the support !
