### ISSUE TITLE
Make C# sdk generator source-available

### ISSUE THREAD

**Issue by kamyker** [PlayEveryWare/eos_plugin_for_unity#6]
Hi, current output of c# sdk generator seems to have pretty bad performance. In most cases it doesn't really matter but p2p networking with few calls per frame requires low overhead.

More info and example: https://eoshelp.epicgames.com/s/question/0D54z0000775IEsCAM/c-sdk-is-too-slow-to-use-p2p?language=en_US

Can't generator be source available so we could try to optimize it?

**Comment by adrianpew** [comment]
Hello. Thank you for the detailed analysis and feedback. Although our plugin for Unity uses Epic Online Service C# SDK, that generated code is maintained and owned by Epic.

From the Epic support forum link you posted, it appears it has been shared with their engineers.

When new versions of the EOS SDK are released, we will integrate and release them bundled with our plugin for Unity.
