### ISSUE TITLE
Android Won't Initialize EOSMANAGER

### ISSUE THREAD

**Issue by laithalshabi** [PlayEveryWare/eos_plugin_for_unity#602]
**Describe the bug**
android wont Initialize eos

the issue happens when eos calls => var funcResult = AndroidBindings.EOS_Initialize(ref optionsInternal); in PlatformInterface.cs
it happens on Editor Platform Android and Android standalone build

the error : 
```
NullReferenceException: Object reference not set to an instance of an object
Epic.OnlineServices.Platform.PlatformInterface.Initialize (Epic.OnlineServices.Platform.AndroidInitializeOptions& options) (at ./Library/PackageCache/com.playeveryware.eos@78b35a9d8c77/Runtime/EOS_SDK/Generated/Android/Platform/PlatformInterface.cs:18)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.InitializePlatformInterface (PlayEveryWare.EpicOnlineServices.EOSConfig configData) (at ./Library/PackageCache/com.playeveryware.eos@78b35a9d8c77/Runtime/Core/EOSManager.cs:465)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) (at ./Library/PackageCache/com.playeveryware.eos@78b35a9d8c77/Runtime/Core/EOSManager.cs:646)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) (at ./Library/PackageCache/com.playeveryware.eos@78b35a9d8c77/Runtime/Core/EOSManager.cs:558)
PlayEveryWare.EpicOnlineServices.EOSManager.Awake () (at ./Library/PackageCache/com.playeveryware.eos@78b35a9d8c77/Runtime/Core/EOSManager.cs:1803)
```

**To Reproduce**
just use the last version with android build or just change the unity platform to android

**Expected behavior**
Initialize EOSManager in android 

**Screenshots**
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/42802759/b07d93de-822d-4e1e-82c8-c7c661896bb1)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows x86, Windows x64, macOS Intel, macOS ARM] : Windows 11 x64
 - Editor, or standalone build : Both
 - Unity Version : 2023.2.12
 - Plugin Version : latest 3.1

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] : Android J8
 - OS: [e.g. iOS8.1] : android 10
 - Unity Version : 2023.2.12
 - Plugin Version : latest 3.1

**Comment by arthur740212** [comment]
Hello, we’re here to help you troubleshoot.

First, check if you have EOSConfig ready.
Open Tools->EOS Configuration and fill in the necessary blanks under Main and Android.

Second, make sure the Android API Level is higher than 29.

Additionally, try clicking on the error log that shows null exception, it might show us what the null variable was.

**Comment by laithalshabi** [comment]
> Hello, we’re here to help you troubleshoot.
> 
> First, check if you have EOSConfig ready. Open Tools->EOS Configuration and fill in the necessary blanks under Main and Android.
> 
> Second, make sure the Android API Level is higher than 29.
> 
> Additionally, try clicking on the error log that shows null exception, it might show us what the null variable was.

the 3.0.3 version was working fine for android platform and windows platform 
but now it won't work with android platform 

config is fine

android api level is fine
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/42802759/6c431b26-bc32-44cf-beeb-db15e4508181)

and its just the var funcResult = AndroidBindings.EOS_Initialize(ref optionsInternal);
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/42802759/c80cf5bb-11ff-4925-bf86-527ffe2d20a4)

**Comment by paulhazen** [comment]
We've found the source of the problem - and will have a hotfix patched in by the end of the day tomorrow.

**Comment by paulhazen** [comment]
Hi @laithalshabi Can you confirm that the changes we merged in resolve your issue? I'm confident that they will but want to double check to make sure things are good on your end.

**Comment by laithalshabi** [comment]
still the same i got the same issue

**Comment by laithalshabi** [comment]
i've created new project just to test is it "me problem" or not but same error with new project and i used the sample that came with the package 
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/42802759/c70e58fb-5cee-43da-bb50-087f09563635)
ullReferenceException: Object reference not set to an instance of an object
PlayEveryWare.EpicOnlineServices.Samples.EOSFriendsManager..ctor () (at Assets/Samples/Epic Online Services Plugin for Unity/3.1.1/Standard Pack _ EOS Plugin for Unity Samples/Scripts/EOSFriendsManager.cs:110)
System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) (at <8d5ef054c27c4b94bf100f8d26466ac6>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) (at <8d5ef054c27c4b94bf100f8d26466ac6>:0)
System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) (at <8d5ef054c27c4b94bf100f8d26466ac6>:0)
System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) (at <8d5ef054c27c4b94bf100f8d26466ac6>:0)
System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) (at <8d5ef054c27c4b94bf100f8d26466ac6>:0)
System.Activator.CreateInstance[T] () (at <8d5ef054c27c4b94bf100f8d26466ac6>:0)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.GetOrCreateManager[T] () (at ./Library/PackageCache/com.playeveryware.eos@0465461da5d5/Runtime/Core/EOSManager.cs:372)
PlayEveryWare.EpicOnlineServices.Samples.UIFriendsMenu.Start () (at Assets/Samples/Epic Online Services Plugin for Unity/3.1.1/Standard Pack _ EOS Plugin for Unity Samples/Scripts/UI/Friends/UIFriendsMenu.cs:92)

**Comment by andrew-hirata-playeveryware** [comment]
Hello @laithalshabi, is this issue still occurring with the most recent release ?

**Comment by laithalshabi** [comment]
> Hello @laithalshabi, is this issue still occurring with the most recent release ?

yeah it works fine rn thanks <3
