### ISSUE TITLE
Compile error on 3.1.0

### ISSUE THREAD

**Issue by FREEZX** [PlayEveryWare/eos_plugin_for_unity#606]
**Describe the bug**
Getting a compile error:
```
Library\PackageCache\com.playeveryware.eos@024a48d770\Editor\Utility\BuildUtility.cs(29,11): error CS0246: The type or namespace name 'Codice' could not be found (are you missing a using directive or an assembly reference?)
````

**To Reproduce**
1. Have a fresh project
2. Install version 3.1.0 from git or upm
3. See error

**Expected behavior**
No compile errors.

**Desktop (please complete the following information):**
 - OS: Windows 11 x64
 - Editor
 - Unity 2022.3.21
 - Plugin Version 3.1.0

**Comment by paulhazen** [comment]
Hi @FREEZX, thanks for reporting this - we will have a fix for you by the end of the day.

**Comment by paulhazen** [comment]
@FREEZX Can you confirm that the issue is resolved? Just want to make sure you're good to go :)
