### ISSUE TITLE
IntegratedPlatformManagementFlags does not parse from expected string values, and fails silently on incorrect input

### ISSUE THREAD

**Issue by DjPls** [PlayEveryWare/eos_plugin_for_unity#613]
**Context**
The user is expected to type in string values for Flags in the EOS config, such as AuthScopeFlags, PlatformFlags and the Steam integrated platform (IntegratedPlatformManagementFlags).

In the case of the first 2, the string values accepted are either EOS C or C# Flag values as they appear in the docs. [These](https://dev.epicgames.com/docs/en-US/api-ref/enums/eos-e-auth-scope-flags) are the values for AuthScopeFlags, and you can see they match with what is being parsed [here](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/900df63bf47db4713bc3262742b704c35234360a/Assets/Plugins/Source/Core/EOSConfig.cs#L251).

**Issue**
`IntegratedPlatformManagementFlags` does NOT parse its flags correctly from the latest C# SDK strings.
See [Flag values](https://dev.epicgames.com/docs/en-US/api-ref/enums/eos-e-integrated-platform-management-flags) and [Parsing](https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/900df63bf47db4713bc3262742b704c35234360a/Assets/Plugins/Source/Core/EOSConfig.cs#L157).
Judging by the secondary C param in the parser there was an SDK change that renamed some of these parameters. The C string was added, but not the C# variant. The plugin should be updated to include these C# Flag strings.

**Expected behavior**
Using the Flag string from either C or C# should correctly parse to a valid flag.
If the flag fails to resolve to any known value, an error should be reported.

**Resolution**
Please add the missing C# strings for `IntegratedPlatformManagementFlags` to their parse locations in `EOSConfig.cs` and `ddlmain.cpp`, and consider adding a warning/error when a string fails to resolve to a valid parameter, for all Flag string parsing.

**Comment by andrew-hirata-playeveryware** [comment]
Hello @DjPls !
Good catch!  I've made a PR for this that should fix the change. It will make it into our next release which will probably land sometime next month.

In the mean time, it should be safe to use the 'old' name in the code. I apologize for the inconvenience.
