### ISSUE TITLE
Build Fails if using EOS_DISABLE directive

### ISSUE THREAD

**Issue by TheSLAP** [PlayEveryWare/eos_plugin_for_unity#62]
LibraryName string isn't complete if using the directive EOS_DISABLE.

`Library\PackageCache\com.playeveryware.eos@b1c455b332\Runtime\EOS_SDK\Core\Config.cs(60,36): error CS1525: Invalid expression term ';'`

**Comment by scovertb** [comment]
LibraryName string is now "EOSSDK-Disabled" when using EOS_DISABLE directive.
