### ISSUE TITLE
Library/PackageCache/com.playeveryware.eos@c13536130d/Runtime/Core/PlatformSpecifics.cs(91,55): error CS1061: 'Options' does not contain a definition for 'RTCOptions' and no accessible extension method 'RTCOptions' accepting a first argument of type 'Options' could be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by arshadbarves** [PlayEveryWare/eos_plugin_for_unity#625]
**Describe the bug**
Upon attempting to update to version 3.1.2 of the plugin in macOS, I encountered an error message indicating an issue within the PlatformSpecifics.cs file. The specific error message is as follows:

`Library/PackageCache/com.playeveryware.eos@c13536130d/Runtime/Core/PlatformSpecifics.cs(91,55): error CS1061: 'Options' does not contain a definition for 'RTCOptions' and no accessible extension method 'RTCOptions' accepting a first argument of type 'Options' could be found (are you missing a using directive or an assembly reference?)`

**Steps to Reproduce:**

Attempt to update the plugin to version 3.1.2 in macOS.
Observe the error message mentioned above.

**Screenshots**
<img width="1369" alt="image" src="https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/39230484/2d2ddb43-821e-47c4-8a08-fc3014622d28">

**System Information:**

Operating System: macOS
Unity Editor: [Please specify the Unity Editor version]
Unity Version: 2023.2.16f1
Plugin Version: 3.1.2

**Expected Behavior:**
The plugin should update smoothly without encountering any errors.

**Comment by arthur740212** [comment]
Hello, thanks for the report.
It looks like there is an extra unwanted line of code that was causing the problem.
Let's look at MacOSPlatformSpecific.cs line 35.
Remove the line

   using Options = Epic.OnlineServices.IntegratedPlatform.Options;
That should solve your issue.

We will include this fix in the release shortly after.

**Comment by arshadbarves** [comment]
Thanks
