### ISSUE TITLE
DllNotFoundException: libDynamicLibraryLoaderHelper on macOS ARM

### ISSUE THREAD

**Issue by fdellabona** [PlayEveryWare/eos_plugin_for_unity#638]
**Description**

Upon updating from version 3.0.3 to 3.1.3 of the plugin and initiating play in Unity Editor, users encounter a DllNotFoundException with the following stack trace. This issue is observed specifically on macOS ARM systems running Unity Version 2022.3.16f1 with Plugin Version 3.1.3.

**To Reproduce**
Updated plugin from 3.0.3 to 3.1.3 and click Play in Unity Editor.

**Desktop (please complete the following information):**
 - OS: macOS ARM
 - Editor
 - Unity Version 2022.3.16f1
 - Plugin Version 3.1.3

**Stacktrace**

```
DllNotFoundException: libDynamicLibraryLoaderHelper assembly:<unknown assembly> type:<unknown type> member:(null)
SystemDynamicLibrary.LoadLibraryAtPath (System.String libraryPath) (at ./Library/PackageCache/com.playeveryware.eos@26c7d90631/Runtime/Core/SystemDynamicLibrary.cs:178)
DLLHandle.LoadDynamicLibrary (System.String libraryName) (at ./Library/PackageCache/com.playeveryware.eos@26c7d90631/Runtime/Core/DLLHandle.cs:180)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadDynamicLibrary (System.String libraryName) (at ./Library/PackageCache/com.playeveryware.eos@26c7d90631/Runtime/Core/EOSManager_DynamicLoading.cs:191)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadDelegatesWithEOSBindingAPI () (at ./Library/PackageCache/com.playeveryware.eos@26c7d90631/Runtime/Core/EOSManager_DynamicLoading.cs:216)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadEOSLibraries () (at ./Library/PackageCache/com.playeveryware.eos@26c7d90631/Runtime/Core/EOSManager_DynamicLoading.cs:357)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) (at ./Library/PackageCache/com.playeveryware.eos@26c7d90631/Runtime/Core/EOSManager.cs:617)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) (at ./Library/PackageCache/com.playeveryware.eos@26c7d90631/Runtime/Core/EOSManager.cs:559)
PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager.Awake () (at Assets/Samples/Epic Online Services Plugin for Unity/3.1.2/Standard Pack _ EOS Plugin for Unity Samples/Scripts/Core/EOSHostManager.cs:49)

```

**Comment by arthur740212** [comment]
Hello, we're here to help.
First thing we'll like to check if those libraries have the size of 1KB.
If so that indicates that the libs aren't completely fetched through lfs.

**Comment by paulhazen** [comment]
@fdellabona thank you for bringing this to our attention. @FabioBocci I believe you are correct that what you are experiencing is a similar issue - or rather that both problems have the same origin.

@arthur740212 is right to ask about the size of the libraries to determine if they are LFS pointer files. That's a common problem when it comes to the architecture of the library not being recognized.

I believe the reason this problem may have reared its head during the new release is that the libraries were added to LFS instead of just using regular Git storage.

Let us know about those library file sizes so we can rule that out as a source of the problem, and we can start looking into other aspects.

**Comment by fdellabona** [comment]
Thanks everyone! The library causing the issue is libEOSSDK-Mac-Shipping.dylib, and it's only 133 bytes. So, it seems like the Git LFS hypothesis is correct.

**Comment by paulhazen** [comment]
> Thanks everyone! The library causing the issue is libEOSSDK-Mac-Shipping.dylib, and it's only 133 bytes. So, it seems like the Git LFS hypothesis is correct.

Glad to hear it @fdellabona! I'm going to close this issue.
