### ISSUE TITLE
Ui not work

### ISSUE THREAD

**Issue by MatiM72737** [PlayEveryWare/eos_plugin_for_unity#65]
After start or build any sample ui buttons not work, and i can't check that sample

**Comment by Nakano37** [comment]
I'm having the same issue I think. Empty project, I import the plugin through github, install the samples. If I run the AuthAndFriends Sample in the Editor I get a "Win32 Exception". If I build that scene and run it, the logs look like everything is working (assuming I've set all the settings to the same as my actual epic game) but none of the input fields can be clicked on, none of the buttons work, only way out is alt-f4.

**Comment by PipeDownAndShipIt** [comment]
I'm also having the same issue.  Fresh install and can't seem to click on anything.  I noticed TAB does goes between the fields but I cannot select anything.

**Comment by domlaurenti** [comment]
We reverted back to the old input system for the 2.0.0 release. You should see that change corrected now and it should resolve your issue.
Addt. what @TheSLAP said is pretty much correct.
