### ISSUE TITLE
Error when using EOS_DISABLE define

### ISSUE THREAD

**Issue by BestStream** [PlayEveryWare/eos_plugin_for_unity#653]
Error when using EOS_DISABLE define:
`Library/PackageCache/com.playeveryware.eos@74682501a1/Runtime/macOS/Core/MacOSPlatformSpecifics.cs(47,43): error CS0246: The type or namespace name 'PlatformSpecifics<>' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by paulhazen** [comment]
We will either ship a hotfix for this release today - or make the change as part of our next release that should be coming within the week. For the time being, you should be able to resolve the issue by surrounding the `MacOSPlatformSpecifics` class definition with 
```
#if !EOS_DISABLE
/* ... */
#endif
```

**Comment by paulhazen** [comment]
@andrew-hirata-playeveryware, @arthur740212 Do y'all have thoughts on whether we should do a hotfix or fix it in the next release?

**Comment by andrew-hirata-playeveryware** [comment]
I think in this case, it is better to wait for a new release.

**Comment by paulhazen** [comment]
Closing because this has been resolved in `development` with PR #662. The change will be included in our upcoming release.
