### ISSUE TITLE
Fail to Create Lobby with RTC Voice Room Enabled

### ISSUE THREAD

**Issue by pewcworrell** [PlayEveryWare/eos_plugin_for_unity#66]
The lobbies sample fails to create a lobby if RTC Voice Room is Enabled.

**Comment by domlaurenti** [comment]
I believe that RTC functionality will come in the next update (which will be in July)

**Comment by domlaurenti** [comment]
This could be a permissions issue in your project on EOS portal. Make sure you have RTC enabled on your project in the EOS portal before trying to utilize it in the samples.

**Comment by andrew-hirata-playeveryware** [comment]
1. Go to the Epic Online Services [Dashboard](https://dev.epicgames.com/portal)
2. Login with an Epic Account
    * If the Epic Account is apart of more than one organization, select the organization for the product in question 
3. From the Dashboard, find the product one wishes to edit.
![eos_dashboard](https://user-images.githubusercontent.com/51927617/180309773-5e738d14-41b6-4742-93c0-922e1c9e0b45.png)
![eos_sdk_unity_plugin_dashboard_item](https://user-images.githubusercontent.com/51927617/180309959-f2cf77b0-d7af-4ab9-a4ab-9018b0cf631a.png)
4. Click the 'Gear' to get to the Product Settings
![eos_sdk_unity_plugin_title_with_gear](https://user-images.githubusercontent.com/51927617/180310047-b1f15300-99eb-4f70-b126-774c0650fe44.png)
5. Click on 'Clients'
![eos_sdk_game_client_ellipsis_menu](https://user-images.githubusercontent.com/51927617/180310157-8647a428-47c9-45e0-9093-f722818ae243.png)
6. If there are no clients, create a client for one's product now. Refer to Epic Documentation for more details
7. Select the ellipsis (The three 'dots'), then click on 'Client Policy' 
![eos_sdk_game_client_item](https://user-images.githubusercontent.com/51927617/180310238-1f44b5e9-b619-4cf5-ac9a-05d28776929e.png)
8. Scroll down to 'Voice', slide slider to 'on'
![eos_sdk_game_client_voice_item](https://user-images.githubusercontent.com/51927617/180310485-617688bf-78ce-4370-9e4e-8724fc24e44f.png)
9. Click on 'Voice', enable createLobbyConference
![eos_sdk_game_client_voice_options](https://user-images.githubusercontent.com/51927617/180310521-6c01c9d0-b53a-4faf-9df5-a8bd9c2cd007.png)

**Comment by pewcworrell** [comment]
This resolved my issue and the sample works now. Thank you.
