### ISSUE TITLE
EOSTransport.GetUserId(ulong clientId) should be public.

### ISSUE THREAD

**Issue by virtualboys** [PlayEveryWare/eos_plugin_for_unity#663]
There are many reasons a developer would want to be able to associate a ProductUserId with a clientId. An in-game name tag that hovers above the player object for example. Can we make this function public?

**Comment by andrew-hirata-playeveryware** [comment]
Hello @virtualboys,

Thank you for the idea! We will need to discuss the ramifications of making this public, and if we would like to do a rename on the method to reflect that it specifically returns a _product_ user ID.

**Comment by paulhazen** [comment]
Since we now have this tracked in our tasking, and it's more properly categorized as a feature request, I'm going to close this issue. 

Thanks again @virtualboys for the feedback - we will be considering it very soon.
