### ISSUE TITLE
EOSTransport.GetCurrentRtt not implemented

### ISSUE THREAD

**Issue by virtualboys** [PlayEveryWare/eos_plugin_for_unity#664]
I think RTT is a very useful metric for debugging but GetCurrentRTT is left as a no-op. How can we implement this?

**Comment by skeyll** [comment]
@virtualboys 
RTT can be calculated by subtracting the time at which DateTime.now is sent from the time at which it is returned from the opponent. 
You can implement it by sending DateTime, then returning the received variable as it is.

**Comment by paulhazen** [comment]
I am going to close this as `wontfix`, but I have opened a PR that adds comments to explain both how to implement it, and why it is not implemented in the sample scripts.
