### ISSUE TITLE
Steam sample code encourages false assumptions about ticket expiry

### ISSUE THREAD

**Issue by secondimpactrob** [PlayEveryWare/eos_plugin_for_unity#669]
PEW plugin's Steam sample code builds in assumptions that Steam's tickets / tokens will never expire.

SteamManager.cs code has retrieved tickets internally cached permanently, after the first time they are requested. These tickets _do_ expire after a time, and need to be requested again, otherwise login calls will fail.

It's probably beyond the scope of PEW plugin/samples to handle the expiry (similar to how the Connect login expiry is not being handled at all) however these samples will form the basis of many developer implementations in future so would be very helpful if they did not imply that permanently caching these tickets is valid. Especially since documentation on this is not at all clear.

**Comment by paulhazen** [comment]
@secondimpactrob You make some very good arguments here for including that functionality. I'll make sure it is on our radar and under consideration for a future release. I can't promise that we will add that functionality - but I tend to agree with your reasoning. It's going to be a matter of where this fits into our priorities. That you mention it will automatically move it up in that list, so thank you for bringing it to our attention. 

I will leave this issue open until we've had a chance to discuss as a team, and I'll get back to you. Cheers.

**Comment by paulhazen** [comment]
Sorry for the delayed response @secondimpactrob. We have added this to our tasks for the release following the one that will be coming out at the beginning of next week. Thanks again for bringing this to our attention. Feel free to re-open if you are encountering further issues on this topic that you would like us to address.
