### ISSUE TITLE
UI for Samples is Display Ratio Dependent 

### ISSUE THREAD

**Issue by pewcworrell** [PlayEveryWare/eos_plugin_for_unity#67]
All of the samples crop important text and input making it impossible for the user to access.

**Comment by domlaurenti** [comment]
Currently we have patch fix for this. You'll see this fix in the next release.

**Comment by domlaurenti** [comment]
This work is currently in progress. This will be fixed after 2.0.0.

**Comment by domlaurenti** [comment]
There is a kind of band-aid fix for this issue that made it into 2.0.0 (it forces the window into 16:9). A more permanent fix will be after 2.0.0.

**Comment by domlaurenti** [comment]
Oh woops I meant to mark this differently. 
Changes for UI in the samples are expected in the August update, which is EOM.

**Comment by domlaurenti** [comment]
Hello @pewcworrell, please update to the latest 2.1.0 version. We have pushed a fix for this issue, let me know if it works for you!
