### ISSUE TITLE
SteamManager callback re-use edge case

### ISSUE THREAD

**Issue by secondimpactrob** [PlayEveryWare/eos_plugin_for_unity#686]
This issue is pretty unlikely to hit others, but it hit me. Since the fix is a simple change thought I'd raise it.

Every call to `SteamManager.RequestAppTicket` shares the same 'CallResult' member object (appTicketCallResult).  If a callback from this function were to result in a new call to this function, then it will hang forever.

E.g. (not real code):

```c#
RequestAppTicket(OnAppTicketRequestComplete);

void OnAppTicketRequestComplete()
{
   if(failed)
   {
       // -> Instigate a single retry of the process, including a new call to RequestAppTicket
   }
}
```

Because the `CallResult` object gets populated during its own callback result, it ends up ill-configured and never triggers for the second call.

A simple fix is to add:

`appTicketCallResult = new CallResult<EncryptedAppTicketResponse_t>();`

Right before this existing line:

`appTicketCallResult.Set(call, RequestAppTicketResponse);`

Which means the new call is using a brand new CallResult object, and the old one will get GC'd. Now the second request comes back as expected.

----

**Side note** the event pattern used in SteamManger also requires small adjustment to not fail in the above use case (where request could be initiated by its own callback):

Here the event invokes and then nulls the line after, but if the invoke were to cause anotehr call, it would register events and then the line after they'd get cancelled.

```
appTicketEvent?.Invoke(null);
appTicketEvent = null;
```

So I adjusted the functions that do this pattern to instead do the clear earlier and invoke a local cached version:

Start of function:
```
var resultEventToTrigger = appTicketEvent;
appTicketEvent = null;
```

Invoke point:
```
resultEventToTrigger?.Invoke(null);
```

**Comment by WispyMouse** [comment]
Ahoy @secondimpactrob ! Thank you for logging this detailed bug report. Our team is going to be working on this very soon, and we'll get back to you as soon as we have results. I appreciate you calling this out as a pattern-implementation problem, it's given me perspective I can use to look at other similar calls in our plugin and improve them.

**Comment by WispyMouse** [comment]
Ahoy @secondimpactrob! I've been trying to reproduce this error, but I am having trouble with recreating this. Can you help me reach an understanding on this with a bit more info? There's definitely a chance this happened to be address in a recent changeset. What branch or release are you using that you get this error?

Inside `SteamManager` the `StartConnectLoginWithSteamAppTicket` function calls to `RequestAppTicket`. From your post, it sounds like you are experiencing a problem where if `RequestAppTicket` is called again after the first time it is run, perhaps like in the error handling scenario you described, the `appTicketCallResult` in `RequestAppTicket` is re-used in a way that doesn't work. The `appTicketCallResult` will set the function `RequestAppTicketResponse` to be called, but from your post it sounds like the second-time call never runs the callback. Am I accurately describing the situation you encountered?

To test this, I created a scenario where `RequestAppTicket` is called with a delegate that will result in `RequestAppTicket` being called again. When I do this, I've seen that the `RequestAppTicketResponse` callback is running appropriately. Inside the `RequestAppTicket` function itself, there's some early-exit handling. In the case where `appTicketEvent` is already set, which is a event that holds the callback, then the function adds the callback provided to `appTicketEvent` and exits early. In the case where this happens, I'm seeing that the events fire appropriately in the order they were provided. Please let me know if this is different from what you're experiencing.

The function that handles this is `RequestAppTicketResponse`, inside of `SteamManager`. In either the case where there was a failure or a success, it clears out `appTicketEvent`, making way for another call later. This should allow for a successful call to `RequestAppTicket `if you do it again after a previous attempt.

**Comment by secondimpactrob** [comment]
Hi, I think there are a few extra factors that may help:

1) I imagine you're testing in a case where it works every time. (i.e. `RequestAppTicket` comes back with a valid ticket.) Once it's received a valid ticket, from there it will always simply return the cached result - no more async Steam calls are actually made. There are cases where `RequestAppTicket` won't succeed, and thus this won't happen, e.g. if there's an issue on the Steam side like no encryption key set in Steamworks.

2) The cache behaviour I mentioned in 1 is likely masking most outcomes.  IMO this cache setup is flawed because it assumes that tickets are valid forever, which they aren't. I've already raised this in another thread, but it means that in my local code I have extra cases where the cache is discarded, and thus subsequent calls don't take the early-out option.

3) From my reading, the part you mention where it checks if appTicketEvent is already set - it would seem this exists so that if a Steam request is still pending and an outside call is made asking for a ticket, then it goes 'rather than make a new request for you, you can just join the list of folks waiting for the current request to come back'.

This makes complete sense, but it does not make sense in the case where that Steam request has _already_ come back and it's callback is mid-invoke. As I said, because that appTicketEvent is cleared the line after the invoke, it'll cause false outcomes in these cases. To be honest I don't know off the top of my head what happens if you subscribe a new listener to an event mid-invoke, whether it gets called. I'd imagine not. So again, you'd get an infinite hang.

Ultimately, in most use cases and if everything's configured fine and working fine then I don't think there will be any issues with the current setup. But it does seem to me the code is flawed, and my approach tends to be to correct that, since usages change and errors happen, and ideally the bit in the middle would be guarded against failure outside those ideal conditions.

**Comment by WispyMouse** [comment]
Thank you for your detailed feedback! We've merged changes addressing this in to `development`. There's better juggling of these event callbacks.
