### ISSUE TITLE
Plugin does not detect epic deployment id override arg

### ISSUE THREAD

**Issue by secondimpactrob** [PlayEveryWare/eos_plugin_for_unity#705]
The plugin's code (in `dllmain.cpp`) checks only for this launch arg:

`-eosdeploymentid=...`

But does not check for the one Epic launcher actually uses:

`-epicdeploymentid=...`

I'm guessing at some point they switched over? I did note that:

1) The `dllmain.cpp` code is checking for both `eos` and `epic` versions of the _sandbox_ arg, but not the deployment arg
2) In `EOSManager.cs`, which runs a similar check, it _does_ correctly check for both variants.

This not working forces the developer to specify sandboxOverrides in their config to avoid a mismatch between deployment id and sandbox id.

**Comment by WispyMouse** [comment]
You're absolutely right; the plugin currently doesn't observe `-epicdeploymentid` at all. At both `dllmain.cpp` and inside `EOSManager`, it looks for a sandbox override, and if one is found it will use the associated deployment id. There is no mechanism, at this moment, for using the deployment id that is provided.

We'll get to work on making this use the provided argument, and if that argument is provided we won't use the sandbox overrides. I'll get back to you on that!

**Comment by secondimpactrob** [comment]
Thanks for your reply! From what I saw the lines directly below the sandbox override _are_ checking for deployment override and applying it?

**Comment by WispyMouse** [comment]
At time of writing, that line will make `-eosdeploymentid` get used, but it's not reading in `-epicdeploymentid`. If you were to provide a sandboxid it'd look that up in the sandbox override, and if you were to provide the `-eosdeploymentid` argument it'd ignore the override it just set and then use that.

I've made two changes that'll go to code review soon; if an epicDeploymentId argument is passed in it'll use it, and if that argument is provided then it won't use the sandbox override look up.

**Comment by WispyMouse** [comment]
This is merged over to `development` and will be available in a later release.
