### ISSUE TITLE
Attempted to create lobby with a RTC Room, but RTC is locally disabled.

### ISSUE THREAD

**Issue by alecpizz** [PlayEveryWare/eos_plugin_for_unity#723]
**Describe the bug**
When attempting to create a lobby using the Lobby sample with RTC Voice Room checked, the lobby creation fails with the error "Attempted to create lobby with a RTC Room, but RTC is locally disabled.". The UILobbiesmenu also prints out an error for a LobbyUpdate error "InvalidRequest"

**To Reproduce**
1. Create a empty unity project and import the latest PlayEveryWare EOS plugin & samples.
2. Populate the EOS configuration menu with all ID's.
3. Go to the Lobbies scene in the sample pack. 
4. Enter play mode and attempt to create a lobby with RTC on.

**Expected behavior**
The lobby with RTC on is successfully created.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Editor
 - Unity 2022.3.27f1, 2022.3.4f1
 - Plugin Version 3.2.0

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by arthur740212** [comment]
Thank you for the report, it looks like there is something changed with the RTC enable pipeline, we'll dive into it.

**Comment by arthur740212** [comment]
Hello, we found out that `WindowsPlatformSpecifics.cs` near line 140.
`createOptions.options.RTCOptions = rtcOptions;` 
is wrapped around #if !UNITY_EDITOR,
removing this ifdef scope should fix the issue.
Thanks for the report, we will have a fix in the next release.

**Comment by paulhazen** [comment]
Closing this as it should have been closed with the latest release.
