### ISSUE TITLE
v3.2.0 DllNotFoundException on Mac?

### ISSUE THREAD

**Issue by KatoneVi** [PlayEveryWare/eos_plugin_for_unity#727]
**Describe the bug**
Runs fine on my PC Windows 10!  But when git pull project onto my Mac, I get error

DllNotFoundException: libDynamicLibraryLoaderHelper assembly:<unknown assembly> type:<unknown type> member:(null)
SystemDynamicLibrary.LoadLibraryAtPath (System.String libraryPath) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/SystemDynamicLibrary.cs:178)
DLLHandle.LoadDynamicLibrary (System.String libraryName) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/DLLHandle.cs:180)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadDynamicLibrary (System.String libraryName) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:140)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadDelegatesWithEOSBindingAPI () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:166)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadEOSLibraries () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:307)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:603)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:555)
PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager.Awake () (at Assets/Samples/EOSHostManager.cs:49)

**To Reproduce**
- Opening project on a Mac
- Press 'Play'
- Error message posted above will appear on the console

**Expected behavior**
You will receive the DllNotFoundException

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS Intel
 - Editor
 - Unity 2023.2.20f1
 - Plugin version:  3.2.0 (latest)

**Additional context**
So I am using your sample code transport for NetCode for GameObjects.
However, I remove the helper class since it was giving me infinite loop.  The plugin uses NGO v1.2.0 or something like that.  I am using the NGO v1.8.1.  But I don't think this is the issue since the error is throwing even before I am attempting connection (need to press START to start connection).

**Comment by arthur740212** [comment]
Looks like Mac is trying to load Windows libraies.
We'll look for a fix, thanks for the report.

**Comment by arthur740212** [comment]
Does `libDynamicLibraryLoaderHelper.dylib` exist in the project?
And if it does, is the size of the `dylib` not 1KB?

**Comment by KatoneVi** [comment]
Hello

I just checked.
{MyProject}/Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/macOS/libDynamicLibraryLoaderHelper.dylib
The size is 208kb

**Comment by arthur740212** [comment]
Is this running standalone or in editor?

**Comment by KatoneVi** [comment]
Editor

**Comment by arthur740212** [comment]
`ENABLE_DLLHANDLE_PRINT`
`ENABLE_DEBUG_EOSMANAGER`

Let's try adding these in script definiton symbols for some extra logs.

**Comment by KatoneVi** [comment]
I inserted those in Player Settings -> Player -> Other Settings -> Scripting Define Symbols
I see the same error message.  Is there something particular you wanted?
I'll attach the log if you like?

**Comment by arthur740212** [comment]
Looking for logs such as 
"Loading Library ..."
"Trying to load with entry ..."
And when they happen.

**Comment by KatoneVi** [comment]
I'll separate each one by spaces between logs
There's only like 6 before the error

**Loading EOS binary libEOSSDK-Mac-Shipping**
UnityEngine.Debug:Log (object)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:print (string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:322)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadDelegatesWithEOSBindingAPI () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:165)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadEOSLibraries () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:307)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner,string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:603)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:555)
PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager:Awake () (at Assets/Scripts/Network/EOSHostManager.cs:49)

**Loading Library libEOSSDK-Mac-Shipping**
UnityEngine.Debug:Log (object)
DLLHandle:print (string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/DLLHandle.cs:45)
DLLHandle:LoadDynamicLibrary (string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/DLLHandle.cs:170)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadDynamicLibrary (string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:140)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadDelegatesWithEOSBindingAPI () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:166)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadEOSLibraries () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:307)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner,string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:603)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:555)
PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager:Awake () (at Assets/Scripts/Network/EOSHostManager.cs:49)

**print /Users/tony/Desktop/hide/Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime**
UnityEngine.Debug:Log (object)
DLLHandle:print (string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/DLLHandle.cs:45)
DLLHandle:GetPathsToPlugins () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/DLLHandle.cs:70)
DLLHandle:LoadDynamicLibrary (string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/DLLHandle.cs:171)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadDynamicLibrary (string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:140)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadDelegatesWithEOSBindingAPI () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:166)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadEOSLibraries () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:307)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner,string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:603)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:555)
PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager:Awake () (at Assets/Scripts/Network/EOSHostManager.cs:49)

**print /Users/tony/Desktop/hide/Assets/Plugins**
UnityEngine.Debug:Log (object)
DLLHandle:print (string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/DLLHandle.cs:45)
DLLHandle:GetPathsToPlugins () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/DLLHandle.cs:70)
DLLHandle:LoadDynamicLibrary (string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/DLLHandle.cs:171)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadDynamicLibrary (string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:140)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadDelegatesWithEOSBindingAPI () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:166)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadEOSLibraries () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:307)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner,string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:603)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:555)
PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager:Awake () (at Assets/Scripts/Network/EOSHostManager.cs:49)

**Evaluating /Users/tony/Desktop/hide/Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime**
UnityEngine.Debug:Log (object)
DLLHandle:print (string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/DLLHandle.cs:45)
DLLHandle:GetPathsToPlugins () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/DLLHandle.cs:78)
DLLHandle:LoadDynamicLibrary (string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/DLLHandle.cs:171)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadDynamicLibrary (string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:140)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadDelegatesWithEOSBindingAPI () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:166)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadEOSLibraries () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:307)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner,string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:603)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:555)
PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager:Awake () (at Assets/Scripts/Network/EOSHostManager.cs:49)

**Evaluating /Users/tony/Desktop/hide/Assets/Plugins**
UnityEngine.Debug:Log (object)
DLLHandle:print (string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/DLLHandle.cs:45)
DLLHandle:GetPathsToPlugins () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/DLLHandle.cs:78)
DLLHandle:LoadDynamicLibrary (string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/DLLHandle.cs:171)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadDynamicLibrary (string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:140)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadDelegatesWithEOSBindingAPI () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:166)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:LoadEOSLibraries () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:307)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner,string) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:603)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:555)
PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager:Awake () (at Assets/Scripts/Network/EOSHostManager.cs:49)

**DllNotFoundException: libDynamicLibraryLoaderHelper assembly:<unknown assembly> type:<unknown type> member:(null)**
SystemDynamicLibrary.LoadLibraryAtPath (System.String libraryPath) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/SystemDynamicLibrary.cs:178)
DLLHandle.LoadDynamicLibrary (System.String libraryName) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/DLLHandle.cs:180)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadDynamicLibrary (System.String libraryName) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:140)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadDelegatesWithEOSBindingAPI () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:166)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadEOSLibraries () (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager_DynamicLoading.cs:307)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:603)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) (at ./Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/Core/EOSManager.cs:555)
PlayEveryWare.EpicOnlineServices.Samples.EOSHostManager.Awake () (at Assets/Scripts/Network/EOSHostManager.cs:49)

**Comment by KatoneVi** [comment]
Hopefully these logs above helps narrow down the issue!

**Comment by arthur740212** [comment]
It looks like `libDynamicLibraryLoaderHelper` wasn't found to load `libEOSSDK-Mac-Shipping.dylib`.
Not sure what, since the `libDynamicLibraryLoaderHelper` seems to be read from lfs correctly.

**Comment by arthur740212** [comment]
We weren't able to reproduce the issue on a new project.
Try importing the 3.2.0 upm via git url `https://github.com/PlayEveryWare/eos_plugin_for_unity.git`
And run again on mac Unity Editor.
Let us know if you still find the same issue.

**Comment by KatoneVi** [comment]
I think you provided the incorrect url.
The instruction says:  **https://github.com/PlayEveryWare/eos_plugin_for_unity_upm.git**

Yes, I just created a brand new project
Package Manager => Install package from git url =>   {url posted above}
Ran it, and had the same issue

Perhaps it is because this laptop is a MacBook Pro 2015?
But I don't see how that would impact this at all... but perhaps it causes issues?

Anyways, if you guys aren't running into any issues on your end, then perhaps it is just me then
No need to spend more time if it is just on my end.

**Comment by KatoneVi** [comment]
SystemDynamicLibrary.cs... where the code is failing, I put a debugger there and check the string libraryPath and confirm its value is
	libraryPath	**"/Users/tony/Desktop/hide2/Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/macOS/libEOSSDK-Mac-Shipping.dylib"**

**Comment by arthur740212** [comment]
It failed when trying to load `libEOSSDK-Mac-Shipping.dylib`,
but the dll exception was on `libDynamicLibraryLoaderHelper.dylib`.
Also you mentioned working on an older device.

Let's check if `libDynamicLibraryLoaderHelper.dylib` platform setting is set to your CPU architecture (or `Any CPU`).

**Comment by KatoneVi** [comment]
$ uname -m
x86_64

$ file Desktop/hide/Library/PackageCache/com.playeveryware.eos\@cfb8541b82/Runtime/macOS/libDynamicLibraryLoaderHelper.dylib

Desktop/hide/Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/macOS/libDynamicLibraryLoaderHelper.dylib: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64:Mach-O 64-bit dynamically linked shared library arm64]

Desktop/hide/Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/macOS/libDynamicLibraryLoaderHelper.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64

Desktop/hide/Library/PackageCache/com.playeveryware.eos@cfb8541b82/Runtime/macOS/libDynamicLibraryLoaderHelper.dylib (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64

**Comment by KatoneVi** [comment]
I will spend time investigating on it... since you guys cannot replicate it on your end, I guess it must just be me

**Comment by arthur740212** [comment]
The libDynamicLibraryLoaderHelper.dylib is built for both architectures.
But we found that the libDynamicLibraryLoaderHelper.dylib.meta was set to Intel 64-Bit.
![pbtest - Achievements - Windows, Mac, Linux - Unity 2021 3 8f1 _DX11_ 6_18_2024 5_18_38 PM](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/36757173/0d6d4517-0350-4a76-96ff-09c32c06004a)
It is likely the reason of the missing file exception.

Not sure if you'll be able to alter that setting from the upm.
Here are some suggestions.
1. Try out the previous version to make sure that this setting does cause the error. (If it does, then yay, your device isn't the problem)
2. Build a new package from this repo [https://github.com/PlayEveryWare/eos_plugin_for_unity](https://github.com/PlayEveryWare/eos_plugin_for_unity). (Build from development to get the latest changes)

**Comment by KatoneVi** [comment]
I moved the files into my Plugins directory and this is the options that I see
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/6052295/8609aea0-a50b-45e6-b0ea-8a4114a9c9da)

**Comment by KatoneVi** [comment]
Okay, I just pulled  v3.1.3
Confirmed that it is already set to "Any CPU" by default
Pressed play... and it failed with same error  😭

**Comment by arthur740212** [comment]
Here are some other angles to maybe find some clues.
1. Try making a build and check if the build runs, if it does then it might be an editor issue.
2. If you have spare storage, try running it with Unity 2021.3.8, which is the version we mostly work on.

**Comment by KatoneVi** [comment]
1. That's freaken weird!  The build version works no problems!  It just doesn't work on the editor!  I would never have guessed that!  Thanks ARTHUR!  WE'll take this route!

2. I just read this online.
> macOS no longer supports 32-bit applications. Apple has phased out support for 32-bit apps starting with macOS Catalina (10.15), so Unity does not provide an option to build 32-bit applications for macOS anymore.

> It turns out that Unity 2018 has dropped support for 32 bit builds, so you'll need to go back to Unity 2017.

If I understand this correctly, it just means if I get a 64 bit laptop, it would resolve the issue.

Overall, this is done to the best of its extent!
Thank you Arthur!

**Comment by arthur740212** [comment]
Glad to help! Have fun with the plugin, and please let us know if you have any feedback.

It does looks like an editor issue; I do wonder what was prevent it from running though.
Based on the notes you mentioned, your unity is running in 32-bit, and making a 64-bit build?

**Comment by KatoneVi** [comment]
I really have no idea...
Macbook Pro is 32 bit, yes
Unity supposedly no longer supports 32 bit for Mac, so the "Build Settings -> Architecture" only have
- Intel 64 bit
- Apple Silicon
- Intel 64 bit + Apple Silicon

I don't know much about Mac, but I assume that is what it means?

**Comment by arthur740212** [comment]
The build 64-bit runs on the 32-bit Mac.
Perhaps it is Unity (supposedly 32-bit) having problems.
Theory : the dylib is set to work on 64-bit according to the meta file,
but it is running in Unity (32-bit) so it is disabled.

**Comment by KatoneVi** [comment]
Sounds like a solid theory

I just am unsure if a 32-bit Mac can build a 64-bit app or even run it
That's the part I am confused about
Looking at it online, it says it should be impossible.  So I'm very confused now  x_x

**Comment by arthur740212** [comment]
It is confusing LOL, but good thing it is running :D

**Comment by KatoneVi** [comment]
Thanks for the time and effort in resolving this, Arthur  :)

**Unrelated to this plugin:**
Now that this part is working, I am now running into other issues with other Unity plugins and assets **(this is unrelated to this plugin!).**  In the end, it seems like the best way to just avoid all these headache is to simply upgrade to a 64 bit MacOS system.

I can continue with my work for timebeing, but in the end, I would have to upgrade for sure.  2015 is pretty dated.  :)

**Comment by KatoneVi** [comment]
Was a fun run, Arthur!  Thank you very much  >:)
