### ISSUE TITLE
libEOSSDK-Mac-Shipping.dylib  on the latest one is corrupted

### ISSUE THREAD

**Issue by KatoneVi** [PlayEveryWare/eos_plugin_for_unity#739]
It took me awhile but I see it now.  It is only like 133 bytes.
If you download the 1.16.3 from eos, you will see it is 45mb

Please update. :)

**Comment by arthur740212** [comment]
Oh, that is lfs not doing its job.
The current 3.2.0 release has a problem where it does not auto initialize lfs upon installing fetching upm.
So try initializing lfs manually, that should fix the `libEOSSDK-Mac-Shipping.dylib` file.

**Comment by paulhazen** [comment]
@KatoneVi - @arthur740212's suggestion should work in the interim, but we will be releasing a hotfix early next week that resolves this issue.

**Comment by KatoneVi** [comment]
Oh I resolved it locally already
I was just informing you guys  :)

@arthur, we meet again  >:)
