### ISSUE TITLE
Error calling showfriends: not configured.

### ISSUE THREAD

**Issue by JellyfishHosting** [PlayEveryWare/eos_plugin_for_unity#745]
**Describe the bug**

When trying to use the Auth and Friends sample with Account Portal and Dev Auth it triggers an error when trying to open the overlay. It says Friends (OnShowFriendsCallback): Error calling ShowFriends: NotConfigured

**To Reproduce**
Start the Auth and Friends sample, go to account portal and authorize, then click overlay, then error pops up.

**Expected behavior**
The program should open the overlay and not error out like it is doing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows x86, Windows x64, macOS Intel, macOS ARM] Windows x64.
 - Editor, or standalone build Editor and standalone.
 - Unity Version 2022.3.34f1
 - Plugin Version Whatever the latest github release is.

**Smartphone (please complete the following information):**
 - Unity Version
 - Plugin Version

**Additional context**

**Comment by arthur740212** [comment]
Hello, we are looking into this task.
We will come back to you when we figure out what happened with overlays.

**Comment by arthur740212** [comment]
Hi, when running in the Editor, the overlay is not supported.
If running standalone, make sure you have Epic Launcher installed on the device, and run the app with the bootstrapper

**Comment by arthur740212** [comment]
Hello, one thing we'd like to add.
The Epic Games Launcher needs be installed on your machine when running standalone.
