### ISSUE TITLE
EAC Settings.json is Reset every Build.

### ISSUE THREAD

**Issue by Dimolade** [PlayEveryWare/eos_plugin_for_unity#757]
So im trying to implement EAC into my game and it is working, but everytime i build i have to manually replace the Settings.json file in the EAC Directory. I can also just Launch the Game without the EAC Launcher, so how would i do that?

**Comment by arthur740212** [comment]
Hello, we are here to help you trouble shoot.

The first issue about `Settings.json`.
The file should be automatically populated with the configs in `EpicOnlineServices.json` whenever a build happens.
Have you made your configurations yet?
The window is at `Tools -> EOS Plugin -> EOS Configuration`

About bypassing EACLauncher, 
we'll start with two checks.
First, make sure the EAC configs are also configured.
Secondly, make sure anticheat related calls are actually being used in the project, or else the validation checks might not be called at all.

**Comment by arthur740212** [comment]
Hello, were you able to solve the issue?
