### ISSUE TITLE
Is 'Encryption Key' in the Config Editor required?

### ISSUE THREAD

**Issue by Jamez0r** [PlayEveryWare/eos_plugin_for_unity#76]
Hey guys, thanks a ton for the plugin! I am just starting to test it out, and was filling out the fields in the Epic Online Services Config Editor. There is a field for "Encryption Key", and I can't find any info on it anywhere.

The only place I see it mentioned anywhere on Epic's documentation website is in this table: https://dev.epicgames.com/docs/services/en-US/GameServices/Platform/index.html#creatingtheplatforminterface

It doesn't explain whether this is an encryption key that is provided to us by Epic somewhere in the developer portal, or if we are supposed to create one ourselves, or if it is even necessary at all. I've tried looking through the documentation, googling, etc.

Could someone enlighten me? Thanks a lot!

**Comment by TheSLAP** [comment]
Encryption key is required. It should be a 256-bit hex string that you create. You can use this website to generate one for you: https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx

**Comment by Jamez0r** [comment]
> 

Thank you!!
