### ISSUE TITLE
Getting errors that shouldn't be happening

### ISSUE THREAD

**Issue by PixelSir** [PlayEveryWare/eos_plugin_for_unity#77]
Unity and VS both seem to say there is missing interface implementation but they are both wrong yet i can't compile because of it.

See screenshot to see what I mean:

![image](https://user-images.githubusercontent.com/33559521/175181437-0a7b5ccf-ff72-48c4-9575-137865334cef.png)

I don't understand why it can't see this function which is clearly defined for the interface...

![image](https://user-images.githubusercontent.com/33559521/175181502-9a93c585-6a1f-4438-8cb1-d13383e0d407.png)

Any ideas why this is happening and how to fix it?

**Comment by TheSLAP** [comment]
LoginCallbackInfo class name is shared by another namespace in the file. Try to explicitly name LoginCallbackInfo to Epic.OnlineServices.Auth.LoginCallbackInfo

**Comment by PixelSir** [comment]
No, even if I explicitly name it, it still says it and VS also says its redundant. I've had to pause the development with it for now - I need to wait until console support is done anyway so i'll try again when most of the platforms are supported.
