### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by LucaSub01** [PlayEveryWare/eos_plugin_for_unity#79]
There are any video tutorial that you can follow?

**Comment by domlaurenti** [comment]
I don't believe so. You may have more success asking for tutorial assistance in [the Discussions page](https://github.com/PlayEveryWare/eos_plugin_for_unity/discussions)

**Comment by LucaSub01** [comment]
Thx i'll take a look

> I don't believe so. You may have more success asking for tutorial assistance in [the Discussions page](https://github.com/PlayEveryWare/eos_plugin_for_unity/discussions)
