### ISSUE TITLE
Stop spamming the log

### ISSUE THREAD

**Issue by Zammstein** [PlayEveryWare/eos_plugin_for_unity#80]
Currently, by default, the plugin constantly spams unity logs. Removing the ENABLE_DEBUG_EOSMANAGER define in the EOSManager.cs manually stops the plugin from bloating the logs, but is there a way to fix this without having to adjust the package ? 

Since Epic isn't the only platform my game supports, I switch from target platform alot and by doing so removing/adding this plugin and discarding all changes from EOSManager. So it would be nice to have this symbol removed by default, or to add a way to disable logging through code.

**Comment by TheSLAP** [comment]
```
Epic.OnlineServices.Logging.LoggingInterface.SetLogLevel(
     Epic.OnlineServices.Logging.LogCategory.AllCategories,
     Epic.OnlineServices.Logging.LogLevel.Warning);
```

**Comment by andrew-hirata-playeveryware** [comment]
A change has been made in the development branch to default it to be off. To enable it, go to 'Scripting Define Symbols' in 'Player Settings'. This change is expected to make it to the public `stable` branch in a release sometime after 2.0.0.

**Comment by domlaurenti** [comment]
Should be in the public plugin as of EOM July
