### ISSUE TITLE
PlayerDataStorage sample can perform partial writes due to encoding issue

### ISSUE THREAD

**Issue by theo-rapidfire** [PlayEveryWare/eos_plugin_for_unity#833]
**Describe the bug**
https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/6ecbcd92a2af3a4eb65b58de7aa5b4ae8e58ca5b/Assets/Scripts/EOSPlayerDataStorageManager.cs#L192

This line doesn't consider the text encoding when determining the total size of the transfer. This means that eg. accented characters (óäïòuûùü) would report a smaller `TotalSize` than what is actually required.

Changing it to utilize `Encoding.UTF8.GetByteCount(fileData)` fixes the issue.

![image](https://github.com/user-attachments/assets/57290feb-4724-462b-8e82-4257c374a6c3)

**To Reproduce**
1. Modify the PlayerDataStorage example to include accented text.
![image](https://github.com/user-attachments/assets/59e40f3c-b380-4e4b-9dbf-4a718cd7c205)
2. Upload the data to the remote.
3. Refresh the data.
4. Compare the received data with the written data, observe that characters at the end of the message are missing.

![image](https://github.com/user-attachments/assets/3bba3aee-56e0-45ad-9d26-50f8bb7955b3)

**Expected behavior**
The received data should match the content of the written data.

**Environment**
 - OS: Windows x64, Android, iOS
 - Both Editor & standalone build
 - Unity Version: 2022.3.26f1
 - Plugin Version: 3.2.1

**Comment by paulhazen** [comment]
Hi @theo-rapidfire, thanks for the feedback! When you encountered this problem in the `TitleDataStorage`, we shipped a fix for `PlayerDataStorage` as well, including the same fix. Can you please try upgrading to `3.3.1` and see if doing so resolves your issue?

**Comment by theo-rapidfire** [comment]
I only did a quick test with `3.3.1` but got the error with the log settings (https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/788), so opted to keep it at `3.2.1` as that's what I verified working. The other fix for https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/804 has also not been included in a release yet.

Since it was in the sample and not the package, I've made the fix in my local version (_along with a bunch of other changes_), so from my side it's not an overly urgent issue.

**Comment by paulhazen** [comment]
🤔 

@theo-rapidfire This isn't great - and certainly doesn't meet our own expectations of our engineering. Let me look into these issues, and I'll have a comprehensive response addressing each item today or tomorrow. I'm going to go re-open the issues that you mentioned above.

**Comment by paulhazen** [comment]
Now that this issue's resolution has been merged into the default branch of the repository, I am marking the issue as resolved.
