### ISSUE TITLE
Server drops after some time playing in-game, disconnects clients and they can't rejoin

### ISSUE THREAD

**Issue by AndrejStojkovic** [PlayEveryWare/eos_plugin_for_unity#837]
**Describe the bug**
After a couple of hours of playing in-game, I get an error that disconnect all clients and the server still continues playing.
It's random, sometimes it could be after 1 hour of playing and sometimes after 2 hours. Clients cannot rejoin in the game after that.
`
08/14/2024 14:12:34 LogEOSP2P(Warning): Attempted to send a packet with a LocalUserId that did not validate correctly. LocalUserId=[000...f6b] RemoteUserId=[000...46b] SocketId=[FishyEOS] Result=[EOS_InvalidAuth]
Failed to send packet to 000...46b with size 336 with error InvalidAuth
`
**Desktop:**
 - OS: Windows 11 x64
 - Standalone build
 - Unity Version: 2022.3.29f1
 - Plugin Version: 3.2.1

**Additional context**
I also get an error that states:
`Could not send: InvalidAuth`

**Comment by WispyMouse** [comment]
Ahoy @AndrejStojkovic ! It sounds like the authentication is expiring after one-ish two-ish hours, so let's try to get you to be able to re-auth correctly. We recently tried to address some of this in development, and it hasn't made it out to a release yet. This can be either needing to re-authenticate and then re-connect, or just re-connect. It is plausible that the authentication method you're using uses a manager that does not correctly handle clearing its cached login ticket.

To start, can you please tell me how your players authenticate in to your game? What login method do you call in the EOSManager for logging in?

If you're able to reproduce, we might be able to identify more closely what's going on if you enable a debugging symbol. Can you define "" in your compilation symbols, please. Whenever the user will de-authenticate, there will be a log like "Changing PUID: SOMEPUIDHERE => null". This indicates that the plugin is signing the user out. It may also enable some other useful logs.

We're probably going to resolve this by one or more of the following actions:
- Giving you code that expires a cached token for your authentication method after it is no longer valid
- Using the ConfigureConnectExpirationCallback to re-authenticate the user when their Connect is about to expire
- Giving you the tools to re-authenticate when you need to

**Comment by AndrejStojkovic** [comment]
Fixed, in the initialization function for EOS where the players login I added in this line:
`EOSManager.Instance.GetEOSConnectInterface().AddNotifyAuthExpiration(ref authExpirationOptions, null, OnAuthExpired);`

Then in the OnAuthExpired function I handle what should happen on expiration which is just `EOSManager.Instance.StartConnectLoginWithOptions`.

Issue resolved and can be closed.
