### ISSUE TITLE
Session Matchmaking Sample doesn't work

### ISSUE THREAD

**Issue by tanaka123** [PlayEveryWare/eos_plugin_for_unity#84]
**Describe the bug**
After creating a session, it disappears in an instant.

I tried the following in the Sample scene.
・ AuthAndFriends ⇒ fine work
・ Lobbies ⇒ fine work
・ Session Matchmaking  ⇒ bad

**To Reproduce**
1. Login
2. Input SessionName
3. Create New Session
4. Session careated
5. See Error

**Expected behavior**
The session should remain until it is erased.

**Screenshots**
![image](https://user-images.githubusercontent.com/21275458/177453292-e798f32c-73b5-4d86-8685-a5115e45107b.png)
![image](https://user-images.githubusercontent.com/21275458/177452331-bc50786c-453c-4033-80aa-aaecba59e096.png)

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Unity Version:2021.3.5f1
 - Plugin Version:1.0.4

**Additional context**
The log at that time is as follows.

02:06:09.606 [Log] : Loaded config file: {"productName":"PieceWars","productVersion":"1.0","productID":"a4f1f08f1b9e4ae0ad477113ae6befad","sandboxID":"4d37c986c923480d82ce9215f14e4577","deploymentID":"4d909975955a4248aa1a47f5238a17b9","clientSecret":"o+WmmyICjUc6f18BNQPgwtmwyAywRakEkXJBEwBxK18","clientID":"xyza7891vnMrXkkE0tZgFeogsCKMN36F","encryptionKey":"","platformOptionsFlags":[""],"alwaysSendInputToOverlay":false,"initialButtonDelayForOverlay":"","repeatButtonDelayForOverlay":""}
02:06:09.613 [Log] : InitializePlatformInterface: platformSpecifics.GetType() = PlayEveryWare.EpicOnlineServices.EOSPlatformSpecificsWindows
02:06:09.613 [Log] : InitializePlatformInterface: initOptions.GetType() = PlayEveryWare.EpicOnlineServices.EOSWindowsInitializeOptions
<color=#FFFF00>02:06:09.661 [Warning] : EOSManager::Init: InitializePlatformInterface: initResult = Success</color>
02:06:09.673 [Log] : 2022-07-06T11:06:09.6664596+09:00 LogEOS(Info): [Boot] EOSSDK Version 1.14.2-18950192 booting at 2022-07-06T02:06:09.665Z
02:06:09.673 [Log] : 2022-07-06T11:06:09.6738567+09:00 LogEOS(Info): [Boot] EOSSDK Platform Properties [OS=Windows/10.0.22000.739.64bit, ClientId=xyza7891vnMrXkkE0tZgFeogsCKMN36F, ProductId=a4f1f08f1b9e4ae0ad477113ae6befad, SandboxId=4d37c986c923480d82ce9215f14e4577, DeploymentId=4d909975955a4248aa1a47f5238a17b9, ProductName=PieceWars, ProductVersion=1.0, IsServer=false, Flags=LoadingInEditor]
02:06:09.678 [Log] : 2022-07-06T11:06:09.6782999+09:00 LogEOSOverlay(Info): Overlay will not load, because it was explicitly disabled when creating the platform
02:06:09.681 [Log] : 2022-07-06T11:06:09.6812957+09:00 LogEOSEcom(Verbose): Purchase flow is disabled due to flags passed to EOS_Platform_Create
02:06:09.681 [Log] : 2022-07-06T11:06:09.6812957+09:00 LogEOSUI(Verbose): Social overlay is disabled due to flags passed to EOS_Platform_Create
02:06:09.694 [Log] : 2022-07-06T11:06:09.6943123+09:00 LogEOSAntiCheat(Info): [AntiCheatClient] Anti-cheat client not available. Verify that the game was started using the anti-cheat bootstrapper if you intend to use it.
02:06:09.700 [Log] : 2022-07-06T11:06:09.7002986+09:00 LogEOSRTC(Info): LibRTCCore: Initializing LibRTC...
02:06:09.712 [Log] : EOS loaded
<color=#FFFF00>02:06:09.714 [Warning] : Session Matchmaking (OnLoggedOut): Not logged in.</color>
<color=#FFFF00>02:06:09.748 [Warning] : Session Matchmaking (OnLoggedOut): Not logged in.</color>
02:06:09.757 [Log] : 2022-07-06T11:06:09.7576692+09:00 LogEOS(Info): Updating Platform SDK Config, Time: 0.046596
02:06:10.543 [Log] : 2022-07-06T11:06:10.5432378+09:00 LogEOS(Info): SDK Config Platform Update Request Successful, Time: 0.829516
02:06:10.545 [Log] : 2022-07-06T11:06:10.5452345+09:00 LogEOSAnalytics(Info): Start Session (User: ...)
02:06:10.545 [Log] : 2022-07-06T11:06:10.5452345+09:00 LogEOSAnalytics(Verbose): Record Event: SDKOverlayComponent.Init <Redacted>
02:06:10.545 [Log] : 2022-07-06T11:06:10.5452345+09:00 LogEOSAnalytics(Verbose): Record Event: EOSSDK.HTTP.Complete <Redacted>
02:06:10.545 [Log] : 2022-07-06T11:06:10.5452345+09:00 LogEOSAnalytics(Warning): EOS SDK Analytics disabled for route [1].
02:06:10.546 [Log] : 2022-07-06T11:06:10.5462318+09:00 LogEOSEcom(Verbose): Purchase flow is disabled due to flags passed to EOS_Platform_Create
02:06:10.546 [Log] : 2022-07-06T11:06:10.5462318+09:00 LogEOS(Info): Updating Product SDK Config, Time: 0.833552
02:06:10.800 [Log] : 2022-07-06T11:06:10.8009295+09:00 LogEOSAnalytics(Verbose): Record Event: EOSSDK.HTTP.Complete <Redacted>
02:06:10.801 [Log] : 2022-07-06T11:06:10.8019267+09:00 LogEOSConnect(Verbose): ConnectClientAuthTask Success
02:06:10.808 [Log] : 2022-07-06T11:06:10.8089082+09:00 LogEOSAnalytics(Info): Start Session (User: ...)
02:06:11.008 [Log] : 2022-07-06T11:06:11.0088254+09:00 LogEOSAnalytics(Verbose): Record Event: EOSSDK.HTTP.Complete <Redacted>
02:06:11.010 [Log] : 2022-07-06T11:06:11.0108199+09:00 LogEOS(Info): SDK Config Product Update Request Successful, Time: 1.298976
02:06:11.011 [Log] : 2022-07-06T11:06:11.0118188+09:00 LogEOSEcom(Verbose): Purchase flow is disabled due to flags passed to EOS_Platform_Create
02:06:11.011 [Log] : 2022-07-06T11:06:11.0118188+09:00 LogEOS(Info): SDK Config Data - Watermark: 1963445314
02:06:11.011 [Log] : 2022-07-06T11:06:11.0118188+09:00 LogEOS(Info): ScheduleNextSDKConfigDataUpdate - Time: 1.298976, Update Interval: 335.701172
02:06:11.212 [Log] : 2022-07-06T11:06:11.2122846+09:00 LogEOSAnalytics(Verbose): Record Event: EOSSDK.HTTP.Complete <Redacted>
02:07:10.539 [Log] : 2022-07-06T11:07:10.5390225+09:00 LogEOSAnalytics(Verbose): Record Event: UsageMetric <Redacted>
02:07:10.539 [Log] : 2022-07-06T11:07:10.5390225+09:00 LogEOSAnalytics(Verbose): Record Event: UsageMetric <Redacted>
02:07:10.801 [Log] : 2022-07-06T11:07:10.8010336+09:00 LogEOSAnalytics(Verbose): Record Event: UsageMetric <Redacted>
02:07:32.986 [Log] : Attempting to login...
02:07:32.986 [Log] : StartLoginWithLoginTypeAndToken
02:07:33.557 [Log] : 2022-07-06T11:07:33.5570565+09:00 LogEOSAuth(Verbose): Received exchange code from dev auth tool. Proceeding with exchange code login
02:07:33.878 [Log] : 2022-07-06T11:07:33.8786188+09:00 LogEOSAnalytics(Verbose): Record Event: EOSSDK.HTTP.Complete <Redacted>
02:07:33.880 [Log] : 2022-07-06T11:07:33.8806580+09:00 LogEOSAuth(Verbose): UserAuth Success
02:07:33.881 [Log] : 2022-07-06T11:07:33.8818748+09:00 LogEOSAuth(Info): NewUserToken: User ClientId: xyz...36F AccountId: 337...4f1 Access[Expires: 2022.07.06-04.07.34 Remaining: 7200.94] Refresh[Expires: 2022-07-06T10:07:34.944Z Remaining: 28800.94] State: Valid
02:07:33.893 [Log] : 2022-07-06T11:07:33.8938631+09:00 LogEOSAuth(Info): GenerateUserAuth success
02:07:34.109 [Log] : 2022-07-06T11:07:34.1091205+09:00 LogEOSAnalytics(Verbose): Record Event: EOSSDK.HTTP.Complete <Redacted>
02:07:34.110 [Log] : 2022-07-06T11:07:34.1101183+09:00 LogEOSAuth(Info): login/queryuserinfo success
02:07:34.112 [Log] : 2022-07-06T11:07:34.1121120+09:00 LogEOSAuth(Info): Login Tasks Complete: 0
02:07:34.402 [Log] : 2022-07-06T11:07:34.4023360+09:00 LogEOSAnalytics(Verbose): Record Event: EOSSDK.HTTP.Complete <Redacted>
02:07:34.404 [Log] : 2022-07-06T11:07:34.4040741+09:00 LogEOSMessaging(Info): Attempting connection to Stomp. LocalUserId=[000...a7d] Url=[<Redacted>]
02:07:34.413 [Log] : Changing PUID: null => 000209f95a4e4ff0bc4ef26c492bea7d
02:07:34.413 [Log] : Connect Login Successful. [Success]
02:07:35.425 [Log] : 2022-07-06T11:07:35.4250271+09:00 LogEOSPresence(Info): Updating Presence to Online. LocalUserId=[337...4f1] RichText=[]
02:07:35.469 [Log] : 2022-07-06T11:07:35.4694528+09:00 LogEOSMessaging(Info): Succesfully connected to Stomp. LocalUserId=[000...a7d]
02:07:35.663 [Log] : 2022-07-06T11:07:35.6638609+09:00 LogEOSAnalytics(Verbose): Record Event: EOSSDK.HTTP.Complete <Redacted>
02:07:35.666 [Log] : Session Matchmaking: set presence successfully.
02:07:35.695 [Log] : 2022-07-06T11:07:35.6957702+09:00 LogEOSMessaging(Verbose): Stomp subscribed to topic /4d909975955a4248aa1a47f5238a17b9/account/000209f95a4e4ff0bc4ef26c492bea7d
02:08:01.707 [Log] : 2022-07-06T11:08:01.7071484+09:00 LogEOS(Warning): Error response received from backend. ServiceName=[Sessions], OperationName=[CreateSession], Url=[<Redacted>], HttpStatus=[403], ErrorCode=[errors.com.epicgames.common.policy_missing_action], NumericErrorCode=[UNSET], ErrorMessage=[Client xyza7891vnMrXkkE0tZgFeogsCKMN36F missing matchmaking:createSession], CorrId=[EOS-NUnnp0zsjUuMnFnKXluNCw-LUUyW2_b_kavKvt-Iq2xww-T6GiUwK46kGMTxZLz3EsDg]
02:08:01.708 [Log] : 2022-07-06T11:08:01.7081457+09:00 LogEOSAnalytics(Verbose): Record Event: EOSSDK.HTTP.Complete <Redacted>
02:08:01.710 [Log] : 2022-07-06T11:08:01.7104059+09:00 LogEOSPresence(Info): Skipping updating Presence to Online. Requested Presence is the same as the current one.
<color=#FF0000>02:08:01.721 [Error] : Session Matchmaking (OnUpdateSessionCompleteCallback): error code: NotConfigured</color>
<color=#FF0000>02:08:01.722 [Error] : Session Matchmaking: could not get ActiveSession for name: 123</color>
02:08:09.895 [Log] : 2022-07-06T11:08:09.8950603+09:00 LogEOSAnalytics(Verbose): Record Event: EOSSDK.HTTP.Complete <Redacted>
02:08:33.848 [Log] : 2022-07-06T11:08:33.8484135+09:00 LogEOSAuth(Verbose): Sending Verify Auth request. url=<Redacted>
02:08:33.881 [Log] : 2022-07-06T11:08:33.8813208+09:00 LogEOSAnalytics(Verbose): Record Event: UsageMetric <Redacted>
02:08:34.043 [Log] : 2022-07-06T11:08:34.0434991+09:00 LogEOSAnalytics(Verbose): Record Event: EOSSDK.HTTP.Complete <Redacted>
02:08:34.044 [Log] : 2022-07-06T11:08:34.0444966+09:00 LogEOSAuth(Verbose): Verify Auth Success
02:08:34.402 [Log] : 2022-07-06T11:08:34.4026063+09:00 LogEOSAnalytics(Verbose): Record Event: UsageMetric <Redacted>
02:08:35.424 [Log] : 2022-07-06T11:08:35.4244634+09:00 LogEOSAnalytics(Verbose): Record Event: UsageMetric <Redacted>
02:08:35.664 [Log] : 2022-07-06T11:08:35.6634147+09:00 LogEOSAnalytics(Verbose): Record Event: UsageMetric <Redacted>
02:09:01.707 [Log] : 2022-07-06T11:09:01.7071801+09:00 LogEOSAnalytics(Verbose): Record Event: UsageMetric <Redacted>
02:09:01.707 [Log] : 2022-07-06T11:09:01.7071801+09:00 LogEOSAnalytics(Verbose): Record Event: UsageMetric <Redacted>
02:09:34.043 [Log] : 2022-07-06T11:09:34.0437174+09:00 LogEOSAuth(Verbose): Sending Verify Auth request. url=<Redacted>
02:09:34.254 [Log] : 2022-07-06T11:09:34.2543493+09:00 LogEOSAnalytics(Verbose): Record Event: EOSSDK.HTTP.Complete <Redacted>
02:09:34.255 [Log] : 2022-07-06T11:09:34.2553469+09:00 LogEOSAuth(Verbose): Verify Auth Success

**Comment by tanaka123** [comment]
I'm sorry, The setting was incorrect.

The settings I was using did not allow 'createSession'.

![image](https://user-images.githubusercontent.com/21275458/177663727-b0f252c1-7aee-45a7-b66c-5c9c76c71dea.png)
![image](https://user-images.githubusercontent.com/21275458/177663693-30fee56c-601b-4eac-a357-255f1095dc26.png)

So I was able to solve this problem by changing the client policy from 'GameClient/ w UnlockArchivements' to 'Peer2Peer'.
![image](https://user-images.githubusercontent.com/21275458/177673964-7bc688de-866b-4ce6-907d-a626f96c4401.png)

However, the following error was output.

Session Matchmaking (OnRegisterCompleteCallback): error code: NotConfigured
UnityEngine.Debug:LogErrorFormat (string,object[])
PlayEveryWare.EpicOnlineServices.Samples.EOSSessionsManager:OnRegisterCompleteCallback (Epic.OnlineServices.Sessions.RegisterPlayersCallbackInfo) (at Assets/Samples/Epic Online Services Plugin for Unity/1.0.4/EOS Plugin for Unity Samples/Scripts/EOSSessionsManager.cs:1670)
Epic.OnlineServices.Sessions.SessionsInterface:OnRegisterPlayersCallbackInternalImplementation (intptr) (at Library/PackageCache/com.playeveryware.eos@b1c455b332/Runtime/EOS_SDK/Generated/Sessions/SessionsInterface.cs:927)
Epic.OnlineServices.Platform.PlatformInterface:Tick () (at Library/PackageCache/com.playeveryware.eos@b1c455b332/Runtime/EOS_SDK/Generated/Platform/PlatformInterface.cs:775)
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Tick () (at Library/PackageCache/com.playeveryware.eos@b1c455b332/Runtime/EOSManager.cs:930)
PlayEveryWare.EpicOnlineServices.EOSManager:Update () (at Library/PackageCache/com.playeveryware.eos@b1c455b332/Runtime/EOSManager.cs:1033)

I booted another Windows and tried to connect to this session, but it doesn't seem to connect successfully.

![image](https://user-images.githubusercontent.com/21275458/177674286-cf2b8bfe-5ac5-4d33-b0b2-dcd4cd66d3a5.png)

What could be the cause of this?

**Comment by scovertb** [comment]
If you're still getting a NotConfigured error you might have another missing permission. Could you post the log for the issue you're currently having? Any permissions error should produce an EOS log message with the format
`Error response received from backend. ... ErrorCode=[errors.com.epicgames.common.policy_missing_action] ... ErrorMessage=[Client <id> missing <permissionCategory:permissionName]`

**Comment by domlaurenti** [comment]
@tanaka123 Do you have the requested log for scovertb?
