### ISSUE TITLE
encryption key

### ISSUE THREAD

**Issue by fgsoftware1** [PlayEveryWare/eos_plugin_for_unity#85]
where can i found encryption key?

**Comment by andrew-hirata-playeveryware** [comment]
Are you talking about the encryption key in the EpicOnlineServicesConfigEditor? If so, you may pick any 64 character (byte) key you would like.

**Comment by sethdenner** [comment]
Do

**Comment by domlaurenti** [comment]
Any arbitrary 64 ASCII characters that you create will work properly.
I can suggest to the devs here to design a tool to generate an arbitrary key for ease of use.

**Comment by domlaurenti** [comment]
This tool may also work for this purpose, but is not designed by PEW developers: https://generate.plus/en/hex/secret-key
