### ISSUE TITLE
Unity 6 (6000.0.15f1) Android builds fail - "A problem occurred configuring project ':unityLibrary:eos_dependencies.androidlib'."

### ISSUE THREAD

**Issue by SniperED007** [PlayEveryWare/eos_plugin_for_unity#863]
1. Created new project
2. Added EOS Plugin for Unity (com.playeveryware.eos-3.3.1)
3. Build to Android (works)
4. Upgrade to Unity 6000.0.15f1
5. Build to Android (fails)
 
 **ERRORS:**

> Configure project :unityLibrary
Variant 'debug', will keep symbols in binaries for:
  'libunity.so'
  'libil2cpp.so'
  'libmain.so'
Variant 'release', symbols will be stripped from binaries.

> Configure project :launcher
Variant 'debug', will keep symbols in binaries for:
  'libunity.so'
  'libil2cpp.so'
  'libmain.so'
Variant 'release', symbols will be stripped from binaries.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun ()

**ERROR 2:**

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':unityLibrary:eos_dependencies.androidlib'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
     
     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2s

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun ()

**Comment by paulhazen** [comment]
Hi @SniperED007, thank you for your interest and attention to detail when filing this issue. At the current moment, we do not support Unity 6 - and do not have immediate plans to support it.

That's not to say that we won't, or that we cannot provide some help here - it's more that support for other more commonly utilized versions of Unity is a higher priority. 

I'll take a look into this and see if I can make some recommendations nonetheless - and will have some information for you by the end of the day on Monday.

**Comment by paulhazen** [comment]
@SniperED007 I am going to convert this issue into a conversation - as that is the context in which it makes sense to lend assistance for this. It is still not currently a high priority for the team - but that environment will be better suited for discussing options.
