### ISSUE TITLE
Android builds fail on Unity version 2022.3.44f1 LTS and later.

### ISSUE THREAD

**Issue by mohumohu-corp** [PlayEveryWare/eos_plugin_for_unity#909]
**Smartphone (please complete the following information):**
 - Device: Android
 - Unity Version 2022.3.44f1 or later

Starting from Unity version 2022.3.44f1 LTS, Android build tools version 34 is being used. To accommodate this, adjustments are required on the Eos side.
https://issuetracker.unity3d.com/issues/android-building-for-android-beta-15-fails-when-using-android-sdk-35-with-lts-unity-versions

`Fixed targetApiLevel 35, add SDK 35 and update BuildTools to 34.0.0. ([UUM-75773]`
https://alpha.release-notes.ds.unity3d.com/search?fromVersion=2022.3.42f1&toVersion=2022.3.46f1

Fix: AndroidBuilder.cs

from
```csharp
private static string GetBuildTools(){
    ...
    #if UNITY_2022_2_OR_NEWER
    const int highestVersion = 32;
#else
    const int highestVersion = 30;
#endif
    ...
}
```

to
```csharp
private static string GetBuildTools(){
    ...
    #if UNITY_2022_2_OR_NEWER
    const int highestVersion = 34;
#else
    const int highestVersion = 30;
#endif
    ...
}
```

**Comment by paulhazen** [comment]
Hi @mohumohu-corp, we have resolved this issue in the `development` branch, and it will be shipped as part of our next release. I will leave the issue as open until we have the change merged into our default branch and it is part of a release.

**Comment by paulhazen** [comment]
Hi @mohumohu-corp, we have now made a [new release](https://github.com/PlayEveryWare/eos_plugin_for_unity/releases/tag/v3.3.3) that contains this fix, so I am going to close this issue. Thank you again for your contribution toward making the plugin better, and feel free to reach out with any other problems you encounter :)
