### ISSUE TITLE
How to filter sessions by BucketId?

### ISSUE THREAD

**Issue by TakoMarie** [PlayEveryWare/eos_plugin_for_unity#917]
Hello,

I am currently able to connect with EOS with an Epic Games account and able to create a session that appears in the Dev Portal. My problem is that I can't set up a functioning search system. My goal is have a refresh button that will start searching for all active sessions with a specific BucketId and display them in a list. I don't know how to achieve that.

In the lobbies sample, there's a SearchByAttribute method in EOSLobbyManager.cs, what can I use to do something similar, but for sessions?

Thank you

**Comment by paulhazen** [comment]
You may want to take a look at 

https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/2a18ec7e3fddff1c35baf37195a9d7989be1c4bd/Assets/Tests/PlayMode/ClientLobbyTests.cs

and 

https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/2a18ec7e3fddff1c35baf37195a9d7989be1c4bd/Assets/Tests/PlayMode/LobbyTests.cs

I know they are both tests and pertain to lobbies instead of sessions - but I believe that the steps involved are very similar.

**Comment by paulhazen** [comment]
@TakoMarie 
I believe that this is the function that you want to utilize: https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/2a18ec7e3fddff1c35baf37195a9d7989be1c4bd/Assets/Scripts/EOSSessionsManager.cs#L1424

Let me know if you have any difficulty getting that to function the way that you want it to.

**Comment by TakoMarie** [comment]
Hello, 
Thanks for your help. I need to keep using version 3.3.0 of the plugins so I don't have the same function. It only takes 1 argument : public void Search(List<SessionAttribute> attributes)

**Comment by paulhazen** [comment]
Interesting. More recent versions of the plugin certainly include a lot of great improvements to this specific area of the codebase. Is there something specific that is impeding your ability to upgrade versions? If there is it would be very valuable for me and the team to understand what kind of hurdles you're encountering so we can make it an easier process for others.

If you're able to upgrade with some help from us I think that would be the best solution for you, but if that's really not a possibility then I can work with you to incorporate the changes you need into the `3.3.0` version - it will be a little trickier to do, but still definitely doable.

Let me know your thoughts and we can proceed accordingly :)

**Comment by TakoMarie** [comment]
Thanks a lot for your help, I cannot upgrade it because the latest version because of compatibility issues, but I already discussed this in private. Anyway, I decided to use lobbies instead of sessions and I was able to search by BucketId! :)
