### ISSUE TITLE
NULL EOS Platform returned by native code: issue probably occurred in GFX Plugin!

### ISSUE THREAD

**Issue by CliffCawley** [PlayEveryWare/eos_plugin_for_unity#939]
Only a very small amount of users are experiencing an issue where this exception is thrown. The rest all work fine.

I noticed that it's thrown from EOSManager_DynamicLoading.cs and is behind the define USE_EOS_GFX_PLUGIN_NATIVE_RENDER.

I don't explicitly define this, so I assume it's defined as part of the build process and must be getting included because the exception gets thrown.

What would be the likely cause for this exception and is there anything that I need to do for those users who have it occur?

We have an EpicHostManager that's attached to the very first scene we load into (which is an intro video scene). There is another 2 scenes loaded after this, and in the third scene is where it tries to access EOSManager.Instance.

The EpicHostManager looks like:

```
public class EpicHostManager : MonoBehaviour, IEOSCoroutineOwner
{
    void Awake()
    {
        DontDestroyOnLoad(gameObject);

        EOSManager.Instance.Init(this);
    }

    void IEOSCoroutineOwner.StartCoroutine(IEnumerator routine)
    {
        base.StartCoroutine(routine);
    }
}
```

(Sorry if this is the wrong Issue format, I couldn't find a more appropriate one)

**Comment by CliffCawley** [comment]
Okay, managed to figure this one out. It's because of the missing vc runtimes.

https://aka.ms/vs/17/release/vc_redist.x64.exe

I'd like to add it as part of the BuildPatchTool Install actions, but it doesn't seem to support adding multiple PrereqPaths and I'm already using it to install EAC.

**Comment by paulhazen** [comment]
@CliffCawley glad you were able to figure out what was going on! Feel free to reach out if you run into any other problems :)

I'm going to close this issue - feel free to reopen if you think it's appropriate.
