### ISSUE TITLE
Null Reference in EOSManager_DynamicLoading

### ISSUE THREAD

**Issue by Ermelious** [PlayEveryWare/eos_plugin_for_unity#94]
Upon importing and setting everything up, EOSManager_DynamicLoading is unable to find the eosLibraryHandle, it returns null. Even in the Sample scenes I'm unable to get it running.

NullReferenceException: Object reference not set to an instance of an object
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton+<>c.<LoadDelegatesWithEOSBindingAPI>b__75_0 (DLLHandle handle, System.String functionName) (at Assets/eos_plugin_for_unity_upm/Runtime/EOSManager_DynamicLoading.cs:218)
Epic.OnlineServices.Bindings.Hook[TLibraryHandle] (TLibraryHandle libraryHandle, System.Func`3[T1,T2,TResult] getFunctionPointer) (at Assets/eos_plugin_for_unity_upm/Runtime/EOS_SDK/Generated/Bindings.cs:1709)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadDelegatesWithEOSBindingAPI () (at Assets/eos_plugin_for_unity_upm/Runtime/EOSManager_DynamicLoading.cs:217)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.LoadEOSLibraries () (at Assets/eos_plugin_for_unity_upm/Runtime/EOSManager_DynamicLoading.cs:345)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) (at Assets/eos_plugin_for_unity_upm/Runtime/EOSManager.cs:447)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) (at Assets/eos_plugin_for_unity_upm/Runtime/EOSManager.cs:421)
PlayEveryWare.EpicOnlineServices.EOSManager.Awake () (at Assets/eos_plugin_for_unity_upm/Runtime/EOSManager.cs:1287)

**Comment by andrew-hirata-playeveryware** [comment]
Just to double check, did you run the EpicOnlineServicesConfigEditor?

**Comment by domlaurenti** [comment]
@Ermelious in case you didn't get a notification for this, we need this information before we can action this.

> Just to double check, did you run the EpicOnlineServicesConfigEditor?Just to double check, did you run the EpicOnlineServicesConfigEditor?

**Comment by Ermelious** [comment]
> @Ermelious in case you didn't get a notification for this, we need this information before we can action this.
> 
> > Just to double check, did you run the EpicOnlineServicesConfigEditor?Just to double check, did you run the EpicOnlineServicesConfigEditor?

Sorry about that! Yes I did, I keyed in the relevant keys located in the Dev Portal. I guess it is because I'm using the newer versions of Unity? e.g 2021 LTS.

**Comment by andrew-hirata-playeveryware** [comment]
2021 may or may not work: we haven't much testing on that series of Unity.
Just to double check some things, I have some more questions:

* Which OS are you running the editor on?
* Which platform are you targeting/running on when the crash occurs ?
* Which plugin version is ?

**Comment by Ermelious** [comment]
> 2021 may or may not work: we haven't much testing on that series of Unity. Just to double check some things, I have some more questions:
> 
> * Which OS are you running the editor on?
> * Which platform are you targeting/running on when the crash occurs ?
> * Which plugin version is ?

Sure!
- Latest version of Windows 11 Pro
- Not running on any Platform, its through the Editor. Platform is set to the default Windows but I did not attempt build.
- The latest version of this Plugin was pulled

**Comment by scovertb** [comment]
@Ermelious Is this still occurring with the latest plugin?
