### ISSUE TITLE
EOSBootstrapper appears even with EOS_DISABLE

### ISSUE THREAD

**Issue by paulhazen** [PlayEveryWare/eos_plugin_for_unity#952]
### Discussed in https://github.com/PlayEveryWare/eos_plugin_for_unity/discussions/951

<div type='discussions-op-text'>

<sup>Originally posted by **ZombossKP** October  8, 2024</sup>
Hello. I'm trying to make a project for both steam and egs in one branch. I tried to disable the appearance of EOSBootstrapper and related operations by adding the EOS_DISABLE key in scripting define symbols. The key is correctly read in my code and removes egs-related things, but BootstrapperTool still runs when building the project. 

If you open the code from the library, it looks like it does not see this define
![image](https://github.com/user-attachments/assets/c0674e56-4572-4587-91a7-117131f709f9)

Although the assemble definition shows that it is aware of it.
![image](https://github.com/user-attachments/assets/4c074b00-6335-4ea6-9d5a-a035f55a49ea)

</div>

#EOS-2173

**Comment by paulhazen** [comment]
Hi @Zomboss, I believe that you have identified a bug in our build process that warrants addressing. I will be looking into it to first replicate the issue and will follow up with you there with what we learn.

Thanks for this input. 

I _believe_ that while the bootstrapper tool is executed, it should have no impact on the executable that is created.

**Comment by ZombossKP** [comment]
Hi @paulhazen, thanks for answer. I'll be waiting for updates.

Additionally, I found that according to the code in WindowsBuilder.cs:91, the platform parameter DisableOverlay should also disable adding the bootstrapper, but that doesn't work for me either.

**Comment by WispyMouse** [comment]
This work has been done in #957 . It'll be a bit before it's included in our main release packages.

Thank you for pointing this out, @ZombossKP !
