### ISSUE TITLE
Lobby Login Failure

### ISSUE THREAD

**Issue by WispyMouse** [PlayEveryWare/eos_plugin_for_unity#956]
Hello,
I had the exact same problem and commenting out this line in EOSLobbyManager.cs also fixed the problem for me. I was just wondering if this can cause other problems in the future?
Thank you!

_Originally posted by @KimulatorsFilms in https://github.com/PlayEveryWare/eos_plugin_for_unity/discussions/525#discussioncomment-10906503_

**Comment by WispyMouse** [comment]
@KimulatorsFilms : Hey! I created this issue because I saw you posted in Discussions. I want to start by gathering information.

It sounds like you had a problem with the Lobby member count not updating, and you solved this by commenting out `CurrentLobby = new Lobby();` inside `EOSLobbyManager.OnLoggedIn()`. Is that correct?

I wanted to check in first; can you please make a log inside `EOSLobbyManager.OnLoggedIn`, and determine when it is being called? The user in the original discussion mentioned that they were running `OnLoggedIn` whenever a lobby is joined; this is incorrect! OnLoggedIn should only be called after authentication is established, but not after each lobby login.

Commenting out the line would fix your issue because the lobby is being created in `EOSLobbyManager.CreateLobby`, and then when `OnLoggedIn` is being called that Lobby is being re-created as an empty lobby.

**Comment by KimulatorsFilms** [comment]
Hi!
Yes, this is correct.

I am calling EOSLobbyManager.OnLoggedIn when a user creates a lobby and calling EOSLobbyManager.OnLoggedOut when destroying said lobby. 

Thanks a lot for the clarification! 
Please tell me if I understand correctly. The EOSLobbyManager.OnLoggedIn should be called when the user successfully connects with their Epic Games account. Then when creating a lobby with EOSLobbyManager.CreateLobby, the Lobby member count should be correctly updating without having to comment out the line. When should I call EOSLobbyManager.OnLoggedOut?

Thank you for your help!

**Comment by WispyMouse** [comment]
> The EOSLobbyManager.OnLoggedIn should be called when the user successfully connects with their Epic Games account.

Yes it should, and it should only be called once. You can see in our samples, `UILobbiesMenu.Show` gets the manager and notes the log in. Make sure it's only running once per actual login!

>  Then when creating a lobby with EOSLobbyManager.CreateLobby, the Lobby member count should be correctly updating without having to comment out the line.

You should be notified when a member joins if you're subscribed to the update. `EOSLobbyManger.OnLoggedIn` does that for you, calling `SubscribeToLobbyUpdates`. This will make `OnLobbyUpdated` get called, which will run all `LobbyUpdateCallbacks`. You can use `EOSLobbyManager.AddNotifyLobbyUpdate` to add a listener to this.

When you say "the Lobby member count should be ... updating", which value are you talking about? Is this in reference to `Lobby` class that is defined inside `EOSLobbyManager`? `OnLobbyUpdated` should be getting called and that should call `CurrentLobby.InitFromLobbyHandle`, which updates the members list. Is this working for you?

> When should I call EOSLobbyManager.OnLoggedOut?

Whenever the user logs out, or when your application is closing. It shouldn't be called between Lobby joins.

**Comment by KimulatorsFilms** [comment]
Thank you very much, It is working great! 

I use EOSLobbyManager.GetCurrentLobby().Members.Count to get the current number of members in a lobby. This number now correctly updates when a new members joins since I called EOSLobbyManager.OnLoggedIn once when the user logs in their Epic Games Account.

**Comment by WispyMouse** [comment]
Hooray! Good luck in your adventures, thank you for messaging.

In the future if you have any further problems, please open up a new Issue or Discussion for them, so we can find them quickly and help you out!
