### ISSUE TITLE
The given sandboxId "*REMOVED*" could not be found in the configured list of deployment override values.

### ISSUE THREAD

**Issue by CliffCawley** [PlayEveryWare/eos_plugin_for_unity#963]
I can't seem to find any information about this, but it only happens on the Mac version.

The EpicOnlineServicesConfig.json has the correct productID, sandboxID and deploymentID values.

The eos_macos_config.json has the same values.

There's an empty array set for sandboxDeploymentOverrides.

The Mac and Windows builds use the configs, but only the Mac build is logging this error.

As far as I can tell, the Mac build correctly switches between each of the sandboxes, even with this error.

As a potential clue, I can't seem to get EasyAntiCheat working on the mac. It doesn't seem to generate the same bootstrapper binaries.

Any ideas?

**Comment by arthur740212** [comment]
On Mac builds, there won't be an individual bootstrapper binary. Instead, the exe will be wrapped in a launcher.

For the sandboxDeploymentOverrides problem.

If running from the Epic launcher, the sandbox used will be the one submitted to in Epic portal.
If running as a standalone build, the sandbox will be from `EpicOnlineServicesConfig.json`.

And the overriding will look into the list of pairs that have the same sandbox, and replace the deployment with the one from the pair.

We'd like to retrieve the following info to better understand the problem:
Which EOS Plugin upm version you were using.
Where the application was ran from.
The config that you were using, (replace the info with A B C and such)

**Comment by arthur740212** [comment]
Update : 
We have identified the error log you were getting.
If the config does not provide an override, it will fallback to the default value provided in the config.
So this error log is pretty much a false alarm.
We will fix that in the next release.

**Comment by CliffCawley** [comment]
> On Mac builds, there won't be an individual bootstrapper binary. Instead, the exe will be wrapped in a launcher.

Okay, should I be expecting to see the splash window appear, with EasyAntiCheat, like it does on Windows? Or is that part of the bootstrapper and is only on Windows?

> If running from the Epic launcher, the sandbox used will be the one submitted to in Epic portal.

This is when running from the Epic launcher, which is why I'm confused about the message. I assumed if Sandbox Deployment overrides were set in the config, that they would override the values. Right now I haven't defined anything there, I've just set the other properties for ProductId, SandboxId and DeploymentId.

> Which EOS Plugin upm version you were using.

3.3.3 from the git url.

> Where the application was ran from.

It's being run from the Epic Games Launcher, so I expect it to pass in the details on the command line. The error is happening in Production.

> The config that you were using, (replace the confidential info with A B C and such)

**EpicOnlineServicesConfig**
```
{
    "productName": "PRODUCT_NAME",
    "productVersion": "PRODUCT_VERSION",
    "productID": "d8f***************************8a",
    "sandboxID": "ac3***************************8f",
    "deploymentID": "21*****************************87",
    "sandboxDeploymentOverrides": [],
    "isServer": false,
    "clientSecret": "A",
    "clientID": "B",
    "encryptionKey": "C",
    "platformOptionsFlags": [
        ""
    ],
    "authScopeOptionsFlags": [
        ""
    ],
    "tickBudgetInMilliseconds": 0,
    "taskNetworkTimeoutSeconds": 0.0,
    "ThreadAffinity_networkWork": "",
    "ThreadAffinity_storageIO": "",
    "ThreadAffinity_webSocketIO": "",
    "ThreadAffinity_P2PIO": "",
    "ThreadAffinity_HTTPRequestIO": "",
    "ThreadAffinity_RTCIO": "",
    "alwaysSendInputToOverlay": false,
    "initialButtonDelayForOverlay": "",
    "repeatButtonDelayForOverlay": "",
    "hackForceSendInputDirectlyToSDK": false,
    "toggleFriendsButtonCombination": [
        "SpecialLeft"
    ]
}
```

**eos_macos_config.json**
```
{
  "flags": [],
  "overrideValues": {
    "productName": "PRODUCT_NAME",
    "productVersion": "PRODUCT_VERSION",
    "productID": "d8f***************************8a",
    "sandboxID": "ac3***************************8f",
    "deploymentID": "21*****************************87",
    "sandboxDeploymentOverrides": [],
    "clientSecret": "A",
    "clientID": "B",
    "encryptionKey": "C",
    "platformOptionsFlags": [],
    "authScopeOptionsFlags": [],
    "tickBudgetInMilliseconds": 0,
    "ThreadAffinity_networkWork": "",
    "ThreadAffinity_storageIO": "",
    "ThreadAffinity_webSocketIO": "",
    "ThreadAffinity_P2PIO": "",
    "ThreadAffinity_HTTPRequestIO": "",
    "ThreadAffinity_RTCIO": "",
    "alwaysSendInputToOverlay": false,
    "initialButtonDelayForOverlay": "",
    "repeatButtonDelayForOverlay": "",
    "hackForceSendInputDirectlyToSDK": false,
    "isServer": false
  }
}
```

Are there any other configs you need to see?

**Comment by CliffCawley** [comment]
> Update : We have identified the error log you were getting. If the config does not provide an override, it will fallback to the default value provided in the config. So this error log is pretty much a false alarm. We will fix that in the next release.

Okay great, that makes sense then, I couldn't figure out what I'd configured incorrectly!

**Comment by arthur740212** [comment]
For the EAC issue. 
If the build is configured correctly, there should be an application with the EAC panda icon.
Running it should get to EAC splash screen, and after the splash screen your game will start running.

**Comment by CliffCawley** [comment]
Hmm okay, I'm not currently getting that, the game is just running as per normal with no splash, from the Epic Launcher.

It works fine on Windows, just not on Mac.

On the Mac, under Tools -> EOS Plugin -> Plugin Configuration and then Tools panel, all the paths are setup, the bootstrapper Name Override is set, and Use EAC is checked.

When building the Anti-Cheat Integrity Tool is run, the log shows the correct private keys, certificate paths and target game directory, the Anti-cheat client-side configuration file was successfully created, and then it hashes all the files before creating the Hash catalogue and copying the certificate, and then says the build succeeded.

The **eos_plugin_tools_config.json** on the Mac looks like:
```
{
    "pathToEACIntegrityTool": "/PathToGame/Game/Build/EAC/anticheat_integritytool",
    "pathToEACIntegrityConfig": "/PathToGame/Game/Build/EAC/anticheat_integritytool.cfg",
    "pathToDefaultCertificate": "",
    "pathToEACPrivateKey": "/PathToGame/Game/Build/EAC/base_private.key",
    "pathToEACCertificate": "/PathToGame/Game/Build/EAC/base_public.cer",
    "pathToEACSplashImage": "/PathToGame/Game/Build/EAC/Splash.png",
    "bootstrapperNameOverride": "LaunchGame",
    "useEAC": true
}
```

There's no additional bootstrapper binary added, as you mentioned, so the only files are the Game.app and the eac_launcher.app.

If I try to manually run the app to see what happens it just says 'The application "eac_launcher" can't be opened'. The properties on the eac_launcher app are drwxr-xr-x so it seems to be set as executable.

When I upload the game using the BuildPatchTool, I'm currently just setting the AppLaunch value to the Game.app. I think I tried setting it to eac_launcher, but it just fails to launch, I assume because of the error above when trying to manually run it.

**Comment by CliffCawley** [comment]
I just decided to interrogate the eac_launcher.app and buried into Contents/MacOS/ to find the 'start_protected_game' binary.

It seems it's not marked as Executable though (-rw-r--r--)

Should it be?

**Comment by CliffCawley** [comment]
Just an update here, I found the following in the Console.app logs:

```handle LS launch error: {\n    Action = oapp;\n    AppMimimumSystemVersion = "10.14";\n    AppPath = "/PathToGame/Game/Build/Current/Mac/eac_launcher.app";\n    ErrorCode = "-10810";\n}```

It seems -10810 is related to macOS failing to launch an application due to system-level issues or compatibility problems with the executable.

I edited the Info.plist for the eac_launcher.app and added LSMinimumSystemVersion (Minimum system version), setting it to 10.14 as suggested by the log and when running it directly, it now runs and shows:
<img width="797" alt="Screen Shot 2024-10-18 at 10 27 31 am" src="https://github.com/user-attachments/assets/aa297eb5-dcd3-4a13-bf4d-2feab2d3a09f">

So that's a little further. I'll try uploading it with the tool and running from the EGL and see if it works any better now.

**Comment by CliffCawley** [comment]
Attempting to launch this file in the Epic Launcher I just get Launch Failed: LS-00013 without the splash appearing, or even the settings.json not found error.

<img width="1380" alt="Screen Shot 2024-10-18 at 10 41 02 am" src="https://github.com/user-attachments/assets/eb88cbc2-a6d7-499f-916f-7dd725bf9d24">

Console.app log shows:
`ASP: Security policy would not allow process: 2121, /Applications/Epic Games Launcher.app/Contents/MacOS/EpicGamesLauncher-Mac-Shipping`

I checked the status using codesign of the .app and because I've modified the Info.plist file, it's reporting that it's been modified. So I assume this might be why it won't load.

So I think the eac_launcher.app needs to have it's Info.plist updated and the app re-signed?

**Comment by CliffCawley** [comment]
Okay, I just self signed it to confirm `codesign --force --deep --sign - /path/to/eac_launcher.app` and then set it all up again in the launcher, and this time I get the splash screen, and it launches the game!

So I think the fix is, that the eac_launcher.app needs to have it's `Info.plist` updated and then rebuilt/resigned with `LSMinimumSystemVersion=10.14`.

I assume that's something you need to update on your end?

**Comment by arthur740212** [comment]
It is likely that there is something done to the base app in post build should also be done on the eaclauncher.
We'll track this and look deeper into it.
Glad you found a resolution. Will keep this open for a while in case we have a question about your settings.

**Comment by CliffCawley** [comment]
Thanks, unfortunately it's not a proper resolution, as self signing it will probably only work on the dev machine that I tested it on.

And even so, making the modification is a manual step each build. I think the original eac_launcher needs to be updated and signed, which is included in your addon.

Not sure who's the maintainer of it.

**Comment by arthur740212** [comment]
I Wasn't able to reproduce the issue you were experiencing.
But code signing seems like something curious.
When you built the app, did you select replace or append?
Try creating a new build instead of overwriting the previous build.
This was really weird thing when building for Mac for us

**Comment by arthur740212** [comment]
We found out an issue with `start_protected_game`.
If the upm is added with git url, the `start_protected_game` cannot be executed.
That can be solved with `chmod +x start_protected_game`
And from there we were able to launch EAC (without Epic Game Launcher).
We shall fix the bits in the next release.

Were you able to launch the app standalone with these steps?

**Comment by CliffCawley** [comment]
> We found out an issue with `start_protected_game`. If the upm is added with git url, the `start_protected_game` cannot be executed. That can be solved with `chmod +x start_protected_game` And from there we were able to launch EAC (without Epic Game Launcher). We shall fix the bits in the next release.

It seems like this was the issue!

I must have missed it the first time when using the debug tools to discover the `info.plist file` issue, but you're right, if I modify the `start_protected_game` to executable, (I imported from the git url), it seems to work great, albeit temporarily, until the next build.  

Will be great when you make this change as part of the build process on Mac, so that it makes it an executable binary :)

**Comment by arthur740212** [comment]
Yes, we should definitely fix the execution bit on the next release.
Just to make sure. Is the re-signing still required for the build to run?
If so, we will have to track that as another task.

**Comment by CliffCawley** [comment]
> Is the re-signing still required for the build to run?

No, it seems it's no longer needed, since no modification is needed to the Info.plist either. Seems it was a red-herring.

Just changing the `start_protected_game` to executable after the build fixes the issue with being unable to launch.

Once you fix the execution bit, and the error log from the first post, this can be closed :)

**Comment by domlaurenti** [comment]
The fix should be directly done now, I'm told. If you update to the latest UPM you should see it resolved.

**Comment by CliffCawley** [comment]
@domlaurenti Doesn't look like there's anything later than 3.3.3, released in Sept.

Perhaps it's not available yet?

https://github.com/PlayEveryWare/eos_plugin_for_unity/releases

**Comment by domlaurenti** [comment]
@CliffCawley Sorry if my language wasn't super clear there, I meant it was fixed here, in the UPM repository: https://github.com/PlayEveryWare/eos_plugin_for_unity_upm

The non-UPM repository will have a release relatively soon, but it's still being unified before release

**Comment by CliffCawley** [comment]
@domlaurenti I thought I was using that.

In my manifest.json I've got the line:

`    "com.playeveryware.eos": "https://github.com/PlayEveryWare/eos_plugin_for_unity_upm.git",`

But when using the Update button it still shows 3.3.3.

Perhaps that's just what you mean and I'll just wait for the release

**Comment by arthur740212** [comment]
Yes. the fix is in the development branch, but not in a release upm yet. It will be in the next release.
We are in our release process now, could probably expect it to arrive next week.
If you would like to try the fix out before the release, we encourage users to clone this repo and build a upm with the Create Package tool in the Editor.

**Comment by CliffCawley** [comment]
No worries, thanks for the clarification!
