### ISSUE TITLE
How to handle lobby invites via the Social Overlay

### ISSUE THREAD

**Issue by KimulatorsFilms** [PlayEveryWare/eos_plugin_for_unity#970]
Hello,

I use the Social Overlay to send lobby invites to friends and NGO with EOSTransport to establish the connection between the host and the client. 

Upon accepting the invite request, the user should get properly redirected to the correct lobby scene or gameplay scene (the same as the lobby owner) and become a client if the host has started.

The problem is that I don't know how to get a proper callback when the invitation is accepted. I tried using EOS_Lobby_AddNotifyLobbyInviteAccepted, but I can't seem to make it work properly.

If there is a better way to handle lobby invites, I would be really glad to hear about it,

Thank you very much!

**Comment by WispyMouse** [comment]
Ahoy @KimulatorsFilms !

I think you're on the right track with using `EOS_Lobby_AddNotifyLobbyInviteAccepted`. I want to ask first, are you using the sample's `EOSLobbyManager`, or are you calling the Lobby Interface directly?

If you're using `EOSLobbyManager`, then the way to handle this is to subscribe to an event within the manager. Look at `EOSLobbyManager`'s `SubscribeToLobbyInvites`; it calls `lobbyInterface.AddNotifyLobbyInviteAccepted`, and runs `OnLobbyInviteAccepted` as a callback. As long as the user is subscribed, this manager will handle joining the lobby when you've accepted the invitation.

`UILobbiesMenu` in the samples is the place that demonstrates setting this up. Inside its `Show` method, there's a call to `EOSManager.Instance.GetOrCreateManager<EOSLobbyManager>().OnLoggedIn();`, which will run the `SubscribeToLobbyInvites` method.

Does the above help? What are you experiencing when you say it isn't working properly; does the callback you're expecting not run after accepting an invitation?

**Comment by KimulatorsFilms** [comment]
Thank you very much! It works now!

 I was indeed on the right track, your comment helped me clear things up. I was calling the Lobby Interface directly, but using the sample's EOSLobbyManager instead fixed my confusion.
 
 Thanks again for the information.
