### ISSUE TITLE
Linux/Mac versions

### ISSUE THREAD

**Issue by PipeDownAndShipIt** [PlayEveryWare/eos_plugin_for_unity#98]
Is there a timeline for when this plugin will support Linux and Mac versions?

**Comment by domlaurenti** [comment]
Not currently. They are planned platforms for support but they are further down the road than others.

**Comment by PipeDownAndShipIt** [comment]
OK thanks, I'm currently working on Linux and Mac versions in our game so will try put that into the plugin.
