### ISSUE TITLE
NetCode For GameObjects transport issue

### ISSUE THREAD

**Issue by EthanJamesBarron** [PlayEveryWare/eos_plugin_for_unity#981]
I'm working on an Oculus game and am trying to import the NetCode For GameObjects transport sample but I'm encountering a couple issues. I've imported the Meta SDK Core and Meta SDK Platform packages but it seems like the sample is separated into a different .sln and cant find the Oculus namespace. I don't really know what to do about this but there was a comment in the sample saying `if erroring Dont forget to import Oculus' .unitypackage` if that helps clarify anything. Otherwise every error is pretty much just `The type or namespace name 'Platform' does not exist in the namespace 'PlayEveryWare.EpicOnlineServices.Samples.OculusEOS' (are you missing an assembly reference?)`

**Comment by EthanJamesBarron** [comment]
> Hello, let me take a look into the plugin. Does the error still exist after importing `Oculus.unitypackage`?

Well unfortunately I don't really know what Oculus.unitypackage is. It's not included in any of the samples and I couldn't find it in the repo. I don't know what Oculus package it's referring to

**Comment by arthur740212** [comment]
It is not part the repo, it could be downloaded from Meta's/Oculus's middleware page.

**Comment by EthanJamesBarron** [comment]
> It is not part the repo, it could be downloaded from Meta's/Oculus's middleware page.

I think that's the one I already have installed. Are you guys depending on the legacy oculus SDK? Either way it doesn't seem like the sample SLNs can access the Oculus namespace
![image](https://github.com/user-attachments/assets/cd5d5e09-173d-41b0-aa0f-401c90f56bb7)
![image](https://github.com/user-attachments/assets/a79df931-a250-4c09-b18f-717ad764fa3c)
![image](https://github.com/user-attachments/assets/a75f5725-7495-4f55-8e9c-188d38540cde)

**Comment by arthur740212** [comment]
We think so yes, the feature was added with `com.unity.xr.oculus` and the Oculus plugin from their page.
We are trying to find which package does `Oculus.Platform` exist in, will report back in a moment.

**Comment by arthur740212** [comment]
https://developers.meta.com/horizon/downloads/unity/
`Oculus.Platform` is in legacy oculus SDK. 
Were you able to make OculusManager recognize that assembly?

**Comment by EthanJamesBarron** [comment]
> https://developers.meta.com/horizon/downloads/unity/ `Oculus.Platform` is in legacy oculus SDK. Were you able to make OculusManager recognize that assembly?

Sorry for the late response I was a bit caught up. I downloaded the legacy package and it seems to also have the same issue. I opened the references dropdown in the `com.playeveryware.eos.samples.oculus` .sln and it's just referencing Unity DLLs and not the Oculus ones. Is there a way for me to maybe add them manually myself? I cant just right click and add dependencies like I could in any other .NET project

**Comment by EthanJamesBarron** [comment]
Okay so I did a BIT of tinkering and it seems the ASMDEF for the samples had a messed up reference to the Oculus ASMDEFs. I've resolved them since and it pretty much worked but there were a few changes I needed to make

I had to change the sample's namespace from `PlayEveryWare.EpicOnlineServices.Samples.Oculus` to `PlayEveryWare.EpicOnlineServices.Samples.OculusSample` because the original namespace was overriding the actual Oculus namespace

I had to change both line 1218 and 1225 to refer to OculusSample since that was the new namespace

After this it's good as new!! I'll keep this open for now in case there's anything else needed but I'm happy for you to close it if you want to

**Comment by arthur740212** [comment]
Hooray, glad you found a fix. 
We will track this issue and look for a way to make it easier to use instead of having users going through the trouble.

**Comment by arthur740212** [comment]
We have some PR merged for this fix and should be out for the next release.
