### ISSUE TITLE
`AccountManager.cs`, line `1285` does not include login info in `connectLoginCallbackInfo` when the Player successfully logins

### ISSUE THREAD

**Issue by Ermelious** [PlayEveryWare/eos_plugin_for_unity#983]
**Describe the bug**
Trying to retrieve any sort of login info, e.g token, epic account details after Login is successful. But the following function in the SDK which handles it, is returning null to those info:
'AccountManager.cs', line 1285
```c#
private void StartConnectLoginWithLoginCallbackInfo(LoginCallbackInfo loginCallbackInfo)
```
"connectLoginCallbackInfo" does not contain login info and both clientData and ContinuanceToken are "null".
![image](https://github.com/user-attachments/assets/aa0fa495-3b1d-4603-a423-60df22215c91)
**Note: I've also tried "loginCallbackInfo", that returns null in clientData and ContinuanceToken too.

**To Reproduce**
1. Login to an epic account via DevAuthTool or AccountPortal login methods.
2. Go to 'AccountManager.cs', line 1285
3. When a user successfully logins, "connectLoginCallbackInfo" does not contain login info and both clientData and ContinuanceToken are "null".

**Expected behavior**
If my assumptions are correct, both clientData and continuanceToken returned in "connectLoginCallbackInfo" should have the relevant data. We need this data to send it to our Firebase Cloud Functions via REST API to have Firebase validate it with EPIC before giving the player access to their data in Firebase.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Editor and Windows Build
 - Unity Version (2023)

**Comment by paulhazen** [comment]
Can you share with us which version of the plugin you are using? That will help me know more precisely where to look.

**Comment by Ermelious** [comment]
> Can you share with us which version of the plugin you are using? That will help me know more precisely where to look.

@paulhazen Excuse me for missing out the plugin version. I'm using 3.3.0.

I think I've mistaken the continuanceToken for the the following "ID Token":
![image](https://github.com/user-attachments/assets/85707555-3e42-4350-9c75-a553e2af7c85)

However may I check, if there is an existing way to retrieve the ID Token from EOSAntiCheatClientManager.cs? Currently I have it exposed with my own changes as seen here by making a public property:
![image](https://github.com/user-attachments/assets/ae73e0d4-a037-4f7b-94a8-bb7955763112)

With the ID Token, I'm attempting to send it over via REST API "Post" to Firebase to have it verify with EPIC via OpenID. Though I'm still figuring the following firebase cloud function: https://firebase.google.com/docs/auth/web/openid-connect?hl=en&authuser=1&_gl=1*zpc9mn*_ga*MTA5Njg0ODIwNC4xNzI4NjY0NjM5*_ga_CW55HF8NVT*MTcyOTcwNTE1MS4zOS4xLjE3Mjk3MDUxNzkuMzIuMC4w#manual
But it seems like if I pass the Epic ID Token to the above Firebase Sign-In function, it should possibly handle the verification between Firebase and Epic.

**Comment by WispyMouse** [comment]
Ahoy @Ermelious ! I had a quick clarification to ask for.

I pulled the 3.3.0 release of the plugin, and could not find a class named `AccountManager`. Is that a class you've created, or is it from a previous iteration of the plugin?

**Comment by WispyMouse** [comment]
Here's documentation relating to the Connect ID token: https://dev.epicgames.com/docs/game-services/eos-connect-interface#user-verification-using-an-id-token

This provides an outlining of steps to get the Id token. The method mentioned there, `EOS_Connect_CopyIdToken`, relates to the function you posted earlier, `ConnectInterface.CopyIdToken`. The `JsonWebToken` inside `IdToken` should be the thing you need.

By default our plugin doesn't expose that value as public. You can continue as you have it here, where you've made that public, or you can call the ConnectHandle in the way that `EOSAntiCheatClientManager.GetLocalIdToken()` has it implemented.

It appears as though the primary reason `LocalUserIdToken` is private is because it can't be guaranteed that it is set and available by the time a caller might need it, but if you're sure you've logged in to the Connect interface already you can just make that public.

**Comment by Ermelious** [comment]
> Ahoy @Ermelious ! I had a quick clarification to ask for.
> 
> I pulled the 3.3.0 release of the plugin, and could not find a class named `AccountManager`. Is that a class you've created, or is it from a previous iteration of the plugin?
Apologies, I've forgotten to indicate that "AccountManager" is just a copy/rename of "UILoginMenu.cs" from PlayEveryWare SDK.

> Here's documentation relating to the Connect ID token: https://dev.epicgames.com/docs/game-services/eos-connect-interface#user-verification-using-an-id-token
> 
> This provides an outlining of steps to get the Id token. The method mentioned there, `EOS_Connect_CopyIdToken`, relates to the function you posted earlier, `ConnectInterface.CopyIdToken`. The `JsonWebToken` inside `IdToken` should be the thing you need.
> 
> By default our plugin doesn't expose that value as public. You can continue as you have it here, where you've made that public, or you can call the ConnectHandle in the way that `EOSAntiCheatClientManager.GetLocalIdToken()` has it implemented.
> 
> It appears as though the primary reason `LocalUserIdToken` is private is because it can't be guaranteed that it is set and available by the time a caller might need it, but if you're sure you've logged in to the Connect interface already you can just make that public.
I'm actually trying to figure if there is even a way to have Firebase act as the backend, if by chance any of you have also implemented something with Firebase using this SDK and via REST API (Not the Firebase Unity SDK as that SDK is limited to mobile platforms), please advice.

I'm trying to find a way to have Firebase act as the back end to verify if the EOS_Connect_CopyIdToken JsonWebToken above (sent via REST API "Post") to is a legitimate login/user or not before Firebase grants access and logs in the user via OpenID using the Epic Games Account Client ID Token.
The following seems to describe something like that but it seems to only handle receiving the already verified token and simply logs in/create account in Firebase using the epic credentials within the Token. 
https://cloud.google.com/identity-platform/docs/reference/rest/v1/accounts/signInWithIdp

Have also tried exploring this:
https://firebase.google.com/docs/auth/web/openid-connect?hl=en&authuser=1&_gl=1*zpc9mn*_ga*MTA5Njg0ODIwNC4xNzI4NjY0NjM5*_ga_CW55HF8NVT*MTcyOTcwNTE1MS4zOS4xLjE3Mjk3MDUxNzkuMzIuMC4w#manual
But the above seems to be meant for a separate backend server aside from the Firebase one.

**Comment by WispyMouse** [comment]
If I'm understanding correctly, perhaps this is an issue that can be configured in the epic portal. If you go to the "Identiy Providers" area, you can add an "OpenID" as an identity provider. Then you can specify the API end point that validates that the ID is from FireBase.

![image](https://github.com/user-attachments/assets/ae2a90cc-3de1-433d-baeb-10c68a2a1f78)

**Comment by Ermelious** [comment]
> If I'm understanding correctly, perhaps this is an issue that can be configured in the epic portal. If you go to the "Identiy Providers" area, you can add an "OpenID" as an identity provider. Then you can specify the API end point that validates that the ID is from FireBase.
> 
> ![image](https://private-user-images.githubusercontent.com/16852552/382917549-ae2a90cc-3de1-433d-baeb-10c68a2a1f78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3ODUwMTQsIm5iZiI6MTczMDc4NDcxNCwicGF0aCI6Ii8xNjg1MjU1Mi8zODI5MTc1NDktYWUyYTkwY2MtM2RlMS00MzNkLWJhZWItMTBjNjhhMmExZjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA1MzE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZDM1NjZhM2VkODI2Y2NkOTQ3OTViMzM0YzkwMWZhYjU4NTkwNTkwMzAzMjg3MDMxZWNlODM1OThjZDRmMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bfMMwEI4QIyFPGYVmi_HUxk2t36sVO5d-dKqzt82ifA)

This does seem like the opposite of what I'm trying to implement. From my understanding, your suggested method is to have the user login to Firebase and also sign up for a new account via Firebase, and than have Firebase send the account credential/token to EPIC and have EPIC use that Firebase account.

What I'm trying to implement is, have the user Login via their EPIC Games Account, and then send the EPIC ID Token from the game Client to Firebase, and have Firebase use the EPIC Games Account as the account to login to Firebase.
The issue with this method is, right after the Epic Login Browser Web Page succeeds and closes, and sends the player back to the game with the EPIC Client ID Token, it will be up to the Client to send this Client ID Token to the backend database (Firebase), to use the EPIC Games Account credentials in that Token to login to Firebase and have access to their data.
The problem with this route is that I would probably need to have Firebase send the EPIC Client ID Token received from the Client, to EPIC Games to validate if the token is Valid and no foul play is involved is that right? If so than I'm trying to figure out how to implement this on Firebase.

From what I'm understanding, it could either be this (I could be wrong):

Manual Sign-In Flow (Problem with this one is that I'm not sure if this piece of code is meant to run on Firebase as a Cloud Function or if a dedicated backend server is required.
https://firebase.google.com/docs/auth/web/openid-connect?hl=en&authuser=1&_gl=1*zpc9mn*_ga*MTA5Njg0ODIwNC4xNzI4NjY0NjM5*_ga_CW55HF8NVT*MTcyOTcwNTE1MS4zOS4xLjE3Mjk3MDUxNzkuMzIuMC4w#manual

OR 

SignInWithIDP (The following seems to describing some similarities to what I'm trying to implement but it seems to only handle receiving the already verified token and simply logs in/create account in Firebase using the epic credentials within the Token. Basically fully trusting the Client that the Token hasn't been tempted with, as the token might not be sent to EPIC for verification. Correct me if I'm wrong.)
https://cloud.google.com/identity-platform/docs/reference/rest/v1/accounts/signInWithIdp

**Comment by WispyMouse** [comment]
Ah, okay. Firebase is a new concept for me personally, so I'll do my best to follow and provide guidance.

So the ideal flow that you're picturing is something like:

1. The user performs an Auth login using the Account Portal login method. In doing so they identify the Epic account they want to log in with.
    - This has an associated EpicAccountId
2. **Possibly** perform a Connect login with the associated EpicAccountId.
    - This has an associated ProductUserId
4. Either the EpicAccountId, ProductUserId, or some other identity is used to produce a token through Epic for use in logging in to Firebase
5. That token is sent to Firebase, which validates it as being correctly made from Epic. Either while validating it or as a separate step, the token is used to sign in to Firebase

Before going further, have I correctly summarized these steps? And if so, the challenge with the above is that you're wondering how to produce a token that can be used with Firebase. Firebase *appears* to use OpenID, so it could be that you produce an OpenID token, but you *don't* want to use Firebase as the authority for the OpenID, just to recognize that ID as correctly being configured and provided from Epic. Is this all correct?

Thank you for your patience! I'm certain was can determine what to do here and what you'll need to implement things.

**Comment by Ermelious** [comment]
> summarized



> Ah, okay. Firebase is a new concept for me personally, so I'll do my best to follow and provide guidance.
> 
> So the ideal flow that you're picturing is something like:
> 
> 1. The user performs an Auth login using the Account Portal login method. In doing so they identify the Epic account they want to log in with.
>    
>    * This has an associated EpicAccountId
> 2. **Possibly** perform a Connect login with the associated EpicAccountId.
>    
>    * This has an associated ProductUserId
> 3. Either the EpicAccountId, ProductUserId, or some other identity is used to produce a token through Epic for use in logging in to Firebase
> 4. That token is sent to Firebase, which validates it as being correctly made from Epic. Either while validating it or as a separate step, the token is used to sign in to Firebase
> 
> Before going further, have I correctly summarized these steps? And if so, the challenge with the above is that you're wondering how to produce a token that can be used with Firebase. Firebase _appears_ to use OpenID, so it could be that you produce an OpenID token, but you _don't_ want to use Firebase as the authority for the OpenID, just to recognize that ID as correctly being configured and provided from Epic. Is this all correct?
> 
> Thank you for your patience! I'm certain was can determine what to do here and what you'll need to implement things.

Thanks! Yes I think you've gotten it down. But basically, to put it simply, the issue I'm facing is:
1. To get the EPIC Token (which I think I've gotten it thanks to your earlier clarifications, its the Epic Client ID Token)
2. To pass the EPIC Token over to Firebase via REST API (I can't use the Firebase Unity SDK as that SDK is only meant for mobile platforms so to achieve the Platform Agnostic route, I've to use REST API)
3. To get Firebase to check first with EPIC if the received Token from the Client, is legitimate (though feel free to correct me here if this checking is necessary or not), if it is legitimate, Firebase will then use the credentials in the Token to either:
- Create a new account for the player in Firebase's Firestore/Database (If the player's data does not exist)
OR
-  Give access/Login to the Client and grants access (via a Firebase Token) over it's respective player data

So the final result will be:
1. The Player launches the Game
2. The Player logins via Epic's Account / Web Portal
And the rest is passed over to the systems to handle the login process.
The final result on the Client side once everything is successfully logged in is the Client would have 2x Tokens, one Access? Token for Epic and one Access? Token for Firebase.

**Comment by WispyMouse** [comment]
Good, I think I understand! Sorry for the delay in response. So, now that you have this process and flow, what are the missing pieces? Have you tried using this token, and gotten results from it? 

I tried poking around the documentation a bit, and found this: https://dev.epicgames.com/docs/epic-account-services/auth/auth-interface#user-verification-using-an-id-token

Firebase uses the term "Identity Provider credential". I can't tell if this is wholly separate from OpenID. But if you can use an OpenID token, I bet this gets you to where you need. You can fetch the ID through the _Auth Interface_, rather than the _Connect Interface_. You said "Client ID" so I want to make sure that we're pointing at the exact right thing. Log in using the Auth interface, and then call `EOSManager.Instance.GetEOSAuthInterface.CopyIdToken`. This produces an `IdToken`, where `JsonWebToken` should be populated with an OpenID token. Then you can pass this ID to Firebase.

You may have to configure Firebase to recognize EOS as a provider. You mentioned you're doing this by web request, so you probably have to fill out a bunch manually. Hopefully the linked EOS documentation has what you need.

Does this help get you unblocked? Perhaps there's another component that I am missing.

**Comment by Ermelious** [comment]
> Good, I think I understand! Sorry for the delay in response. So, now that you have this process and flow, what are the missing pieces? Have you tried using this token, and gotten results from it?
> 
> I tried poking around the documentation a bit, and found this: https://dev.epicgames.com/docs/epic-account-services/auth/auth-interface#user-verification-using-an-id-token
> 
> Firebase uses the term "Identity Provider credential". I can't tell if this is wholly separate from OpenID. But if you can use an OpenID token, I bet this gets you to where you need. You can fetch the ID through the _Auth Interface_, rather than the _Connect Interface_. You said "Client ID" so I want to make sure that we're pointing at the exact right thing. Log in using the Auth interface, and then call `EOSManager.Instance.GetEOSAuthInterface.CopyIdToken`. This produces an `IdToken`, where `JsonWebToken` should be populated with an OpenID token. Then you can pass this ID to Firebase.
> 
> You may have to configure Firebase to recognize EOS as a provider. You mentioned you're doing this by web request, so you probably have to fill out a bunch manually. Hopefully the linked EOS documentation has what you need.
> 
> Does this help get you unblocked? Perhaps there's another component that I am missing.

I'm already aware of the stuff you've shared. My question is more towards this:
Can the player/client simply send the EPIC Token to Firebase and have Firebase trust that token 100% OR must Firebase do a check with EPIC's endpoint to verify that the Token is legitimate BEFORE logging in the Player to Firebase.
This is what I've been trying to describe in my previous posts. Additionally if the check is needed, I need to find an existing endpoint in Firebase that does this or a way to implement this as a cloud function.

**Comment by WispyMouse** [comment]
Unfortunately I, and the EOS Plugin for Unity team, do not have the relevant experience with Firebase to guide you further. However, _I think_ you have what you need here; try using the OpenID token provided from the Auth interface and see if Firebase has any issues with it. The OpenID token generated should have the necessary "iss" property that will inform Firebase of the issuer and how to validate the token, though you might have to configure Epic as an OpenID provider in Firebase. The information on how to acquire the Epic endpoints that is linked at this documentation: https://dev.epicgames.com/docs/epic-account-services/auth/auth-interface#user-verification-using-an-id-token.

_I believe_ either way, Firebase will do the validation work for you, you won't need to handle that validation by code. I searched around the EOS Help forums and found a seemingly relevant thread, which amusingly went through similar phases as this ticket: https://eoshelp.epicgames.com/s/question/0D5QP00000e3zhd0AA/is-it-possible-to-login-a-user-via-epics-login-portal-and-then-have-epic-send-the-credentials-to-firebase

Beyond this, though, the plugin team won't be able to provide informed assistance about setting Firebase up. You may be able to open a ticket with Epic through either a community or private discussion (https://eoshelp.epicgames.com/s/discussions), or alternatively Firebase's helpline (https://firebase.google.com/support). I apologize for the inconvenience, and I feel like you're very close to the solution you require.

**Comment by WispyMouse** [comment]
Ahoy @Ermelious ! I'd like to close out this Git Issue, but first I want to touch base with you. Does the above address your needs enough that we could close this out?

**Comment by Ermelious** [comment]
> Ahoy @Ermelious ! I'd like to close out this Git Issue, but first I want to touch base with you. Does the above address your needs enough that we could close this out?

Yes my issue has been resolved. Thanks for the assistance @WispyMouse

**Comment by paulhazen** [comment]
Thanks @Ermelious! We appreciate your engagement on things - you are always free to reach out for assistance, thanks for helping to make the plugin better! 😄
