### ISSUE TITLE
'FileUtility' does not exist in IOSBuilder.cs

### ISSUE THREAD

**Issue by AdriaandeJongh** [PlayEveryWare/eos_plugin_for_unity#984]
**Describe the bug**
When switching to the iOS build target, my project doesn't compile because of the following error:

```
Library/PackageCache/com.playeveryware.eos@2b19812166/Editor/Platforms/iOS/IOSBuilder.cs(63,33): error CS0103: The name 'FileUtility' does not exist in the current context
```

I fixed it by changing `FileUtility` to `System.IO.File` on line 63 in IOSBuilder.cs.

**Desktop (please complete the following information):**
 - OS: macOS ARM
 - Editor: Unity 2022.3.51f1
 - Plugin Version: 3.3.3

**Comment by paulhazen** [comment]
Hi @AdriaandeJongh, we have fixed this in our upcoming release. I will leave this issue as unresolved until we actually ship the fix. Glad that you were able to find a solution. If you run into trouble with it for any reason, you could have switched `FileUtility` to `FileSystemUtility` and all would have been well.

Thanks again, and I'll keep you posted.

**Comment by paulhazen** [comment]
I'm opting to close this for the time being, since it is fixed in `development`, and will be included in our next release. I will nonetheless update here when the fix is released.
